### ISSUE TITLE
Documentation Offline

### ISSUE THREAD

**Issue by MojoCreator** [crawlab-team/crawlab#1003]
**Describe the bug**
Your current documentation links are all offline. Cloudflare Forbidden error. It has been like this for a couple weeks.

**To Reproduce**
1. Go to 'https://docs.crawlab.cn/'
2. See error
403 Forbidden
cloudflare

**Screenshots**
![image](https://user-images.githubusercontent.com/2466912/132396052-425313b8-574a-47c3-874c-3466ec52f2db.png)

**Comment by tikazyq** [comment]
Due to the ICT policy in Mainland China, the site's beian has expired which resulted in the inaccessibility. You are recommended to check out the documentation in the Github repo https://github.com/crawlab-team/crawlab-docs.

**Comment by tikazyq** [comment]
Fixed
