### ISSUE TITLE
settings 引入 datetime后系统json报错

### ISSUE THREAD

**Issue by zhangqiang603zq** [crawlab-team/crawlab#1004]
import datetime

BOT_NAME = 'spidertest'

SPIDER_MODULES = ['spidertest.spiders']
NEWSPIDER_MODULE = 'spidertest.spiders'

to_day = datetime.datetime.now()
log_file_path = BOT_NAME + "/logs/spidertest{}_{}_{}.log".format(to_day.year, to_day.month, to_day.day)
LOG_LEVEL = "INFO"
LOG_FILE = log_file_path

上传包到平台系统报错：

http://xxx.com:8077/spiders/61404bf8c6435042811f56a7/scrapy/settings. Traceback (most recent call last): File "/usr/local/bin/crawlab", line 11, in <module> sys.exit(main()) File "/usr/local/lib/python3.6/site-packages/crawlab/cli/__init__.py", line 150, in main cli() File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke return callback(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/crawlab/cli/__init__.py", line 109, in settings client.settings(directory) File "/usr/local/lib/python3.6/site-packages/crawlab/core/client.py", line 195, in settings print(json.dumps(data)) File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps return _default_encoder.encode(obj) File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/usr/lib64/python3.6/json/encoder.py", line 180, in default o.__class__.__name__) TypeError: Object of type 'module' is not JSON serializable

**Comment by tikazyq** [comment]
不在`settings.py`里写动态内容就可以，去掉`import`这些
