### ISSUE TITLE
master控制台的日志输出太多，可以关闭么？

### ISSUE THREAD

**Issue by 8-l8l-8** [crawlab-team/crawlab#1005]
**问题描述**
master控制台的日志输出太多，可以关闭么？

**控制台输出**
 [GIN] 2021/09/15 - 14:23:38 | 200 |   17.457762ms |    192.168.0.29 | GET      "/nodes/61416c9401eeaa627dc6c3d4/langs"
[GIN] 2021/09/15 - 14:23:46 | 200 |    4.437441ms |    192.168.0.29 | GET      "/nodes/61416aaa01eeaa627dc6c38c/langs"
[GIN] 2021/09/15 - 14:23:46 | 200 |    8.759655ms |    192.168.0.29 | GET      "/nodes/61416c9401eeaa627dc6c3d4/langs"
[GIN] 2021/09/15 - 14:23:46 | 200 |   10.066907ms |    192.168.0.29 | GET      "/nodes/61416c7601eeaa627dc6c3ce/langs"
[GIN] 2021/09/15 - 14:23:52 | 200 |     753.459µs |    192.168.0.29 | GET      "/spiders?page_num=1&page_size=10&sort_key=&keyword=&type=all&project_id=&owner_type=me"
[GIN] 2021/09/15 - 14:23:56 | 200 |    4.132902ms |    192.168.0.29 | GET      "/nodes/61416aaa01eeaa627dc6c38c/langs"
[GIN] 2021/09/15 - 14:23:56 | 200 |    9.620434ms |    192.168.0.29 | GET      "/nodes/61416c7601eeaa627dc6c3ce/langs"
[GIN] 2021/09/15 - 14:23:56 | 200 |    9.369125ms |    192.168.0.29 | GET      "/nodes/61416c9401eeaa627dc6c3d4/langs"
[GIN] 2021/09/15 - 14:24:06 | 200 |    9.545563ms |    192.168.0.29 | GET      "/nodes/61416aaa01eeaa627dc6c38c/langs"
[GIN] 2021/09/15 - 14:24:06 | 200 |    9.437134ms |    192.168.0.29 | GET      "/nodes/61416c9401eeaa627dc6c3d4/langs"
[GIN] 2021/09/15 - 14:24:06 | 200 |   11.019194ms |    192.168.0.29 | GET      "/nodes/61416c7601eeaa627dc6c3ce/langs"
[GIN] 2021/09/15 - 14:24:07 | 200 |    1.084675ms |    192.168.0.29 | GET      "/spiders?page_num=1&page_size=10&sort_key=&keyword=&type=all&project_id=&owner_type=me"

**期望结果**
如何关闭这些

**Comment by tikazyq** [comment]
docker启动的么？
