### ISSUE TITLE
Runing spiders ?!

### ISSUE THREAD

**Issue by Nesma-m7md** [crawlab-team/crawlab#1006]
I can't run spider neither outside docker master container nor inside it
Inside i get this error after typing: crawlab upload spider
Not authorized
Error loging in

Out side i only can upload zip file and it's not connected to my script and doesn't returen any data

Any help?!

**Comment by tikazyq** [comment]
Can you provide more information like what you have done and what error logs you have?

**Comment by Nesma-m7md** [comment]
I followed this for installing
https://hub.docker.com/r/tikazyq/crawlab

After that i'm trying to run my scraper.py using crawlab
Uploading zip is runing and every thing but it's not connected to my source path file nor to mongo, so my source file isn't acctualy running

Is there any thing should i add to it?

 I tried cli by typing crawlab upload spider inside docker master container where i copyied my py file i get the error above , and i really don't think this is the best way to run it coase i don't want to copy all my files there

I don't know what i missing?!

I'm new to using crawlab and cann't find any guidness to run my scrapers

Thanks in advance

**Comment by tikazyq** [comment]
Have you tried something in the documentation https://github.com/crawlab-team/crawlab-docs/blob/master/en/Integration/Scrapy.md

**Comment by Nesma-m7md** [comment]
I tried to add this line yes, this change nothing

**Comment by Nesma-m7md** [comment]
I tried following the nothing changed
https://pypi.org/project/crawlab-sdk/
 For GENERAL PYTHON SPIDER INTEGRATION

**Comment by tikazyq** [comment]
Can you share some of your code in the spider?

**Comment by Nesma-m7md** [comment]
Ok i'll as soon as i solve my new problem, i cann't log in to localhost:8080 it says your network is upnormal cann't connect to server, i've changed nothing why is this happening?

**Comment by Nesma-m7md** [comment]
I tried more than one code, every time i get this 
![IMG-20210916-WA0002](https://user-images.githubusercontent.com/90795794/133675671-3dfb53e4-7943-4fa4-91c3-eec5275d5066.jpg)

And nothin in mongo!!

**Comment by tikazyq** [comment]
Have you use `save_item` from `crawlab-sdk`?

**Comment by Nesma-m7md** [comment]
I used save_item from crawlab,
Pip instal crawlab-sdk returning errors and not working for me

**Comment by tikazyq** [comment]
Can you paste the error messages?

**Comment by Nesma-m7md** [comment]
![Screenshot_20210917-060024_Gallery](https://user-images.githubusercontent.com/90795794/133722154-0208ecf1-ddc7-4e81-95f9-5b13a01be190.jpg)
![Screenshot_20210917-060129_Gallery](https://user-images.githubusercontent.com/90795794/133722222-f717c54e-ba03-4ddc-b6c9-7b18bc4b27e0.jpg)
![Screenshot_20210917-060141_Gallery](https://user-images.githubusercontent.com/90795794/133722231-a7471afe-65fa-47fe-b17b-c1cf651fa2ee.jpg)

And i did run pip install psycopg2-binary 
Still having error

**Comment by tikazyq** [comment]
I would suggest you use docker to make things easier.

**Comment by Nesma-m7md** [comment]
I'm using docker, you mean to type pip install crawlab-sdk inside the container? I've already did, crawlab upload is  not working from inside container

If you run a spider can you till me what is the steps i should follow?

**Comment by tikazyq** [comment]
I think your `Execute Command` should not be `python` only. It should be something like `python main.py`. I think you forgot to add a script name or script path to it.

**Comment by Nesma-m7md** [comment]
Oh thanks , i was typing that at first donn't know why forgott!!
Thinks this is what was missing!
