### ISSUE TITLE
v0.5.1的代码无法创建docker镜像

### ISSUE THREAD

**Issue by lanjing99** [crawlab-team/crawlab#1007]
我对v0.5.1的代码创建docker镜像，
docker build -t wenjing/crawlab .
遇到下面的错误
[frontend-build 4/4] RUN yarn install && yarn run build:prod:

日志详情：
[install_log.txt](https://github.com/crawlab-team/crawlab/files/7175648/install_log.txt)

**Comment by LiuHaiYang** [comment]
+1

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
