### ISSUE TITLE
Cannot rename file v0.6.0 beta

### ISSUE THREAD

**Issue by anhtai1907** [crawlab-team/crawlab#1008]
**Describe the bug**
After choosing to rename the file on the interface, there is no message of success or failure, when I check the network, I see HTTP Code 500

**To Reproduce**
1. Go to http://localhost:8080/#/spiders/<spider_id>/files
2. Click on 'rename'
3. F12 (if you use Google Chrome) or inspect network

**Expected behavior**
Can rename a file via UI

**Screenshots**

![image](https://user-images.githubusercontent.com/59684727/133743480-ba7fb6e2-189b-4ea5-9250-ed6566927e56.png)

![image](https://user-images.githubusercontent.com/59684727/133743453-e1d5e3d9-ee20-490b-9597-5fcc55270e96.png)

**Comment by tikazyq** [comment]
Can you check the master node's container log?

**Comment by anhtai1907** [comment]
> Can you check the master node's container log?

This is container logs after I choose rename file
![image](https://user-images.githubusercontent.com/59684727/133761734-811332fd-5ec7-4d3b-b876-456d26b6000e.png)
