### ISSUE TITLE
v0.5.1启动性能问题

### ISSUE THREAD

**Issue by twinsant** [crawlab-team/crawlab#1009]
**Describe the bug**
当tasks很多时，启动非常慢.

**To Reproduce**
task超过9万条

**Expected behavior**
后端仍然快速启动

**Screenshots**
 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/299586/135202230-2ff8eeae-fa4a-414c-aac1-5ee4cb5c68cc.png">

**Comment by tikazyq** [comment]
noted。可以先删掉一部分老数据临时解决
