### ISSUE TITLE
上传文件失败

### ISSUE THREAD

**Issue by liaojin0914** [crawlab-team/crawlab#1014]
![image](https://user-images.githubusercontent.com/18436148/137587012-2e2e089d-cf21-4234-a354-a9f0a6ac2ac0.png)
上传文件保存提示成功上传后，相应新建的spider文件夹没有对应文件，而是空。
![ab7b9274d1e5f68015154983ce87987](https://user-images.githubusercontent.com/18436148/137587057-b46e5e4d-9521-40e8-aa79-4847233ef374.png)
![image](https://user-images.githubusercontent.com/18436148/137587133-2c31cb7e-2d95-4bd1-a9d5-7d6285649942.png)

**Comment by tikazyq** [comment]
Duplicated in https://github.com/crawlab-team/crawlab/issues/1022
