### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by Nesma-m7md** [crawlab-team/crawlab#1016]
i have a spider which been running for a month now perfectly and suddenly this error happened any help?!  
![Capture](https://user-images.githubusercontent.com/90795794/138060678-355edf70-5e6c-4b57-9fc3-6f8150e64906.PNG)

**Comment by Nesma-m7md** [comment]
But spider still working on another crawlab machine.

**Comment by tikazyq** [comment]
It might be that this machine's IP is blocked by the target site.
