### ISSUE TITLE
0.6版本无法自动安装requirements.txt的依赖库文件，而且没有界面可以主动给节点安装依赖库。

### ISSUE THREAD

**Issue by ljq29** [crawlab-team/crawlab#1017]
0.6版本无法自动安装requirements.txt的依赖库文件，而且没有界面可以主动给节点安装依赖库。

![Snipaste_2021-10-23_20-47-03](https://user-images.githubusercontent.com/25943689/138558860-0d6f56be-ab6b-4f41-b1ff-370a3077cf44.png)
![Snipaste_2021-10-23_21-38-31](https://user-images.githubusercontent.com/25943689/138558871-93976628-5cb9-4243-9cba-b6950caa00e6.png)

![image](https://user-images.githubusercontent.com/25943689/138558850-1ec3f1e5-cbde-4eeb-ab72-e8451f93db38.png)

**Comment by tikazyq** [comment]
暂时是不行的，可以拉取最新的代码，然后尝试安装dependency这个插件。

https://github.com/crawlab-team/plugin-dependency

**Comment by Kohtie** [comment]
> 暂时是不行的，可以拉取最新的代码，然后尝试安装dependency这个插件。
> 
> https://github.com/crawlab-team/plugin-dependency

Have the same problem. I did everything with doc, but it's doesn't work for me. I already install an official plugin for dependencies, but there is no guide how to use it. Can you explain please how to use that plugin?

**Comment by tikazyq** [comment]
> 

Thanks for using it. However, it seems plugin-dependency has something off and I am now trying to fix it. In the meantime, you can try the steps below to manually install dependencies.

```bash
docker exec -it <container_id> bash

pip3 install <packages>
```

**Comment by tikazyq** [comment]
You can now install dependencies on web UI in Crawlab, with [plugin-dependency](https://github.com/crawlab-team/plugin-dependency). This is a plugin that helps you install and manage dependencies on Crawlab. You can also check the documentation here: https://docs-next.crawlab.cn/zh/guide/use-crawlab/public-plugins/plugin-dependency.html
