### ISSUE TITLE
0.5.1版本爬虫列表不显示

### ISSUE THREAD

**Issue by loadingin** [crawlab-team/crawlab#1021]
**Bug 描述**
当点击爬虫列表的，数据库中有爬虫数据，爬虫列表不能正常显示。

**复现步骤**
该 Bug 复现步骤如下
1. 上传爬虫
2. 打开爬虫列表

**截屏**
![image](https://user-images.githubusercontent.com/17758014/140880726-0f21691d-e2ce-485f-aa46-9ca1ed60cb37.png)
![image](https://user-images.githubusercontent.com/17758014/140880909-0a0cf48c-b1e7-4f16-a796-fc17c00267e9.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
