### ISSUE TITLE
0.6.0 Spider 无法上传文件，只能上传目录

### ISSUE THREAD

**Issue by CrazyMouse** [crawlab-team/crawlab#1022]
**Bug 描述**
Spider 无法上传文件，只能上传目录
目前测试最新chrome和safari都是同样问题
版本0.6.0

没有网络通信，页面提示一个没有文字显示的红框

**截屏**
![image](https://user-images.githubusercontent.com/1176862/141718980-d09e9f55-0a85-498e-86b1-5df527fc8975.png)

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab-ui/commit/8a002146ae370e03cc5a70b4ddd5c123fc5ae463
