### ISSUE TITLE
dependency安装依赖错误问题 rpc error: code = Unknown desc = grpc error: stream not found

### ISSUE THREAD

**Issue by loadingin** [crawlab-team/crawlab#1028]
**Bug 描述**
安装完dependency插件之后一直报错
并且项目中的requirements.txt依赖文件也无法正常安装

**复现步骤**
该 Bug 复现步骤如下
1. 
2. 
3. 

**期望结果*
dependency插件能工作。

**截屏**
![ca09367949f5f232d7e6b4383e5f7e5](https://user-images.githubusercontent.com/17758014/142976032-360f5951-45d6-4665-a2ad-9202db873988.png)
![4a09d35999cb6a0ba12ab397649067f](https://user-images.githubusercontent.com/17758014/142976036-36693d7d-152b-41c5-b8cf-a2a8d887b466.png)

**Comment by tikazyq** [comment]
试试最新版本的插件系统
