### ISSUE TITLE
woker在执行一次后挂掉了

### ISSUE THREAD

**Issue by CrazyMouse** [crawlab-team/crawlab#1029]
images信息
![image](https://user-images.githubusercontent.com/1176862/143231961-8f7ba17b-f76d-449b-9daa-f71197354a24.png)
woker后台日志

![image](https://user-images.githubusercontent.com/1176862/143231989-a2a39513-e54e-45dd-8bb6-b5f8b69d0f88.png)

**Comment by tikazyq** [comment]
有对应的master上的日志么

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab-core/commit/9e9d77549f3624fefc0da4a63a4acd83d79c03a2
