### ISSUE TITLE
"TypeError: res is undefined" when i tried to sign in

### ISSUE THREAD

**Issue by Kohtie** [crawlab-team/crawlab#1032]
I did everything according to the instructions from GitHub. When I try to login, I get an error "TypeError: res is undefined". Please, help me to resolve that problem
![Screenshot from 2021-12-10 22-41-58](https://user-images.githubusercontent.com/18247002/145601186-d5df5e34-f58e-4484-9c80-039141f0f0d0.png)
![Screenshot from 2021-12-10 22-41-41](https://user-images.githubusercontent.com/18247002/145601204-560009c9-138d-4eed-899b-1dbb67295a56.png)
![Screenshot from 2021-12-10 22-44-24](https://user-images.githubusercontent.com/18247002/145601267-8dff341e-65f9-47e5-93d6-eb52b80940e8.png)

**Comment by tikazyq** [comment]
Can you show me the logs of master node?

**Comment by Kohtie** [comment]
> Can you show me the logs of master node?

Sorry, can you tell me where i can found that logs?

**Comment by Kohtie** [comment]
> Can you show me the logs of master node?
admin:///var/lib/docker/containers/3c2a86430ee99ec57bdc3ee90472c1153fa0a328f152d6b7a6dadd9127f05edf/3c2a86430ee99ec57bdc3ee90472c1153fa0a328f152d6b7a6dadd9127f05edf-json.log

**Comment by Kohtie** [comment]
![Screenshot from 2021-12-11 23-40-51](https://user-images.githubusercontent.com/18247002/145684519-aae3ea15-41e0-4b4a-b9be-5b4c7c45a0b4.png)

**Comment by Kohtie** [comment]
> Can you show me the logs of master node?
![Screenshot from 2021-12-11 23-40-51](https://user-images.githubusercontent.com/18247002/145684533-948fd74b-ea2c-4b3f-9df8-e6a803f5eae6.png)

**Comment by Kohtie** [comment]
> Can you show me the logs of master node?

I checked a lite version, everything is working fine. But i still have an issue with full version

**Comment by tikazyq** [comment]
![image](https://user-images.githubusercontent.com/3393101/145920699-55abe494-b8f1-4a9f-80d2-339c24ffc636.png)

The issue seems to be from your mongo connection shown in the logs. Can you check if your mongo is running okay.

**Comment by Kohtie** [comment]
> ![image](https://user-images.githubusercontent.com/3393101/145920699-55abe494-b8f1-4a9f-80d2-339c24ffc636.png)
> 
> The issue seems to be from your mongo connection shown in the logs. Can you check if your mongo is running okay.

I installed oldest version of mongod 4.2, now master is started succesfully. Mongo is working, but exception is still here
![Screenshot from 2021-12-14 18-02-26](https://user-images.githubusercontent.com/18247002/145986517-55f76268-eb45-4027-b500-b136c8d20933.png)

**Comment by tikazyq** [comment]
I can see from your `docker ps` results that the mongo container is restarting, so something is definitely off there.

**Comment by Kohtie** [comment]
> I can see from your `docker ps` results that the mongo container is restarting, so something is definitely off there.

I reinstall my OS to Ubuntu 18.04 because i though the problem is something with Ubuntu 20. I tried to install mongodb from official site, tried to install mongodb 4.4, 4.2 and 5.0 (5.0 isn't works because there is troubles with avx support, my cpu dont support it). I tried to check the connection, i think everything is good. What i should try to fix that?
![Screenshot from 2021-12-14 20-12-51](https://user-images.githubusercontent.com/18247002/146005061-5e7f8b83-0f78-4402-be2e-8e7b7ef60e17.png)

**Comment by Kohtie** [comment]
> I can see from your `docker ps` results that the mongo container is restarting, so something is definitely off there.

It's decided. The whole problem was that in docker-compose.yml specified mongo:latest, so mongo 5.0 was used, and it is not supported on my CPU. Changed to mongo:3.6.3 and everything worked. Thank you so much for your help!
