### ISSUE TITLE
0.6数据页面bug

### ISSUE THREAD

**Issue by mydes** [crawlab-team/crawlab#1038]
**Bug 描述**
0.6版本：当爬虫把大量数据赋值到单一字段，点开数据页面后点其它页面都不会跳转，界面删除功能也不起作用

**复现步骤**
该 Bug 复现步骤如下
1. 爬取大量数据赋值到单一字段
2. 点开数据页面
3. 点击其它页面地址栏会动，一直停留在数据页面
4.试图利用界面的删除功能把整条数据删除，删除失效

**期望结果**
xxx 能工作。

**截屏**
![微信图片编辑_20211227135542](https://user-images.githubusercontent.com/58588344/147439288-ed575023-1d53-43ae-aa68-fb31964b4e69.jpg)

**Comment by tikazyq** [comment]
可以发一下 `name` 字段以及其他字段的详细信息么？

**Comment by mydes** [comment]
![微信图片编辑_20211230162546](https://user-images.githubusercontent.com/58588344/147734490-26b32c27-9f72-48d5-ad94-f698686d0d67.jpg)

**Comment by tikazyq** [comment]
可能是因为nested json的原因，回头测试下

**Comment by tikazyq** [comment]
可能是因为nested json的原因，回头测试下
