### ISSUE TITLE
scrapy目录结构问题

### ISSUE THREAD

**Issue by TalentedBastard** [crawlab-team/crawlab#1047]
上传爬虫之后，如果我的爬虫没有严格按照scrapy项目结构设置的话，在爬虫 - 爬虫详情 - scrapy设置里识别不到对应的文件，控制台也会提示错误

比如：scrapy的settings和pipeline、middleware在同一文件夹下，而我的爬虫把pipeline和middleware独立成了文件夹

**Comment by tikazyq** [comment]
请发一下具体的目录结构

**Comment by TalentedBastard** [comment]
items
	item1.py
	item2.py
	item3.py
middlewares
	middleware1.py
	middlewares2.py
spiders
	spider1.py
	spider2.py

大致类似这样

**Comment by tikazyq** [comment]
是0.6么？

**Comment by TalentedBastard** [comment]
我检查了一下是0.5.1，是docker-compose部署的

0.6修复了这个问题么？

**Comment by tikazyq** [comment]
0.6是以插件形式存在的([plugin-spider-assistant](https://github.com/crawlab-team/plugin-spider-assistant)), 不过你的问题也还没解决。这个应该是一个enhancement，而不是bug。先log在这里，后续考虑优化，请关注[plugin-spider-assistant](https://github.com/crawlab-team/plugin-spider-assistant)这个repo的更新

**Comment by tikazyq** [comment]
Please refer to https://github.com/crawlab-team/crawlab/issues/1054 for future update

**Comment by TalentedBastard** [comment]
谢谢回复
