### ISSUE TITLE
安装python第三方库提示暂无数据

### ISSUE THREAD

**Issue by oioie** [crawlab-team/crawlab#1048]
**Bug 描述**
我需要在我节点上安装python语言的playwright包时，提示暂无数据，不只是playwright，其他的如何包都是这样。
我使用的docker部署的。
**截屏**
![图片](https://user-images.githubusercontent.com/66261721/147849484-21922669-f4cd-4de4-bce2-80317ec02b7f.png)
![图片](https://user-images.githubusercontent.com/66261721/147849493-d45328ef-61fa-43c7-bfb5-c61cc07ac7e5.png)

**Comment by liuxizaxs** [comment]
请问问题解决了吗  我也遇到这个问题，搜索pandas也查不到

**Comment by luo-geng** [comment]
playwright 怎么安装浏览器
