### ISSUE TITLE
the binary data cause crawlab task stuck

### ISSUE THREAD

**Issue by cong-dc** [crawlab-team/crawlab#1053]
This line,the binary data cause crawlab0.6 task stuck,but will not stuck in version 0.5

The problem is in the line  'r.content' ,print this binary data causes crawlab0.6 task stuck (task always is in running status)

If comment this line, the task will finish in ten seconds

#=======code as below=========
#coding=utf8
import os
import sys
import requests
from bs4 import BeautifulSoup
import json
req = requests.session()
url = "http://www.cnblogs.com"
url = "http://news.cnblogs.com"
r = req.get(url=url)
print(r.content)      #-------->   this line,the binary data cause crawlab task stuck
#print(r.text)     #this line will not cause stuck
#soup = BeautifulSoup(r.text, 'html5lib', from_encoding='utf-8')
#soup = BeautifulSoup(r.text, 'html5lib')
soup = BeautifulSoup(r.text, 'html.parser')
sp = soup.find(id='news_list')
print(sp)
div_class = sp.find_all(class_='content')
for div in div_class:
  news_title = div.find(class_='news_entry').text.strip()
  news_link = div.find(class_='news_entry').a.get('href').strip()
  news_content = div.find(class_='entry_summary').text.strip()
  print("***"*20)
  print(news_title, news_link)
  print("\n")
  #[print("--"*10)]([url](url))
  print(news_content)
  print("\n")

**Comment by tikazyq** [comment]
You mean the task never ends?

**Comment by cong-dc** [comment]
> You mean the task never ends?

yes,task is in 'running' status for serval hours,

if not using 'print res.content',the task will finish in ten seconds.

code is as above
