### ISSUE TITLE
使用docker-compose部署 8080端口访问后弹出502 且不能输入账号密码

### ISSUE THREAD

**Issue by bupei98** [crawlab-team/crawlab#1055]
![](https://s3.bmp.ovh/imgs/2022/01/bba1ba8390d87416.png)

**Comment by tikazyq** [comment]
需要查看日志

`docker-compose logs master`

**Comment by whn24** [comment]
> 我用docker-compose部署v0.5.1的问题和这个一样，这里是我的日志，日志中说无法连接mongo数据库 ![image](https://user-images.githubusercontent.com/54256372/156316252-40af0be8-4deb-44ad-9615-5fcfa5e8cfab.png)

这个问题我自己解决了。出现的原因是mongodb没有正常运行，docker部署时拉取的镜像是mongodb:latest，目前最新版本的mongodb已经是5.x，需要带有AVX的CPU来运行，对于部分机器部署会有如下报错，：
![image](https://user-images.githubusercontent.com/54256372/158115464-fa4581fe-ca13-458f-92f7-5c74dd1f80f6.png)
这时可以将crawlab的docker部署文件改为mongo:4.4.6，改成一个4.x的版本，重新部署crawlab，crawlab就可正常运行

**Comment by superzw** [comment]
> > 我用docker-compose部署v0.5.1的问题和这个一样，这里是我的日志，日志中说无法连接mongo数据库 ![image](https://user-images.githubusercontent.com/54256372/156316252-40af0be8-4deb-44ad-9615-5fcfa5e8cfab.png)
> 
> 这个问题我自己解决了。出现的原因是mongodb没有正常运行，docker部署时拉取的镜像是mongodb:latest，目前最新版本的mongodb已经是5.x，需要带有AVX的CPU来运行，对于部分机器部署会有如下报错，： ![image](https://user-images.githubusercontent.com/54256372/158115464-fa4581fe-ca13-458f-92f7-5c74dd1f80f6.png) 这时可以将crawlab的docker部署文件改为mongo:4.4.6，改成一个4.x的版本，重新部署crawlab，crawlab就可正常运行

改成4.4可以

**Comment by dongloong** [comment]
我的是redis拒绝连接
![Image](https://github.com/user-attachments/assets/6e93075b-d767-421c-9b5d-77a79d002bfd)
