### ISSUE TITLE
安装官方插件plugin-dependency失败

### ISSUE THREAD

**Issue by Aunus** [crawlab-team/crawlab#1061]
**Bug 描述**
例如，在插件中安装官方插件plugin-dependency，显示已安装但无法启动，日志：[PLUGIN-dependency] chmod: cannot access './build/start': No such file or directory

**期望结果**
该plugin-dependency能工作。

v0.6.0社区版

**Comment by tikazyq** [comment]
> 我安装插件也是这个问，请问有解决方案吗？

是因为新的变更还没生效，等最新版本同步到master就可以了，估计周末搞定吧

**Comment by Foreverpy** [comment]
安装这个插件时，日志：[PLUGIN-dependency] sh: 0: Can't open ./bin/start.sh，
请问这个怎么解决

**Comment by tikazyq** [comment]
> 安装这个插件时，日志：[PLUGIN-dependency] sh: 0: Can't open ./bin/start.sh， 请问这个怎么解决

怎么安装的？

**Comment by Foreverpy** [comment]
https://github.com/crawlab-team/crawlab/issues/1061#issuecomment-1121763533
通过前端插件模块安装，可以安装成功
![image](https://user-images.githubusercontent.com/91273504/167526613-9509e064-6ae3-4eec-9aef-3fdf69c4cded.png)
但是无法启动插件，启动后就立即停止，查看docker日志记录：
![image](https://user-images.githubusercontent.com/91273504/167526710-e538bbfe-a62e-417e-907b-fd4584605c31.png)

**Comment by tikazyq** [comment]
是docker安装的么？

**Comment by Foreverpy** [comment]
https://github.com/crawlab-team/crawlab/issues/1061#issuecomment-1121925854
通过dockerhub，crawlabteam/crawlab镜像启动的项目

**Comment by liuxizaxs** [comment]
同样的问题，请问解决了吗
