### ISSUE TITLE
Integrate URLFrontier as a backend for URL storage

### ISSUE THREAD

**Issue by jnioche** [crawlab-team/crawlab#1062]
Hi, 

This is a question, not a bug report. 

[url-frontier](https://github.com/crawler-commons/url-frontier) is an API to define a [crawl frontier](https://en.wikipedia.org/wiki/Crawl_frontier). It uses gRPC and has a service implementation. It is crawler-neutral and is suitable to being used in a distributed environment.

How could URLFrontier fit within crawlab? Is there a similar abstraction over the URL storage? Is there something missing in URLFrontier's API?

Thanks

**Comment by tikazyq** [comment]
I am looking at [url-frontier](https://github.com/crawler-commons/url-frontier) and the concept behind it. This is interesting to me as it is quite useful in large-scale web crawling systems. But it seems your project has quite few documentation I can refer to. Would you let me know where I can look for more details?

**Comment by tikazyq** [comment]
For those who are unfamiliar with this topic, please refer to [this article](https://nlp.stanford.edu/IR-book/html/htmledition/the-url-frontier-1.html).

**Comment by jnioche** [comment]
@tikazyq  did you manage to have a closer look at URLFrontier?
