### ISSUE TITLE
 unknown error Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by Nesma-m7md** [crawlab-team/crawlab#1063]
Hi there Crawlab,

I'm running scrapper that uses selenium need (chrome & chromedrive) so I installed both inside the master container but I'm getting the following Error after RUN spider

" selenium.common exceptions WebDriverException: Message: unknown error Chrome failed to start: exited abnormally "
(unknown error DevToolsActivePort file doesn't exist)

how to solve this issue !!

**Comment by tikazyq** [comment]
Can you upload your detailed error logs here?

**Comment by Nesma-m7md** [comment]
![c](https://user-images.githubusercontent.com/90795794/153181178-e22eb23d-973a-4a4f-9556-f34693500d67.JPG)
