### ISSUE TITLE
English installation links are broken and return 404 errors

### ISSUE THREAD

**Issue by wahyd4** [crawlab-team/crawlab#1068]
**Describe the bug**

the following installation-related links return 404 error.

* https://docs.crawlab.cn/Installation/Docker.html
* https://docs.crawlab.cn/Installation/Direct.html
* https://docs.crawlab.cn/Installation/Kubernetes.html

**Expected behavior**

Actual docs

**Comment by tikazyq** [comment]
https://docs.crawlab.cn/en/Installation/Docker.html
https://docs.crawlab.cn/en/Installation/Direct.html
https://docs.crawlab.cn/en/Installation/Kubernetes.html
