### ISSUE TITLE
0.5.1版本定时任务无法自动启动

### ISSUE THREAD

**Issue by volleyball26** [crawlab-team/crawlab#1070]
**Bug 描述**
当 网页关闭时，定时任务功能不工作。

**复现步骤**
该 Bug 复现步骤如下
1. 设置定时任务 
2. 关闭网页

**期望结果**
定时任务 能工作。

**备注**
网页一直打开时，定时任务可以启动

**Comment by tikazyq** [comment]
保存了么？

**Comment by volleyball26** [comment]
![image](https://user-images.githubusercontent.com/54010676/154908233-7ebda53d-e3ce-42ec-87b4-5d4d799db44e.png)

**Comment by volleyball26** [comment]
是的，我提交并启用了定时任务，我不清楚是否是因为版本原因

**Comment by volleyball26** [comment]
> 保存了么？
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/54010676/155107544-ff28c664-6f2d-4b72-845e-9e169b36db0a.png">

是的，我提交并启用了定时任务，我不清楚是否是因为版本原因

**Comment by tikazyq** [comment]
查看一下是否是因为时区问题

**Comment by volleyball26** [comment]
> 查看一下是否是因为时区问题

我后来使用admin账户重新设置了定时任务、定时任务目前正常启动。谢谢之前的帮助。⭐️
