### ISSUE TITLE
Crawler的worker中报错 :cannot import name 'create_handler'

### ISSUE THREAD

**Issue by castle-boom** [crawlab-team/crawlab#1077]
**Bug 描述**
例如，当 xxx 时，xxx 功能不工作。
之前正常运行的爬虫，突然运行失败。
错误信息如下：
import crawlab
4File "/usr/local/lib/python3.8/dist-packages/crawlab/__init__.py", line 1, in
5from crawlab.crawler import Crawler
6File "/usr/local/lib/python3.8/dist-packages/crawlab/crawler.py", line 3, in
7from crawlab.utils import create_handler
8ImportError: cannot import name 'create_handler' from 'crawlab.utils' (/usr/local/lib/python3.8/dist-packages/crawlab/utils/__init__.py)
**复现步骤**
该 Bug 复现步骤如下
1. 
2. 
3. 

**期望结果**
 能工作。

**截屏**
![截屏1](http://static-docs.crawlab.cn/login.png)

**Comment by tikazyq** [comment]
pip install crawlab-sdk

**Comment by castle-boom** [comment]
> pip install crawlab-sdk



> pip install crawlab-sdk

感谢回复。但是看起来是已经有安装crawlab-sdk与crawlab的。
<img width="530" alt="image" src="https://user-images.githubusercontent.com/20089267/156875535-97f96e16-031e-4e45-8836-d7bd77dca4df.png">

**Comment by tikazyq** [comment]
`pip uninstall crawlab`

**Comment by castle-boom** [comment]
> `pip uninstall crawlab`

感谢回复。请问crawlab是会自动被重新安装吗？我卸载后，过一会会自动又装上了，是我这边设置的问题吗？比如requirements.txt?

**Comment by castle-boom** [comment]
如果有类似的问题，可以按照Marvin说的进行修复并检查requirements，如果还是不行，可以尝试两个都卸载后重装crawlab-sdk
