### ISSUE TITLE
schedule page not visible to public 

### ISSUE THREAD

**Issue by KiranBCh** [crawlab-team/crawlab#1092]
I've Cron Expression but not visible schedule page. Please find it.

**Comment by tikazyq** [comment]
Do you have any screenshot?

**Comment by KiranBCh** [comment]
Hi Team,

I've screenshot please check it.

**Comment by KiranBCh** [comment]
![Screenshot from 2022-04-10 17-56-32](https://user-images.githubusercontent.com/29542107/165223832-5dca5929-e402-4fbc-8c98-aa0207fd6469.png)
![Screenshot from 2022-04-10 17-56-50](https://user-images.githubusercontent.com/29542107/165223841-9b8f1a3c-4506-4742-bc35-6d934aaf947f.png)
Please check..

**Comment by voctenzuk** [comment]
> ![Screenshot from 2022-04-10 17-56-32](https://user-images.githubusercontent.com/29542107/165223832-5dca5929-e402-4fbc-8c98-aa0207fd6469.png) ![Screenshot from 2022-04-10 17-56-50](https://user-images.githubusercontent.com/29542107/165223841-9b8f1a3c-4506-4742-bc35-6d934aaf947f.png) Please check..

I have the same problem. In Chinese the schedule is displayed correctly

**Comment by tikazyq** [comment]
Please pull the latest docker image and try again. Should be fixed. If not, let's re-open and re-produce the issue.
