### ISSUE TITLE
crawlab upload 命令报错

### ISSUE THREAD

**Issue by lx1054331851** [crawlab-team/crawlab#1093]
不同的项目报不同的错误
![image](https://user-images.githubusercontent.com/12423206/162884122-3e077a4a-b5df-4ae2-a7aa-4f7056045330.png)
![image](https://user-images.githubusercontent.com/12423206/162884187-039da675-a506-473f-b4c8-4e8f10b244c0.png)

**Comment by tikazyq** [comment]
which version?
