### ISSUE TITLE
docker-compose up -d正常，容器都起来了，但是http://localhost:8080打不开？

### ISSUE THREAD

**Issue by 600ML** [crawlab-team/crawlab#1104]
求助：代码仓库clone下来后，docker-compose up -d正常，容器都起来了，但是http://localhost:8080打不开
![image](https://user-images.githubusercontent.com/5793023/166108710-f88cf6b3-922f-4f94-a80a-fe9f498f8e8d.png)

![image](https://user-images.githubusercontent.com/5793023/166108723-0bac97b9-f1fe-4f4f-9b06-0afa0dac7f5f.png)

![image](https://user-images.githubusercontent.com/5793023/166108734-e2ac0f0c-53ad-42bd-9bb5-b9c90d2a55b1.png)

version: '3.3'
services:
  master:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_master
    environment:
      CRAWLAB_BASE_URL: crawlab
      CRAWLAB_SERVER_MASTER: Y
      CRAWLAB_MONGO_HOST: mongo
    ports:
      - "8080:8080" # frontend port mapping 前端端口映射
    depends_on:
      - mongo
    # volumes:
    #   - "/var/crawlab/log:/var/logs/crawlab" # log persistent 日志持久化
  worker:
    image: crawlabteam/crawlab:latest
    container_name: worker
    environment:
      CRAWLAB_SERVER_MASTER: "N"
      CRAWLAB_MONGO_HOST: "mongo"
    depends_on:
      - mongo
    # volumes:
    #   - "/var/crawlab/log:/var/logs/crawlab" # log persistent 日志持久化
  mongo:
    image: mongo:latest
    #restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - "/opt/crawlab/mongo/data/db:/data/db"  # make data persistent 持久化
    # ports:
    #   - "27017:27017"  # expose port to host machine 暴露接口到宿主机

**Comment by 600ML** [comment]
镜像换成"tikazyq/crawlab:latest"就能正常访问
但是tikazyq跑起来后，创建爬虫，能爬到数据，显示结果集为空

**Comment by 600ML** [comment]
跑完爬虫后，出现名为test的db，里边存有刚爬到的数据

![image](https://user-images.githubusercontent.com/5793023/166140815-171b6cc1-6e8d-4884-bbb7-61f3be53d2d7.png)

**Comment by 600ML** [comment]
crawlab_test库里，也有一个名为test_spider_results的collection，但是没有数据
![image](https://user-images.githubusercontent.com/5793023/166140863-f15df808-132c-4f64-ae90-66c7016ed2ba.png)

**Comment by 600ML** [comment]
我猜查不到数据，是因为爬虫入错库，或查询查错库

**Comment by henryclw** [comment]
You could try replacing `CRAWLAB_SERVER_MASTER` to `CRAWLAB_NODE_MASTER`  #1105

**Comment by tikazyq** [comment]
fixed, refer for details in https://github.com/crawlab-team/crawlab/issues/1105

**Comment by tikazyq** [comment]
fixed, refer for details in https://github.com/crawlab-team/crawlab/issues/1105
