### ISSUE TITLE
Update documents required, inconsistent environment variable name, `CRAWLAB_SERVER_MASTER` and `CRAWLAB_NODE_MASTER`

### ISSUE THREAD

**Issue by henryclw** [crawlab-team/crawlab#1105]
**Describe the bug**

In the latest README, it's the `CRAWLAB_NODE_MASTER`

<https://github.com/crawlab-team/crawlab/blob/8ea596068a2b01ea4c75343f9844363f48d7fbf2/README.md#L79>

---

But in the older files, such as the `docker-compose.local.yml` file, it's the `CRAWLAB_SERVER_MASTER`

<https://github.com/crawlab-team/crawlab/blob/8ea596068a2b01ea4c75343f9844363f48d7fbf2/docker-compose.yml#L8>
<https://github.com/crawlab-team/crawlab/blob/8ea596068a2b01ea4c75343f9844363f48d7fbf2/docker-compose.local.yml#L10>

**What to do**

Maybe the documents should be updated? The latest image of `crawlabteam/crawlab` should use `CRAWLAB_NODE_MASTER`

**Comment by tikazyq** [comment]
Fixed in https://github.com/crawlab-team/crawlab-docs/commit/9684f8731e264bec3870b2826b055d554415f68f
