### ISSUE TITLE
通过网页前端打开上传后的文件，会出现文件内容清空的情况

### ISSUE THREAD

**Issue by Foreverpy** [crawlab-team/crawlab#1106]
通过 爬虫 -> 文件 双击打开文件时，有时候会出现文件中的内容全部清空的问题，这个有办法避免吗

**Comment by tikazyq** [comment]
正在解决

**Comment by lalalada-201281016** [comment]
+1

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab-core/commit/b82db7f8b4f4ec24df9b1f018e10c9d741fb3bc0
