### ISSUE TITLE
数据展示页面优化。

### ISSUE THREAD

**Issue by liziqiang0523** [crawlab-team/crawlab#1107]
在爬虫爬虫结果的数据展示页面 建议增加表格的长文本缩略展示功能。 类似各数据库软件。因为某个字段太长的时候会严重影响页面展示。

**Comment by liziqiang0523** [comment]
比如我把html 的内容保存到 html 字段，很长。 显示就乱了。

**Comment by tikazyq** [comment]
是哪个版本呢？

**Comment by liziqiang0523** [comment]
> 是哪个版本呢？

v6.0 社区版
