### ISSUE TITLE
localhost:8080 无法访问

### ISSUE THREAD

**Issue by ZhuJianan143** [crawlab-team/crawlab#1110]
拉取 crawlabteam/crawlab:0.6.0，yml文件和docker-compose启动后日志如图
![e0f15211af271996f567a1b68317775](https://user-images.githubusercontent.com/49135623/170030245-ba9b1812-2da2-4711-9f4b-bb573df4539d.png)
![dc2d4cd629e45c7644e32db09b2222f](https://user-images.githubusercontent.com/49135623/170030333-e4d15574-cf00-4d76-b280-a14839b010b0.png)

**Comment by tikazyq** [comment]
有更详细的日志么？

**Comment by Yuehua-Liu** [comment]
【需修改的 Config】
CRAWLAB_NODE_MASTER： Y -----> "Y"

我這樣修正就正常了

Worker Node 那邊的 YAML 文件也同理
CRAWLAB_NODE_MASTER：N -----> "N"

**Comment by ZhuJianan143** [comment]
> 【需修改的 Config】 CRAWLAB_NODE_MASTER： Y -----> "Y"
> 
> 我這樣修正就正常了，Login 畫面也都可以正常登入無誤
> 
> Worker Node 那邊的 YAML 文件也同理 CRAWLAB_NODE_MASTER：N -----> "N"
> 
> 目前官方的文件(網頁文件)都還是原本的 Y/N 參數 因此需要手動修改

已解决，多谢
