### ISSUE TITLE
爬蟲分配至子節點工作時，能調用子節點本機資料庫或本機網路磁碟機路徑嗎？

### ISSUE THREAD

**Issue by Yuehua-Liu** [crawlab-team/crawlab#1112]
### 【問題描述】
開發團隊您好，想請教一個小弟目前開發上的問題，關於子節點部分，自己目前有部分 PC 綁定購買的資料庫，因此過去若要透過爬蟲爬取固定資料庫的資料，都是要放在該 PC 端，才能串接該資料庫 API 使用。

若目前我想將該 PC 設定成子節點，由 Master Node 派發爬蟲任務至該 PC 端執行，這樣的話該爬蟲是否能夠讀取到本機端資料庫或者訪問本機資料夾呢？

另外，原本爬蟲在執行時會先開啟本機端 Anaconda 的 venv 作為環境，若改成以派發 Worker Node 執行，請問能夠仔入本機端的 venv 嗎？或者需要以 CrawLab 本身的 Python 依賴套件為主？

因為這個環境概念自己在文件中沒有看到，因此來這邊詢問，謝謝！

**Comment by tikazyq** [comment]
看起来是环境集成问题，可以考虑将Anaconda的环境安装在docker容器里，或者另外打包一个docker镜像集成anaconda的依赖

**Comment by Yuehua-Liu** [comment]
感謝回覆

那請問若是 Worker 本機端的資料庫/資料夾
被派發的爬蟲有辦法檢索嗎？

**Comment by tikazyq** [comment]
> 感謝回覆
> 
> 那請問若是 Worker 本機端的資料庫/資料夾 被派發的爬蟲有辦法檢索嗎？

您是指在Worker节点宿主机上的爬虫么？

**Comment by Yuehua-Liu** [comment]
> > 感謝回覆
> > 那請問若是 Worker 本機端的資料庫/資料夾 被派發的爬蟲有辦法檢索嗎？
> 
> 您是指在Worker节点宿主机上的爬虫么？

是的，就是當爬蟲被分配到 Worker 節點上執行時，該爬蟲能否使用 Worker 節點 Local 端的資料 (ex. 資料夾、檔案等)

**Comment by tikazyq** [comment]
> > > 感謝回覆
> > > 那請問若是 Worker 本機端的資料庫/資料夾 被派發的爬蟲有辦法檢索嗎？
> > 
> > 
> > 您是指在Worker节点宿主机上的爬虫么？
> 
> 是的，就是當爬蟲被分配到 Worker 節點上執行時，該爬蟲能否使用 Worker 節點 Local 端的資料 (ex. 資料夾、檔案等)

ok. noted

**Comment by Yuehua-Liu** [comment]
> > > 感謝回覆
> > > 那請問若是 Worker 本機端的資料庫/資料夾 被派發的爬蟲有辦法檢索嗎？
> > 
> > 
> > 您是指在Worker节点宿主机上的爬虫么？
> 
> 是的，就是當爬蟲被分配到 Worker 節點上執行時，該爬蟲能否使用 Worker 節點 Local 端的資料 (ex. 資料夾、檔案等)

請問一下，所以說這個 ISSUE 所描述的狀況，Crawlab  是有辦法檢索的嗎？

**Comment by tikazyq** [comment]
> 

看起来是可以解决的，需要花点时间看看如何实现，不过你也可以试试实现下 ;-)
