### ISSUE TITLE
官方插件无法启动（社区版v0.6.0）

### ISSUE THREAD

**Issue by Tereams** [crawlab-team/crawlab#1113]
**Bug 描述**
官方插件可以通过官方文档中的通过名称安装的方法正常安装，点击启动后会弹出 “启动成功” 标签，但是插件却没有启动：插件的状态栏没有发生变化；点击插件图标没有响应，打开浏览器控制台返回500.  docker-compose日志如图
![image](https://user-images.githubusercontent.com/106360504/170613455-113bfb7c-0954-4336-a2cf-7e9b7391b6de.png)

**复现步骤**
该 Bug 复现步骤如下
1. 按官方文档中的通过名称安装的方法安装
2. 点击启动插件
3. 插件无法启动

**期望结果**
官方插件能工作。

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/63b2f4283361aeb2e1a6e320764977d123cfb3d1

please pull the latest docker image

```bash
# pull latest image
docker pull crawlabteam/crawlab

# restart
docker-compose down
docker-compose up -d
```

**Comment by tikazyq** [comment]
fixed in latest release
