### ISSUE TITLE
v 0.6.0 版本 爬虫卡住， 停止后无法启动新任务

### ISSUE THREAD

**Issue by timewalkerF** [crawlab-team/crawlab#1118]
**Bug 描述**
v 0.6.0 版本  原先 v 0.5.0 版本不会卡死。

**复现步骤**
该 Bug 复现步骤如下
1. 爬虫不知道为什么卡死，然后之后任务全部变成待定。
2. 把运行中的任务和待定任务全部停止，然后重启容器。
3. 启动新任务还是待定。

**期望结果**
为什么会卡死，怎么样能启动新的任务。

**截屏**
![image](https://user-images.githubusercontent.com/30802962/172082768-4f3c8ea6-04d2-48ac-9ebd-dd3486090ccd.png)

**Comment by tikazyq** [comment]
日志可以导出一份么

**Comment by timewalkerF** [comment]
已经重新拉了一遍最新的docker镜像。日志都没了。下次吧

**Comment by tikazyq** [comment]
先关闭，后面出现了再reopen

**Comment by timewalkerF** [comment]
[crawlab.log](https://github.com/crawlab-team/crawlab/files/8888429/crawlab.log)

**Comment by timewalkerF** [comment]
![image](https://user-images.githubusercontent.com/30802962/173292855-59826ad9-d516-44b9-ba8d-bfb516fc8cb9.png)
scrapy爬虫没有结束

**Comment by timewalkerF** [comment]
不清除mongo 数据库里面的数据无法开始新的任务，就算没有运行中的任务并且重新拉取了crawlab 和 mongo 镜像。看页面是否需要提供对mongo 中的数据有个操作来让我可以开始新的任务。

**Comment by xuyilun** [comment]
请问你解决了吗，我也遇到 了这个问题

**Comment by timewalkerF** [comment]
> 你解决了，我也遇到了这个问题

没有，需要定时清理卡死的脚本。

**Comment by tikazyq** [comment]
duplicated in https://github.com/crawlab-team/crawlab/issues/1160
