### ISSUE TITLE
crawlab安裝依赖插件后无法在web端进行依赖安装

### ISSUE THREAD

**Issue by bestRunner** [crawlab-team/crawlab#1123]
**Bug 描述**
目前使用crawlabV0.6.0集群版，无法通过web端进行依赖安装，在设置中设置了代理也一样（代理设置为：Goproxy.cn），每次安装需要到各个节点的docker容器下，十分不方便且不安全。请问有何好的解决办法？

**期望结果**
能够在web端安装依赖。

**Comment by tikazyq** [comment]
拉取最新镜像是否可以解决问题？

**Comment by bestRunner** [comment]
> 拉取最新镜像是否可以解决问题？

目前目前还是报这个错误，镜像重新拉了一遍
![image](https://user-images.githubusercontent.com/36727232/173290014-120d23dd-96a8-44d6-923d-d3c9fb39512b.png)
![image](https://user-images.githubusercontent.com/36727232/173290103-eac792c5-3f0c-4d1b-a46c-650a592f9eb5.png)

**Comment by bestRunner** [comment]
已经解决了，最新版的去掉代理，可以安装成功
