### ISSUE TITLE
v0.6 爬虫名称在docker容器中显示问题

### ISSUE THREAD

**Issue by Yinhm-6** [crawlab-team/crawlab#1125]
**Bug 描述**
现阶段爬虫名称在docker容器中显示为密文，望改为明文，增强可读性。

**截屏**
<img width="533" alt="示例" src="https://user-images.githubusercontent.com/74165571/173319418-2aa8651a-ea1b-4c7a-af6c-6bf5c9106138.png">

**Comment by tikazyq** [comment]
Not planned at this moment
