### ISSUE TITLE
cannot download scrape results

### ISSUE THREAD

**Issue by gregorth** [crawlab-team/crawlab#1129]
**Describe the bug**
After scrapy task finished, I cannot download results. Button is disabled, tooltip says Export (currently unavailable)

**To Reproduce**
just run crawlab from basic docker-compose.yml
enter spiders, choose scrapy quotes, data tab at the bottom of the page button is disabled.

**Expected behavior**
I should be able to download fetched results in - at least- csv format. 

<img width="1728" alt="Screenshot 2022-06-17 at 10 21 02" src="https://user-images.githubusercontent.com/743438/174257923-5a272ed8-2e40-42d5-a953-9b228426cc07.png">

**Comment by gregorth** [comment]
I got this on latest docker-compose.yml so it should be tagged as 0.6 version

**Comment by tikazyq** [comment]
Yes, this is a WIP feature that needs to be implemented. Please subscribe this issue for future update.

**Comment by tikazyq** [comment]
implemented
