### ISSUE TITLE
Python dependency 安裝 "pyodbc" 套件一直無法成功

### ISSUE THREAD

**Issue by Yuehua-Liu** [crawlab-team/crawlab#1131]
### 【問題描述】
您好
我透過 Web UI 安裝 Python 的 pyodbc 套件時，都沒辦法成功，有些節點會顯示錯誤，有些則是一直跑圈圈，沒顯示成功與否
不知道這是因為什麼問題？

### 【Error Log】
`
running build
running build_ext
building 'pyodbc' extension
creating build
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/src
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYODBC_VERSION=4.0.32 -I/usr/include/python3.8 -c src/buffer.cpp -o build/temp.linux-x86_64-3.8/src/buffer.o -Wno-write-strings
In file included from src/buffer.cpp:12:
src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
56 | #include
Collecting pyodbc
Using cached pyodbc-4.0.32.tar.gz (280 kB)
Building wheels for collected packages: pyodbc
Building wheel for pyodbc (setup.py): started
Building wheel for pyodbc (setup.py): finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6g3x7c1w/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6g3x7c1w/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6fw9k9ou
cwd: /tmp/pip-install-6g3x7c1w/pyodbc/
Complete output (14 lines):
running bdist_wheel
| ^~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

ERROR: Failed building wheel for pyodbc
Running setup.py clean for pyodbc
Failed to build pyodbc
Installing collected packages: pyodbc
Running setup.py install for pyodbc: started
Running setup.py install for pyodbc: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6g3x7c1w/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6g3x7c1w/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-75gk25qf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pyodbc
cwd: /tmp/pip-install-6g3x7c1w/pyodbc/
Complete output (14 lines):
running install
running build
running build_ext
building 'pyodbc' extension
creating build
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/src
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYODBC_VERSION=4.0.32 -I/usr/include/python3.8 -c src/buffer.cpp -o build/temp.linux-x86_64-3.8/src/buffer.o -Wno-write-strings
In file included from src/buffer.cpp:12:
src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
56 | #include
| ^~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6g3x7c1w/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6g3x7c1w/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-75gk25qf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pyodbc Check the logs for full command output.
`

**Comment by tikazyq** [comment]
which version?

**Comment by Yuehua-Liu** [comment]
![image](https://user-images.githubusercontent.com/13415294/174760742-3d46353d-0408-4c8f-a388-f75a436c30c2.png)

最新版本的 pyodbc
看起來也無法選擇更新特定版本？

**Comment by tikazyq** [comment]
看起来插件没有启动，需要看看后端相关日志

`docker-compose logs master | grep dependency`

**Comment by Yuehua-Liu** [comment]
還有一個奇怪的事情
docker-compose down
再重新啟動後

我在「節點」頁面，發現主節點又會新增一個新的？
![image](https://user-images.githubusercontent.com/13415294/174782652-896d49e6-b19e-423c-aacd-21e13f171fe8.png)

**Comment by Yuehua-Liu** [comment]
重啟後 發現
「運行中」標示一直不會清除

![image](https://user-images.githubusercontent.com/13415294/174786972-66bc420f-5c15-4a0c-979a-615c40548756.png)

**Comment by tikazyq** [comment]
Perhaps you can join our wechat group for discussion in detail
