### ISSUE TITLE
插件安装成功，但无法启动（社区版v0.6）

### ISSUE THREAD

**Issue by a2011318824** [crawlab-team/crawlab#1132]
**Bug 描述**
   安装官方插件时，提示插件安装成功，但显示状态为“停止中”，无法启动（点击启动，虽然显示成功，但状态没有变化）。
查看后台日志，显示：'./build/start': No such file or directory'。
我已将镜像更新至最新，重启仍然不行。

**复现步骤**
该 Bug 复现步骤如下
1. 按照官方文档使用docker单节点部署
2. 设置安装源'gitee'，以及go代理'Goproxy.cn'
3. 安装插件 'plugin-spider-assistant'

**期望结果**
插件可以正常安装，并启用

**截屏**
![截屏1](http://static-docs.crawlab.cn/login.png)
![image](https://user-images.githubusercontent.com/50091372/174970500-448056db-9127-4f30-9e79-bc949316ff91.png)
![image](https://user-images.githubusercontent.com/50091372/174970596-48617fa9-bf13-4b1d-9ac4-5b3ffdc6bd1e.png)
![image](https://user-images.githubusercontent.com/50091372/174970648-99047288-1741-48d0-97f1-eecd832adee5.png)

**Comment by tikazyq** [comment]
镜像版本是多少，打印一下镜像的hash和大小

**Comment by a2011318824** [comment]
![Uploading image.png…]()
hash：a551feec72d491bf5f28bd8d8e725d8597a5f162a0f55e528f27b17c17bec364
size：1.45GB

**Comment by tikazyq** [comment]
请拉取最新镜像

https://hub.docker.com/layers/crawlabteam/crawlab/latest/images/sha256-3ee109e4a531f1910e9bbc0d614b94c85981aa9af1dc6b841f0a02d62fb0bc6f?context=explore

**Comment by a2011318824** [comment]
原来是docker镜像源的问题。国内的镜像源中，crawlab不是最新的
