### ISSUE TITLE
前端项目crawlab-ui，无法启动，是怎么回事呢，运行npm run build 和npm run serv都失败

### ISSUE THREAD

**Issue by fangwei0701** [crawlab-team/crawlab#1133]
**Bug 描述**
例如，当 xxx 时，xxx 功能不工作。

**复现步骤**
该 Bug 复现步骤如下
1. 
2. 
3. 

**期望结果**
xxx 能工作。

**截屏**
![截屏1](http://static-docs.crawlab.cn/login.png)

**Comment by tikazyq** [comment]
具体一点？
