### ISSUE TITLE
内存占用会一直涨

### ISSUE THREAD

**Issue by xuyilun** [crawlab-team/crawlab#1136]
内存占用会一直涨，这个能优化吗，或者如何控制，否则内存占用太高可能会被直接kill掉

**Comment by tikazyq** [comment]
有具体数据么？

**Comment by xuyilun** [comment]
> 有具体数据么？

我没有把数据输出到数据上面，我是直接在程序中输出了类似print的日志，并且直接把日志文件写到宿主机的(挂载了日志目录)

**Comment by tikazyq** [comment]
等我复测一下

**Comment by wf4867612** [comment]
我这边也是，尤其是mongo，时不时的被OOM
