### ISSUE TITLE
用scrapy运行时爬虫运行两条数据后日志会卡住，取消任务后数据就正常入库了

### ISSUE THREAD

**Issue by JayHolly-home** [crawlab-team/crawlab#1139]
**Bug 描述**
用scrapy运行时爬虫运行两条数据后日志会卡住，取消任务后数据就正常入库了

**复现步骤**
该 Bug 复现步骤如下
1. 运行scrapy crawl xxx
2. 日志爬取几条数据后就卡住，数据库也不进数据
3. 取消任务后，数据就正常入库了

**期望结果**
能够正常入库

**截屏**
![image](https://user-images.githubusercontent.com/72968910/177460093-f54ed9c3-d629-4915-9d3d-829171877eb1.png)

**Comment by JayHolly-home** [comment]
![image](https://user-images.githubusercontent.com/72968910/177461890-1c18c4d6-c04c-45cf-b5f5-c999768e652d.png)
本地用这个方法就可以正常插入

**Comment by tikazyq** [comment]
用 `crawlab-sdk`，请参考这里 https://docs.crawlab.cn/zh/guide/basic-tutorial/#%E5%88%9B%E5%BB%BA%E7%88%AC%E8%99%AB

```python
from crawlab import save_item

...
save_item(item) # here to insert into mongo and integrate to crawlab
...
```
