### ISSUE TITLE
获取最新镜像后，第一次打开就多出很多爬虫项目或者其他内容

### ISSUE THREAD

**Issue by ZhuJianan143** [crawlab-team/crawlab#1140]
因为v0.6.0安装插件一直失败，拉取最新镜像后，插件能安装成功，但是第一次打开就存在很多用户、爬虫、项目等等，感觉latest镜像体积也比0.6.0要大出不少

**Comment by tikazyq** [comment]
这是因为首次加载会将demo数据加载进来，后续会调整一下

**Comment by tikazyq** [comment]
attempted to fix in https://github.com/crawlab-team/crawlab-core/commit/53097a1f65d13aa763eddb655a1a7bddde37817e
