### ISSUE TITLE
修改配置非一台机器部署seaweedfs时，调用/logs接口还是走了 localhost:8888，导致无法查看日志

### ISSUE THREAD

**Issue by jjzhoujun** [crawlab-team/crawlab#1144]
**Bug 描述**
源码编译，当seaweedfs和master程序不在同一服务器部署时候，修改default_config.go里的 seaweedfs 的路径，在上传文件时候正常，但是查看 /logs/{id} 对应的日志时候发现接口还是走 localhost:8888 ，导致无法正常读取。

**复现步骤**
该 Bug 复现步骤如下
1. crawlab主程序部署在 A服务器，seaweedfs部署在B服务器，修改主程序default_config.go 的seaweedfs访问地址指向B；
2. 上传爬虫，运行爬虫任务，查看日志，发现接口报500错误
3. 查看日志，发现还是走 localhost:8888来请求日志，没有走 B 地址的 8888 端口。如下图所示。

**期望结果**
查看任务日志的能工作。

**截屏**
![e7ede87a968f69e2ba1159b5b029450](https://user-images.githubusercontent.com/5793642/179363153-02c854e3-8045-4232-8c9d-48087ee58d0d.png)
![c8bc89811f778fe3d5a09348717bfc4](https://user-images.githubusercontent.com/5793642/179363160-ce17fdde-5a57-4fa0-aec7-5f6ca9593b21.png)
![9417419bc7a1e6d55b08c93d5e97ef5](https://user-images.githubusercontent.com/5793642/179363161-cc76c982-c09c-4e6c-96fe-dcbdd2555197.png)

**Comment by tikazyq** [comment]
设置环境变量 `CRAWLAB_FS_FILER_PROXY`

**Comment by tikazyq** [comment]
是否已经修复？ @jjzhoujun
