### ISSUE TITLE
添加爬虫无法自定义名字与路径

### ISSUE THREAD

**Issue by 1941198** [crawlab-team/crawlab#115]
爬虫项目已经建立好，有些爬虫共用许多东西区别不大，在一个目录中已经定义好了。 这时想要上传爬虫必需分开建立目录上传，无法自定义一个名字与指定路径来当爬虫项目。

**Comment by tikazyq** [comment]
好问题！对于需要加参数执行的爬虫，功能已经在开发了，请关注 https://github.com/tikazyq/crawlab/issues/31

**Comment by tikazyq** [comment]
crawlab可以添加爬虫程序的参数了，这样可以在一个项目中通过传参的方式执行多个爬虫

fixed in https://github.com/crawlab-team/crawlab/commit/50132334811d1a6c58422c346d2fb81806e12c25
