### ISSUE TITLE
v0.6.0定时任务未及时生效 和 cron表单bug

### ISSUE THREAD

**Issue by DUnionCY** [crawlab-team/crawlab#1158]
**Bug 描述**
在v0.6.0 中定时任务在修改cron后，未实时生效，需要点击开启关闭按钮后才能生效
在新建定时任务后，点击查看的新建任务 Cron表达式input中可以填写任意内容并保存

**Comment by J0o1h** [comment]
@tikazyq  这个修复了吗？

**Comment by tikazyq** [comment]
看起来无法复现，本地测试是没问题的，后面如果出现可以再re-open
