### ISSUE TITLE
如何搭建开发环境

### ISSUE THREAD

**Issue by zplzpl** [crawlab-team/crawlab#1159]
**请描述该需求尝试解决的问题**
本地环境，作者是怎么搭建开发和调试的环境？也是基于docker吗？

**Comment by tikazyq** [comment]
文档还不完善

**Comment by xiaoliangnuomi** [comment]
不要尝试去搭建他的开发环境，无论是前端ts还是后端的go，他的代码封装的太厉害了，能累死人，我建议能用就用，不能用，就直接放弃。

**Comment by zplzpl** [comment]
已经搭建出来
