### ISSUE TITLE
爬虫任务重新运行疑问

### ISSUE THREAD

**Issue by Mankvis** [crawlab-team/crawlab#1163]
目前在创建爬虫的时候，命令输入空格为空，因为一个项目有多个爬虫文件，所以创建爬虫后，手动添加多个不同爬虫的任务，点击重新运行后，运行的命令则为创建的 空 命令。

重新运行不应该是在点击 运行 时输入的命令吗

**Comment by tikazyq** [comment]
不太理解什么意思？
