### ISSUE TITLE
权限控制不完整

### ISSUE THREAD

**Issue by lixingpu** [crawlab-team/crawlab#117]
前端注册后即可登录看到爬虫内容并且还可以修改删除爬虫，权限控制不全

**Comment by tikazyq** [comment]
duplicated with https://github.com/crawlab-team/crawlab/issues/608

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/7e343cdde1a2540a28bcfdc08ea106a728218e54
