### ISSUE TITLE
worker node run task pending

### ISSUE THREAD

**Issue by zplzpl** [crawlab-team/crawlab#1172]
**Bug 描述**

按TEST目录运行master\worker1两个节点，指定worker1节点运行，发现task一直处于pending；

**复现步骤**
该 Bug 复现步骤如下
1. 起master节点
2. 起worker1节点
3. 运行spider指定worker1节点运行任务

**期望结果**
任务正常运行

**截屏**

基本定位到代码有问题的地方：（怀疑是依赖注入的对象，是未运行Register()的Client）
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/7931755/185986043-9e056dfa-57b1-433d-98bb-c86101cde715.png">

一直再重试。
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/7931755/185986182-c04b7490-20ba-4918-a44c-d61a14c35a6b.png">

**Comment by zplzpl** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/7931755/185991230-a53a2b18-71cf-40f4-83ac-61c4d9dbc3bb.png">

大概定位到问题。

CRAWLAB_CONFIG_PATH=./test/config-worker-01.json;CRAWLAB_NODE_MASTER=N

config_path没有使用环境变量；

**Comment by zplzpl** [comment]
这代码封装，让我咬牙切齿，依赖注入，让依赖管理变得混乱。

**Comment by tikazyq** [comment]
why do you test master and worker nodes on the same machine?

**Comment by tikazyq** [comment]
> 我想从源代码编译运行。并且进行调试。

I would suggest using VM to debug distributed system
