### ISSUE TITLE
工作节点连接不稳定

### ISSUE THREAD

**Issue by motingjun** [crawlab-team/crawlab#1173]
docker多节点部署，mongo使用的是外部连接方式，工作节点经常显示离线，过一会又显示正常在线，一般这种情况是什么原因导致？会不会后期影响任务正常运行？

- 异常情况：

![image](https://user-images.githubusercontent.com/43468078/186051552-30d3d1da-3d55-4b9a-9e20-7ec89699d625.png)

- 正常情况：

![image](https://user-images.githubusercontent.com/43468078/186051631-f71eef52-5e7a-49f1-871f-d39dec08a356.png)

**Comment by tikazyq** [comment]
是否可以将每个节点的日志上传看看？

**Comment by motingjun** [comment]
- 异常节点：

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/43468078/186061486-d5dda478-5f1b-4115-8001-ced1f9b1100b.png">

- 正常节点：

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/43468078/186061636-6ed7bd4a-914b-4ff6-9ce2-cd89d5c1caa0.png">

**Comment by tikazyq** [comment]
看起来异常节点无法连接9666这个端口，这个端口是grpc节点通信用的。需要检查一下该异常节点与主节点的连接情况
