### ISSUE TITLE
docker-compose部署，重启导致之前数据全部丢失

### ISSUE THREAD

**Issue by motingjun** [crawlab-team/crawlab#1179]
**Bug 描述**
docker-compose 部署的crawlab，mongo采用的是外部部署方式，但是每次用docker-compose start 重启容器以后，里面的数据就全部没有了，全部变为了初始部署时候测试案例数据！之前添加的新用户数据全部没有了。

**复现步骤**
该 Bug 复现步骤如下
1. docker-compose up -d
2. docker-compose stop
3. docker-compose start

**期望结果**
1.服务可以正常重启、停止，部署项目数据不被篡改；
2.哪里可以配置任务日志定期删除的配置选项；

**截屏**
![image](https://user-images.githubusercontent.com/43468078/188345908-d33ff14b-7f4b-40ba-87c6-b8040fd67fcf.png)
![image](https://user-images.githubusercontent.com/43468078/188345982-c93bcdeb-ff2c-4d62-9c54-523da6ebbf54.png)
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/43468078/188346074-3f64a13a-3fdd-47cf-8936-2b98d224ce65.png">

**Comment by tikazyq** [comment]
用最新镜像

**Comment by motingjun** [comment]
可以了，感谢~

**Comment by motingjun** [comment]
> 用最新镜像

可以了，感谢~
