### ISSUE TITLE
日志路径错误

### ISSUE THREAD

**Issue by li904775857** [crawlab-team/crawlab#1181]
**Bug 描述**
crawlab和seaweedfs不在同一台机器上时，配置了CRAWLAB_FS_FILER_PROXY路径，还是会出现
Get "http://localhost:8888/logs/63183f8c1daf1288cdc1a0b8/00000000": dial tcp [::1]:8888: connect: connection refused

**配置文件**
![1662537364586](https://user-images.githubusercontent.com/43633294/188822532-cffd40d6-211c-4e11-9b08-58676098d98d.png)

**错误日志**
![1662537404048](https://user-images.githubusercontent.com/43633294/188822671-8aab12ce-c659-4e71-abb4-fa4d5cf2db02.png)

**Comment by Roc826** [comment]
碰到了同样的问题，定位到了crawlab-fs 下的seaweedfs_manager.go NewSeaweedFsManager这个函数硬编码了seaweedfs的地址
![image](https://user-images.githubusercontent.com/44332309/191233578-4164fc42-5052-453c-b161-2a7ba92750d3.png)

**Comment by tikazyq** [comment]
不再使用seaweedfs作为日志储存
