### ISSUE TITLE
已不在运行状态的爬虫，点击取消后，显示尝试取消，但是取消不掉。

### ISSUE THREAD

**Issue by w8741906** [crawlab-team/crawlab#1182]
**Bug 描述**
例如，当 爬虫已不在工作节点运行时，Crawlab的管理平台显示仍然是运行中，这时候使用取消任务功能，无效。

**复现步骤**
该 Bug 复现步骤如下
1. 执行爬虫任务
2. 爬虫任务不知道是正常结束还是中止了，但是已不运行了
3. 在Crawlab的任务功能中，点击“取消”，无反应，爬虫工作节点日志如下：
task error: not exists
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220820100747-949070004761/task/handler/service.go:255 github.com/crawlab-team/crawlab-core/task/handler.(*Service).getRunner()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220820100747-949070004761/task/handler/service.go:107 github.com/crawlab-team/crawlab-core/task/handler.(*Service).Cancel()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220820100747-949070004761/node/service/worker_service.go:134 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).handleStreamMessage()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220820100747-949070004761/node/service/worker_service.go:108 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Recv()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
task error: not exists
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220820100747-949070004761/task/handler/service.go:255 github.com/crawlab-team/crawlab-core/task/handler.(*Service).getRunner()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220820100747-949070004761/task/handler/service.go:107 github.com/crawlab-team/crawlab-core/task/handler.(*Service).Cancel()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220820100747-949070004761/node/service/worker_service.go:134 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).handleStreamMessage()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220820100747-949070004761/node/service/worker_service.go:108 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Recv()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
4、从日志中可以看到，取消任务时，已经找不到该任务了。

**期望结果**
在这种状态下，任务的状态能够显示为“已取消”或“！异常”。

**Comment by tikazyq** [comment]
看起来应该是任务被删除了
