### ISSUE TITLE
requirements.txt文件解析错误

### ISSUE THREAD

**Issue by blackchery** [crawlab-team/crawlab#1194]
**Bug 描述**
在爬虫项目中添加requirements.txt文件，当文件中python依赖包名称中包含中杠字符“-”时，无法正确解析包名。

**复现步骤**
该 Bug 复现步骤如下
1. 项目根目录添加requirements.txt文件
2. 文件中添加依赖信息如：mq-http-sdk==1.0.3
3. 点击爬虫项目中“依赖“tab页，无法正确显示依赖内容。

![1665281578465](https://user-images.githubusercontent.com/16129929/194734390-e2ad0574-c1fc-4e89-94f8-123348bcf5e3.png)
![1665281593484](https://user-images.githubusercontent.com/16129929/194734393-a961f7c7-f21e-4be3-b9fc-6c4eaabb127c.png)

**Comment by tikazyq** [comment]
无法复现
