### ISSUE TITLE
上传的文件在一段时间后显示不出来

### ISSUE THREAD

**Issue by XMQ66** [crawlab-team/crawlab#1195]
在一周前上传的文件，今天打开都是空白的
![image](https://user-images.githubusercontent.com/115385096/194736527-5a47d622-af3f-4306-bfd1-ed82faaa21ab.png)
查看docker后报错如下：
![image](https://user-images.githubusercontent.com/115385096/194736565-4b494a66-8440-4989-bc28-0a78d4d14e8b.png)

**Comment by tikazyq** [comment]
有更详细的日志么？

**Comment by XMQ66** [comment]
![image](https://user-images.githubusercontent.com/115385096/194749063-0f42755e-2f82-4c66-a6df-bb86f613baa4.png)

**Comment by XMQ66** [comment]
就是点击已经上传文件显示是空的，
![image](https://user-images.githubusercontent.com/115385096/194749131-68480ed0-704e-4692-bf2f-402c3211f9a6.png)

**Comment by tikazyq** [comment]
看上去应该是没有持久化 `/data` 这个目录。

在 `docker-compose.yml` 文件中加入这个配置
```yaml
...
    volumes:
      - /opt/crawlab/data:/data # 持久化 /data 目录
...
```

**Comment by tikazyq** [comment]
或者尝试重启主节点

**Comment by XMQ66** [comment]
好的，我试试看
重启可以解决，但是过一段时间不知道会不会反复出现

**Comment by XMQ66** [comment]
![image](https://user-images.githubusercontent.com/115385096/194749509-8d18e89e-1a22-46f0-ab25-fe6e35aaf7ab.png)
这个我有加上去

**Comment by tikazyq** [comment]
如果还出现问题 pin 我，到时reopen
