### ISSUE TITLE
master节点内存还是在慢慢涨

### ISSUE THREAD

**Issue by Lounin** [crawlab-team/crawlab#1196]
**Bug 描述**
开了一台测试4G内存的测试服务器，使用docker拉去最新镜像部署后，只开一个简单的py任务，设置定时5分钟执行一次，主节点占用的内存随时间仍然在慢慢增长

**复现步骤**
该 Bug 复现步骤如下
1. docker-compose部署
2. 开启一个.py文件，内容为简单两数相加运算，设置定时5分钟执行一次

**期望结果**
主节点内存不会泄露

**截屏**
![mempic](https://user-images.githubusercontent.com/93168838/194793689-97e6096f-8a81-47a0-90cd-bb1400d75f0a.png)
服务器内存增长

![dockercompose1](https://user-images.githubusercontent.com/93168838/194794040-b408d58e-9722-4bcc-b835-714093890034.png)
![dockercompose2](https://user-images.githubusercontent.com/93168838/194794047-c646a2d5-eae7-4e51-bbac-479625a2f672.png)

![pyfile](https://user-images.githubusercontent.com/93168838/194793707-a8739ed7-ca1b-4fc8-9d68-78182bc74ad0.png)
执行的Python脚本文件

![seche](https://user-images.githubusercontent.com/93168838/194793798-c5673fea-20fe-40e0-9a60-ecd3c366402e.png)
设置的定时任务，5分钟执行一次

![crawlab-server](https://user-images.githubusercontent.com/93168838/194793673-838a127b-316b-4722-8929-aeacfc2df381.png)
crawlabserver内存占用

[dockermasterlogs.txt](https://github.com/crawlab-team/crawlab/files/9743170/dockermasterlogs.txt)
主节点的日志文件

**Comment by Lounin** [comment]
![images](https://user-images.githubusercontent.com/93168838/194794361-0e5708ca-1a62-4e24-9d5e-55d178fb97bf.png)
镜像是最新的

**Comment by tikazyq** [comment]
Fixed in the newest version
