### ISSUE TITLE
0.6版本爬虫文件丢失部分爬虫

### ISSUE THREAD

**Issue by arden-yang** [crawlab-team/crawlab#1200]
创建一个爬虫，上传爬虫文件夹，文件夹里面有206个爬虫，但上传成功后，查看文件只有100个爬虫，其它的没有

**Comment by tikazyq** [comment]
有相关截图以及docker容器日志可以看看么？

**Comment by arden-yang** [comment]
[weed.2676ccd2d573.root.log.INFO.20221011-141844.zip](https://github.com/crawlab-team/crawlab/files/9784254/weed.2676ccd2d573.root.log.INFO.20221011-141844.zip)
附件为日志
