### ISSUE TITLE
v0.6.0 python定时任务未能按期执行

### ISSUE THREAD

**Issue by vipsky** [crawlab-team/crawlab#1203]
**Bug 描述**
任务创建成功，但未能如期执行
**复现步骤**
该 Bug 复现步骤如下
web界面保存任务成功，master节点日志如下
1. [GIN] 2022/10/19 - 08:40:41 | 200 |    1.230609ms |       127.0.0.1 | GET      "/schedules/634e692053a242a8c11527cb"
[GIN] 2022/10/19 - 08:47:57 | 200 |    2.386682ms |       127.0.0.1 | GET      "/nodes?all=true"
[GIN] 2022/10/19 - 08:47:57 | 200 |    1.286901ms |       127.0.0.1 | GET      "/tasks?page=1&size=10&conditions=[%7B%22key%22:%22schedule_id%22,%22op%22:%22eq%22,%22value%22:%22634e692053a242a8c11527cb%22%7D]&sort=[]&stats=true"
[GIN] 2022/10/19 - 08:47:57 | 200 |    1.583714ms |       127.0.0.1 | GET      "/spiders?all=true"
[GIN] 2022/10/19 - 08:47:57 | 200 |    1.673541ms |       127.0.0.1 | GET      "/schedules?all=true"
[GIN] 2022/10/19 - 08:47:57 | 200 |    1.461814ms |       127.0.0.1 | GET      "/projects?all=true"
[GIN] 2022/10/19 - 08:47:57 | 200 |    1.642425ms |       127.0.0.1 | GET      "/tasks?page=1&size=10&conditions=[%7B%22key%22:%22schedule_id%22,%22op%22:%22eq%22,%22value%22:%22634e692053a242a8c11527cb%22%7D]&sort=[]&stats=true"
[GIN] 2022/10/19 - 08:48:52 | 200 |     4.91577ms |       127.0.0.1 | PUT      "/schedules/634e692053a242a8c11527cb"
[GIN] 2022/10/19 - 08:48:52 | 200 |    1.480942ms |       127.0.0.1 | GET      "/schedules/634e692053a242a8c11527cb"
[GIN] 2022/10/19 - 08:48:52 | 200 |    1.874117ms |       127.0.0.1 | GET      "/schedules?all=true"

**期望结果**
按期执行定时任务

**截屏**
![image](https://user-images.githubusercontent.com/53033023/196572006-e3bcb624-d2e3-40f2-a15a-3ea7cfb29c1a.png)

**Comment by tikazyq** [comment]
现在还有这个问题么？
