### ISSUE TITLE
有空闲节点时还在等待

### ISSUE THREAD

**Issue by JunBa0** [crawlab-team/crawlab#1207]
**Bug 描述**
有空闲节点时定时任务显示等待，任务是随机节点

**复现步骤**
该 Bug 复现步骤如下
1. 添加多个爬虫，添加定时任务，大部分任务完成后会有部分任务显示等待，节点无任务

**截屏**
![微信图片1](https://user-images.githubusercontent.com/38783769/196890764-2b5ab7fa-bd42-48c6-bfdf-cfabe33daeba.jpg)
![微信图片2](https://user-images.githubusercontent.com/38783769/196890777-4d5ae8c0-e8e4-403c-83f6-2abebf857782.jpg)

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/ec19c4ed8f573c881dcba4df7f82eb80d147656a
