### ISSUE TITLE
希望可以增加类似Gerapy的可配置爬虫的功能

### ISSUE THREAD

**Issue by 52Lau** [crawlab-team/crawlab#121]
![image](https://user-images.githubusercontent.com/37538641/62955246-4b6bce80-be23-11e9-99b2-de9c0f0456e5.png)

这个应该还是不错的，因为一些简单的站点可以通过这样来配置，不用写脚本

**Comment by tikazyq** [comment]
老版本有，新版本快了，请关注

**Comment by 52Lau** [comment]
嗯，

**Comment by tikazyq** [comment]
快了，已经完成基本的可配置爬虫，利用Spiderfile做到Spider as Code，可以用很简单的配置方式来定义爬虫

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/pull/336
