### ISSUE TITLE
社区版V0.6 定时任务的状态一直处于待定状态

### ISSUE THREAD

**Issue by motingjun** [crawlab-team/crawlab#1210]
**Bug 描述**
定时任务已经触发，任务也已经分配好节点，但是任务状态一直显示 "待定"，这种情况随着时间会越来越多。

**复现步骤**
该 Bug 复现步骤如下
1. 定时任务设置；
2. 持续几天，筛选状态为“待定”，会筛选出异常任务；
3. 删除“待定”任务，过段时间又会出现

**截屏**
![截屏1](
![image](https://user-images.githubusercontent.com/43468078/197488544-a41e4fb2-106c-485c-914c-c2950b8651ca.png)

**Comment by tikazyq** [comment]
是否是最新的docker镜像呢？对比一下docker hub上的image hash

**Comment by tikazyq** [comment]
可以试试最新镜像，不要用阿里云的镜像代理

**Comment by motingjun** [comment]
重新拉取镜像，基于之前镜像的容器内的配置是不是就没了

**Comment by motingjun** [comment]
使用的是腾讯云代理，image hash ： eb6412456c88
重新运行后：
![Uploading image.png…]()

**Comment by motingjun** [comment]
使用的是腾讯云代理，image hash ： eb6412456c88
重新运行后：
![image](https://user-images.githubusercontent.com/43468078/197520657-b59bead8-dd40-45b5-8c0b-1b60f4b6cadf.png)

**Comment by tikazyq** [comment]
现在是否还会出现这个问题？

可能相关的 issue: https://github.com/crawlab-team/crawlab/issues/1207 https://github.com/crawlab-team/crawlab/issues/1204

**Comment by motingjun** [comment]
还是会出现

**Comment by tikazyq** [comment]
请导出主节点和工作节点docker日志发上来看看？

**Comment by OliverXiao** [comment]
我的主节点也是一直pending，而且不能在线修改文件内容，前几天还可以

**Comment by tikazyq** [comment]
现在还有这个问题吗？
