### ISSUE TITLE
0.6版本不支持配置环境变量

### ISSUE THREAD

**Issue by Ronghefeng** [crawlab-team/crawlab#1213]
**解决的问题**
希望可以增加环境变量配置，轻松切换到不同的环境，使用不同的配置，而无需重新上传代码

**请描述您认为可行的解决方案**
0.5版本我看到有支持对爬虫任务不同的环境配置，06版本中没有看到。

**Comment by tikazyq** [comment]
目前已经支持环境变量，请查看最新版本
