### ISSUE TITLE
Crawlab 社区版 任务日志超过100页BUG

### ISSUE THREAD

**Issue by snackdeng** [crawlab-team/crawlab#1214]
**Bug 描述**
当任务日志超过100页或者更多页时 自动跳转第一页，无法实时显示最新的日志

**复现步骤**
该 Bug 复现步骤如下
1.运行爬虫打印日志使其超过100页或更多页
2. 它会短暂的跳转最新页(但是输出的内容是第一页)，然后强行跳转第一页
3. 周而复始

**期望结果**
希望他能正常的显示日志

**Comment by tikazyq** [comment]
https://user-images.githubusercontent.com/3393101/198167312-0d52b1b3-cebc-4552-adf3-e7e994a9087b.mp4
