### ISSUE TITLE
消息通知配置不能保存

### ISSUE THREAD

**Issue by YuCoke** [crawlab-team/crawlab#1218]
**Bug 描述**
消息通知配置：当配置消息通知 时，配置信息不能保存，显示保存成功后刷新数据清空。
触发器：选择好触发条件后不能添加到触发条件里

**截屏**
配置
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/87290342/198560657-a3640d8e-626f-4e1c-a4a9-00623d950ea9.png">
触发器
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/87290342/198561594-e75b8ecd-a149-44df-bda9-89ea318dc10b.png">

**Comment by tikazyq** [comment]
Fixed
