### ISSUE TITLE
一个scrapy task 开启后，我的期待是爬虫只运行一次，但crawlab会同时开启多个spider，重复运行，浪费资源

### ISSUE THREAD

**Issue by OliverXiao** [crawlab-team/crawlab#1219]
一个scrapy task 开启后，我的期待是爬虫只运行一次，但crawlab会同时开启多个spider，重复运行，浪费资源

该 Bug 复现步骤如下
1. 在页面点击run
2. 选择随机节点，confirm
3. 点击查看log：某个task的log日志输出多个爬虫同时运行的log

**期望结果**
一个task在同一时刻运行一个就行

**截屏**
windows不会截屏，以下是日志，为什么会同时启动两个一样的spider，有时候会是更多，有时只有一个，为什么
2022-10-31 10:24:13 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://i.instagram.com/api/v1/feed/user/1/?count=12&max_id=> (referer: https://www.instagram.com/)
2022-10-31 10:24:13 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://i.instagram.com/api/v1/feed/user/1/?count=12&max_id=> (referer: https://www.instagram.com/)

**Comment by tikazyq** [comment]
去掉敏感信息发一下具体的爬虫代码和截图

**Comment by OliverXiao** [comment]
代码的setting文件只添加了 CrawlabPipeline，其他代码均为默认设定
以下是运行的task和最新task的log
<img width="1645" alt="截屏2022-10-31 14 01 53" src="https://user-images.githubusercontent.com/47119172/198942539-d54ed918-50f8-4e24-955c-86ef10798919.png">
日志，第1行表示第一次运行，第40行又莫名其妙开启了一个相同的spider，最后也关闭了两次，数据是单个爬虫的两倍
<img width="1147" alt="截屏2022-10-31 13 44 21" 
<img width="1656" alt="截屏2022-10-31 14 02 05" src="https://user-images.githubusercontent.com/47119172/198942567-58a47aaf-462b-40e8-9496-fdc1f130770c.png">
src="https://user-image
<img width="1654" alt="截屏2022-10-31 14 02 20" src="https://user-images.githubusercontent.com/47119172/198942596-0983f8a8-a814-4930-a7b6-ab634d0e5cd5.png">
s.githubusercontent.com/47119172/198942232-c203e05c-f4b2-40a7-a07b-cf05705fe3e3.png">

<img width="1657" alt="截屏2022-10-31 14 02 47" src="https://user-images.githubusercontent.com/47119172/198942619-b9202a2a-aeed-499f-b2c7-b025c75115b7.png">


> 去掉敏感信息发一下具体的爬虫代码和截图

**Comment by OliverXiao** [comment]
> 去掉敏感信息发一下具体的爬虫代码和截图
有时候正常，有时候就会同时启动多个spider
<img width="1147" alt="截屏2022-10-31 13 44 21"src="https://user-images.githubusercontent.com/47119172/198942232-c203e05c-f4b2-40a7-a07b-cf05705fe3e3.png">

**Comment by OliverXiao** [comment]
> 是定时任务？

没设置定时，手动启动的。

**Comment by tikazyq** [comment]
可以录屏一下么？上面的操作记录以及截屏看不出具体问题

**Comment by wangcenjie** [comment]
应该怎么解决这种问题呢?

**Comment by tikazyq** [comment]
现在还有这个问题吗？
