### ISSUE TITLE
你好，作者，我有几个建议，就是在关于我使用的过程中所想到的：

### ISSUE THREAD

**Issue by k-fire** [crawlab-team/crawlab#122]

**Comment by k-fire** [comment]
这个平台界面很好看，很是符合我的审美，所以我希望能越做越好。
1：前端注册用户时限制太少，组合上面老哥提到的权限控制不全很容易被篡改或者剽窃源码，建议加上邀请码或者提供选项是否可以注册用户。
2：安全问题：在自定义爬虫配置时，输入的命令没有过滤等限制，能实现任意代码执行，如果是生产环境，很可能造成服务器种马等安全问题。
3:有个问题想问一下，在与scrapy交互的过程中，是不是一定要带入 _id 和task_id ？我感觉在结果输出的时候没必要输出这个，当然这只是我的个人看法。
希望平台越来越完善。

**Comment by tikazyq** [comment]
@k-fire 首先，非常感谢您的建议

1. 现在权限控制的确还不是很完善，我们没有做RBAC权限管理，现在的demo只是做展示作用，实际是部署在自己机器上的，后期待优化；
2. 安全问题我一直在考虑，还没有想到最佳的解决办法，唯一能想到的是去用关键词禁用某些命令，待讨论；
3. 如果您想在crawlab中看到结果的话，在scrapy中是一定要传的，但如果您无所谓，就不需要传了，_id是不用传的。

可以加我微信注明crawlab来加群里讨论。

非常感谢！

**Comment by k-fire** [comment]
感谢解答。
