### ISSUE TITLE
运行python 爬虫中有涉及到修改json文件以及创建日志，但是无法进行创建以及修改，但是读取没问题

### ISSUE THREAD

**Issue by yueddie** [crawlab-team/crawlab#1220]
爬虫需要操作一个json文件用于记录一些数据，但是在网页端页面进行操作没有反应。进入docker容器执行爬虫命令是可以的

**Comment by yueddie** [comment]
已经尝试过添加文件权限给所有人，但是还是不行

**Comment by tikazyq** [comment]
是需要操作本地json临时文件么？哪个版本？

**Comment by yueddie** [comment]
版本：社区v0.6.0-1，操作的服务器本地的json文件。

**Comment by yueddie** [comment]
> 

还有就是读取json是没问题的。修改或者新建文件不行，所以是不是执行权力的问题

**Comment by tikazyq** [comment]
目前每次crawlab要重新拉取代码，因此不会保存在本地，请用其他目录
