### ISSUE TITLE
0.6版本 重新运行任务时，任务的执行命令是爬虫定义的执行命令，而不是上一次任务执行的命令

### ISSUE THREAD

**Issue by ma-pony** [crawlab-team/crawlab#1221]
**Describe the bug**
社区版v0.6.0-1
不确定是bug，还是未实现的功能

重新运行任务时，任务的执行命令是爬虫定义的执行命令，而不是上一次任务执行的命令

**To Reproduce**
1. 新建任务1，自定义任务的执行命令，执行任务1
2. 点击重新运行，执行任务2
3. 新任务2的执行命令为爬虫定义的执行命令，而不是任务1 的执行命令

**Expected behavior**
重新运行的新任务命令取自上一个任务

**Screenshots**

**Comment by tikazyq** [comment]
Fixed in recent release
