### ISSUE TITLE
上传的文件在容器对应的文件里找不到文件，但是在网页端可以显示出来。也能执行

### ISSUE THREAD

**Issue by yueddie** [crawlab-team/crawlab#1223]
我在网页端上传一个文件夹得文件，上传成功后网页端可以看到对应文件，但是当我前往docker容器里寻找对应文件的时候无法找到
**复现步骤**
该 Bug 复现步骤如下
1. 网页端上传文件
2. 前往服务器查看文件找不到对应文件

**Comment by yueddie** [comment]
当前版本是社区办v0.6.0-1

**Comment by Specificsuper** [comment]
文件在seaweedfs里面，运行时才会下载到临时目录，比如/root/crawlab_workspace/任务id

**Comment by tikazyq** [comment]
最新版有问题么？
