### ISSUE TITLE
0.6.0-1版本 任务执行错误，重启后恢复正常，原因未知

### ISSUE THREAD

**Issue by ma-pony** [crawlab-team/crawlab#1228]
**Describe the bug**
crawlab0.6 运行两天后（此时内存占用在95%左右）
突然出现所有任务执行错误:exit status 2，任务log无任何记录

pod log中显示：dial tcp 127.0.0.1:8888: connect: connection refused
不确定是不是这个原因导致的

**To Reproduce**
1. 设置好100+定时任务
3. 运行N天之后，
4. 所有任务执行错误:exit status 2

**Expected behavior**
任务正常执行

**Screenshots**

master log文件

[crawlab.log](https://github.com/crawlab-team/crawlab/files/9986188/crawlab.log)

**Comment by motingjun** [comment]
我的也出现了，但是重启以后也没效果，重新拉取代码以后才恢复正常

**Comment by zoulux** [comment]
我的任务都是等待中，然后也不执行

**Comment by ma-pony** [comment]
我临时的解决方案是升级到0.6.0v2，同时设置了一个定时任务，每天重启一次crawlab

**Comment by tikazyq** [comment]
现在解决了么？

**Comment by tikazyq** [comment]
将你pr中seaweedfs的优化部分merge进来，可以用最新版本看是否有帮助

**Comment by tikazyq** [comment]
尝试一下最新版的镜像观察下
