### ISSUE TITLE
missing the generated output files regarding the /root/crawlab_workspace path.

### ISSUE THREAD

**Issue by KiranBCh** [crawlab-team/crawlab#1234]
Missing the generated output files regarding the /root/crawlab_workspace path.

**Comment by KiranBCh** [comment]
I upload a file in a folder on the web page. After the upload is successful, the corresponding file can be seen on the web page, but when I go to the docker container to find the corresponding file, I cannot find
the reproduction steps
. The steps to reproduce the bug are as follows

Upload files on the web
Go to the server to view the file and cannot find the corresponding file

**Comment by tikazyq** [comment]
Hi @KiranBCh, in Crawlab v0.6, spider files are uploaded and stored into [SeaweedFS](https://github.com/seaweedfs/seaweedfs), a distributed file system. Therefore, you can only view them in its web portal. To do so, you can expose 8888 port and visit this port via http.
