### ISSUE TITLE
执行爬虫任务时选择随机节点就会重复执行？

### ISSUE THREAD

**Issue by yechuzheng** [crawlab-team/crawlab#1235]
**Bug 描述**
执行爬虫任务时选择随机节点就会重复执行，指定节点就没问题。

**截屏**
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/12510820/206142630-4dbded02-9d5e-48c8-ba53-67383556ed9f.png">
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/12510820/206143324-8ce39e6b-29f2-4e5a-a6c9-d504ec66eecf.png">

这里是上面第一个任务的日志：
<img width="543" alt="image" src="https://user-images.githubusercontent.com/12510820/206143447-cbe82c07-5df6-4a3e-934a-fac2eaf0a7f1.png">
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/12510820/206143494-3ee1fd7e-813d-49e6-8f7a-57c466ea3222.png">

定时任务触发的也是如此。

其它BUG：

1. 任务里保存的数据删不掉。
2. #1226 的问题还是存在。。。

**Comment by tikazyq** [comment]
无法复现

**Comment by shaohongwu** [comment]
我也出现了 这样的情况

**Comment by Victor624424010** [comment]
请问大佬这个问题解决了吗
