### ISSUE TITLE
Is there any way to import automatically scrapy spiders to crawlab?

### ISSUE THREAD

**Issue by Canahmetozguven** [crawlab-team/crawlab#1237]
Hi guys ı have watched the autors video he says you can host more then 100 spiders on crawlab but how can we import them automatically? It's very hard to import one by one.

**Comment by tikazyq** [comment]
That's a good question! Actually, importing multiple spiders can be achieved through [crawlab-cli](https://docs.crawlab.cn/en/guide/cli/). By using scripts with crawlab-cli you can automatically batch import your spiders. 

But I am happy to hear your thoughts if you have any good ideas.

**Comment by Canahmetozguven** [comment]
In docs it doesn't very descriptive I'm planning to develop my projects on my locally and then host them on a tmux. Can you be more specific?

**Comment by tikazyq** [comment]
Okay. What you need to do is to check out the Git tab in your spiders detail page, which is currently not documented.
