### ISSUE TITLE
每次Recreate之后节点ID会变化

### ISSUE THREAD

**Issue by mattholy** [crawlab-team/crawlab#1244]
**Bug 描述**
每次Recreate之后节点ID会变化

**复现步骤**
该 Bug 复现步骤如下
1. 正常create一个容器
2. recreat
3. 发现节点ID变化

**期望结果**
节点ID不变化。

请问是否有什么环境变量可以直接设定呢？我在文档中没见到相关信息

**Comment by tikazyq** [comment]
大概率是没有持久化

**Comment by mattholy** [comment]
`./data/master:/data`
我挂载了/data目录呀

**Comment by tikazyq** [comment]
还需要这个 `/root/.crawlab`

**Comment by mattholy** [comment]
哦感谢它好了，你们可能需要人帮助更新下文档23333333
