### ISSUE TITLE
结果总数计数不准

### ISSUE THREAD

**Issue by mattholy** [crawlab-team/crawlab#1247]
**Bug 描述**
当删除某个任务后，结果总数会不准确

**复现步骤**
该 Bug 复现步骤如下
1. 随机运行数个任务
2. 删除其中任何结果
3. 发现结果总数不对
4. 查询数据库发现删掉的任务依然在数据库里

**期望结果**
删除任务后能同步移除相关数据

**截屏**
![image](https://user-images.githubusercontent.com/22177897/209564428-4a9b7ae5-ba81-4f9d-9764-fc74889fe01b.png)

**Comment by mattholy** [comment]
主要是`task_stats`这个表里面还存有记录。

我理解是这里应该存的是历史数据，用来在下面展示每日的统计折线，
那么应该是结果总数只统计仍然健在任务的结果数量

**Comment by tikazyq** [comment]
之前删过么？

**Comment by mattholy** [comment]
> 之前删过么？

没有，这是个我新开的测试容器

**Comment by tikazyq** [comment]
这应该是历史累积的数据，建议清空mongo数据之后，重新创建容器
