### ISSUE TITLE
0.6版本 任务取消按钮不能真正停止任务

### ISSUE THREAD

**Issue by youthsnow** [crawlab-team/crawlab#1248]
**Bug 描述**
对运行中的任务进行取消，点击取消按钮，页面上展示取消。实际在后台程序仍然在运行。
**复现步骤**
该 Bug 复现步骤如下
1. 运行一个scrapy 任务
2. 记住启动的执行命令 中的xxx.py文件
3. 点击任务中的取消按钮，取消任务
4. 在linux终端  执行ps  -ef  |grep  xxx.py  可定位到进程仍在运行

**期望结果**
点击任务取消按钮，任务程序能停止工作。

**截屏**
![image](https://user-images.githubusercontent.com/50894561/209650858-ae4d79f3-5918-490a-8c73-193bf89e5b23.png)

**Comment by tikazyq** [comment]
脚本内容大概是什么？

**Comment by youthsnow** [comment]
> 脚本内容大概是什么？
脚本是  使用scrapy-redis 抓取一个网站的数据

**Comment by tikazyq** [comment]
Fixed in https://github.com/crawlab-team/crawlab/pull/1334
