### ISSUE TITLE
Constantly Spawning Nodes

### ISSUE THREAD

**Issue by zerafachris** [crawlab-team/crawlab#1252]
**Describe the bug**
I deployed Crawlab on GCP Cloud Run. I am ending up with constantly spawning nodes and all my tasks are failing with status exit code 2.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/22851907/211773064-b6bd2bbf-c07e-42d8-8e35-7fcdd41f187a.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/22851907/211772167-56e8e7c3-2167-42e8-bd58-2713c2cd10de.png">

**To Reproduce**
1. I am using GCP Cloud Run
2. This is my DockerFile
```
FROM crawlabteam/crawlab:latest

RUN apt-get update && \
    apt-get install libleptonica-dev  -y && \
    apt-get install tesseract-ocr -y && \
    apt-get install libtesseract-dev -y
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
RUN pip install pytesseract

ENV TZ="Europe/Rome"
ENV CRAWLAB_NODE_MASTER="Y" 
ENV CRAWLAB_MONGO_URI="***"
ENV CRAWLAB_MONGO_HOST="***"
ENV CRAWLAB_MONGO_PORT="***"
ENV CRAWLAB_MONGO_DB="***"
ENV CRAWLAB_MONGO_USERNAME="***"
ENV CRAWLAB_MONGO_PASSWORD="***"
ENV CRAWLAB_MONGO_AUTHSOURCE="***" 
ENV GIN_MODE="release"

CMD ["/bin/bash", "/app/bin/docker-init.sh"]
```
3. I then try and run the task and get the error.

**Expected behaviour**
Tasks to execute successfully

**Comment by tikazyq** [comment]
Hi @zerafachris 

Thanks for the feedback. 

You can try to troubleshoot your problem: click on the `Logs` tab in the Task Detail page to view the [task logs](https://docs.crawlab.cn/en/guide/task/#view-logs). You might need to check if there is any error info in the task logs.

**Comment by zerafachris** [comment]
Hi @tikazyq , the logs are empty

**Comment by tikazyq** [comment]
I think you can use `docker logs --tail 1000 master` to get the latest logs and see if there is any error.
