### ISSUE TITLE
mongo高版本（5.0.6）认证失败

### ISSUE THREAD

**Issue by zzb980881** [crawlab-team/crawlab#1254]
**Describe the bug**
mongo最新版本，如果添加了安全认证，会提示错误：
warn waiting for connect mongo database, after 3.221480 seconds try again. error=server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field.

去掉安全认证的话，可以使用。
网上搜索，怀疑可能是go驱动问题，https://blog.csdn.net/weixin_45388588/article/details/123530971

**Comment by tikazyq** [comment]
哪个版本？

**Comment by zzb980881** [comment]
升级到最新的镜像就可以了，我还用的是tikazyq/crawlab:latest，换成crawlabteam/crawlab就可以了

**Comment by zzb980881** [comment]
升级到最新的镜像就可以了，我还用的是tikazyq/crawlab:latest，换成crawlabteam/crawlab就可以了
