### ISSUE TITLE
环境依赖包的安装有问题

### ISSUE THREAD

**Issue by zzb980881** [crawlab-team/crawlab#1255]
**Bug 描述**
环境依赖安装选择的包，一直在运行中，安装不上。进容器直接运行pip命令是可以正常安装的。

![image](https://user-images.githubusercontent.com/1118228/212259331-64af21dd-865b-4307-bcef-0a8a65f965eb.png)

设置的pip代理好像也一直不生效，提交完返回还是空
![image](https://user-images.githubusercontent.com/1118228/212259457-764f94dc-73b3-494c-9798-779a06f272b8.png)

但依赖包安装不了应该不是代理问题，我进容器内部是可以正常安装的。

**Comment by fightingfish008** [comment]
遇到同样的问题。希望尽快出解决方案

**Comment by tikazyq** [comment]
Fixed in recent release
