### ISSUE TITLE
Task in schedule is pending due to call to removed worker node

### ISSUE THREAD

**Issue by thachnv92** [crawlab-team/crawlab#1262]
**Describe the bug**
I have some worker nodes and schedule for run task on this worker nodes.
Due to some reason, some worker nodes is removed and create new worker nodes.
But when schedule run, this make some task and still call to old worker nodes - which worker nodes is removed.
And don't have logs in task.

**To Reproduce**
1. Create schedule A run on worker node B
2. Remove worker node B
3. Wait for schedule A run or update time for run soon
4. Task C in schedule A pending always, It's call to worker node B - which worker nodes is removed.

**Expected behavior**
1. Or need to have an alert to report to end user know worker nodes is removed.
2. Or print log alert about don't find worker nodes.
3. Or can be replace worker node B by other node same name or unique identity node.

**Screenshots**
![image](https://user-images.githubusercontent.com/38679578/216878846-30a41c7d-78de-448c-b158-9f00ae0e4820.png)
![image](https://user-images.githubusercontent.com/38679578/216878856-da5d5627-9a91-490b-974d-a2eb2ab594cc.png)

**Comment by ssi-thachnv** [comment]
Screenshots:

![image](https://user-images.githubusercontent.com/119549074/216878649-dc2ae814-64ec-4493-b8a6-b40270489964.png)

**Comment by ssi-thachnv** [comment]
Don't have any logs

![image](https://user-images.githubusercontent.com/119549074/216878764-f80162e8-2d37-4b48-9f60-67be077d7294.png)

**Comment by tikazyq** [comment]
This might be a bug. Would you be able to upload a full list of docker logs (both master and workers) here?

**Comment by tikazyq** [comment]
I think this is because of the documentation issue which missed a config setting up metadata persistence of volume. You can try adding below config in your `volumes` fields in `docker-compose.yml`.

```yaml
    volumes:
      - "/opt/.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
      - "/opt/crawlab/master:/data"  # persistent crawlab data
```

**Comment by tikazyq** [comment]
Try the newest version because the logs have been on the master disk now, not seaweedfs

**Comment by thachnv92** [comment]
> I think this is because of the documentation issue which missed a config setting up metadata persistence of volume. You can try adding below config in your `volumes` fields in `docker-compose.yml`.
> 
> ```yaml
>     volumes:
>       - "/opt/.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
>       - "/opt/crawlab/master:/data"  # persistent crawlab data
> ```

I fixed it by use Random nodes, so it doesn't assign to worker node which die.

**Comment by thachnv92** [comment]
@tikazyq anyway, I just config persistent volume for /data mount point.
and I think it's ok.
