### ISSUE TITLE
Don't show selected nodes in Schedule

### ISSUE THREAD

**Issue by thachnv92** [crawlab-team/crawlab#1263]
**Describe the bug**
Don't show selected nodes in Schedule although before select nodes for run task.
But check DB, still have selected nodes.

**To Reproduce**
1. Create new Schedule
2. Select Nodes for run Task
3. Confirm to Save Schedule
4. Click to Schedule just create
5. Don't see any Selected nodes although before select nodes for run task 
6. Task run in Schedule don't have selected nodes, too

**Expected behavior**
show selected nodes in Schedule and Task

**Screenshots**
Before confirm to save Schedule:
![image](https://user-images.githubusercontent.com/38679578/216941309-c66aac95-44eb-4fbd-b10b-a087db50c19a.png)

View Schedule:
![image](https://user-images.githubusercontent.com/38679578/216941384-5807978a-63c9-4243-9312-b7f2b9643edd.png)
![image](https://user-images.githubusercontent.com/38679578/216941405-0f354861-d47d-4f5c-8093-0d0aeee76dc1.png)

**Comment by ssi-thachnv** [comment]
![image](https://user-images.githubusercontent.com/119549074/216941019-a34a35ce-2a96-41c0-9b75-8c1073fe3efe.png)
![image](https://user-images.githubusercontent.com/119549074/216941131-7aab44f5-2930-46a1-b881-f7e5ab489f1f.png)
![image](https://user-images.githubusercontent.com/119549074/216941205-3ba73c78-806e-417a-bf74-c1584042d702.png)
