### ISSUE TITLE
Certificate expired https://plugins.crawlab.cn

### ISSUE THREAD

**Issue by GGPay** [crawlab-team/crawlab#1266]
**Describe the bug**

Certificate expired https://plugins.crawlab.cn/plugins.json

**To Reproduce**
1. docker logs crawlab-master

**Screenshots**
![image](https://user-images.githubusercontent.com/17413180/217578486-7a69fe17-bd7f-40a9-ba07-4bd8d92ce21f.png)

**Comment by tikazyq** [comment]
Plugins are not used anymore
