### ISSUE TITLE
Master node increases ram memory day by day.

### ISSUE THREAD

**Issue by crissvilleda** [crawlab-team/crawlab#1267]
**Describe the bug**
I successfully implemented the Crawlab software utilizing the power of Kubernetes, consisting of a single Node Master and three Worker nodes. On a daily basis, I undertake the rigorous task of executing a total of 23 tasks. Unfortunately, I encountered an issue where the Node Master would crash. Upon conducting a thorough investigation, I discovered that the memory RAM usage of the Node Master consistently increases after executing all tasks each day.

**Expected behavior**
The expected behavior of the system is for the Node Master to smoothly carry out its responsibilities without any crashes or system failures. Additionally, it is also expected for the memory RAM usage of the Node Master to remain stable and not increase significantly after executing all tasks each day.

**Screenshots**
The memory usage of the first day
![image](https://user-images.githubusercontent.com/41885675/217892047-439c9b36-1b53-4cdf-9a5e-87aa29680518.png)
The memory usage in the second day
![image](https://user-images.githubusercontent.com/41885675/217892361-fc88827e-5925-4651-8bf6-17a3b1c7328b.png)

This goes on and on until it crash, the Node Master restarted and I lost the files of the scrapy bot.

**Comment by tikazyq** [comment]
Which version you are using?

**Comment by crissvilleda** [comment]
Hi, thanks to respond 
I am using the crawlab's version V0.6.0

**Comment by ma-pony** [comment]
> Hi, thanks to respond I am using the crawlab's version V0.6.0

It is recommended that you upgrade to 0.6.1, which fixes some memory  overflow bugs

**Comment by tikazyq** [comment]
As @ma-pony mentioned, v0.6.1 fixed memory leaking issue. You can upgrade and see if this issue persist.
