### ISSUE TITLE
rpc error, grpc error, connect to grpc: connection refused

### ISSUE THREAD

**Issue by thachnv92** [crawlab-team/crawlab#1268]
**Describe the bug**
I have 3 servers:
- Server 1: Run docker compose to run 1 master node
- Server 2: Run docker compose to run 2 worker nodes
- Server 3: Install mongoDB
- **docker image use latest version**

I setup crawlab Ok, all thing is work fine.

Yesterday, all task get status is Error, with message: "Task ended with an error: grpc error: stream not found"

![image](https://user-images.githubusercontent.com/38679578/219262610-5ddd7e55-949f-433b-963e-af2fe35c7ce3.png)

I check logs of container worker node and get logs as below:
![image](https://user-images.githubusercontent.com/38679578/219262636-2af16c9f-6e96-4a0b-8bfa-f5023349f263.png)

I check master node, It's OK.
I try to check connection from both server A and 2 worker node container in server A to grpc :9666, all thing is Ok. Telnet OK and curl connection OK.

I try to create one more worker node is worker_node_3, and run task on it, It's Ok.
Then, I must remove old worker node and re-create to fix this issue temporary.

**Comment by ssi-thachnv** [comment]
![image](https://user-images.githubusercontent.com/119549074/219262268-b04f619a-8062-4b29-85c7-e67b4cba6f0c.png)
![image](https://user-images.githubusercontent.com/119549074/219262546-b97026b5-ce7d-482f-a586-adb3ea9e5ed1.png)

**Comment by tikazyq** [comment]
Hi @thachnv92,

Have you tried upgrading to the newest version and restart all master and worker nodes to see if it works okay?

**Comment by thachnv92** [comment]
Many thanks,
I forgot to update this.

It need to more time to retry connect grpc to master node.
