### ISSUE TITLE
⚠️⚠️⚠️ mongo 和mysql 数据库连接不释放问题，严重问题请尽快解决

### ISSUE THREAD

**Issue by TigerShuai** [crawlab-team/crawlab#1271]
**Bug 描述**
例如，当采集器任务完成时数据库连接没有回收，数据库连接一直属于Sleep 状态，入库通过pyhon 的crawlab库的save_item 单采集器任务连接占用上千，通过save_items 批量写入也会占用几百的数据库连接，多采集器任务采集时，数据库连接很快就会被crawlab使用完，导致影响正常业务❌❌❌。

严重影响正常业务，希望马上解决，mongo和mysql都同样存在这样的问题。

**复现步骤**
该 Bug 复现步骤如下
1. 创建采集器脚本，通过save_item或save_items批量写入
2. 观察任务结束后的数据库连接情况

**期望结果**
crawlab能真正实现分布式采集调度的功能。

**截屏**
让dba导出了数据库连接情况，发现目前没有任何采集器任务在工作，连接也存在500多个，一直是sleep状态，这还是我优化了脚本写入，使用save_items后的情况，采集器如果选择单条数据写入占用连接更是恐怖😱😱😱

⚠️：各位使用开源尤其是使用企业级的开发者，当前问题你们也会遇到，未解决前，分布式采集方案谨慎选型。
![image](https://user-images.githubusercontent.com/35909241/225495854-d7c7bc9b-bc33-4ae0-8534-09c3901a4c73.png)

**Comment by TigerShuai** [comment]
刚把采集器脚本又改了下，全部先写入到内存，然后任务结束时，通过save_items 批量写入，看源码应该是50个数据写入一次，1800多条数据，占用38个连接数，和dba查询到的占用数据量一致

**Comment by tikazyq** [comment]
fixed in db72bfcb7dca8daa3723cfa045bf49ecdb12e68f

**Comment by tikazyq** [comment]
please pull the latest image and try again
