### ISSUE TITLE
请教作者

### ISSUE THREAD

**Issue by Will-Liang** [crawlab-team/crawlab#1272]
想请教下作者，开发这个crawlab爬虫管理平台需要用到哪些技术栈或知识储备呢。来自一名学生

**Comment by horennel** [comment]
go gin(或python flask fastapi),vue,grpc,mongodb,redis,docker等

**Comment by horennel** [comment]
go gin(or python flask fastapi),vue,grpc,mongodb,redis,nginx,docker

**Comment by tikazyq** [comment]
> 想请教下作者，开发这个crawlab爬虫管理平台需要用到哪些技术栈或知识储备呢。来自一名学生

您好，可以参考一下这篇文章 https://juejin.cn/post/6844903912349122573

**Comment by Will-Liang** [comment]
> 

谢谢！我很好奇上传的爬虫中使用到的第三方库，管理平台是怎么去自动下载这些库的呢
