### ISSUE TITLE
打开自动从git上拉取代码后 git的日志丢失

### ISSUE THREAD

**Issue by yuzaii** [crawlab-team/crawlab#1275]
**打开自动从git上拉取代码后 git的日志丢失**
没开启自动拉取代码正常显示日志
![image](https://user-images.githubusercontent.com/82126539/226980315-67d28235-8b12-4105-90ab-04eac96c8a16.png)
开启自动拉取代码 git日志丢失
![image](https://user-images.githubusercontent.com/82126539/226980546-77c1860d-0660-4051-9736-3d7442594de4.png)
请求的信息
![image](https://user-images.githubusercontent.com/82126539/226981206-8880e66b-2dbe-4d78-bee2-c760f3e30a02.png)

**Comment by tikazyq** [comment]
无法复现
