### ISSUE TITLE
CRAWLAB_TASK_HANDLER_MAXRUNNERS is not effect

### ISSUE THREAD

**Issue by thachnv92** [crawlab-team/crawlab#1288]
**Describe the bug**
CRAWLAB_TASK_HANDLER_MAXRUNNERS | Max number of task runners (concurrent spider tasks) that a node can run | 16 | 8

I want to set CRAWLAB_TASK_HANDLER_MAXRUNNERS = 0 for Crawlab master, due to I don't want to run task on Crawlab master

**To Reproduce**
Update CRAWLAB_TASK_HANDLER_MAXRUNNERS = 0

**Expected behavior**
Max runner on Crawlab master is 0

**Comment by tikazyq** [comment]
Have you tried disabling the master node?

<img width="784" alt="image" src="https://user-images.githubusercontent.com/3393101/230573625-53f99a2c-c4e9-4efe-9768-7b9b51d77f67.png">

**Comment by thachnv92** [comment]
I try it.
But when master node die, other master node replace it.
It stills enable with 8 runners.

**Comment by tikazyq** [comment]
Can you put your config file docker-compose.yaml without sensitive info?

**Comment by thachnv92** [comment]
I use manifest K8s

**Comment by tikazyq** [comment]
You can send the YAML config as well
