### ISSUE TITLE
社区版修改密码后无法登录

### ISSUE THREAD

**Issue by lesamly** [crawlab-team/crawlab#1296]
**Bug 描述**
修改了密码之后，退出登录再登录是正常的，过一段时间后，密码无论怎么试都是错误的，无法找到重置密码的方法，造成不停的重装，重装了几次都是如此，难道是不给修改密码

**复现步骤**
该 Bug 复现步骤如下
1. 
2. 
3. 

**期望结果**
xxx 能工作。

**截屏**
![截屏1](http://static-docs.crawlab.cn/login.png)

**Comment by tikazyq** [comment]
是哪个版本？

**Comment by MasterShu** [comment]
我的也是，不知道怎么充值密码？ 0.6.1 的社区版本。
