### ISSUE TITLE
上传文件没反应

### ISSUE THREAD

**Issue by hyliush** [crawlab-team/crawlab#1298]
0.6.1社区版，上传文件显示upload sucessfully，但页面不显示文件

**Comment by hyliush** [comment]
感谢大佬回复，就是看不到上传的文件，文件页签没有任何变化。
![image](https://user-images.githubusercontent.com/49185490/232179023-16c64cab-b3d1-4098-947a-36d3519f6784.png)

**Comment by tikazyq** [comment]
文件名是什么

**Comment by hyliush** [comment]
目录是proxy_pool，里面文件全是英文的，文件名会影响吗？上传文件也是显示成功但看不到

**Comment by ma-pony** [comment]
本地环境的话，可以把master节点的8888端口，看看里边有没有文件
线上环境不要暴露8888端口
