### ISSUE TITLE
当节点离线后希望将该节点上的任务都置为取消或错误状态

### ISSUE THREAD

**Issue by ma-pony** [crawlab-team/crawlab#1300]
**请描述该需求尝试解决的问题**
当节点离线后，该节点的任务仍处于运行状态，并且会一直处于运行状态

**请描述您认为可行的解决方案**
当节点离线后发送事件通知，自动将该节点上的任务都置为取消或错误状态

**考虑过的替代方案**
任务执行时间隔一段时间后自动扫描节点状态，节点离线后将其发送到另一个节点执行

**Comment by tikazyq** [comment]
已经改为重启后会重置为“异常”状态
