### ISSUE TITLE
v0.6版本全局变量

### ISSUE THREAD

**Issue by yu8883** [crawlab-team/crawlab#1306]
![企业微信截图_16832690077900](https://user-images.githubusercontent.com/130326987/236392563-ca3b9467-7941-49f3-a2fc-a0f830f0880d.png)
v0.6版本有类似的全局变量吗， v0.6版本默认是python10 ,可以搞成其他python环境吗

**Comment by tikazyq** [comment]
新功能已经加入全局变量的功能
<img width="1162" alt="image" src="https://github.com/crawlab-team/crawlab/assets/3393101/cac578b8-eba8-4abf-a581-e59b14236f91">
