### ISSUE TITLE
导出json内容全部都是object

### ISSUE THREAD

**Issue by chenjinlei1122** [crawlab-team/crawlab#1307]
**Describe the bug**
社区版
![image](https://user-images.githubusercontent.com/32697166/236616831-8dea0297-23fc-480d-8f4d-34f25a5cadec.png)

**To Reproduce**
1. 
![image](https://user-images.githubusercontent.com/32697166/236616791-ff6acc73-b3d0-425e-92b4-d0a2f3226b95.png)

2.
![image](https://user-images.githubusercontent.com/32697166/236616899-39b2945c-f911-43a9-9940-aa7e266ab684.png)

**Comment by tikazyq** [comment]
pull the latest image to get the fixed version
