### ISSUE TITLE
社区版最新版python bug

### ISSUE THREAD

**Issue by chenjinlei1122** [crawlab-team/crawlab#1309]
**Bug 描述**
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**复现步骤**
该 Bug 复现步骤如下
![image](https://user-images.githubusercontent.com/32697166/236717779-86315ce2-c4de-46d0-9627-4e555a8b16d7.png)

**Comment by andreyluchianic** [comment]
i have same error ! using default docker-compose.yml from repository example 
just with `docker compose` (docker compose V2)

**Comment by jiuhuche120** [comment]
pip3 install cryptography
pip3 install pyopenssl

**Comment by chenjinlei1122** [comment]
> i have same error ! using default docker-compose.yml from repository example just with `docker compose` (docker compose V2)
> 
> ## UPD
> update dependencies for
> 
> * cryptography
> * pyopenssl
> 
> to the latest, you can do that from admin panel

that's right
