### ISSUE TITLE
社区版 0.6.1 使用 crawlab.CrawlabPipeline 报错

### ISSUE THREAD

**Issue by beiliubei** [crawlab-team/crawlab#1312]
![image](https://github.com/crawlab-team/crawlab/assets/1127875/e036a3af-facf-496c-b7aa-cbd55ba50980)

**Comment by beiliubei** [comment]
![image](https://github.com/crawlab-team/crawlab/assets/1127875/5031b333-76e3-447f-a241-e559b1c8f5e4)

https://demo-pro.crawlab.cn/#/tasks/6466e7befa13afd98c7d772d/logs

prod 也报错

**Comment by tikazyq** [comment]
`pip install crawlab-sdk` instead of `pip install crawlab`

有个包 `crawlab` 会导致这个问题

**Comment by beiliubei** [comment]
![image](https://github.com/crawlab-team/crawlab/assets/1127875/dd779659-1572-44ed-b7e9-0ccf97ea5ae5)

![image](https://github.com/crawlab-team/crawlab/assets/1127875/6508f4c4-78d6-43c1-b9b9-71dc060554f9)

@tikazyq 
uninstall crawlab 之后 报这个错误

**Comment by beiliubei** [comment]
在页面上面安装 crawlab_sdk 失败；
在docker 容器内，使用命令行安装后，成功了

**Comment by tikazyq** [comment]
可以试试 `crawlab.pipelines.CrawlabPipeline`
