### ISSUE TITLE
我的也是，不知道怎么重置密码？ 0.6.1 的社区版本。

### ISSUE THREAD

**Issue by MasterShu** [crawlab-team/crawlab#1322]
我的也是，不知道怎么充值密码？ 0.6.1 的社区版本。

_Originally posted by @MasterShu in https://github.com/crawlab-team/crawlab/issues/1296#issuecomment-1575933252_

**Comment by tikazyq** [comment]
MongoDB里 `passwords` 表中的 `p` 字段用md5加密后设置
