### ISSUE TITLE
crawlab容器启动后一分钟内自动down掉

### ISSUE THREAD

**Issue by AslanLau** [crawlab-team/crawlab#1326]
**Bug 描述**
本人是windows下使用wsl提供的linux能力，安装好docker后，使用docker-compose up -d启动容器后，一分钟内crawlab容器停止，mongo容器运行正常。

**复现步骤**
版本：0.6.1

docker-compose.yml内容如下：
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2

crawlab容器报错日志如下：

[Plugin-notification] 2023/06/09 14:50:15  info start handling events    
[Plugin-notification] 2023/06/09 14:50:15  info attempt to obtain grpc stream...
[Plugin-notification] 2023/06/09 14:50:15  info obtained grpc stream, start receiving messages...
(BadValue) $in needs an array
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.2-0.20230604073947-ed9c36918bbd/models/service/binder_list.go:90 github.com/crawlab-team/crawlab-core/models/service.(*ListBinder).Process()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.2-0.20230604073947-ed9c36918bbd/models/service/binder_list.go:74 github.com/crawlab-team/crawlab-core/models/service.(*ListBinder).Bind()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.2-0.20230604073947-ed9c36918bbd/models/service/base_service.go:71 github.com/crawlab-team/crawlab-core/models/service.(*BaseService).GetList()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.2-0.20230604073947-ed9c36918bbd/models/service/git_service.go:34 github.com/crawlab-team/crawlab-core/models/service.(*Service).GetGitList()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.2-0.20230604073947-ed9c36918bbd/spider/admin/service.go:225 github.com/crawlab-team/crawlab-core/spider/admin.(*Service).syncGit()
/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 github.com/robfig/cron/v3.FuncJob.Run()
/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 github.com/robfig/cron/v3.(*Cron).startJob.func1()
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit()
2023/06/09 14:50:15  info [PluginServer] master received subscribe req from plugin[notification]
2023/06/09 14:50:15  info [PluginServer] master subscribed plugin[notification]
2023/06/09 14:50:15  info [NotificationService] obtained grpc stream, start receiving messages...
2023/06/09 14:51:00  info [SpiderAdminService] start to sync git
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14a2af6]
goroutine 1929 [running]:
github.com/crawlab-team/crawlab-core/models/service.(*Service).GetGitList(0x19d9e20?, 0xc00207a690?, 0x1c042d4?)
        /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.2-0.20230604073947-ed9c36918bbd/models/service/git_service.go:35 +0x56
github.com/crawlab-team/crawlab-core/spider/admin.(*Service).syncGit(0xc00089ee60)
        /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.2-0.20230604073947-ed9c36918bbd/spider/admin/service.go:225 +0x2b8
github.com/robfig/cron/v3.FuncJob.Run(0xde07f7?)
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xad

麻烦大佬帮忙看下什么问题？是否是我哪里配置的不对？

**Comment by tikazyq** [comment]
最新版本应该解决了这个问题，请拉取latest镜像

**Comment by AslanLau** [comment]
> 最新版本应该解决了这个问题，请拉取latest镜像

已经ok了，感谢大佬
