### ISSUE TITLE
想提一个需求，已完成的任务能不能自动清理。

### ISSUE THREAD

**Issue by Super-Brother** [crawlab-team/crawlab#1337]
**请描述该需求尝试解决的问题**
目前使用了几天，任务都已经55页了，因为这边部署了一些定时任务，每五分钟、每小时、每天，所以产生了超级多的任务。

**请描述您认为可行的解决方案**
已完成的任务，我不太关心，我一般会关心爬虫出错的任务，已完成的任务能不能可以设置定时清理。

**考虑过的替代方案**
目前只能手动清理，很麻烦。

**Comment by tikazyq** [comment]
30天后任务自动清除
