### ISSUE TITLE
节点设置执行器数量时，希望有保留的执行器，防止被定时任务全部占用

### ISSUE THREAD

**Issue by 2145579473** [crawlab-team/crawlab#1338]
问题点：我设置了大量的定时任务，节点的执行器被占用，导致我手动执行一个爬虫时，需要等待很久的时间

希望：节点的执行器可以手动配置保留几个专门用于手动执行爬虫的执行器（自定义配置总执行器数量=定时任务执行器数量+手动执行爬虫数量）

**Comment by tikazyq** [comment]
是否可以考虑将节点的执行器数量设置到比较大的数量？

**Comment by 2145579473** [comment]
执行器数量不是跟CPU数有关吗？能设置的很大？

**Comment by tikazyq** [comment]
> 执行器数量不是跟CPU数有关吗？能设置的很大？

不跟CPU数有关，而单纯是可以并行执行的任务数最大数量，可以设置为比较大的数量
