### ISSUE TITLE
重装crawLab时异常

### ISSUE THREAD

**Issue by hy928302776** [crawlab-team/crawlab#1347]
Creating network "crawlab_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-ec15892add61 -j RETURN: iptables: No chain/target/match by that name.
<img width="1323" alt="image" src="https://github.com/crawlab-team/crawlab/assets/26709680/875d13f4-726e-46a5-bc91-a96116eefc30">
第一次安装成功了，在进行重装crawLab时，出现了以上问题。
我的步骤是：
1、docker rm -f 强制删除了crawlab-master的容器，
2、然后重新执行 yaml文件，就报这样的错误了
我该如何解决呢

**Comment by tikazyq** [comment]
请执行 `docker network rm crawlab_default` 后再重新试一下
