### ISSUE TITLE
每次执行一个爬虫都会去拉取一次项目代码，导致任务执行慢

### ISSUE THREAD

**Issue by 2145579473** [crawlab-team/crawlab#1350]
问题点：执行一个爬虫时，都会去拉取一次项目代码（项目文件多时要很久），导致很多任务一直在等待状态

希望：能否拉取代码不要这么频繁？对于一个增量的爬虫来说，一次任务执行的时间是很短的（可能比拉取代码的时间都短）

**Comment by 2145579473** [comment]
啥时候能解决这个问题鸭，目前任务堆积很严重哦

**Comment by tikazyq** [comment]
期待下个版本，估计近期就会开发

**Comment by hy928302776** [comment]
为啥我的git不回拉取代码呢，怎么设置的

**Comment by tikazyq** [comment]
设置爬虫开启“增量同步”即可
