### ISSUE TITLE
为什么加pro上的微信, 没通过, 是不维护pro了吗

### ISSUE THREAD

**Issue by sqzxcv** [crawlab-team/crawlab#1353]
为什么加pro上的微信, 没通过, 是不维护pro了吗

**Comment by tikazyq** [comment]
微信 tikazyq1 再加
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/05/2023 16:29 |
| To | crawlab-team/crawlab ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [crawlab-team/crawlab] 为什么加pro上的微信, 没通过, 是不维护pro了吗 (Issue #1353) |

为什么加pro上的微信, 没通过, 是不维护pro了吗

**Comment by sqzxcv** [comment]
> 微信 tikazyq1 再加 ---- Replied Message ---- | From | ***@***.***> | | Date | 07/05/2023 16:29 | | To | crawlab-team/crawlab ***@***.***> | | Cc | Subscribed ***@***.***> | | Subject | [crawlab-team/crawlab] 为什么加pro上的微信, 没通过, 是不维护pro了吗 (Issue #1353) | 为什么加pro上的微信, 没通过, 是不维护pro了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

加了,但是还没反应


另外请教一下: a 爬虫爬取的链接存入 MongoDB后, b 爬虫怎么获取a的数据进行二次爬取内容?
