### ISSUE TITLE
任务无法删除

### ISSUE THREAD

**Issue by liulinlin** [crawlab-team/crawlab#1361]
**Describe the bug**
任务无法删除

**To Reproduce**
1. 在worker 中运行一个一直执行的爬虫任务
2. 将该worker 下线，直接干掉
3. 该任务在实际worker中已经不存在了，然后执行删除总是删除不了

**Expected behavior**
在机器离线的时候，对应的该服务器下的爬虫任务状态改为错误或者异常

**Screenshots**
![image](https://github.com/crawlab-team/crawlab/assets/8653966/56547c23-f6a1-4c3b-b298-6c38b09c6336)

**Comment by tikazyq** [comment]
是无法取消么，后台有不有报错日志

**Comment by liulinlin** [comment]
后台没看到报错，一直没搞懂是因为啥，后面我直接进mongo 库删除的。
