### ISSUE TITLE
Scrapy-Pipeline

### ISSUE THREAD

**Issue by PShiYou** [crawlab-team/crawlab#1367]
如果在Scrapy中已经写好了自己的数据存储管道时，在settings启动时，可以直接将数据存入到自己的数据库中，例如MySQL、MongoDB。个人认为比使用SDK方便

**Comment by tikazyq** [comment]
有具体的实际例子么？

**Comment by PShiYou** [comment]
![11111111](https://github.com/crawlab-team/crawlab/assets/118948488/97611408-fadf-4256-ba02-7a6d7b5fac37)
![22222222](https://github.com/crawlab-team/crawlab/assets/118948488/975a6942-393f-4411-808c-eca041141119)
![3333333](https://github.com/crawlab-team/crawlab/assets/118948488/6333bee9-2dfa-45c0-8139-c3fea29820b0)
![44444444](https://github.com/crawlab-team/crawlab/assets/118948488/4f51772a-5fa1-49aa-9fdd-a43062efd001)
先写了一个Excel pipeline，保存的路径是桌面

**Comment by tikazyq** [comment]
建议用Crawlab SDK自带的pipeline，然后在数据标签中下载CSV文件

**Comment by PShiYou** [comment]
可以增加这个功能吗
