### ISSUE TITLE
环境变量可否做成下拉选择？

### ISSUE THREAD

**Issue by zsf513** [crawlab-team/crawlab#137]
环境变量名能否做成在页面选择的，否则每次要添加一个环境变量都要看文档？

**Comment by tikazyq** [comment]
你是说哪个页面呢，爬虫详情页面里环境配置那个？还是其他的

**Comment by zsf513** [comment]
![image](https://user-images.githubusercontent.com/4221354/63139092-95b1a300-c00f-11e9-80e4-6034fa04b266.png)

**Comment by tikazyq** [comment]
这个环境变量是选择“结果集”，直接传到爬虫程序里的
