### ISSUE TITLE
Cron jobs don't kick off at the expected time

### ISSUE THREAD

**Issue by DevinSmith69** [crawlab-team/crawlab#1383]
I am having an issue trying to figure out the Cron job's scheduled time. My Crawlab is sitting on a digital ocean droplet and hosted in Amsterdam which is on GMT+2 (same as my timezone). When I schedule the Cron at * 16 * * * expecting it to kick off at 16:00 in the afternoon it runs at 08:30 in the morning, I have attempted to kick it off this morning by moving the cron job time every hour and it just doesn't kick off, yet it moves the cron info after the time passes till tomorrow - for example, I attempted to kick it off this morning at 11:00 am, 11:00 came and went and the cron info moved till tomorrow but no task kicked off.

My question is - is the cron info based on your server's time or what would the cron job timezone be so I can adjust accordingly? I am running crawlab v0.6.0

![image](https://github.com/crawlab-team/crawlab/assets/33171507/1c2b87df-06b9-4223-94b3-e363738116f4)

**Comment by tikazyq** [comment]
Hi @DevinSmith69,

I think the cron time is based on your local server time zone and please check your host server's tz config and make sure it aligns with your current time zone.

**Comment by oyhel** [comment]
For those using docker/docker compose, set the TZ environment variable to fix this. The documentation could benefit from adding this info. I assume it is set to the developers point of origin.

**Comment by DevinSmith69** [comment]
Ahhh, thank you @oyhel - think that is my issue - will check it out
