### ISSUE TITLE
Crawlab Pro !Abnormal status on tasks

### ISSUE THREAD

**Issue by Voyewodayer** [crawlab-team/crawlab#1388]
**Describe the bug**
Certain tasks show !Abnormal status after running them for few hours but there aren't any errors shown either in task logs or in docker logs. Few hours later they tend to change to finished status even though they do not finish properly. Resource use for underlying node is in norm (less than 60% on every metric) and there aren't any availability issues.

**To Reproduce**
1. Schedule task
2. Wait few hours
3. !Abnormal status is being shown.
4. Few hours later task shows finished status but it didn't finish correctly.

**Expected behavior**
Task finishes with successful status or with error with proper logs

**Screenshots**
![obraz](https://github.com/crawlab-team/crawlab/assets/65357788/bb5654a3-0715-4f73-a887-d847c87232eb)

**Comment by tikazyq** [comment]
Hi @Voyewodayer ,

Thanks for the feedback. The Abnormal status means the tasks were pending/running and somehow the server/node restarted so it's set as abnormal. You can check the docker logs to find out what happened to your master node.

Marvin
