### ISSUE TITLE
请问下爬虫支持其他语言么？

### ISSUE THREAD

**Issue by ztcjn** [crawlab-team/crawlab#139]
请问下爬虫支持用go写么？？

另外爬虫任务支持分批么，比如我要爬一个300页的列表页数据  但是我想把这三百页的任务自动分配给3个爬虫去执行，还不能重复爬，这样的需求~

**Comment by tikazyq** [comment]
当然可以支持其他语言，这里可能有些misleading了，其实crawlab后端是用golang写，不代表不能执行其他语言的爬虫，理论上可以执行任何语言的爬虫。

你的需求只需要将要抓取的种子页储存在数据库里，让三个爬虫去拿就可以了，典型的生产者消费者模式

**Comment by ztcjn** [comment]
对的 对的 就是生产者消费者模式

**Comment by tikazyq** [comment]
至于怎么组合，那是你写爬虫的事情了，这个不是管理平台的任务，不过这是个很好的idea，你可以安装crawlab然后研究一下，将您的运行经历更新到文档里去

**Comment by Zerorigin** [comment]
crawlab 只是个管理平台，负责管理爬虫项目而已，如果你是使用 scrapy 来爬取数据，可以直接搭配 scrapy-redis 很方便的实现主从分布式爬虫。
