### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by jf888123** [crawlab-team/crawlab#1394]
日志被缓存在了文件系统里吗
![image](https://github.com/crawlab-team/crawlab/assets/60995035/e936380b-d33c-4fa3-b615-8ab5b5a82df6)

是否会随着任务的删除而释放掉

**Comment by ma-pony** [comment]
日志在另外的目录下

**Comment by tikazyq** [comment]
请查看 `/var/log/crawlab`
