### ISSUE TITLE
fail to init submodule

### ISSUE THREAD

**Issue by okki-dev1** [crawlab-team/crawlab#1397]
**Describe the bug**
`git submodule init` not work

**To Reproduce**
1. clone the repo
2. run `git submodule init`
3. nothings happens

**Expected behavior**
All the submodule should be initialized well

**Fix advice**
According to this [answer](https://stackoverflow.com/a/33369709), all the folder for submodule should be committed to the repo

**Workaround**
For whom met this issue, you can manually add submodule by yourself
```bash
git submodule add https://github.com/crawlab-team/crawlab-core backend/core
git submodule add https://github.com/crawlab-team/crawlab-db backend/db
git submodule add https://github.com/crawlab-team/crawlab-fs backend/fs
git submodule add https://github.com/crawlab-team/crawlab-vcs backend/vcs
git submodule add https://github.com/crawlab-team/crawlab-log backend/log
```

**Comment by tikazyq** [comment]
This is interesting but submodule is not recommended. If you want to contribute to the core code, you can git clone each repo to your local machine and try to link them in the go.mod file.
