### ISSUE TITLE
Crawlab Evaluation

### ISSUE THREAD

**Issue by username-mike** [crawlab-team/crawlab#1399]
Hey There -  

I'm evaluating using Crawlab for our crawlers, but came across an issue trying to deploy our first crawler using the framework.  Our existing Python spider navigates to the site we want to scrape and parses the data into a relational structure using Beautiful Soup.  The data is saved to a JSON lines file and saved to the local disk.  It also will save all the pages and images it traverses during the crawl to the local disk as back up just in case we need to re-parse any of the pages (could be millions) it collected.

The issue we have is that we are unable to figure out how to save the data, images or HTML to our local 10TB windows hard drive that we use for our data retention and data processing.  Is there a way to pass context to the spider so that it knows where it can place the data it collects?

Environment:
Windows 2022 Server running Docker WSL2
Spider - Python 3.10

**Comment by tikazyq** [comment]
Hi @username-mike,

Thanks for your interest in Crawlab. I understand you are trying to save files/images on local disk. However, in Crawlab, the working directory for crawler program to run is temporary, so that the files/images you saved on the folders will not persist. The way to solve this issue is to save to an absolute path folder and mount that folder to the host machine.

**Comment by username-mike** [comment]
Thank you for your comment.  Since we are evaluating the software, we only have Crawlab set up with the Master Node deployment where we are executing our python script.  If we go to the path on the windows server, we don't see the files.  Do we need to specify the network path?

![image](https://github.com/crawlab-team/crawlab/assets/145069239/a94dbfc1-7a9d-451b-8932-d3f7f0fddc58)

**Comment by tikazyq** [comment]
You are trying to save files on the host machine (C:\Users\Index.csv) directly, which might not be working because in Crawlab the files are supposed to be in the container, i.e. volumes. You can refer to https://docs.docker.com/storage/volumes/ for more information.

**Comment by oyhel** [comment]
Hi, 
we are currently running into the same problem with a slightly different setup. For testing we have one master node and two worker nodes. We are using the multi-node deployment for testing set up as described in the docker-compose example in the documentation. We are running into a problem wherein we are not able to make the worker node data persist. If we for some reason need to take the containers down and later spin these up again the workers are provided with a new random ID and we need install all dependencies again. Where is the data for the worker nodes stored, and how to make the worker nodes persist?
