### ISSUE TITLE
文件保存（About the problem of file saving）

### ISSUE THREAD

**Issue by flyz1** [crawlab-team/crawlab#1401]
使用Selenium爬取页面的过程中  需要将文件临时保存下来  然后  再对保存的文件处理后  得到最终结果，请问为什么运行之后没有保存的文件呢？
In the process of using Selenium to crawl the page, I need to save the file temporarily. Then, after processing the saved file, I can get the final result. May I ask why there is no saved file after running?

![image](https://github.com/crawlab-team/crawlab/assets/43409572/547968ce-aab6-44b2-9470-5ba2265e01f3)
![image](https://github.com/crawlab-team/crawlab/assets/43409572/6f39230b-6cbb-46ea-a5e4-1c50e56dbf38)

**Comment by tikazyq** [comment]
可以尝试用绝对路径保存，相对路径会保存失败的
