### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by zhangwei199207** [crawlab-team/crawlab#1407]
**Describe the bug**
can not support dependency  version chose 
**To Reproduce**
1. Go to 'http://localhost:8080/#/env/deps/python'
2. 
**Can not get the old  version selenium,suggest support version search **
![image](https://github.com/crawlab-team/crawlab/assets/72115258/17077a34-8963-406c-b1cf-6bec7b8c325e)

**Screenshots**

**Comment by tikazyq** [comment]
Will update in later version in Crawlab Pro
