### ISSUE TITLE
Elastic search包依赖安装不起作用

### ISSUE THREAD

**Issue by bright2013** [crawlab-team/crawlab#1409]
**Describe the bug**
Docker最新版，安装ES依赖后，爬虫运行时仍显示找不到包
![image](https://github.com/crawlab-team/crawlab/assets/4150196/142ead93-c8de-4eca-9b23-9a52f9a8c688)

![image](https://github.com/crawlab-team/crawlab/assets/4150196/35298df1-3288-4e21-b981-9a77c789a63d)

**Comment by tikazyq** [comment]
看看是否有其他python环境，理论上默认的python环境应该可以导入到
