### ISSUE TITLE
pip 搜索trafilatura包，找不到

### ISSUE THREAD

**Issue by glacierck** [crawlab-team/crawlab#1412]
**Describe the bug**
如题，需要安装个提取内容的包，trafilatura，pypi.org官网都找得到
，兼容python3 到了3.12了
**To Reproduce**
安装依赖
python
查找trafilatura

**Comment by glacierck** [comment]
好吧，点了一下旁边的更新按钮居然又能搜出东西了。。。。什么逻辑。。。

**Comment by tikazyq** [comment]
感谢反馈，很高兴你自己解决了问题

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/25/2023 10:45 |
| To | crawlab-team/crawlab ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | Re: [crawlab-team/crawlab] pip 搜索trafilatura包，找不到 (Issue #1412) |

Closed #1412 as completed.
