### ISSUE TITLE
crawlab依赖管理界面 安装指定版本的依赖包

### ISSUE THREAD

**Issue by whoishuhu** [crawlab-team/crawlab#1423]
![image](https://github.com/crawlab-team/crawlab/assets/59349728/4cd3fbfb-47b1-4175-80a9-2c99705ccd7b)
如图所示的安装界面，希望可以增加包的版本选择

目前安装依赖包的方式：
![image](https://github.com/crawlab-team/crawlab/assets/59349728/0036773f-f227-4716-a8c8-fdcdc4c43cf9)
![image](https://github.com/crawlab-team/crawlab/assets/59349728/c48da682-b9bf-4301-9c23-6c0d1dd8e67f)
不知道是不是正确的方式，但是需要新建爬虫，选择所有节点，运行爬虫执行requirements.txt  这种方式过于不友好

**Comment by tikazyq** [comment]
Will release in the upcoming Crawlab Pro

**Comment by tikazyq** [comment]
<img width="624" alt="image" src="https://github.com/crawlab-team/crawlab/assets/3393101/6d8827c5-ded8-4f18-934e-33e17a2b9150">
