### ISSUE TITLE
单节点安装以后总是显示requests依赖没有安装，导致爬虫运行失败

### ISSUE THREAD

**Issue by perpetually** [crawlab-team/crawlab#1426]
**Bug 描述**
next.crawlab.cn/zh/guide/installation/docker.html#%E5%8D%95%E8%8A%82%E7%82%B9%E9%83%A8%E7%BD%B2)

**复现步骤**
该 Bug 复现步骤如下
1单节点部署
2上传爬虫文件
3启动爬虫(命令是python3 run.py)
4启动失败了，ModuleNotFoundError: No module named 'requests'

**期望结果**
在底部安装依赖栏，选择了python安装到所有节点

**Comment by tikazyq** [comment]
执行命令中请使用 python，而不是python3

**Comment by tikazyq** [comment]
python3是容器自带的，后续会修复这个问题
