### ISSUE TITLE
作者您好，关于配置信息的请教

### ISSUE THREAD

**Issue by kanadeblisst** [crawlab-team/crawlab#143]
如果要在虚拟机中运行crwalab，CRAWLAB_REDIS_ADDRESS、CRAWLAB_MONGO_HOST、CRAWLAB_API_ADDRESS应该是怎么配置。

我试着这样运行，虽然能在Windows访问到登录界面，但无法登录(登录按钮一直转圈)。
```
docker run -d --restart always --name crawlab \
        -e CRAWLAB_SERVER_MASTER=Y \
        -e CRAWLAB_API_ADDRESS=192.168.199.150:8000 \
        -p 8080:8080 \
        -p 8000:8000 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:latest
```

我一直不明白，CRAWLAB_REDIS_ADDRESS、CRAWLAB_MONGO_HOST应该填什么，我百度了一下Docker Machine，这个应该是为了批量部署docker的，但我现在只想在一台机器上实验一下您的项目。请问该如何配置。以下是crawlab容器的日志信息，应该是访问不到mongo数据库。我在主机是可以直接进入mongo命令行的，未设置密码。那么就是CRAWLAB_MONGO_HOST配置错误。

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

2019/08/18 06:03:40  info 初始化配置成功                  
2019/08/18 06:03:40  info 初始化日志设置成功                
2019/08/18 06:03:51 error init mongodb error:no reachable servers
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
main.main()
	/go/src/app/main.go:35 +0x23c
panic: no reachable servers

goroutine 1 [running]:
main.main()
	/go/src/app/main.go:36 +0x20d0

**Comment by tikazyq** [comment]
您好，针对您的问题，强烈建议您去看相关文档，关于配置的 https://tikazyq.github.io/crawlab-docs/Config/ 。

如果您是docker machine的话，您的mongodb连接应该指向宿主机的ip地址，也就是192.168.99.1，redis也是一样。您的问题应该是没有指定mongodb和redis的连接导致的。

您可以尝试设置一下相关参数试试

**Comment by hantmac** [comment]
登录转圈圈很大的可能是后端服务没有起来，可以F12看一下network的接口，应该是404，需要根据文档把后端配好

**Comment by kanadeblisst** [comment]
> 您好，针对您的问题，强烈建议您去看相关文档，关于配置的https://tikazyq.github.io/crawlab-docs/Config/。
> 
> 如果你是docker machine的话，你的mongodb连接应该指向宿主机的ip地址，也就是192.168.99.1，redis也是一样。你的问题应该是没有指定mongodb和redis的连接导致的。
> 
> 您可以尝试设置一下相关参数试试

您好。这是虚拟执行ifconfig的结果。如果需要宿主机的IP，应该是172.17.0.1吧。但是我将MongoDB和Redis的地址改成这个也是同样的问题。
```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ca:be:4e:8b  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.8.23  netmask 255.255.255.0  broadcast 192.168.8.255
        inet6 fe80::34ff:56c9:5dcf:7a66  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:65:00:22  txqueuelen 1000  (Ethernet)
        RX packets 7541  bytes 605439 (591.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1365  bytes 109032 (106.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 44  bytes 3788 (3.6 KiB)
```

**Comment by kanadeblisst** [comment]
> 登录转圈圈很大的可能是后端服务没有起来，可以F12看一下网络的接口，应该是404，需要根据文档把后端配好

其实服务并没有起起来，因为加了这个参数--restart always，所以一直在重启，重启的过程中能访问页面。如果去掉这个参数，报完错容器就停止了，我觉得可能还是因为mongo和Redis的地址没有填对。

**Comment by wo10378931** [comment]
> > 您好，针对您的问题，强烈建议您去看相关文档，关于配置的[https://tikazyq.github.io/crawlab-docs/Config/。](https://tikazyq.github.io/crawlab-docs/Config/%E3%80%82)
> > 如果你是docker machine的话，你的mongodb连接应该指向宿主机的ip地址，也就是192.168.99.1，redis也是一样。你的问题应该是没有指定mongodb和redis的连接导致的。
> > 您可以尝试设置一下相关参数试试
> 
> 您好。这是虚拟执行ifconfig的结果。如果需要宿主机的IP，应该是172.17.0.1吧。但是我将MongoDB和Redis的地址改成这个也是同样的问题。
> 
> ```
> docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
>         inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
>         ether 02:42:ca:be:4e:8b  txqueuelen 0  (Ethernet)
>         RX packets 0  bytes 0 (0.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 0  bytes 0 (0.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.8.23  netmask 255.255.255.0  broadcast 192.168.8.255
>         inet6 fe80::34ff:56c9:5dcf:7a66  prefixlen 64  scopeid 0x20<link>
>         ether 00:0c:29:65:00:22  txqueuelen 1000  (Ethernet)
>         RX packets 7541  bytes 605439 (591.2 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 1365  bytes 109032 (106.4 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 44  bytes 3788 (3.6 KiB)
> ```

不对哦，怎么是docker0的IP。应该是你ssh上去的那个IP
