### ISSUE TITLE
Installing Software Dependencies

### ISSUE THREAD

**Issue by username-mike** [crawlab-team/crawlab#1433]
We currently use pypostal to parse addresses within our crawlers (https://github.com/openvenues/pypostal).  This software requires some C code to be installed.  After installed the pre-requisites, the libpostal software needs the C libraries to be installed and set up.  Is this something that can be set up to run in the Crawlab container (see the relevant section below).  One other option I'm considering is running another container on my Ubuntu server with the libpostal API (https://github.com/johnlonganecker/libpostal-rest-docker), but I'm not sure if Crawlab would have access to the localhost API on my Ubuntu server.  Let me know what you think would be a workable solution.

git clone https://github.com/openvenues/libpostal
cd libpostal
./bootstrap.sh
./configure --datadir=[...some dir with a few GB of space...]
make
sudo make install
On Linux it's probably a good idea to run
sudo ldconfig

**Comment by tikazyq** [comment]
Hi, you can actually enter the Docker container to manually install the required library.

```bash
docker exec -it <container_name> bash

# commands to install the library
...
```

**Comment by username-mike** [comment]
This worked beautifully.  Thanks for your help with this item!
