### ISSUE TITLE
The background page can execute any command

### ISSUE THREAD

**Issue by aomanbuaoman** [crawlab-team/crawlab#1440]
After logging in to rawlab, in the task module, you can create commands and execute them

![image](https://github.com/crawlab-team/crawlab/assets/75356114/1ed32058-d5d5-411f-9da8-a27a02735493)

like:

Add task

![image](https://github.com/crawlab-team/crawlab/assets/75356114/8c5e8b19-89bb-454e-9b8a-357787cab866)

Execute ifconfig

![image](https://github.com/crawlab-team/crawlab/assets/75356114/8b4b9e57-3939-4fa7-9f23-782b486dce1e)

successfully executed

![image](https://github.com/crawlab-team/crawlab/assets/75356114/ea5a1022-1d82-4684-9804-f8f608564213)

![image](https://github.com/crawlab-team/crawlab/assets/75356114/ba74be33-8336-40da-9474-61e254271196)

**Comment by tikazyq** [comment]
This is expected as it is designed as shell script execution
