### ISSUE TITLE
磁盘被占满了

### ISSUE THREAD

**Issue by DJGods** [crawlab-team/crawlab#1460]
我现在使用的是crawlab0.6.3
主节点不启用，配置两个工作节点执行爬虫

主节点居然占用了70多个g，差点把我磁盘爆了

**Comment by ma-pony** [comment]
日志清一清

**Comment by DJGods** [comment]
> 日清一清

docker日志吗还是啥？清理哪里的？

**Comment by ma-pony** [comment]
> > 日清一清
> 
> docker日志吗还是啥？清理哪里的？

任务运行日志，应该在容器的/var/log/crawlab目录下

**Comment by DJGods** [comment]
> > > 日清一清
> > 
> > 
> > docker 日志吗？清理哪里的？
> 
> 任务运行日志，应该在容器的/var/log/crawlab目录下

看到了，现在爬虫任务的日志都存这边吗？我记得以前的版本不是在MongoDB里面吗

**Comment by ma-pony** [comment]
> > > > 日清一清
> > > 
> > > 
> > > docker 日志吗？清理哪里的？
> > 
> > 
> > 任务运行日志，应该在容器的/var/log/crawlab目录下
> 
> 看到了，现在爬虫任务的日志都存这边吗？我记得以前的版本不是在MongoDB里面吗

目前都存在这
