### ISSUE TITLE
SDK支持条用统计接口么？目前数据源有bug，我应该如何在爬虫完成时自己更新爬虫的总结果数

### ISSUE THREAD

**Issue by TDxhfeng** [crawlab-team/crawlab#1474]
![image](https://github.com/crawlab-team/crawlab/assets/64594937/49f679f5-7138-4168-8dce-9e59afd20bc7)
![image](https://github.com/crawlab-team/crawlab/assets/64594937/4d41736e-16f7-4da4-9e3e-d49cec561266)
此处的外部数据源是有bug的。所以我无法使用sdk的 saveitem方法，我就自己实现爬虫的数据存储，但是这样就导致在任务执行完成的时候，我无法更新爬虫的结果数，所以有无办法调取sdk的统计接口，使得我自己更新统计数来判断爬虫是否成功

**Comment by jf888123** [comment]
框架其实主负责调度,统计不需要再这里做

**Comment by 7ee3** [comment]
+1, same issure

**Comment by tikazyq** [comment]
可以在 mongo 里进行操作，具体的collection是spider_stats
