### ISSUE TITLE
安装依赖插件，点击启动后立即走动停止，

### ISSUE THREAD

**Issue by SlinZhang** [crawlab-team/crawlab#1492]
**Bug 描述**
安装依赖插件，点击启动后立即走动停止，

**复现步骤**
该 Bug 复现步骤如下

**期望结果**
能使用依赖插件

**截屏**
![截屏2024-07-10 17 19 08](https://github.com/crawlab-team/crawlab/assets/35492662/3f35be25-b052-44ed-9ac3-8c12363e243c)

**Comment by tikazyq** [comment]
插件已不再支持，请用最新镜像
