### ISSUE TITLE
How to clean/empty mongodb?

### ISSUE THREAD

**Issue by milosh-dev** [crawlab-team/crawlab#1504]
Over the time the mongodb database is growing, but there aparently is no method to empty/clean the database.

In my case - I am sending scraped data over the email and I don't use crawlab's internal database. Hence the UI does not indicate that I have date in the database. However, over the time the database will grow for some reason (there has to be some bug to cause that). Even If I delete all the task history, the database will remain large.  

Once the mongodb will grow to the size of 0.5GB, the crawlab system crahses with the clame "No space left on device". The HDD is not full, but I suppose this is the limitation of mongodb. 

How to clean the mongodb?

**Comment by ma-pony** [comment]
In MongoDB, disc space is not automatically freed up after a collection is emptied (deleted).

**Comment by tikazyq** [comment]
Perhaps it's because of the log size issue with docker. You can limit the docker log size by configuring the settings. Please read https://docs.docker.com/engine/logging/configure/#configure-the-default-logging-driver
