### ISSUE TITLE
这项目是认真的吗，docker部署都登陆不上去，默认指向localhost:8000，而且不能改

### ISSUE THREAD

**Issue by hcaihao** [crawlab-team/crawlab#1508]
这项目是认真的吗，docker部署都登陆不上去，默认指向localhost:8000，而且不能改

**Comment by m220745** [comment]
按文档部署，没有问题呀，肯定是你的步骤有问题了，还有默认访问的端口也不是8000。
（PS：没有操作步骤截图或日志，大家怎么知道你是卡在哪一步呢？）

**Comment by tikazyq** [comment]
可以去掉敏感信息看看docker-compose.yml配置么？

**Comment by tikazyq** [comment]
no response
