### ISSUE TITLE
License Server SSL Cert Expired

### ISSUE THREAD

**Issue by SamTheGeek** [crawlab-team/crawlab#1517]
**Describe the bug**
The certificate for `license.crawlab.cn` is expired

**To Reproduce**
`curl -vvl https://license.crawlab.cn`

**Expected behavior**
The SSL certificate would be returned as valid.

**Comment by tikazyq** [comment]
Hi @SamTheGeek , you can pull the latest image "crawlabteam/crawlab-pro:latest" as it won't validate through the license server. This should solve the issue.

**Comment by SamTheGeek** [comment]
Will give that a shot! Thanks @tikazyq
