### ISSUE TITLE
Docker镜像构建时注意精简清理

### ISSUE THREAD

**Issue by maoxuner** [crawlab-team/crawlab#1525]
**Describe the bug**
构建临时文件保留在镜像中，导致镜像体积特别大。同样的文件，比如weed在镜像中存在好几份

**To Reproduce**
```bash
$ docker run --rm crawlabteam/crawlab ls /
app
bin
boot
chromedriver_linux64.zip
dev
etc
go1.22.4.linux-amd64.tar.gz
home
lib
lib32
lib64
libx32
linux_amd64.tar.gz
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
weed
```

以下这些都是构建中的临时文件，镜像各个layer用完相关文件后要及时清理不需要的文件，不能传递到其他layer。可能还有其它多余的文件

- /chromedriver_linux64.zip
- /go1.22.4.linux-amd64.tar.gz
- /linux_amd64.tar.gz
- /weed
- /opt/bin/crawlab
- /root/go

**Expected behavior**
精简的镜像

**Screenshots**
<img width="848" alt="image" src="https://github.com/user-attachments/assets/d4b665cd-80c9-471d-b86a-1f78ef729cc7">

---
**其它建议：**
- 前端编译的时候不应该把api主机地址编译到代码里。或者，前端资源 js api地址的调整应该在构建过程中就调整，不要放在镜像入口文件里
- 镜像启动使用脚本时，需要用exec命令执行主程序，否则主程序接收不到终止信号
- 同上问题，一个镜像中要运行多个服务时，可以用s6-overlay套件。光看镜像文件没看明白weed和nginx是怎么启动起来的，我猜测是crawlab-server拉起来的
- 基础镜像ubuntu20版本太老了，建议换到ubuntu22及以上版本。否则无法使用更高版本的python及扩展库。未支持venv，容器重新构建的时候，库版本都会退回

**Comment by tikazyq** [comment]
addressed in recent commits, e.g. db4dce33a4c4546c22b882af7833e97fe1ebba6c

**Comment by tikazyq** [comment]
for other issues you mentioned, please submit as separate issues
