### ISSUE TITLE
which folder to place the yml config file when I deploy crawlab using docker-compose up?

### ISSUE THREAD

**Issue by nomoreplay** [crawlab-team/crawlab#159]
When I run the demo spider using default settings, it return "	pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
"
How can I fix this? thanks.

**Comment by tikazyq** [comment]
Hi, thanks for the feedback. I would suggest you to go to File tab on spider page and check out the scrapy spider file in detail. In there, you would see the environment variable named MONGO_HOST. The solution is to add MONGO_HOST as an environment variable with value as “mongo” in the Environment tab on spider page.

**Comment by tikazyq** [comment]
Hi, thanks for the feedback. I would suggest you to go to File tab on spider page and check out the scrapy spider file in detail. In there, you would see the environment variable named MONGO_HOST. The solution is to add MONGO_HOST as an environment variable with value as “mongo” in the Environment tab on spider page.
