### ISSUE TITLE
爬虫项目的环境依赖问题

### ISSUE THREAD

**Issue by hexiaosong** [crawlab-team/crawlab#161]
添加爬虫项目时，如何安装设置其依赖的环境呢？比如依赖python2或python3、第三方包等。

**Comment by tikazyq** [comment]
> 添加爬虫项目时，如何安装设置其依赖的环境呢？比如依赖python2或python3、第三方包等。

目前Crawlab还不支持在界面中安装依赖，因此需要自己手动安装。如果您是Docker部署的话，可以执行以下命令进入到Docker容器中。

```bash
docker -it <container_name> bash
```

然后您就可以通过`pip`或者其他命令来安装依赖了。

**Comment by hantmac** [comment]
最好是自定义所需要的镜像，这样以后可以重复使用

**Comment by hexiaosong** [comment]
按gitbook上的直接部署的文档步骤，没有运行起来，是程序更新了而文档没更新吗？   另外依赖的mongodb和reids部署项目前就先启动吗?

**Comment by tikazyq** [comment]
> 按gitbook上的直接部署的文档步骤，没有运行起来，是程序更新了而文档没更新吗？ 另外依赖的mongodb和reids部署项目前就先启动吗?

可以发一下错误日志看看
