### ISSUE TITLE
你好，python3.6 运行脚本打印中文字符出错，直接部署和docker部署都会出现这种情况

### ISSUE THREAD

**Issue by 126217832** [crawlab-team/crawlab#172]
运行前：
![image](https://user-images.githubusercontent.com/40737253/63677347-5b21e480-c81f-11e9-992e-6c7ab9aeada7.png)

运行后：
![image](https://user-images.githubusercontent.com/40737253/63677384-755bc280-c81f-11e9-8742-822f794fb7a5.png)

注：脚本在本地可以运行，排除字符集

**Comment by tikazyq** [comment]
是有这个问题，mark为bug，暂时的解决办法：在爬虫程序中用英文代替中文

**Comment by yaziming** [comment]
fix by #191
