### ISSUE TITLE
全局环境变量设置

### ISSUE THREAD

**Issue by coopergoon** [crawlab-team/crawlab#177]
可以设置全局的环境变量， 所有的爬虫任务都可以读取到 ， 不用每个任务都去设置一遍；同时保留每个任务也可以设置环境变量的功能（这个已经有了）

**Comment by tikazyq** [comment]
好建议！争取后期开发过程中加入进来

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/123e3835d25a874659e484c3706f7eb7db63fe01
