### ISSUE TITLE
将节点名称显示为ip地址而非Mac地址

### ISSUE THREAD

**Issue by hantmac** [crawlab-team/crawlab#178]
- 建议显示为 IP 地址，而不是 Mac 地址，因为 Mac 地址比 IP 地址更艰涩难记，手动分配任务或创建定时任务时容易错选

- 拓扑图的地方建议也改成主展示 IP地址，鼠标移动到相应节点上在展示具体的节点信息。

**Comment by wo10378931** [comment]
可以在节点详情编辑节点名称。然后在爬虫选择节点的下拉框就是显示节点名称

**Comment by hantmac** [comment]
默认将name改为ip吧，这个应该比较好改，我来吧
