### ISSUE TITLE
docker-compose up启动项目，页面登录时一直转圈

### ISSUE THREAD

**Issue by hexiaosong** [crawlab-team/crawlab#180]
使用命令"docker-compose up"启动项目后，访问首页，输入admin/admin，点击登录，登录图标一直转圈，登录不了。

**Comment by tikazyq** [comment]
请查看Q&A https://tikazyq.github.io/crawlab-docs/QA/

**Comment by hexiaosong** [comment]
OK了，将docker-compose.yml中的CRAWLAB_API_ADDRESS由原先的“localhost:8000”改成"主机IP:8000"即可。
