### ISSUE TITLE
任务删除后docker内部的代码和日志还存在

### ISSUE THREAD

**Issue by coopergoon** [crawlab-team/crawlab#183]
前端页面删除任务之后， 但是代码文件，写的日志还是留在子节点的docker里面  /app/spiderl路径下面。

**Comment by wo10378931** [comment]
还有删除爬虫后，在gf上的files也会存留

**Comment by tikazyq** [comment]
感觉是时候画画ER图了

**Comment by tikazyq** [comment]
duplicated in https://github.com/crawlab-team/crawlab/issues/174

**Comment by wo10378931** [comment]
fix #224
