### ISSUE TITLE
直接部署：登录时一直转圈，请问直接部署在哪里配置CRAWLAB_API_ADDRESS？

### ISSUE THREAD

**Issue by hexiaosong** [crawlab-team/crawlab#186]
1. 使用直接部署的方式，登录时候一直转圈，docker部署是直接在docker-compose.yml中配置CRAWLAB_API_ADDRESS为部署机器的ip地址，那如果是直接部署呢，怎么配置这个？
2. 另外项目有没有讨论的QQ群或微信群？

**Comment by tikazyq** [comment]
加微信 tikazyq1 加群
