### ISSUE TITLE
master 节点挂掉

### ISSUE THREAD

**Issue by pwen2018** [crawlab-team/crawlab#188]
fatal error: concurrent map writes

**Comment by hantmac** [comment]
==================
WARNING: DATA RACE
Read at 0x00c0001fcb78 by goroutine 42:
  crawlab/services.ExecuteTask()
      /workspace/Golang/crawlab/backend/services/task.go:223 +0x98
  crawlab/services.GetExecuteTaskFunc.func1()
      /workspace/Golang/crawlab/backend/services/task.go:202 +0x41
  crawlab/lib/cron.FuncJob.Run()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:131 +0x34
  crawlab/lib/cron.(*Cron).startJob.func1()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:307 +0x70

Previous write at 0x00c0001fcb78 by goroutine 24:
  crawlab/services.ExecuteTask.func1()
      /workspace/Golang/crawlab/backend/services/task.go:233 +0x61
  crawlab/services.ExecuteTask()
      /workspace/Golang/crawlab/backend/services/task.go:263 +0x383
  crawlab/services.GetExecuteTaskFunc.func1()
      /workspace/Golang/crawlab/backend/services/task.go:202 +0x41
  crawlab/lib/cron.FuncJob.Run()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:131 +0x34
  crawlab/lib/cron.(*Cron).startJob.func1()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:307 +0x70

Goroutine 42 (running) created at:
  crawlab/lib/cron.(*Cron).startJob()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:305 +0x84
  crawlab/lib/cron.(*Cron).run()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:268 +0x15ea

Goroutine 24 (finished) created at:
  crawlab/lib/cron.(*Cron).startJob()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:305 +0x84
  crawlab/lib/cron.(*Cron).run()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:268 +0x15ea
==================
==================
WARNING: DATA RACE
Read at 0x00c0001fcb79 by goroutine 43:
  crawlab/services.ExecuteTask()
      /workspace/Golang/crawlab/backend/services/task.go:223 +0x98
  crawlab/services.GetExecuteTaskFunc.func1()
      /workspace/Golang/crawlab/backend/services/task.go:202 +0x41
  crawlab/lib/cron.FuncJob.Run()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:131 +0x34
  crawlab/lib/cron.(*Cron).startJob.func1()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:307 +0x70

Previous write at 0x00c0001fcb79 by goroutine 25:
  crawlab/services.ExecuteTask.func1()
      /workspace/Golang/crawlab/backend/services/task.go:233 +0x61
  crawlab/services.ExecuteTask()
      /workspace/Golang/crawlab/backend/services/task.go:263 +0x383
  crawlab/services.GetExecuteTaskFunc.func1()
      /workspace/Golang/crawlab/backend/services/task.go:202 +0x41
  crawlab/lib/cron.FuncJob.Run()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:131 +0x34
  crawlab/lib/cron.(*Cron).startJob.func1()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:307 +0x70

Goroutine 43 (running) created at:
  crawlab/lib/cron.(*Cron).startJob()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:305 +0x84
  crawlab/lib/cron.(*Cron).run()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:268 +0x15ea

Goroutine 25 (finished) created at:
  crawlab/lib/cron.(*Cron).startJob()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:305 +0x84
  crawlab/lib/cron.(*Cron).run()
      /workspace/Golang/crawlab/backend/lib/cron/cron.go:268 +0x15ea

**Comment by hantmac** [comment]
Has been fixed in https://github.com/crawlab-team/crawlab/pull/210
