### ISSUE TITLE
爬虫结果集显示优化及文档改进建议

### ISSUE THREAD

**Issue by 52Lau** [crawlab-team/crawlab#196]
![image](https://user-images.githubusercontent.com/37538641/64066659-53af7080-cc4f-11e9-8e62-5f7b607c760a.png)
1、结果集里面，每一行显示过高

2、建议更新下文档里面关于“与Scrapy集成”这一块的内容，
比如MONGO_HOST = '192.168.99.100'  设置成MONGO_HOST = 'mongo'
item里面添加"_id"和”task_id“

3、爬虫配置结果集增加提示，提醒用户是mongdb的数据集
![image](https://user-images.githubusercontent.com/37538641/64066735-0f70a000-cc50-11e9-89a9-72e7cd0b1ce8.png)

**Comment by tikazyq** [comment]
已在 https://github.com/crawlab-team/crawlab/releases/tag/v0.4.5 中fix
