### ISSUE TITLE
关于结果数据的请教

### ISSUE THREAD

**Issue by KeXin95** [crawlab-team/crawlab#199]
作者您好，

我在scrapy爬虫任务执行完毕之后，数据库里面和前端任务详情里面都无法找到结果数据～不知道是否是我在哪个配置方面的问题？

<img width="576" alt="Screenshot 2019-09-01 at 10 55 01 PM" src="https://user-images.githubusercontent.com/29350673/64078298-8d45b180-cd0b-11e9-9cf9-8fcccd3240c8.png">

日志显示爬虫已执行完毕：
<img width="1261" alt="Screenshot 2019-09-01 at 10 45 58 PM" src="https://user-images.githubusercontent.com/29350673/64078209-4c00d200-cd0a-11e9-8d01-663ad8632e15.png">

结果那一栏没有任何数据：
<img width="1290" alt="Screenshot 2019-09-01 at 10 46 35 PM" src="https://user-images.githubusercontent.com/29350673/64078222-6044cf00-cd0a-11e9-8a15-bfce71d49778.png">

mongoDB也没有结果集：
<img width="205" alt="Screenshot 2019-09-01 at 10 48 50 PM" src="https://user-images.githubusercontent.com/29350673/64078245-b0bc2c80-cd0a-11e9-9ff2-b35b43f97bce.png">

**Comment by tikazyq** [comment]
是否按照这个文档来操作的？

https://tikazyq.github.io/crawlab-docs/Examples/ScrapyIntegration.html

**Comment by KeXin95** [comment]
谢谢您！根据那个操作能行了， 但是看起来前端的结果栏不能显示json（？）

<img width="1281" alt="Screenshot 2019-09-02 at 11 50 00 AM" src="https://user-images.githubusercontent.com/29350673/64089308-172b6400-cd78-11e9-93c4-804e6c2794d8.png">

在mongodb的这个数据是有的：
<img width="1087" alt="Screenshot 2019-09-02 at 11 50 09 AM" src="https://user-images.githubusercontent.com/29350673/64089334-3d510400-cd78-11e9-98ae-89d078efc10e.png">

**Comment by tikazyq** [comment]
> 谢谢您！根据那个操作能行了， 但是看起来前端的结果栏不能显示json（？）
> 
> <img alt="Screenshot 2019-09-02 at 11 50 00 AM" width="1281" src="https://user-images.githubusercontent.com/29350673/64089308-172b6400-cd78-11e9-93c4-804e6c2794d8.png">
> 
> 在mongodb的这个数据是有的：
> <img alt="Screenshot 2019-09-02 at 11 50 09 AM" width="1087" src="https://user-images.githubusercontent.com/29350673/64089334-3d510400-cd78-11e9-98ae-89d078efc10e.png">

JSON的显示可以后续加入，请重新提enhancement issue
