### ISSUE TITLE
初始账号密码无法登录

### ISSUE THREAD

**Issue by iambyd** [crawlab-team/crawlab#211]
服务已经正常启动，不过，输入账号密码始终等待中，无法进入系统
![image](https://user-images.githubusercontent.com/11927058/64232459-92317d80-cf24-11e9-9e72-3371233e0261.png)

**Comment by tikazyq** [comment]
请看文档 https://tikazyq.github.io/crawlab-docs/QA/

:)

**Comment by iambyd** [comment]
我是按照你们提供docker-compose.yml进行配置和启动的，CRAWLAB_API_ADDRESSyml里面已经配置过了，我也在windows系统下，按照你们官方提供示例命令启动了，但是也是同样的问题，所以还请指导下，谢谢
![image](https://user-images.githubusercontent.com/11927058/64240774-112eb200-cf35-11e9-8342-f0aff5e46c9e.png)

**Comment by tikazyq** [comment]
您这个是用的docker run的命令，而不是docker-compose的方式。

请查看docker-compose的方式

**Comment by iambyd** [comment]
我在windows环境下没有docker-compose，所以只能用docker直接启动，在centos下使用docker-compose，不过也是同样的问题

**Comment by tikazyq** [comment]
你的`CRAWLAB_API_ADDRESS`需要改为你宿主机的IP地址

**Comment by iambyd** [comment]
可以啦，我把localhost修改了下，就可以访问了，谢谢
