### ISSUE TITLE
任务派发问题

### ISSUE THREAD

**Issue by coopergoon** [crawlab-team/crawlab#215]
点击所有节点执行任务的时候， 任务列表里面之后显示一个节点，并不会显示所有节点，但是实际后台运行的时候，是所有节点执行

**Comment by tikazyq** [comment]
能说具体点么？

**Comment by coopergoon** [comment]
部署任务的时候， 点击运行， 在选择执行节点的时候， 选择其中一个节点执行是正常的，但是选择全部节点执行，在任务列表只能看到一个节点任务启动， 其余节点并不没有显示出来。  但是实际没有显示出来的节点的任务，也都在执行中。

**Comment by tikazyq** [comment]
这是表述的问题，所有节点其实意思是任意节点，后期我们会把真正的所有节点加上

**Comment by coopergoon** [comment]
原理如此
