### ISSUE TITLE
python执行print报编码问题

### ISSUE THREAD

**Issue by iambyd** [crawlab-team/crawlab#217]
在crawlab中执行print打印中文，报编码问题，本地验证没有问题
![image](https://user-images.githubusercontent.com/11927058/64407576-3b0fe200-d0b7-11e9-8ef3-85794e98bc84.png)

**Comment by tikazyq** [comment]
请用latest镜像试试

**Comment by iambyd** [comment]
最新镜像也不行，需要添加一个环境变量：PYTHONIOENCODING=UTF-8

**Comment by tikazyq** [comment]
看看这个解决方案 https://github.com/crawlab-team/crawlab/issues/219

在镜像中设置LANG环境变量
