### ISSUE TITLE
生成的日志文件中文编码为Unicode问题

### ISSUE THREAD

**Issue by xuanbo** [crawlab-team/crawlab#219]
golang通过命令（sh -c）调用py脚本时（https://github.com/crawlab-team/crawlab/blob/master/backend/services/task.go），我发现重定向标准、错误输出创建的日志文件为编码：ASCII text，（通过file xx），导致scrapy爬虫日志中文为Unicode。

发现，在golang代码调用命令的环境变量加入**LANG=zh_CN.UTF-8**，则生成的日志文件编码为：UTF-8 Unicode，中文可以正确显示。

	// 添加默认环境变量
	cmd.Env = append(cmd.Env, "CRAWLAB_TASK_ID="+t.Id)
	cmd.Env = append(cmd.Env, "CRAWLAB_COLLECTION="+s.Col)
        // 指定sh -c启动的环境语言
        cmd.Env = append(cmd.Env, "LANG=zh_CN.UTF-8")

**Comment by tikazyq** [comment]
good job，可以提PR来fix这个问题
