### ISSUE TITLE
修改docker-compose.yml连接本地的mongo和redis，在访问主页时报错

### ISSUE THREAD

**Issue by douxingjie** [crawlab-team/crawlab#225]
默认使用mongo和redis镜像时没有异常，当修改docker-compose.yml连接本地的mongo和redis，在访问主页时报错，其他功能正常
![image](https://user-images.githubusercontent.com/37068558/64601240-27ce8080-d3ef-11e9-9f78-b1d08e394b0c.png)

![image](https://user-images.githubusercontent.com/37068558/64601102-e5a53f00-d3ee-11e9-96e4-3d68babb420e.png)

![M`(JIW20)O_RV65NP8NG 2I](https://user-images.githubusercontent.com/37068558/64600886-7e878a80-d3ee-11e9-815f-b678ef50c976.png)

**Comment by yaziming** [comment]
Go 1.12+
Node 8.12+
Redis
MongoDB 3.6+

看下mongo的版本是否满足条件

**Comment by Zerorigin** [comment]
空字段不要配置出来，另外字段值全部用英文双引号引注。工作节点和 master 节点一样要配置 redis 和 mongodb 参数。另外记得配置好正确的宿主防火墙

**Comment by douxingjie** [comment]
是mongo的版本问题

**Comment by lostimever** [comment]
> 是mongo的版本问题

你好，请问在`docker-compose.yml`中如何配置，可以让`Docker`访问本地`Mongodb`

**Comment by charlesXu86** [comment]
> > 是mongo的版本问题
> 
> 你好，请问在`docker-compose.yml`中如何配置，可以让`Docker`访问本地`Mongodb`

同问
