### ISSUE TITLE
worker 节点运行的爬虫脚本日志信息不显示

### ISSUE THREAD

**Issue by Moxida** [crawlab-team/crawlab#229]
分别单独的在master 和 worker 上跑相同的爬虫任务，master 和 worker 都可以正常执行，但是只有master 的“任务详情”中有日志输出，worker 的“任务详情”中“日志” 为空。但是进入worker容器中根据日志文件路径，是可以看到日志信息的，只是Crawlab worker 的任务详情中没有显示

**Comment by hantmac** [comment]
@tikazyq 这个问题现在xyz解决了吗

**Comment by wo10378931** [comment]
已修复 #233
