### ISSUE TITLE
定时任务执行问题

### ISSUE THREAD

**Issue by xiaohuziaps** [crawlab-team/crawlab#230]
设置了一个定时任务，放在其中一个节点运行，开始还是可以定时执行的。运行一段时间后，就显示“待定”状态
![image](https://user-images.githubusercontent.com/3488917/65810235-8ca11d80-e1da-11e9-86a4-763471869527.png)
       需要重新在定时任务中设置节点后，任务正常执行。请问这是什么问题？

**Comment by tikazyq** [comment]
具体描述一下问题？

**Comment by xiaohuziaps** [comment]
![image](https://user-images.githubusercontent.com/3488917/65812900-5ffffc80-e200-11e9-99a9-0704566dcdfd.png)
我这个定时任务，节点：172.20.0.4。在2019-09-23 11:10:00这个时间之前，一直都是正确执行。这个时间后就一直是待定状态。一直到2019-09-28 10:01:15这个时间，我在“定时任务”里再次指定了执行节点为：172.20.0.4，后才可以正常执行任务。

**Comment by xiaohuziaps** [comment]
放假回来后又出现了这个问题
![image](https://user-images.githubusercontent.com/3488917/66372822-8f212580-e9d9-11e9-9dcd-30b217a49bd8.png)
![image](https://user-images.githubusercontent.com/3488917/66372837-9b0ce780-e9d9-11e9-8b30-b678099d34f2.png)
从上面的图中可以看到，节点从原来的“172.20.0.4”变成了一推字符串，然后定时任务就是待定状态了
![image](https://user-images.githubusercontent.com/3488917/66372948-f048f900-e9d9-11e9-8506-4f919c05284c.png)

**Comment by wo10378931** [comment]
你好，问题应该是这样的。
爬虫的程序可能某些原因把节点搞挂了，导致节点重启过，然后再注册的过程会出现重复注册的情况，导致数据库的节点被删除，并新建。这样定时任务那边关联的节点还是旧的节点ID，在定时任务调度的时候会找不到对应的节点。就会出现截图的情况

解决办法：
1、不要使用mac地址注册，使用ip注册，然后指定IP（也不一定是IP，只要是唯一的字符串即可）
2、升级到0.3.3版本，该版本会比较稳定
3、等下个版本，我fix后再告知
