### ISSUE TITLE
后端启动异常退出了

### ISSUE THREAD

**Issue by klights** [crawlab-team/crawlab#231]
panic: cannot get current node

goroutine 1 [running]:
crawlab/services.GetCurrentNode(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/soft/crawlab/backend/services/node.go:51 +0x5b3
crawlab/services.InitNodeService(0x13ac050, 0xd0bddd)
	/root/soft/crawlab/backend/services/node.go:301 +0xd3
main.main()
	/root/soft/crawlab/backend/main.go:79 +0x495

**Comment by wo10378931** [comment]
错误信息不够，无法正确判断

**Comment by 545119811** [comment]
我的问题跟你一样的，我把config.yml的server的master配置为Y，register配置为：type：ip，ip修改为的本机ip。这样重新运行就可以了。

**Comment by wo10378931** [comment]
请尝试拉下最新版本的镜像0.3.2
