### ISSUE TITLE
新的docker镜像定时任务执行有问题，建议docker镜像有版本号做区分

### ISSUE THREAD

**Issue by Ahaaaaaa** [crawlab-team/crawlab#239]
问题截图：
![image](https://user-images.githubusercontent.com/16437917/66013361-7b6b5000-e4fd-11e9-8dc0-1aad93dd1a0d.png)
![image](https://user-images.githubusercontent.com/16437917/66013373-8920d580-e4fd-11e9-801d-100f79487492.png)
镜像版本：
![image](https://user-images.githubusercontent.com/16437917/66013421-b9687400-e4fd-11e9-8cbc-12bbd42303c3.png)

感谢。

**Comment by wo10378931** [comment]
你好，关于镜像版本，可以在dockerhub上找最高版号即可。

另外，从0.3.2版本也可以在退出按钮那边查看当前使用的版本号

关于执行日志的问题，截图显示是找不到日志文件，请排查：节点的日志文件是否被删除，被删除一般是因为docker没有挂载volume，然后重启就没有了

**Comment by Ahaaaaaa** [comment]
好的，谢谢回复，我拉新版本的镜像再试一下
