### ISSUE TITLE
task正常执行退出也会保存异常信息?

### ISSUE THREAD

**Issue by lijr20171011** [crawlab-team/crawlab#249]
文件：crawlab/backend/services/task.go
![image](https://user-images.githubusercontent.com/33930082/66545030-5feeed80-eb6c-11e9-85c2-26d9dad97a15.png)

**Comment by tikazyq** [comment]
似乎是个问题

**Comment by wo10378931** [comment]
嗯 位置放错了。 应该是在第一个if里面
