### ISSUE TITLE
redis中删除离线节点时没有及时修改mongo中的节点状态?

### ISSUE THREAD

**Issue by lijr20171011** [crawlab-team/crawlab#250]
文件：crawlab/backend/services/node.go
![image](https://user-images.githubusercontent.com/33930082/66548176-574de580-eb73-11e9-881c-5b14ea2e6ba2.png)

**Comment by tikazyq** [comment]
我记得是有逻辑来改变状态的，但不在这里

**Comment by wo10378931** [comment]
那个list会在下一次的轮训少一项，然后会在model.RestNodeStatusToOfflien中重置节点为离线。

PS : 该问题已修复，还未发布

**Comment by tikazyq** [comment]
> 那个list会在下一次的轮训少一项，然后会在model.RestNodeStatusToOfflien中重置节点为离线。
> 
> PS : 该问题已修复，还未发布

确定是Offlien? 这个是个typo bug哟
