### ISSUE TITLE
port 8080 is already in use

### ISSUE THREAD

**Issue by infantras** [crawlab-team/crawlab#251]
how to resolve this case??

**Comment by tikazyq** [comment]
can you elaborate a bit more? Which deployment type you use?

**Comment by infantras** [comment]
I'm using docker deployment type and in my docker the port 8080 is assigned to another program, so that port is currently unavailable. Is there any way to change the port number??

**Comment by infantras** [comment]
![Screenshot_2019-10-10-22-34-50-707_com android chrome](https://user-images.githubusercontent.com/55379315/66590357-3d7dc400-ebae-11e9-8090-ff229c92b503.png)

**Comment by tikazyq** [comment]
@infantras I think you are better off using the docker-compose to start crawlab. For how to use docker-compose, please refer to https://github.com/crawlab-team/crawlab#docker. I think the tutorial you are looking at is out-dated, so please check out the newer one. 

Basically, what you need to do is to change the port number on the LHS.

**Comment by infantras** [comment]
thank a lot.
but same problem arises for redis port also, saying the port 6379 is already in use.
as the redis server is already running, is using the port 6379 for other programs.
is there any way to solve this issue or as you said if i change port number on LHS will it run without affecting the other program.

FYI the error encountered during the docker installation is mentioned below:



Status: Downloaded newer image for redis:latest
Creating crawlab_redis_1 ... error
Creating crawlab_mongo_1 ...

ERROR: for crawlab_redis_1  Cannot start service redis: driver failed programming external connectivity on endpoint crawlab_redis_1 (f): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: addresCreating crawlab_mongo_1 ... done

ERROR: for redis  Cannot start service redis: driver failed programming external connectivity on endpoint crawlab_redis_1 (): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address **already in use**
ERROR: Encountered errors while bringing up the project.

**Comment by tikazyq** [comment]
@infantras I think you can refer to this issue for help. https://github.com/docker/compose/issues/4950

**Comment by infantras** [comment]
How long it usually takes to deploy?? Because it been running for past 6 hour and its still getting the meta data from each port in ip: 172.19.0.4

Or because of accessing from india
