### ISSUE TITLE
在管理页面修改爬虫文件时似乎没有同步到mongo

### ISSUE THREAD

**Issue by lijr20171011** [crawlab-team/crawlab#252]
我看到在管理页面修改爬虫文件时似乎只调用了修改主节点本地爬虫文件的接口，而且没有修改md5.txt。但并没有同步到mongo，也没有通知其他工作节点？还是在其他地方有同步？我暂时没找到。
![image](https://user-images.githubusercontent.com/33930082/66618865-76995100-ec0d-11e9-99c3-40d81f8670a5.png)
文件: crawlab/backend/routes/spider.go
![image](https://user-images.githubusercontent.com/33930082/66618941-b5c7a200-ec0d-11e9-9031-a60644ff4010.png)

**Comment by wo10378931** [comment]
嗯。界面修改爬虫的编辑器会禁用掉。因为机制不支持。
现在是上传爬虫后直接上传到GridFs，然后各个节点再同步到本地。
所以修改爬虫，实际上并不会上传到数据库，并且同步。
