### ISSUE TITLE
default username & password is not working

### ISSUE THREAD

**Issue by infantras** [crawlab-team/crawlab#255]
@tikazyq 
as i first time logging in

default username: admin
password : admin
is not working. what might be the cause??

**Comment by tikazyq** [comment]
First of all, please check if you have correctly set the `CRAWLAB_API_ADDRESS`. 90% possibility would be because of this. Please refer to https://tikazyq.github.io/crawlab-docs/QA/ for help (Chinese, you can translate into English using Google Translate).
