### ISSUE TITLE
Error when logging, blocked by CORS policy

### ISSUE THREAD

**Issue by leonlyu1996** [crawlab-team/crawlab#257]
已经将CRAWLAB_API_ADDRESS设置为宿主机ip，使用默认admin账号登录提示登录时出错，F12错误截图如下：
![image](https://user-images.githubusercontent.com/10532548/66696600-0ae3e080-ed00-11e9-812e-4380e62aa6e8.png)
docker日志截图如下：
![image](https://user-images.githubusercontent.com/10532548/66696687-a37a6080-ed00-11e9-97ee-a844cc459306.png)

**Comment by tikazyq** [comment]
根据日志来看，似乎没有到API这里来

**Comment by wo10378931** [comment]
建议直接访问后端API地址，看看是否能正常访问。
如果出现：404 page not found 就是可以正常访问

**Comment by tikazyq** [comment]
现在是否还存在问题
