### ISSUE TITLE
api接口环境变量参数的问题

### ISSUE THREAD

**Issue by TerribleLife** [crawlab-team/crawlab#258]
文档中参数名是CRAWLAB_API_PATH
> https://tikazyq.github.io/crawlab-docs/Config/

但实际部署时发现使用CRAWLAB_API_ADDRESS才有效，代码里也只有CRAWLAB_API_ADDRESS的存在，是不是需要更新一下文档

**Comment by tikazyq** [comment]
是的，这是个issue，我们会找时间修复的，你也可以提PR到 https://github.com/tikazyq/crawlab-docs
