### ISSUE TITLE
数据量大了前端获取不到结果数

### ISSUE THREAD

**Issue by XiaCo** [crawlab-team/crawlab#260]
给task_id加了索引后解决了问题

**Comment by tikazyq** [comment]
需要给结果集的 `task_id` 加上索引

**Comment by Abraham-liuhai** [comment]
> 给task_id加了索引后解决了问题

在哪里加啊

**Comment by XiaCo** [comment]
> > 给task_id加了索引后解决了问题
> 
> 在哪里加啊

docker exec -it xxxxxx bash 然后进mongo交互终端创建
