### ISSUE TITLE
Is there any way to integrate with selenium.

### ISSUE THREAD

**Issue by infantras** [crawlab-team/crawlab#261]

**Comment by tikazyq** [comment]
Yes. But we have no demo at this moment. Suggest you register a wechat account and ask me to join you into the dev group for further discussion :)

**Comment by tikazyq** [comment]
@infantras my wechat ID: tikazyq1

**Comment by tikazyq** [comment]
Please install the environment of Selenium in the docker through either re-building an image based on the Crawlab image adding Selenium libraries or `docker exec` to the container to manually install it.
