### ISSUE TITLE
时区好像有点不正确~

### ISSUE THREAD

**Issue by Williamsunsir** [crawlab-team/crawlab#262]
![1](https://user-images.githubusercontent.com/48049042/66879621-80e29300-eff1-11e9-846d-85edae896e73.png)
![2](https://user-images.githubusercontent.com/48049042/66879627-83dd8380-eff1-11e9-8580-e8cf295f6985.png)
MongoDB中的数据和前端对比~

**Comment by wo10378931** [comment]
经过校验，前端显示的时间是正确的，在mongodb中是使用了函数，所以显示不对。
建议修改下Mongodb的配置

**Comment by yaziming** [comment]
MongoDB中的Date类型数据只保存绝对时间值，不保存时区信息。 不一致是正确的
