### ISSUE TITLE
爬虫里面的环境变量主要是设置什么的？

### ISSUE THREAD

**Issue by yjiu1990** [crawlab-team/crawlab#264]
如题

**Comment by tikazyq** [comment]
传递环境变量到爬虫程序

**Comment by yjiu1990** [comment]
谢谢，再请问一下，我在设置了环境变量，可以在docker容器里的哪一个文件可以查看我设置的环境变量？因为设置了两个节点，有一个节点获取不到在WEB上设置的环境变量

**Comment by tikazyq** [comment]
> 谢谢，再请问一下，我在设置了环境变量，可以在docker容器里的哪一个文件可以查看我设置的环境变量？因为设置了两个节点，有一个节点获取不到在WEB上设置的环境变量

环境变量是直接传给爬虫程序的，如果接收不到环境变量是不正常的，请多测几次，如果有问题提bug issue

**Comment by yjiu1990** [comment]
好的，谢谢
