### ISSUE TITLE
设置完环境变量之后，两个节点有一个节点获取不到环境变量的信息?

### ISSUE THREAD

**Issue by yjiu1990** [crawlab-team/crawlab#265]
两个节点，一个运行正常，一个报如下错误

1	Traceback (most recent call last):
2	File "/usr/local/bin/scrapy", line 11, in <module>
3	sys.exit(execute())
4	File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 145, in execute
5	cmd.crawler_process = CrawlerProcess(settings)
6	File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 267, in __init__
7	super(CrawlerProcess, self).__init__(settings)
8	File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 145, in __init__
9	self.spider_loader = _get_spider_loader(settings)
10	File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 347, in _get_spider_loader
11	return loader_cls.from_settings(settings.frozencopy())
12	File "/usr/local/lib/python3.6/dist-packages/scrapy/spiderloader.py", line 61, in from_settings
13	return cls(settings)
14	File "/usr/local/lib/python3.6/dist-packages/scrapy/spiderloader.py", line 25, in __init__
15	self._load_all_spiders()
16	File "/usr/local/lib/python3.6/dist-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
17	for module in walk_modules(name):
18	File "/usr/local/lib/python3.6/dist-packages/scrapy/utils/misc.py", line 73, in walk_modules
19	submod = import_module(fullpath)
20	File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
21	return _bootstrap._gcd_import(name[level:], package, level)
22	File "<frozen importlib._bootstrap>", line 994, in _gcd_import
23	File "<frozen importlib._bootstrap>", line 971, in _find_and_load
24	File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
25	File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
26	File "<frozen importlib._bootstrap_external>", line 678, in exec_module
27	File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
28	File "/app/spiders/aliyun_ecs/aliyun/spiders/aliyun_monitor.py", line 41, in <module>
29	charset='utf8'
30	File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
31	return Connection(*args, **kwargs)
32	File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
33	self.connect()
34	File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 589, in connect
35	self.host_info = "socket %s:%d" % (self.host, self.port)
36	TypeError: %d format: a number is required, not str

**Comment by tikazyq** [comment]
看起来需要转换一下类型，这里要求是 int

**Comment by yjiu1990** [comment]
> 看起来需要转换一下类型，这里要求是int

那为什么有一个节点会正常运行呢，另外一个就不行，这是我要改哪里呢？

**Comment by tikazyq** [comment]
用最新镜像试试
