### ISSUE TITLE
日志的留存

### ISSUE THREAD

**Issue by fafafafso** [crawlab-team/crawlab#266]
能不能设置不清除日志

**Comment by tikazyq** [comment]
可以，参照配置文档

**Comment by fafafafso** [comment]
是/app/backend/conf下的config.yml文件吗

**Comment by tikazyq** [comment]
是的，还有配置文档，就是文档链接里的配置这一块

**Comment by fafafafso** [comment]
修改了文件，也添加了环境变量CRAWLAB_LOG_ISDELETEPERIODICALLY为N，日志还是被清除

**Comment by tikazyq** [comment]
我们会调查一下这个情况

**Comment by hantmac** [comment]
<img width="715" alt="截屏2019-10-2021 29 18" src="https://user-images.githubusercontent.com/7600925/67160195-c5b75280-f380-11e9-80bf-1b1f2d2b0b85.png">

我又测试了一下，源代码这里`isDeletePeriodically`设置成 `N`日志是不会被清除的。
ps:你是容器启的还是本机测试？

**Comment by fafafafso** [comment]
docker-compose启的

**Comment by fafafafso** [comment]
而且我发现有部分爬虫的日志，一部分是保留的，一部分被清除了（这些操作日志时间是穿插的）

**Comment by hantmac** [comment]
> 而且我发现有部分爬虫的日志，一部分是保留的，一部分被清除了（这些操作日志时间是穿插的）

这么玄幻的吗

**Comment by hantmac** [comment]
应该没啥问题，先close了
