### ISSUE TITLE
Fix to pass CRAWLAB_API_ADDRESS with scheme such as https://example.com

### ISSUE THREAD

**Issue by haivp3010** [crawlab-team/crawlab#267]
Currently environment variable CRAWLAB_API_ADDRESS, when passed with the `https://` part will cause the frontend not to work.

This is due to these lines of code that are not properly handled:

In `request.js` file, the default fallback URL is prefixed with `http`:

https://github.com/crawlab-team/crawlab/blob/89c446ec9f2013a401c1e23db8077225c272b9a5/frontend/src/api/request.js#L4

But when replacing it inside the docker container, we're only replacing the `localhost:8080` part:

https://github.com/crawlab-team/crawlab/blob/89c446ec9f2013a401c1e23db8077225c272b9a5/docker_init.sh#L9

I'd like to make a change to the `docker_init.sh` file so that it becomes:
`sed -i "s?http://localhost:8000?${CRAWLAB_API_ADDRESS}?g" ${jspath}`

**Comment by tikazyq** [comment]
Hi @haivp3010 

I think you are right. This may cause an issue when you are trying to use https instead of http. We will look at this issue and try to come up with a solution. In the mean time, you can try to find a solution fixing this problem.
