### ISSUE TITLE
python依赖其他爬虫项目做模块无法运行

### ISSUE THREAD

**Issue by zzl221000** [crawlab-team/crawlab#269]
## 日志文件丢失
- `no such dictionary or file`
- 进docker ，logs文件夹文件全没了

## 模块导入问题
- 按照目录结构`sys.path.append()`导入其他爬虫项目文件夹，爬虫不能启动

**Comment by hantmac** [comment]
1.配置文件里isDeletePeriodically默认是设置成 Y,日志每小时清除一次，如果要保留日志的话，设置成N，具体请看文档。
2. 爬虫不能启动的报错贴一下

**Comment by zzl221000** [comment]
无任何报错，状态是待定

**Comment by hantmac** [comment]
- `no such dictionary or file`确实是个bug，在 https://github.com/crawlab-team/crawlab/pull/324 这个PR修复了，可以再试试；
- 要长时间保存日志的话，`isDeletePeriodically`可以设置长一点
