### ISSUE TITLE
使用pymysql连接数据库后不自动连接远程数据库会一直连接到本地的数据库？

### ISSUE THREAD

**Issue by yjiu1990** [crawlab-team/crawlab#270]
将mongodb与redis都设置密码后，设置环境变量，再使用pymysql模块去连接时会一直连接到本地数据库中，不会连接到远程数据库
21	return _bootstrap._gcd_import(name[level:], package, level)
22	File "<frozen importlib._bootstrap>", line 994, in _gcd_import
23	File "<frozen importlib._bootstrap>", line 971, in _find_and_load
24	File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
25	File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
26	File "<frozen importlib._bootstrap_external>", line 678, in exec_module
27	File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
28	File "/app/spiders/aliyun/aliyun/spiders/rds_module.py", line 32, in <module>
29	charset='utf8'
30	File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
31	return Connection(*args, **kwargs)
32	File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
33	self.connect()
34	File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 599, in connect
35	self._request_authentication()
36	File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 861, in _request_authentication
37	auth_packet = self._read_packet()
38	File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
39	packet.check_error()
40	File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
41	err.raise_mysql_exception(self._data)
42	File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
43	raise errorclass(errno, errval)
44	pymysql.err.OperationalError: (1045, "Access denied for user 'oper'@'172.21.0.202' (using password: YES)") 此处是本地IP地址，我在环境变量中设置了远程IP

**Comment by tikazyq** [comment]
建议在docker中手动测试一下连接mysql
