### ISSUE TITLE
可以单独在另一台服务器开节点么？

### ISSUE THREAD

**Issue by xwg-github** [crawlab-team/crawlab#274]
我查看了example中开节点的docker-compose.yml以及readme.md，其中提到network字段。具体是如何定义呢？

**Comment by tikazyq** [comment]
召唤大佬来解答

**Comment by wo10378931** [comment]
docker-compose.yml中的network字段是用于定义启动的docker容器的网段，docker容器的网段是一个默认值，在某些情况下可能和主机上的路由冲突。所以可以通过该字段修改docker容器网段默认值。

**Comment by xwg-github** [comment]
![image](https://user-images.githubusercontent.com/50061664/67660891-ceb8ad00-f99a-11e9-96b2-638539ea1052.png)
之前有人问到类似的问题，在别的服务器要开节点，是要同样的开启主节点再开工作节点么？
