### ISSUE TITLE
Feature request: More advanced file management

### ISSUE THREAD

**Issue by haivp3010** [crawlab-team/crawlab#286]
Hey, I think it would be great if we can do more things with spider files, such as renaming, deleting, or download. Do you think this should be integrated into Crawlab or is it out of scope? I'd be happy to work on this if it's not out of scope.

**Comment by tikazyq** [comment]
We are still deciding whether to allow adding, editing or deleting spider files. This is because of concerns for versioning. We are absolutely happy that you can work on our new features. Would you mind adding my WeChat account to discuss further? WeChat ID: tikazyq1

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/releases/tag/v0.4.2
