### ISSUE TITLE
前端无法登录

### ISSUE THREAD

**Issue by gloomyzerg** [crawlab-team/crawlab#289]
![微信截图_20191031163630](https://user-images.githubusercontent.com/1195510/67931426-c2cc2580-fbfc-11e9-96eb-4950225c8e18.png)

自行安装和http://crawlab.cn/demo#/login  提供的demo 均有次问题

**Comment by zhaizhifen** [comment]
docker 安装的也是这样，怎么解决？

**Comment by zhaizhifen** [comment]
# windows下docker测试ok
```bash
docker run -d --name=redis505 -p 6379:6379 redis
docker run -d --name=mongodb4.2.1 -p 27017:27017 mongo:latest
# 查看 redis 和 mongodb的地址
docker inspect redis505
docker inspect mongodb4.2.1
docker pull tikazyq/crawlab
docker run -d --restart always --name crawlab-master -e CRAWLAB_REDIS_ADDRESS=172.17.0.2 -e CRAWLAB_MONGO_HOST=172.17.0.3 -e CRAWLAB_SERVER_MASTER=Y -p 8080:8080 -p 8000:8000 tikazyq/crawlab
```
浏览器访问http://127.0.0.1:8080
![图片](https://user-images.githubusercontent.com/14256359/68449512-5798d980-0222-11ea-854d-cd9420c17a08.png)

**Comment by CN-P5** [comment]
windows10+firefox测试好像有问题，官方demo提示：
![1](https://user-images.githubusercontent.com/6131031/68530518-9d998e80-0343-11ea-82e5-ad7ea4c3952b.png)
使用docker搭建时提示也是如此。

**Comment by CN-P5** [comment]
windows10+firefox测试好像有问题，官方demo提示：
![1](https://user-images.githubusercontent.com/6131031/68530549-df2a3980-0343-11ea-9e87-91e91d49ca82.png)

使用docker搭建时提示也是如此。

**Comment by CN-P5** [comment]
docker搭建前端登陆提示请检查用户名密码
firefox调试点击提交按钮数据发送地址出错类似于：http://宿主ip:8080/宿主ip:8000/login
![3](https://user-images.githubusercontent.com/6131031/68530702-e3efed00-0345-11ea-80ef-7a87eef827df.png)
我的宿主机IP：192.168.10.172 8080端口映射到9180 8000映射到9100

**Comment by CN-P5** [comment]
好像是VUE_APP_BASE_URL这个地址有问题，这个地址跟docker配置里的什么有关？

**Comment by tikazyq** [comment]
> 好像是VUE_APP_BASE_URL这个地址有问题，这个地址跟docker配置里的什么有关？

`CRAWLAB_API_ADDRESS`

**Comment by CN-P5** [comment]
> > 好像是VUE_APP_BASE_URL这个地址有问题，这个地址跟docker配置里的什么有关？
> 
> `CRAWLAB_API_ADDRESS`

CRAWLAB_API_ADDRESS 环境变量设置为http://192.168.10.172:9180，测试环境是群辉6.2出现上面问题。我在另一台机器（debian）上测试是没问题的。可能在群辉这种环境使用者并不多并且或许只有我出现这种情况，可以忽略不用检查调试这个错误。
