### ISSUE TITLE
使用另外一个容器的docker 中的redis服务时，worker服务起不来，查看容器日志

### ISSUE THREAD

**Issue by mr-chen-king** [crawlab-team/crawlab#293]
goroutine 1155 [running]:
runtime/debug.Stack(0xe4f660, 0xc000477de0, 0x40d9b8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
crawlab/database.(*Redis).HSet(0xc0001862f8, 0xcf8022, 0x5, 0xc0002aef60, 0x11, 0xc00030e0a0, 0x9f, 0x0, 0x0)
	/go/src/app/database/redis.go:50 +0x1eb
crawlab/services.UpdateNodeData()
	/go/src/app/services/node.go:180 +0x32a
crawlab/lib/cron.FuncJob.Run(0xd23e70)
	/go/src/app/lib/cron/cron.go:131 +0x25
crawlab/lib/cron.(*Cron).startJob.func1(0xc0001dbd60, 0xe31a20, 0xd23e70)
	/go/src/app/lib/cron/cron.go:307 +0x5f
created by crawlab/lib/cron.(*Cron).startJob
	/go/src/app/lib/cron/cron.go:305 +0x73
2019/11/02 10:26:05 error dial tcp: lookup redis on 127.0.0.11:53: no such host
try reconnect 15 times 
try reconnect 15 times 
dial tcp: lookup redis on 127.0.0.11:53: no such host
dial tcp: lookup redis on 127.0.0.11:53: no such host
goroutine 1168 [running]:
runtime/debug.Stack(0xe4f660, 0xc000475de0, 0x40d9b8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
crawlab/database.(*Redis).HSet(0xc0001862f8, 0xcf8022, 0x5, 0xc0003c9c40, 0x11, 0xc0001480a0, 0x9f, 0x0, 0x0)
	/go/src/app/database/redis.go:50 +0x1eb
crawlab/services.UpdateNodeData()
	/go/src/app/services/node.go:180 +0x32a
crawlab/lib/cron.FuncJob.Run(0xd23e70)
	/go/src/app/lib/cron/cron.go:131 +0x25
crawlab/lib/cron.(*Cron).startJob.func1(0xc0001dbd60, 0xe31a20, 0xd23e70)
	/go/src/app/lib/cron/cron.go:307 +0x5f
created by crawlab/lib/cron.(*Cron).startJob
	/go/src/app/lib/cron/cron.go:305 +0x73
2019/11/02 10:26:10 error dial tcp: lookup redis on 127.0.0.11:53: no such host
try reconnect 16 times 
try reconnect 16 times 
{subscribe nodes:public 1}
{subscribe nodes:5dbd5648b24f78001b2c3cf1 1}

> 我redis设置了登录秘密，这边的docker-compose 如何添加一个变量来传递这个登录密码？

**Comment by tikazyq** [comment]
请参考配置文档 https://tikazyq.github.io/crawlab-docs/Config/
