### ISSUE TITLE
“定时任务” 管理 增加 启用/禁用 功能

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#297]
#/schedules
如题

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/pull/355/commits/dccc90e45125ad6e796d266cf6384abe355d71ef

**Comment by tikazyq** [comment]
`run_type` has caused conflicts with this feature so it is re-opened

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/fafdccecf7f5a6d2b396421cacfef062d5ac1fed
