### ISSUE TITLE
使用docker-compose安装的，每过一个星期master就会挂掉？需要手动重启

### ISSUE THREAD

**Issue by yjiu1990** [crawlab-team/crawlab#303]
这一个是日志文件输出：
crawlab-master | 2019/11/10 06:00:00 error handle task error:open /var/logs/crawlab/5daef3fd05363c0015606068/20191110060000.log: no such file or directory
crawlab-master | 2019/11/10 06:00:00 error [Worker 3] open /var/logs/crawlab/5daef3fd05363c0015606068/20191110060000.log: no such file or directory
crawlab-master | fatal error: concurrent map writes
crawlab-master | fatal error: concurrent map writes
crawlab-master | 2019/11/11 12:03:39 error open /var/logs/crawlab/5daef3fd05363c0015606068/20191111021501.log: no such file or directory
crawlab-master | 2019/11/11 12:03:39 error open /var/logs/crawlab/5daef3fd05363c0015606068/20191111021501.log: no such file or directory

**Comment by tikazyq** [comment]
能提供多点信息么

**Comment by yjiu1990** [comment]
我全部给删了,每过七天就会出现这样的情况，重启master就正常了

**Comment by hantmac** [comment]
> 我全部给删了,每过七天就会出现这样的情况，重启master就正常了

你是不是把 `/var/logs/crawlab`文件夹给删了？

**Comment by yjiu1990** [comment]
没有删过，都是每个星期一上班的时候看到master就挂了

**Comment by hantmac** [comment]
> 没有删过，都是每个星期一上班的时候看到master就挂了

config.yml中的 `deleteFrequency`参数写的是什么？

**Comment by yjiu1990** [comment]
> > 没有删过，都是每个星期一上班的时候看到master就挂了
> 
> config.yml中的`deleteFrequency`参数写的是什么？
这一个配置文件在哪里看？

**Comment by hantmac** [comment]
> > > 没有删过，都是每个星期一上班的时候看到master就挂了
> > 
> > 
> > config.yml中的`deleteFrequency`参数写的是什么？
> > 这一个配置文件在哪里看？

conf/config.yaml

**Comment by yjiu1990** [comment]
> > > > 没有删过，都是每个星期一上班的时候看到master就挂了
> > > 
> > > 
> > > config.yml中的`deleteFrequency`参数写的是什么？
> > > 这一个配置文件在哪里看？
> 
> conf/config.yaml

写的是Y，我给改成N了，现在过了一个星期，没有出现那种情况了,但是这一处日志要怎么设置删除七天以前的日志？

**Comment by hantmac** [comment]
> > > > > 没有删过，都是每个星期一上班的时候看到master就挂了
> > > > 
> > > > 
> > > > config.yml中的`deleteFrequency`参数写的是什么？
> > > > 这一个配置文件在哪里看？
> > 
> > 
> > conf/config.yaml
> 
> 写的是Y，我给改成N了，现在过了一个星期，没有出现那种情况了,但是这一处日志要怎么设置删除七天以前的日志？

  ```
isDeletePeriodically: "Y"
  deleteFrequency: "0 5 * * * *"
```
修改 `deleteFrequency`，可以随意指定删除日志的频率，每周，每月，指定日期等，可以参考 https://cloudsjhan.github.io/2019/10/29/golang-cron%E4%BD%BF%E7%94%A8/#more
