### ISSUE TITLE
使用docker-compose重新搭建3.5的版本后，第一次能登陆进么，点击退出后无法进行登陆？

### ISSUE THREAD

**Issue by yjiu1990** [crawlab-team/crawlab#304]
![image](https://user-images.githubusercontent.com/41354304/68658257-15e49780-0570-11ea-95f4-d9d6d9a104ac.png)

**Comment by tikazyq** [comment]
看看后台是不是运行正常

**Comment by yjiu1990** [comment]
> 看看后台是不是运行正常

后台都是正常，我把版本降到3.4就没有任何问题了

**Comment by tikazyq** [comment]
现在是否还会出现原来的情况？
