### ISSUE TITLE
定时任务发生冲突导致crawlab被kill掉

### ISSUE THREAD

**Issue by H-B999** [crawlab-team/crawlab#306]
定时任务执行一段时间后发生冲突导致crawlab后台被kill掉
![微信截图_20191118115914](https://user-images.githubusercontent.com/50934900/69023766-f085dc80-09fa-11ea-90af-e467c494e15a.png)

**Comment by hantmac** [comment]
是最新版本的crawlab吗

**Comment by H-B999** [comment]
不是，是上一个版本的

**Comment by hantmac** [comment]
> 不是，是上一个版本的

我记得这个问题好像解决过了，你拉最新的版本试试

**Comment by H-B999** [comment]
好的，谢谢
