### ISSUE TITLE
使用官方的docker-compose.yml文件创建的实例，没办法登陆

### ISSUE THREAD

**Issue by wyfsxs** [crawlab-team/crawlab#307]
redis mongo 和服务都正常启动，页面能访问，但是无法登陆，登陆直接报错，也没办法创建用户

**Comment by tikazyq** [comment]
打开F12，看Network是否有报错？

**Comment by wyfsxs** [comment]
![QQ截图20191119213544](https://user-images.githubusercontent.com/37430434/69150886-8f522c00-0b14-11ea-8e8d-c29fbf947574.png)
点击提交直接报错

**Comment by wyfsxs** [comment]
![QQ截图20191119213641](https://user-images.githubusercontent.com/37430434/69150960-b3157200-0b14-11ea-9434-c6b2cbb3d8d1.png)
服务都是正常的，用的是github的上yaml

**Comment by tikazyq** [comment]
> ![QQ截图20191119213544](https://user-images.githubusercontent.com/37430434/69150886-8f522c00-0b14-11ea-8e8d-c29fbf947574.png)
> 点击提交直接报错

需要看看向后台请求的地址是否正确

**Comment by next-to-you** [comment]
我遇到了同样的问题，登录会显示登录出错（检查用户名密码），点击提交以后只请求了一个 /fonts/element-icons.535877f5.woff ，状态码200，没有其它请求，不知怎么解决
然后我看了下初次请求localhost:8080的时候，前端控制台会出现js加载错误，怎么解决？
`xhr.js:178XMLHttpRequest cannot load %3192.168.99.100:8000/nodes. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource`
`es6.promise.js:110Unhandled promise rejection TypeError: Cannot read property 'status' of undefined(…)`
图片上传抽风，就暂时粘贴代替，能解决吗？

**Comment by tikazyq** [comment]
> 我遇到了同样的问题，登录会显示登录出错（检查用户名密码），点击提交以后只请求了一个 /fonts/element-icons.535877f5.woff ，状态码200，没有其它请求，不知怎么解决
> 然后我看了下初次请求localhost:8080的时候，前端控制台会出现js加载错误，怎么解决？
> `xhr.js:178XMLHttpRequest cannot load %3192.168.99.100:8000/nodes. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource`
> `es6.promise.js:110Unhandled promise rejection TypeError: Cannot read property 'status' of undefined(…)`
> 图片上传抽风，就暂时粘贴代替，能解决吗？
> 
> 应该是初次加载的时候js未正确执行导致的

看起来应该是你没有设置好`CRAWLAB_API_ADDRESS`导致的，这个环境变量必须要加 `http://`
