### ISSUE TITLE
爬虫项目能实现工程化多实例化

### ISSUE THREAD

**Issue by lissh** [crawlab-team/crawlab#31]
希望可以实现，通过配置参数（环境变量传参数也可以的），对同一个爬虫工程，可以实现保存多个爬虫实例。 # # #

**Comment by tikazyq** [comment]
现在有定时任务传参的功能，但是直接跑是没有的，后续加上

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/50132334811d1a6c58422c346d2fb81806e12c25
