### ISSUE TITLE
登陆时出错，请坚持用户名和密码

### ISSUE THREAD

**Issue by xuchunlin168** [crawlab-team/crawlab#310]
使用docker安装部署的，但是一直保不能登陆，点击登陆的时候按钮一直转圈圈；

试了   绝大多数情况下，您可能是没有正确配置CRAWLAB_API_ADDRESS这个环境变量。这个变量是告诉前端应该通过哪个地址来请求API数据的，因此需要将它设置为宿主机的IP地址＋端口，例如 192.168.0.1:8000。接着，重启容器，在浏览器中输入宿主机IP＋端口，就可以顺利登陆了。
请注意，8080是前端端口，8000是后端端口，您在浏览器中只需要输入前端的地址就可以了，要注意区分

但是还没有成功，请问方便远程吗？

**Comment by tikazyq** [comment]
需要设置为 `http://192.168.0.1:8000`

**Comment by xuchunlin168** [comment]
是这样设置吗？


		
		docker run -d --restart always --name crawlab \
        -e CRAWLAB_REDIS_ADDRESS=192.168.99.1 \
        -e CRAWLAB_MONGO_HOST=192.168.99.1 \
        -e CRAWLAB_SERVER_MASTER=Y \
        -e CRAWLAB_API_ADDRESS=192.168.0.1:8000 \
        -p 8080:8080 \
        -p 8000:8000 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:0.3.0

**Comment by Action8686** [comment]
@xuchunlin168 你docker部署的问题解决了吗？

**Comment by xuchunlin168** [comment]
没有解决呢

**Comment by tikazyq** [comment]
加微信 tikazyq1 拉群在线问大佬
