### ISSUE TITLE
演示demo 挂掉了

### ISSUE THREAD

**Issue by xuchunlin168** [crawlab-team/crawlab#312]
![image](https://user-images.githubusercontent.com/20205072/69300466-3d152600-0c4e-11ea-9261-2453c677dc2b.png)

**Comment by tikazyq** [comment]
正常，经常有挖矿程序注入了把站点搞挂

**Comment by xuchunlin168** [comment]
能修复吗？需要服务器资源吗？我可以提供一台1核2g的服务器
