### ISSUE TITLE
长时间工作后两个节点都会进入离线状态, 并偶发丢失任务

### ISSUE THREAD

**Issue by myuanz** [crawlab-team/crawlab#314]
使用docker部署, 最近一个月状况已经发生多次, 间隔1~5天必然发生.
日志显示redis i/o timeout, 竟能多达七八千次.

```text
2019/11/22 11:04:40 error dial tcp 172.18.0.3:6379: i/o timeout
2019/11/22 11:04:40 error dial tcp 172.18.0.3:6379: i/o timeout
dial tcp 172.18.0.3:6379: i/o timeout
dial tcp 172.18.0.3:6379: i/o timeout
goroutine 4820354 [running]:
runtime/debug.Stack(0xe4f660, 0xc0002d9de0, 0x40d9b8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
crawlab/database.(*Redis).HSet(0xc000440038, 0xcf8022, 0x5, 0xc00071a900, 0x11, 0xc0004b0000, 0x9e, 0x0, 0x0)
	/go/src/app/database/redis.go:50 +0x1eb
crawlab/services.UpdateNodeData()
	/go/src/app/services/node.go:180 +0x32a
crawlab/lib/cron.FuncJob.Run(0xd23e70)
	/go/src/app/lib/cron/cron.go:131 +0x25
crawlab/lib/cron.(*Cron).startJob.func1(0xc000402140, 0xe31a20, 0xd23e70)
	/go/src/app/lib/cron/cron.go:307 +0x5f
created by crawlab/lib/cron.(*Cron).startJob
	/go/src/app/lib/cron/cron.go:305 +0x73
2019/11/22 11:04:45 error dial tcp 172.18.0.3:6379: i/o timeout
try reconnect 7219 times 
try reconnect 7219 times 

```
两个节点的日志都是这样的重复.
我尝试过进入容器查看redis状态, 结果是可连接的.
由于不太熟悉docker和redis, 无法做出更多推断.

**Comment by hantmac** [comment]
Redis确实容易出现一些性能问题，再观察一下吧

**Comment by hantmac** [comment]
> Redis确实容易出现一些性能问题，再观察一下吧

https://www.cnblogs.com/CtripDBA/p/9776466.html

**Comment by hantmac** [comment]
> 使用docker部署, 最近一个月状况已经发生多次, 间隔1~5天必然发生.
> 日志显示redis i/o timeout, 竟能多达七八千次.
> 
> ```
> 2019/11/22 11:04:40 error dial tcp 172.18.0.3:6379: i/o timeout
> 2019/11/22 11:04:40 error dial tcp 172.18.0.3:6379: i/o timeout
> dial tcp 172.18.0.3:6379: i/o timeout
> dial tcp 172.18.0.3:6379: i/o timeout
> goroutine 4820354 [running]:
> runtime/debug.Stack(0xe4f660, 0xc0002d9de0, 0x40d9b8)
> 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
> runtime/debug.PrintStack()
> 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
> crawlab/database.(*Redis).HSet(0xc000440038, 0xcf8022, 0x5, 0xc00071a900, 0x11, 0xc0004b0000, 0x9e, 0x0, 0x0)
> 	/go/src/app/database/redis.go:50 +0x1eb
> crawlab/services.UpdateNodeData()
> 	/go/src/app/services/node.go:180 +0x32a
> crawlab/lib/cron.FuncJob.Run(0xd23e70)
> 	/go/src/app/lib/cron/cron.go:131 +0x25
> crawlab/lib/cron.(*Cron).startJob.func1(0xc000402140, 0xe31a20, 0xd23e70)
> 	/go/src/app/lib/cron/cron.go:307 +0x5f
> created by crawlab/lib/cron.(*Cron).startJob
> 	/go/src/app/lib/cron/cron.go:305 +0x73
> 2019/11/22 11:04:45 error dial tcp 172.18.0.3:6379: i/o timeout
> try reconnect 7219 times 
> try reconnect 7219 times 
> ```
> 
> 两个节点的日志都是这样的重复.
> 我尝试过进入容器查看redis状态, 结果是可连接的.
> 由于不太熟悉docker和redis, 无法做出更多推断.

有Redis的监控吗，有的话提供下监控数据

**Comment by myuanz** [comment]
> > 使用docker部署, 最近一个月状况已经发生多次, 间隔1~5天必然发生.
> > 日志显示redis i/o timeout, 竟能多达七八千次.
> > ```
> > 2019/11/22 11:04:40 error dial tcp 172.18.0.3:6379: i/o timeout
> > 2019/11/22 11:04:40 error dial tcp 172.18.0.3:6379: i/o timeout
> > dial tcp 172.18.0.3:6379: i/o timeout
> > dial tcp 172.18.0.3:6379: i/o timeout
> > goroutine 4820354 [running]:
> > runtime/debug.Stack(0xe4f660, 0xc0002d9de0, 0x40d9b8)
> > 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
> > runtime/debug.PrintStack()
> > 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
> > crawlab/database.(*Redis).HSet(0xc000440038, 0xcf8022, 0x5, 0xc00071a900, 0x11, 0xc0004b0000, 0x9e, 0x0, 0x0)
> > 	/go/src/app/database/redis.go:50 +0x1eb
> > crawlab/services.UpdateNodeData()
> > 	/go/src/app/services/node.go:180 +0x32a
> > crawlab/lib/cron.FuncJob.Run(0xd23e70)
> > 	/go/src/app/lib/cron/cron.go:131 +0x25
> > crawlab/lib/cron.(*Cron).startJob.func1(0xc000402140, 0xe31a20, 0xd23e70)
> > 	/go/src/app/lib/cron/cron.go:307 +0x5f
> > created by crawlab/lib/cron.(*Cron).startJob
> > 	/go/src/app/lib/cron/cron.go:305 +0x73
> > 2019/11/22 11:04:45 error dial tcp 172.18.0.3:6379: i/o timeout
> > try reconnect 7219 times 
> > try reconnect 7219 times 
> > ```
> > 
> > 
> > 两个节点的日志都是这样的重复.
> > 我尝试过进入容器查看redis状态, 结果是可连接的.
> > 由于不太熟悉docker和redis, 无法做出更多推断.
> 
> 有Redis的监控吗，有的话提供下监控数据

没有redis的监控, 我在尝试改改代码, 连错多次的时候重启

**Comment by tikazyq** [comment]
无法复现
