### ISSUE TITLE
【优化建议】新增项目菜单，在项目多爬虫的情况下能够复用项目

### ISSUE THREAD

**Issue by ZanXusV** [crawlab-team/crawlab#316]
【Issue】：当前crawlab在管理爬虫时不是很方便，如果一个项目里爬虫很多，想每个爬虫都单独保存，不用每次运行都通过传参方式启动不同爬虫的话就得挨个上传同一个项目到容器中不同的爬虫目录下，目前crawlab平台项目和爬虫的概念没有区分好，是把每一个项目看做一个爬虫来处理的，像scrapyd打包完一个egg上传之后，会自动识别文件里的多个爬虫。

【Suggestion】：新增一个项目的菜单，打包后的项目的zip包传到项目菜单那里，然后新建爬虫的时候可以从当前已有的项目列表中直接选则项目，这样同一个项目就无需多次上传了。

**Comment by tikazyq** [comment]
https://github.com/crawlab-team/crawlab/commit/9d5d0253a87b8e1483a3cfffc75f7c5e21115a41
