### ISSUE TITLE
优化建议 docker镜像

### ISSUE THREAD

**Issue by Tang-1** [crawlab-team/crawlab#317]
在crawlab上面镜像里面配置个人环境发现几个小问题  建议下次更新镜像优化下
1.路径显示只显示 #  建议当前路径显示出来
2.时间默认为UTC  建议设置为CST
3.backspace 功能会打印^H  建议设置为正常的回删
4.中文显示为???

**Comment by tikazyq** [comment]
> 在crawlab上面镜像里面配置个人环境发现几个小问题 建议下次更新镜像优化下
> 1.路径显示只显示 # 建议当前路径显示出来
> 2.时间默认为UTC 建议设置为CST
> 3.backspace 功能会打印^H 建议设置为正常的回删
> 4.中文显示为???

1. 你是指前端的URL么，那个是hash url，专门这么设计的，防止刷新的时候丢失页面
2. 这个应该可以设置的，可以启动docker的时候配置环境变量，你可以搜索一下
3. 请提供更多具体内容
4. 中文也可以支持，请查看issues中的解决方法

**Comment by Tang-1** [comment]
几个问题均为docker镜像内的问题，路径指docker镜像里面命令窗口路径，目前几处问题都已经设置ok了。
下次crawlab的镜像更新希望可以默认

这是第3个问题的打印截图
![image](https://user-images.githubusercontent.com/43632943/69524150-644a5b00-0fa0-11ea-9dda-7c90cc73dcc2.png)

**Comment by tikazyq** [comment]
你是用什么编辑器？
