### ISSUE TITLE
优化建议  文件权限

### ISSUE THREAD

**Issue by Tang-1** [crawlab-team/crawlab#318]
在scrapy settings中LOG_ENABLED = True并设置LOG_FILE路径  打印日志运行会出错 几次尝试后应该是打印log时的文件权限问题！ 
建议上传时设置下默认权限

**Comment by tikazyq** [comment]
确实可能存在这样的问题，能上传截图和日志么

**Comment by Tang-1** [comment]
在设置路径  “./xxx/xxx.log”时
![image](https://user-images.githubusercontent.com/43632943/69525715-aa54ee00-0fa3-11ea-9098-027aa345f4a7.png)
![image](https://user-images.githubusercontent.com/43632943/69526024-4d0d6c80-0fa4-11ea-9a80-9cf30fb208f3.png)
![image](https://user-images.githubusercontent.com/43632943/69526299-d7ee6700-0fa4-11ea-945e-04fab56c477a.png)


设置路径为  “./xxx.log”时
![image](https://user-images.githubusercontent.com/43632943/69526094-62829680-0fa4-11ea-9d7c-c443315afaf4.png)
![image](https://user-images.githubusercontent.com/43632943/69526024-4d0d6c80-0fa4-11ea-9a80-9cf30fb208f3.png)
![image](https://user-images.githubusercontent.com/43632943/69526111-6e6e5880-0fa4-11ea-923a-dac915dcb961.png)

当关闭LOG_ENABLED 和 LOG_FILE 时代码运行正常

**Comment by tikazyq** [comment]
先暂时不要启用LOG_ENABLED和LOG_FILE，我们调查一下原因

**Comment by hantmac** [comment]
> 在设置路径 “./xxx/xxx.log”时
> ![image](https://user-images.githubusercontent.com/43632943/69525715-aa54ee00-0fa3-11ea-9098-027aa345f4a7.png)
> ![image](https://user-images.githubusercontent.com/43632943/69526024-4d0d6c80-0fa4-11ea-9a80-9cf30fb208f3.png)
> ![image](https://user-images.githubusercontent.com/43632943/69526299-d7ee6700-0fa4-11ea-945e-04fab56c477a.png)
> 
> 当关闭LOG_ENABLED 和 LOG_FILE 时代码运行正常

问题找到了，你是不是根本没有提前创建log文件夹呀？

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/pull/322

**Comment by Tang-1** [comment]
运行之前文件夹是已经存在的

**Comment by hantmac** [comment]
> 运行之前文件夹是已经存在的

尝试把log文件夹移到上一层目录里

**Comment by hantmac** [comment]
> 运行之前文件夹是已经存在的

尝试把log文件夹移到上一层目录里

**Comment by Tang-1** [comment]
ok
