### ISSUE TITLE
主节点迁移但数据库及ip还是上一个服务器信息

### ISSUE THREAD

**Issue by Tang-1** [crawlab-team/crawlab#319]
使用crawlab镜像添加个人配置后将镜像打包，迁移至第二台服务器，但第二台机器启动后节点和数据信息任然是第一台服务器上面的数据。
![image](https://user-images.githubusercontent.com/43632943/69630826-41937180-1088-11ea-859e-c1f8c9e2124e.png)
![image](https://user-images.githubusercontent.com/43632943/69630841-43f5cb80-1088-11ea-8fe6-5e421df24cc8.png)

已确认在启动时更改过以下几个环境变量
![image](https://user-images.githubusercontent.com/43632943/69630911-57a13200-1088-11ea-8cb4-c0eddef07054.png)

已在第二台服务器中以执行/app/docker_init.sh文件
第二台服务器依赖第一台服务器的数据库  （将第一个服务器关闭后第二台启动会失败）

**Comment by tikazyq** [comment]
现在是否还会出现原来的情况？

**Comment by Tang-1** [comment]
已升到0.4.1&nbsp; 还未测试这个问题是否解决&nbsp; &nbsp;
我测试后向你发送邮件！

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Marvin Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 中午12:33
收件人:&nbsp;"crawlab-team/crawlab"<crawlab@noreply.github.com&gt;;
抄送:&nbsp;"."<2300309546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crawlab-team/crawlab] 主节点迁移但数据库及ip还是上一个服务器信息 (#319)




现在是否还会出现原来的情况？
