### ISSUE TITLE
服务器IP更换后，节点登录请求地址不变，仍是上一个

### ISSUE THREAD

**Issue by xwg-github** [crawlab-team/crawlab#323]
![image](https://user-images.githubusercontent.com/50061664/69771056-5b3ad300-11c6-11ea-9f1d-6ce2f7a5c701.png)

**Comment by xwg-github** [comment]
能否在不新建容器的情况下，更改api_address?

**Comment by tikazyq** [comment]
现在是否还会出现原来的情况？
