### ISSUE TITLE
关闭正在运行的爬虫  爬虫还是在后台运行

### ISSUE THREAD

**Issue by Tang-1** [crawlab-team/crawlab#325]
关闭正在运行的爬虫  爬虫还是在后台运行

**Comment by Abraham-liuhai** [comment]
> 关闭正在运行的爬虫爬虫还是在后台运行

这个问题解决了吗 我也遇到了

**Comment by tikazyq** [comment]
是哪个版本

**Comment by Abraham-liuhai** [comment]
我忘记了 前一个月装的


| |
abraham_liuhai
|
|
邮箱：abraham_liuhai@163.com
|

Signature is customized by Netease Mail Master

在2019年12月03日 18:01，Marvin Zhang 写道：

是哪个版本

**Comment by tikazyq** [comment]
请用最新镜像试试看

**Comment by Tang-1** [comment]
新镜像已解决这个问题，感谢你们的付出






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Marvin Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 中午12:33
收件人:&nbsp;"crawlab-team/crawlab"<crawlab@noreply.github.com&gt;;
抄送:&nbsp;"."<2300309546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crawlab-team/crawlab] 关闭正在运行的爬虫  爬虫还是在后台运行 (#325)




请用最新镜像试试看
