### ISSUE TITLE
爬虫跑着跑着就卡主了，面板上爬虫归属的节点那个位置就变成空了

### ISSUE THREAD

**Issue by sunnnnz** [crawlab-team/crawlab#334]
172.31.16.104 | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 12:34:34
-- | -- | -- | -- | --
  | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 12:34:26
172.31.16.102 | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 12:34:22
172.31.16.102 | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 00:10:53
172.31.16.105 | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 00:10:50
172.31.16.103 | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 00:10:48
172.31.16.103 | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 00:10:46
172.31.16.103 | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 00:10:43
  | tmall_spider_v03 | 0 | 进行中 | 2019-12-03 00:10:31

**Comment by sunnnnz** [comment]
并且在这个情况下进入，单独的爬虫里面去停止，停不下来，然后我去终端里Kill进程 随便杀了一个 ，爬虫就动了，当时遇到的是这个情况

**Comment by wo10378931** [comment]
因为节点定时上报自身信息导致重复节点，然后删除节点重建导致的。
Fix By #355
