### ISSUE TITLE
【优化建议】区分结果数据库和配置数据库

### ISSUE THREAD

**Issue by BottleMan** [crawlab-team/crawlab#338]
【Issue】
目前 Crawlab 只使用一个 MongoDB，同时用来保存爬虫信息、运行结果。

【Suggestion】
增加配置项，可以区别配置「运行库」和「结果库」。

**Comment by hantmac** [comment]
> 【Issue】
> 目前 Crawlab 只使用一个 MongoDB，同时用来保存爬虫信息、运行结果。
> 
> 【Suggestion】
> 增加配置项，可以区别配置「运行库」和「结果库」。

你可以只把mongodb作为配置库；然后在爬虫代码里另起数据库去存储结果。
