### ISSUE TITLE
【优化建议】建议为每个节点增加网页命令行

### ISSUE THREAD

**Issue by jueshiyizhimao** [crawlab-team/crawlab#342]

**Comment by hantmac** [comment]
具体描述下需求。
每个节点增加命令行是什么意思呢？

**Comment by jueshiyizhimao** [comment]
可通过网页端进入docker容器的命令行，为了确认真实情况，以及完成部署无法可能完成的操作。

**Comment by hantmac** [comment]
> 可通过网页端进入docker容器的命令行，为了确认真实情况，以及完成部署无法可能完成的操作。
类似于web terminal?

**Comment by jueshiyizhimao** [comment]
@hantmac 是这个想法
