### ISSUE TITLE
【优化建议】希望在爬虫模块中增加一栏运行中的任务数

### ISSUE THREAD

**Issue by jueshiyizhimao** [crawlab-team/crawlab#348]
希望在爬虫模块中增加一栏运行中的任务数。
建议增加一个爬虫“状态”，或者更改“最后运行状态”。
只要爬虫有一个任务运行中，就认为此爬虫正常运行。这样能体现爬虫的真实状态
![image](https://user-images.githubusercontent.com/26734950/70217056-8059b380-177b-11ea-89f4-d47922b04b8b.png)

**Comment by wo10378931** [comment]
这个不是已经有了吗？ 在爬虫列表有一列是最后状态，取的就是最后一个任务的运行状态

**Comment by tikazyq** [comment]
fixed
