### ISSUE TITLE
管理页面定时任务没有展示

### ISSUE THREAD

**Issue by zhengrenfeng** [crawlab-team/crawlab#353]
db中的定时任务中有数据，但是管理页面缺没有展示
![image](https://user-images.githubusercontent.com/9197074/70376603-71bef800-1945-11ea-8203-7d047409e004.png)

**Comment by tikazyq** [comment]
看看后台接口请求如何

**Comment by jk50505k** [comment]
相同情况 数据库有定时任务记录，前端不显示，检查前端请求的接口没有数据，当定时任务自动运行过后 ，会重新出现在前端

**Comment by wo10378931** [comment]
Fib By #355
