### ISSUE TITLE
db中的任务记录被清空

### ISSUE THREAD

**Issue by zhengrenfeng** [crawlab-team/crawlab#354]
同个爬虫，先通过手动方式启动运行（任务A），再换个参数用定时任务的方式启动（任务B），此时页面显示两条任务。一段时间后B任务正常结束后，上web页面发现无任务数据，进db中的发现任务记录为空（任务A和任务B都不存在）。此时任务A还在后台正确运行，日志正常。
ps：任务A比较大，已经采集20W条数据

**Comment by tikazyq** [comment]
哪个版本

**Comment by jk50505k** [comment]
上个版本和当前v4版本，都有此情况，隔一段时间后，任务会自动清空。我是源码直接编译启动的 前端node启动 后端go直接启动

**Comment by tikazyq** [comment]
可以看看日志和配置文件不

**Comment by tikazyq** [comment]
无法复现
