### ISSUE TITLE
【优化建议】 "爬虫" > "爬虫详情" 页面，增加 "定时任务" 选项卡

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#360]
/#/spiders/xxxxxxxxxxxxxx
如题：
增加 "定时任务" 选项卡，方便查看及管理当前爬虫的定时任务

**Comment by tikazyq** [comment]
added in https://github.com/crawlab-team/crawlab/commit/7835de2641a9fd58c16ca9114bb6553c22649ad4
