### ISSUE TITLE
【优化建议】Crawlab版本号集中维护

### ISSUE THREAD

**Issue by duanbin0414** [crawlab-team/crawlab#371]
目前用到的版本号：左上交logo处、用户登录信息处，均为页面写死，不利于发版管理，一致性维护，建议版本号由配置文件中统一指定。

**Comment by hantmac** [comment]
后端写一个接口读配置文件感觉可以吧？发版的时候更新下配置文件就可以

**Comment by tikazyq** [comment]
> 后端写一个接口读配置文件感觉可以吧？发版的时候更新下配置文件就可以

这个idea很棒

**Comment by hantmac** [comment]
> > 后端写一个接口读配置文件感觉可以吧？发版的时候更新下配置文件就可以
> 
> 这个idea很棒

https://github.com/crawlab-team/crawlab/pull/382

简单的接口有了，前端交给你了。
以后就直接修改 ./backend/conf/config.yaml的version字段就行。
