### ISSUE TITLE
前端日志获取超时，重新编译之后可以看到，过一段时间就消失了

### ISSUE THREAD

**Issue by Abraham-liuhai** [crawlab-team/crawlab#372]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tikazyq** [comment]
有日志么

**Comment by Abraham-liuhai** [comment]
> 有日志没

**Comment by Abraham-liuhai** [comment]
> 有日志么

没有啊

**Comment by Abraham-liuhai** [comment]
> 有日志么

没有啊  get remote log timeout
