### ISSUE TITLE
希望自定义爬虫文档给个简单的demo实例

### ISSUE THREAD

**Issue by Voccoo** [crawlab-team/crawlab#379]
自定义爬虫运行没有demo示例，使用该功能太心酸了。
期望大佬能在近期的使用文档说明上，在自定义爬虫的内容中增加一个简单的demo示例，更方便新人对自定义爬虫的使用，减少使用困难。

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/5740774ccc7b3d5557c4e9af5b0a933016a0c272 and https://github.com/crawlab-team/crawlab/commit/cb6a8f79d898579ed6b09e77cd7192323d268b84
