### ISSUE TITLE
Cron expression confusing

### ISSUE THREAD

**Issue by Neutrino3316** [crawlab-team/crawlab#383]
**Describe the bug**
I'm confused when using cron expression to scheduled tasks.

**To Reproduce**
1. Create a scheduled task with cron expressions `46 * * * * *`

**Expected behavior**
This task should execute when the minute reaches 46 (e.g. 21:46:00 22:46:00 23:46:00)

**Actual behavior**
This task is executed when the second reaches 46 (e.g. 23:00:46 23:01:46 23:02:46)

**Screenshots**
![image](https://user-images.githubusercontent.com/20875523/71188265-9e66fe00-22bb-11ea-9cfb-87f65eac39d7.png)

**Version**
 - crawlab v0.4.1
 - tikazyq/crawlab image version: c7e7311cd15b

**Why this is confusing**
No hint is provided when I input the corn expression. Also, [the guidelines](https://tikazyq.github.io/crawlab-docs/Usage/Schedule/) have a link to [a blog](https://www.cnblogs.com/longjshz/p/5779215.html), which shows how to use crontab expressions. 
![image](https://user-images.githubusercontent.com/20875523/71189537-f0a91e80-22bd-11ea-9cc1-caafd320e051.png)
In most cases(or the default), the first element is minute, like the blog says, or [some online editor](https://crontab.guru/) says. However, according to these illustrations, the first element of the cron expression should be minute.

**How to improve**
The best solution is to bring back the feature once crawlab has. In the crawlab's README, there still has a screenshot of a wonderful user interface, which I cann't find it in version 0.4.1
![image](https://raw.githubusercontent.com/tikazyq/crawlab-docs/master/images/schedule.png)
If this feature can't bring back soon, I humbly suggest that we should have a hotfix, which can pop out hint when inputting the cron expression. What's more, updating the documentation is a good habit. Every new user have to read these guidelines. They may feel frustrate when these documentations lead they to a wrong way.

**Comment by tikazyq** [comment]
Hi @Neutrino3316, 

Thanks for the feedback. I totally agree with you that the visualization of the cron expression is very useful when creating a scheduled job. However, right now we have removed it because of its instability and bugs occasionally occur. This is because we were using a 3rd-party library for the visualization. We will add it back once we figure it out.

Marvin

**Comment by Neutrino3316** [comment]
@tikazyq , thanks for your reply. If the visualization can't bring back soon, adding an illustration is a good idea. Because in most cases, the first element stands for minutes, user should be informed that in our case, the first one stands for seconds.

**Comment by tikazyq** [comment]
> @tikazyq , thanks for your reply. If the visualization can't bring back soon, adding an illustration is a good idea. Because in most cases, the first element stands for minutes, user should be informed that in our case, the first one stands for seconds.

Indeed, will do in the next release

**Comment by tikazyq** [comment]
fixed in fafdccecf7f5a6d2b396421cacfef062d5ac1fed

**Comment by tikazyq** [comment]
Added a placeholder indicating the correct format of the cron expression and aligned it with Linux
