### ISSUE TITLE
支持 JSON 接口的爬取

### ISSUE THREAD

**Issue by cielpy** [crawlab-team/crawlab#385]
**Is your feature request related to a problem? Please describe.**

字段只支持 CSS selector 或者 XPath，如果接口返回 JSON，就没有办法获取某个字段了

**Describe the solution you'd like**

可以支持 JSONPath 方法拿字段的值 https://github.com/json-path/JsonPath

**Describe alternatives you've considered**

集成 JSONPath 库，前端实现配置选项

**Additional context**

**Comment by dengtongcai** [comment]
支持

**Comment by chenarmy** [comment]
希望能支持
