### ISSUE TITLE
toscrapy_books 爬虫选择所有节点运行，任务运行了两遍

### ISSUE THREAD

**Issue by cielpy** [crawlab-team/crawlab#388]
**Describe the bug**

**To Reproduce**

toscrapy_books 爬虫选择所有节点运行，任务运行了两遍
![image](https://user-images.githubusercontent.com/3138493/71252373-c445de80-235f-11ea-917e-34a2fb0e077f.png)

**Expected behavior**
只爬一遍

**Comment by tikazyq** [comment]
**所有节点** 意味着将在所有在线节点每个运行一次爬虫任务，所以是两遍

**Comment by cielpy** [comment]
是设计如此吗，这个设计想适用于什么场景解决什么问题呢，我觉得应该是爬一遍，速度减半比较合理

**Comment by tikazyq** [comment]
这么设计是为了解决分布式爬虫的运行问题，分布式爬虫通常需要同时在多台机器上跑任务

**Comment by cielpy** [comment]
分布式爬虫通常需要在多台机器上跑不同的任务，这样设计跑的任务是相同的，不是分布式吧

**Comment by tikazyq** [comment]
通常是从种子url队列里获取，然后抓取数据，说白了需要在多个节点同时运行来增大网络带宽

**Comment by cielpy** [comment]
如果是不同节点执行不同任务的话，可以达到增大网络带宽的目的
拿 toscrapy_books 模板来说，种子 URL 只有一个，可以根据种子 URL 爬到 1000 个详情的 URL，这 1000 个 URL 分到两个节点爬，这样带宽翻倍，效率翻倍
而现在生成的代码是两个节点都以种子 URL 开始，把 1000 个详情都爬了一遍，这样效率并没有提升

**Comment by tikazyq** [comment]
你说的对，可配置爬虫还可以再进一步优化，请关注后续开发，现在先close

**Comment by cielpy** [comment]
有 roadmap 吗，我有兴趣搞点东西

**Comment by tikazyq** [comment]
可配置爬虫、定时任务等等，roadmap暂时没有公开
