### ISSUE TITLE
【bug】出现重复主节点

### ISSUE THREAD

**Issue by jk50505k** [crawlab-team/crawlab#391]
![109051576998920_ pic_hd](https://user-images.githubusercontent.com/38711478/71321573-13257c80-24f6-11ea-9336-ed7689397ddc.jpg)

**Comment by jk50505k** [comment]
版本0.4.1  发现在mongodb重启后会出现新增节点

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/893476bd0b92132115073be0b59db1ef59ded26c

**Comment by tikazyq** [comment]
also fixed in https://github.com/crawlab-team/crawlab/pull/400

**Comment by tikazyq** [comment]
继续观察下
