### ISSUE TITLE
上传了个node的爬虫 ,然后node  no find

### ISSUE THREAD

**Issue by 1014470807** [crawlab-team/crawlab#396]
上传了个node的爬虫 ,然后node  no find

**Comment by tikazyq** [comment]
可以提供一下后台报错日志么

**Comment by 1014470807** [comment]
> 可以提供一下后台报错日志么

b1e20ce00176f0b9a/tasks
master    | [GIN] 2019/12/25 - 05:02:56 | 204 |       17.07?s |   113.72.146.54 | OPTIONS  /tasks
master    | [GIN] 2019/12/25 - 05:02:56 | 200 |    1.576472ms |   113.72.146.54 | PUT      /tasks
master    | 2019/12/25 05:02:57  info [Worker 0] 开始执行任务(ID:02df0e5d-feac-4423-bdb7-758dbebf8a4c)
master    | 2019/12/25 05:02:57  info cwd: /app/spiders/node-crawler-jianshu-master
master    | 2019/12/25 05:02:57  info cmd: node crawler-jianshu.js
master    | 2019/12/25 05:02:57 error wait process finish error: exit status 127
master    | goroutine 1598 [running]:
master    | runtime/debug.Stack(0x0, 0x0, 0x0)
master    | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
master    | runtime/debug.PrintStack()
master    | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
master    | crawlab/services.WaitTaskProcess(0xc0004c6580, 0xc0000936e0, 0x24, 0xc00047dae0, 0xc, 0xbf78d940404d816a, 0x21058375fa, 0x13db000, 0x0, 0x0, ...)
master    | 	/go/src/app/services/task.go:185 +0x142
master    | crawlab/services.ExecuteShellCmd(0xc0004edca0, 0x17, 0xc0002afce0, 0x28, 0xc0000936e0, 0x24, 0xc00047dae0, 0xc, 0xbf78d940404d816a, 0x21058375fa, ...)
master    | 	/go/src/app/services/task.go:262 +0xad8
master    | crawlab/services.ExecuteTask(0x0)
master    | 	/go/src/app/services/task.go:452 +0xf03
master    | crawlab/services.GetExecuteTaskFunc.func1()
master    | 	/go/src/app/services/task.go:301 +0x2a
master    | crawlab/lib/cron.FuncJob.Run(0xc000187470)
master    | 	/go/src/app/lib/cron/cron.go:131 +0x25
master    | crawlab/lib/cron.(*Cron).startJob.func1(0xc00018e5a0, 0xe49300, 0xc000187470)
master    | 	/go/src/app/lib/cron/cron.go:307 +0x5f
master    | created by crawlab/lib/cron.(*Cron).startJob
master    | 	/go/src/app/lib/cron/cron.go:305 +0x73
master    | 2019/12/25 05:02:57 error exit error, exit code: 127
master    | 2019/12/25 05:02:57 error [Worker 0] exit status 127
master    | [GIN] 2019/12/25 - 05:02:58 | 204 |       13.55?s |   113.72.146.54 | OPTIONS  /spiders/5e022bab1e20ce00176f0b9a/tasks
master    | [GIN] 2019/12/25 - 05:02:58 | 200 |    2.205568ms |   113.72.146.54 | GET      /spiders/5e022bab1e20ce00176f0b9a/tasks

**Comment by 1014470807** [comment]
> 可以提供一下后台报错日志么

- [ ] 

1. 

- 

> 

> 可以提供一下后台报错日志么

sh: 1: node: not found

**Comment by 1014470807** [comment]
> 可以提供一下后台报错日志么

执行命令 node crawler-jianshu.js

**Comment by tikazyq** [comment]
请用绝对路径

**Comment by 1014470807** [comment]
> 请用绝对路径

不对啊兄弟 node: not found  是找不到node这个东西 但是我linux是配置了

**Comment by 1014470807** [comment]
> 请用绝对路径

是node -v 在那个爬虫平台运行也不行  说找不到node  但是运行python-V就可以

**Comment by tikazyq** [comment]
这个。。。需要你安装一下node的环境

**Comment by 1014470807** [comment]
> 这个。。。需要你安装一下node的环境

不是啊兄弟 我这个linux 已经是有node的环境了 我是用docker-compose up运行你的程序了,而且我还发觉一个问题 我在你那个平台那里运行python 然后和我在linux xshell 那运行的版本居然是不一致的，你那个平台是已经自带了python3.6的了,在那个后台里面运行的语言环境读取不了外界的环境的,这个是怎么回事呢？你那个平台是自带语言环境的吧,我已经在linux安装了node,结果在你的后台里面运行命令的时候说找不到node

**Comment by tikazyq** [comment]
可能你需要补充一下docker的知识，docker是一个容器，里面的环境和宿主机的环境是不一样的，需要在docker容器里自行安装各种环境

**Comment by 1014470807** [comment]
> 可能你需要补充一下docker的知识，docker是一个容器，里面的环境和宿主机的环境是不一样的，需要在docker容器里自行安装各种环境
这个我也在 docker里面也安装了node  就是找不到 不知道为什么

**Comment by tikazyq** [comment]
> > 可能你需要补充一下docker的知识，docker是一个容器，里面的环境和宿主机的环境是不一样的，需要在docker容器里自行安装各种环境
> > 这个我也在 docker里面也安装了node  就是找不到 不知道为什么

如果安装的？

**Comment by 1014470807** [comment]
> > > 可能你需要补充一下docker的知识，docker是一个容器，里面的环境和宿主机的环境是不一样的，需要在docker容器里自行安装各种环境
> > > 这个我也在 docker里面也安装了node  就是找不到 不知道为什么
> 
> 如果安装的？

version: '3.3'
services:
  master:
    image: tikazyq/crawlab:latest
    container_name: master
    environment:
      CRAWLAB_API_ADDRESS: "http://106.54.53.151:8000"
      CRAWLAB_SERVER_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_REDIS_ADDRESS: "redis"
    ports:
      - "8080:8080" # frontend
      - "8000:8000" # backend
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  node:
    image: node:latest
    container_name: node
    hostname: node
    ports:
      - "7001:7001"
docker-compose up运行 成功跑起来程序 然后运行脚本说找不到node
 然后就去菜鸟教程 在安装了一次docker node  还是说找不到

**Comment by tikazyq** [comment]
```bash
# 进入容器
docker exec -it master bash

# 安装node
```

**Comment by 1014470807** [comment]
> ```shell
> # 进入容器
> docker exec -it master bash
> 
> # 安装node
> ```

我用这个docker run -itd --name node-test node 就能运行  
这个进入容器
docker exec -it master bash
就运行不了node了 怎么回事嘛

**Comment by 1014470807** [comment]
> ```shell
> # 进入容器
> docker exec -it master bash
> 
> # 安装node
> ```
问题我在你那个后台运行docker 的命令 他都说docker是找不到的  sh: 1: docker: not found
？？？

**Comment by tikazyq** [comment]
加微信拉群讨论 tikazyq1
