### ISSUE TITLE
爬虫的文档管理，建议修改为：左树型目录，右编辑框的形式。避免爬虫文档管理过多切换。

### ISSUE THREAD

**Issue by expressways** [crawlab-team/crawlab#398]
![图片](https://user-images.githubusercontent.com/52902289/71453172-e65ab900-27c4-11ea-96f5-0b9ebfdd96cd.png)

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/ef2a4b35318953b759c6ffbf957e09b819634383
