### ISSUE TITLE
添加节点不成功

### ISSUE THREAD

**Issue by ksiailaohuyou** [crawlab-team/crawlab#401]
**Describe the bug**
添加work节点不成功，redis只有master的数据，mongo只有一个主节点的信息(master可以正常访问UI界面)，worker节点信息打印如下，一直停留于此，但是测试上传一个zip包。worker节点又有信息输出

**To Reproduce**
1.使用命令添加master 
```
docker run -d --restart always --name crawlab_master \
        -e CRAWLAB_REDIS_ADDRESS=10.2.7.61 \
        -e CRAWLAB_MONGO_HOST=10.2.7.61 \
        -e CRAWLAB_SERVER_MASTER=Y \
        -e CRAWLAB_API_ADDRESS=http://10.2.7.61:8000 \
        -p 8001:8080 \
        -p 8000:8000 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:latest
```
2. 使用命令添加worker

```
docker run  --name crawlab_worker04 \
        -e CRAWLAB_REDIS_ADDRESS=10.2.7.61 \
        -e CRAWLAB_MONGO_HOST=10.2.7.61 \
        -e CRAWLAB_SERVER_MASTER=N \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:latest
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35055524/71466930-11acca80-27fc-11ea-9a9a-95b4db3fa9d6.png)

![image](https://user-images.githubusercontent.com/35055524/71467995-7f0e2a80-27ff-11ea-9656-2fbc978fa4dd.png)

![image](https://user-images.githubusercontent.com/35055524/71467690-9dbff180-27fe-11ea-808e-9d82a7aa0a69.png)

![image](https://user-images.githubusercontent.com/35055524/71467170-f0001300-27fc-11ea-9705-d23b3c7e4e5b.png)

![image](https://user-images.githubusercontent.com/35055524/71468997-cf3abc00-2802-11ea-95d0-3394931a2695.png)

**Comment by tikazyq** [comment]
是一个机器上部署的还是多台机器？

**Comment by ksiailaohuyou** [comment]
> 是一个机器上部署的还是多台机器？

一台windows运行VMware跑三个节点， 桥连接网络，每个节点都有固定的局域网ip

**Comment by tikazyq** [comment]
用`CRAWLAB_SERVER_REGISTER_TYPE`，设置为ip，`CRAWLAB_SERVER_REGISTER_IP `设置为节点ip

**Comment by tikazyq** [comment]
参考 http://docs.crawlab.cn/Config/

**Comment by ksiailaohuyou** [comment]
> 参考 http://docs.crawlab.cn/Config/

感谢🙏 已成功配置
```
docker run -d --restart always --name crawlab_worker \
        -e CRAWLAB_REDIS_ADDRESS=10.2.7.61 \
        -e CRAWLAB_MONGO_HOST=10.2.7.61 \
        -e CRAWLAB_SERVER_MASTER=N \
        -e CRAWLAB_SERVER_REGISTER_TYPE =ip \
        -e CRAWLAB_SERVER_REGISTER_IP=10.2.6.62 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:latest
```

**Comment by jackcily** [comment]
> > 参考 http://docs.crawlab.cn/Config/
> 
> 感谢🙏 已成功配置
> 
> ```
> docker run -d --restart always --name crawlab_worker \
>         -e CRAWLAB_REDIS_ADDRESS=10.2.7.61 \
>         -e CRAWLAB_MONGO_HOST=10.2.7.61 \
>         -e CRAWLAB_SERVER_MASTER=N \
>         -e CRAWLAB_SERVER_REGISTER_TYPE =ip \
>         -e CRAWLAB_SERVER_REGISTER_IP=10.2.6.62 \
>         -v /var/logs/crawlab:/var/logs/crawlab \
>         tikazyq/crawlab:latest
> ```

docker 指令有误，多了个空格，正确指令如下：
```bash

docker run -d --restart always --name crawlab_worker \
        -e CRAWLAB_REDIS_ADDRESS=10.2.7.61 \
        -e CRAWLAB_MONGO_HOST=10.2.7.61 \
        -e CRAWLAB_SERVER_MASTER=N \
        -e CRAWLAB_SERVER_REGISTER_TYPE=ip \
        -e CRAWLAB_SERVER_REGISTER_IP=10.2.6.62 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:latest
```
