### ISSUE TITLE
crawlab爬虫程序找不到node环境

### ISSUE THREAD

**Issue by H-B999** [crawlab-team/crawlab#402]
Ubuntu已有node环境，直接在spider目录下运行爬虫文件，可以找到node环境，直接在crawlab上运行爬虫程序的的话找不到node环境，好像crawlab环境变量都没使用，我是直接部署的，这个爬虫程序是scrapy爬虫，使用execjs库调度js代码，返回cookie的一个流程

**Comment by navyren** [comment]
> Ubuntu已有node环境，直接在spider目录下运行爬虫文件，可以找到node环境，直接在crawlab上运行爬虫程序的的话找不到node环境，好像crawlab环境变量都没使用，我是直接部署的，这个爬虫程序是scrapy爬虫，使用execjs库调度js代码，返回cookie的一个流程

最新crawlab已经修复环境变量不好使的问题了，cmd.Env = append(os.Environ(), "CRAWLAB_TASK_ID="+taskId)；老版本可以手动添加爬虫环境变量PATH，不过最好升级到新版本 @tikazyq @H-B999
