### ISSUE TITLE
重启服务之前上传的文件报错

### ISSUE THREAD

**Issue by duanbin0414** [crawlab-team/crawlab#404]
重启服务，文件列表中存在，亦能打开查看信息，但有报错。

![image](https://user-images.githubusercontent.com/50389867/71507029-0fab4000-28be-11ea-86c2-989d75c827f7.png)

develop branch.

**Comment by tikazyq** [comment]
这似乎是因为没有即时获取文件导致的，在 https://github.com/crawlab-team/crawlab/commit/cb33e8860fe3106f4ad95074c2d9f8fef94d4a2a 中已经尝试解决
