### ISSUE TITLE
爬虫详情->上传文件无效

### ISSUE THREAD

**Issue by duanbin0414** [crawlab-team/crawlab#406]
通过爬虫详情中的文件上传按钮上传文件，功能无效，且无任何反馈。

![image](https://user-images.githubusercontent.com/50389867/71510778-fc52a180-28ca-11ea-8210-7729f75ffcc5.png)

develop branch

**Comment by hnljq** [comment]
你这不是最新版本吧，是041吗

**Comment by tikazyq** [comment]
本地似乎可以了
