### ISSUE TITLE
【bug】修改爬虫文件后保存，显示找不到文件

### ISSUE THREAD

**Issue by jk50505k** [crawlab-team/crawlab#419]
0.4.2版本,修改爬虫文件后，保存文件，再保存爬虫信息，然后运行爬虫，显示找不到文件出错。
服务器本地存在爬虫文件和md5文件
![120461577974112_ pic_hd](https://user-images.githubusercontent.com/38711478/71671753-d0de2400-2dae-11ea-815a-369c381c1bda.jpg)

**Comment by tikazyq** [comment]
暂时解决办法，删除爬虫，重新上传

**Comment by tikazyq** [comment]
可能是上传文件到GridFS的时候失败导致的
