### ISSUE TITLE
【BUG】机器重启后节点，爬虫数据全部消失，退出登录后无法再次登录

### ISSUE THREAD

**Issue by player-Ling** [crawlab-team/crawlab#421]
机器重启后crawlab中内容全部消失
![image](https://user-images.githubusercontent.com/26917052/71761021-d8addd80-2f00-11ea-8b29-5d9386691f92.png)

**Comment by tikazyq** [comment]
down了么

**Comment by player-Ling** [comment]
![image](https://user-images.githubusercontent.com/26917052/71789181-3c9ce700-3064-11ea-9370-ea5f27aa232c.png)
好像是参数顺序问题，把这两个反过来就好了
