### ISSUE TITLE
【优化建议】爬虫状态展示与监控

### ISSUE THREAD

**Issue by jueshiyizhimao** [crawlab-team/crawlab#425]
需要一目了然的看到那些爬虫在运行，哪些爬虫挂了（而不是上次运行的状态），如果在运行，展示有几个正常任务数。

监控进程状态。比如10分钟查询一次爬虫的进程状态，如果有任务异常退出或者爬虫异常退出，就通过钉钉机器人通知。这一步要可以设定通知等级。

爬虫状态栏，展示爬虫任务分布的节点，可能同一个爬虫在有些节点挂了，有些却没有。

**Comment by tikazyq** [comment]
这是长任务需求，我们目前都针对的是短任务需求，心跳检测确实也有必要，防止爬虫意外挂掉

**Comment by tikazyq** [comment]
已经完成钉钉机器人消息通知功能，对于长任务功能，还有待开发。

https://github.com/crawlab-team/crawlab/commit/32bfb63d8f248d14de96198c2a347531e67a1270

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/e3883faf1c3b55b7909153d7d21e3032147fe911 and https://github.com/crawlab-team/crawlab/commit/010f3ec1faa456b2d6fefa8bf6604d54d3d296e2
