### ISSUE TITLE
上传文件报错问题

### ISSUE THREAD

**Issue by duanbin0414** [crawlab-team/crawlab#427]
version 0.4.3
当默认爬虫路径没有操作权限时会出现的问题：

1.上传文件后，前端可以看到添加的爬虫信息。
2.但报错，显示文件不存在。
![image](https://user-images.githubusercontent.com/50389867/71821190-6c7fd500-30cc-11ea-9772-9977eef0e5f2.png)
3.轮询获取不到任务也会持续报出 not find.
![image](https://user-images.githubusercontent.com/50389867/71821275-a81a9f00-30cc-11ea-8d9d-323dcedc4136.png)

优化建议：
前端添加爬虫操作与后端上传文件处理，应该处于同一个事物中，当后端默认路径不可用，前端不应该展示出创建出爬虫信息。并明确返回出具体错误原因，比如：创建爬虫文件夹失败，请使用CRAWLAB_SPIDER_PATH=/Users/duanbin/Downloads/data/。指定可用爬虫路径。

**Comment by wo10378931** [comment]
爬虫文件的同步是异步同步的。master上传到db中，各个节点自行从db把爬虫文件同步到本地。
可以考虑这么处理：节点在启动的时候在爬虫目录下写入一个文件，如果写入失败，则节点启动失败，需要用户修改爬虫目录的权限
