### ISSUE TITLE
【bug】爬虫不执行

### ISSUE THREAD

**Issue by duanbin0414** [crawlab-team/crawlab#429]
version 0.4.3

存在的问题：
1.点击爬虫按钮，派发了一个爬虫任务，但未执行。
2.点击状态栏，待定按钮。后端请求 /nodes/000000000000000000000000 500。

![image](https://user-images.githubusercontent.com/50389867/71822884-fb8eec00-30d0-11ea-9ee1-82ec829c9aa3.png)

![image](https://user-images.githubusercontent.com/50389867/71822621-43f9da00-30d0-11ea-9ffd-fc7c08f749ee.png)

**Comment by tikazyq** [comment]
很可能是脏数据导致的，清除数据后再执行一下
