### ISSUE TITLE
scrapy项目中的多爬虫识别

### ISSUE THREAD

**Issue by Tang-1** [crawlab-team/crawlab#435]
![image](https://user-images.githubusercontent.com/43632943/71875859-5b80a380-3160-11ea-98ff-bed6562f6738.png)
公司前辈写的爬虫  类似设计使用 crawlab上传爬虫比较繁琐
建议加入多爬虫识别功能

**Comment by tikazyq** [comment]
会加入更多scrapy的支持




| |
张冶青 Yeqing Zhang
邮箱：tikazyq@163.com
|

签名由 网易邮箱大师 定制

在2020年01月07日 15:16，Tang 写道：


公司前辈写的爬虫 类似设计使用 crawlab上传爬虫比较繁琐
建议加入多爬虫识别功能

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/25b4c7d272fa06e8013a8d87ff2a7c675994ce6b
