### ISSUE TITLE
希望添加IP代理池及管理功能

### ISSUE THREAD

**Issue by tom2jack** [crawlab-team/crawlab#439]
希望添加IP代理池及管理功能，比如在左边菜单导航栏添加IP代理池及管理功能，配合crawlab的各爬虫任务使用。

**Comment by HaoKunT** [comment]
同样希望能增加IP代理池的管理功能，或者与已有的一些开源代理池管理工具集成，例如[ProxyPool](https://github.com/jhao104/proxy_pool) @tikazyq
