### ISSUE TITLE
【BUG】Page refresh bug. 

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#441]
**Describe the bug**
Task interface updated too quickly, less than 2 seconds. 
It causes checkbox target lost. 
Please remove the auto-refresh feature for specific page. 

**To Reproduce**
Null. 

**Expected behavior**
Nil.

**Screenshots**
None.

**Desktop:**
 - Device: [any]
 - OS: [any]
 - Browser [any]
 - Version [v0.4.3]

**Additional context**
Zero.

**Comment by tikazyq** [comment]
It is not necessary to disable the auto-update. We can fix it.
