### ISSUE TITLE
节点_id随机时间会自动变更

### ISSUE THREAD

**Issue by 126217832** [crawlab-team/crawlab#450]
节点的_id随机时间会自动变更，导致历史任务节点全部消失，定时执行的任务显示待定不能执行任务，目前解决方案是写一个脚本先查询当前可用节点，再依次替换定时任务和任务的节点id信息

**Comment by tikazyq** [comment]
有不有详细的后台日志

**Comment by 126217832** [comment]
抱歉，没有收集这类错误，我所看到的日志错误信息仅仅是当点击历史任务后出现节点信息没有找到

**Comment by tikazyq** [comment]
先观察一下，如果下次再出现同样的情况，请用 `docker logs <container_name>` 来查看错误日志

**Comment by 126217832** [comment]
![image](https://user-images.githubusercontent.com/40737253/72398098-c9d6ee80-377c-11ea-897a-57e5377d3440.png)
以上图片是节点信息丢失后报错

**Comment by tikazyq** [comment]
节点丢失是出现为离线，然后新节点出现么？

**Comment by tikazyq** [comment]
是哪个版本？

请拉取最新镜像再试一下

**Comment by 126217832** [comment]
1，没有观察到节点是否离线，但可以确定放在mongo中的节点_id变了即可以认为是新节点出现了，从而导致定时任务和历史任务中绑定的节点id还是旧的，从定时任务启动的任务显示待定，历史任务报。
2，mongo,redis一直运行正常。
3，还是三个月之前的版本
4，我之前用的python后台2.x版本没有出现过这样的问题

**Comment by tikazyq** [comment]
请升级到最新的0.4.3版本，用 `docker pull tikazyq/crawlab:latest` 来拉取

**Comment by 126217832** [comment]
好的，先试试，后期有问题再反馈
