### ISSUE TITLE
【优化建议】希望在可配置爬虫时，增加浏览器滑动选择对应字段的提取功能，用于简化配置流程

### ISSUE THREAD

**Issue by lanren0451** [crawlab-team/crawlab#453]
希望对于列表页和详情页能提供通过浏览器滑动选择，来进行字段提取的配置，简化通过人工总结xpath或css的方式进行字段提取

**Comment by tikazyq** [comment]
翻页功能么？

**Comment by lanren0451** [comment]
是简化筛选目标字段的功能，目前都是要人工输入xpath，是否可以通过浏览器渲染之后 通过滑动鼠标的方式选择需要采集的目标属性

**Comment by tikazyq** [comment]
> 是简化筛选目标字段的功能，目前都是要人工输入xpath，是否可以通过浏览器渲染之后 通过滑动鼠标的方式选择需要采集的目标属性

界面操作暂时还没有，底层是scrapy，暂时不支持click、select等事件，等后续开发以puppeteer为底层引擎的可配置爬虫
