### ISSUE TITLE
后端无法部署

### ISSUE THREAD

**Issue by goofts** [crawlab-team/crawlab#454]
~/crawlab/backend# go install ./...
main.go:12:2: cannot find package "github.com/apex/log" in any of:
        /usr/lib/go-1.10/src/github.com/apex/log (from $GOROOT)
        /root/go/src/github.com/apex/log (from $GOPATH)
main.go:13:2: cannot find package "github.com/gin-gonic/gin" in any of:
        /usr/lib/go-1.10/src/github.com/gin-gonic/gin (from $GOROOT)
        /root/go/src/github.com/gin-gonic/gin (from $GOPATH)
main.go:14:2: cannot find package "github.com/gin-gonic/gin/binding" in any of:
        /usr/lib/go-1.10/src/github.com/gin-gonic/gin/binding (from $GOROOT)
        /root/go/src/github.com/gin-gonic/gin/binding (from $GOPATH)
main.go:15:2: cannot find package "github.com/spf13/viper" in any of:
        /usr/lib/go-1.10/src/github.com/spf13/viper (from $GOROOT)
        /root/go/src/github.com/spf13/viper (from $GOPATH)
config/config.go:4:2: cannot find package "github.com/fsnotify/fsnotify" in any of:
        /usr/lib/go-1.10/src/github.com/fsnotify/fsnotify (from $GOROOT)
        /root/go/src/github.com/fsnotify/fsnotify (from $GOPATH)
database/mongo.go:4:2: cannot find package "github.com/globalsign/mgo" in any of:
        /usr/lib/go-1.10/src/github.com/globalsign/mgo (from $GOROOT)
        /root/go/src/github.com/globalsign/mgo (from $GOPATH)
database/pubsub.go:8:2: cannot find package "github.com/gomodule/redigo/redis" in any of:
        /usr/lib/go-1.10/src/github.com/gomodule/redigo/redis (from $GOROOT)
        /root/go/src/github.com/gomodule/redigo/redis (from $GOPATH)
database/pubsub.go:9:2: cannot find package "github.com/pkg/errors" in any of:
        /usr/lib/go-1.10/src/github.com/pkg/errors (from $GOROOT)
        /root/go/src/github.com/pkg/errors (from $GOPATH)
lib/validate_bridge/validator.go:8:2: cannot find package "gopkg.in/go-playground/validator.v9" in any of:
        /usr/lib/go-1.10/src/gopkg.in/go-playground/validator.v9 (from $GOROOT)
        /root/go/src/gopkg.in/go-playground/validator.v9 (from $GOPATH)
mock/node.go:9:2: cannot find package "github.com/globalsign/mgo/bson" in any of:
        /usr/lib/go-1.10/src/github.com/globalsign/mgo/bson (from $GOROOT)
        /root/go/src/github.com/globalsign/mgo/bson (from $GOPATH)
mock/task.go:12:2: cannot find package "github.com/satori/go.uuid" in any of:
        /usr/lib/go-1.10/src/github.com/satori/go.uuid (from $GOROOT)
        /root/go/src/github.com/satori/go.uuid (from $GOPATH)
model/spider.go:12:2: cannot find package "gopkg.in/yaml.v2" in any of:
        /usr/lib/go-1.10/src/gopkg.in/yaml.v2 (from $GOROOT)
        /root/go/src/gopkg.in/yaml.v2 (from $GOPATH)
services/user.go:8:2: cannot find package "github.com/dgrijalva/jwt-go" in any of:
        /usr/lib/go-1.10/src/github.com/dgrijalva/jwt-go (from $GOROOT)
        /root/go/src/github.com/dgrijalva/jwt-go (from $GOPATH)

**Comment by tikazyq** [comment]
是不是被墙了，试试设置`GOPROXY=https://goproxy.cn`

**Comment by goofts** [comment]
Go的包路径错误

**Comment by tikazyq** [comment]
解决了吗

**Comment by zzk1314** [comment]
我也遇到了一样的问题，请问这个是怎么解决啊？
`root@ecs-422f:/data/deploy/crawlab/backend# go install ./...
main.go:5:2: cannot find package "crawlab/config" in any of:
	/usr/lib/go-1.10/src/crawlab/config (from $GOROOT)
	/root/go/src/crawlab/config (from $GOPATH)
main.go:6:2: cannot find package "crawlab/database" in any of:
	/usr/lib/go-1.10/src/crawlab/database (from $GOROOT)
	/root/go/src/crawlab/database (from $GOPATH)
main.go:7:2: cannot find package "crawlab/lib/validate_bridge" in any of:
	/usr/lib/go-1.10/src/crawlab/lib/validate_bridge (from $GOROOT)
	/root/go/src/crawlab/lib/validate_bridge (from $GOPATH)
main.go:8:2: cannot find package "crawlab/middlewares" in any of:
	/usr/lib/go-1.10/src/crawlab/middlewares (from $GOROOT)
	/root/go/src/crawlab/middlewares (from $GOPATH)
main.go:9:2: cannot find package "crawlab/model" in any of:
	/usr/lib/go-1.10/src/crawlab/model (from $GOROOT)
`
