### ISSUE TITLE
Restart the cralwer when it crashed immediately

### ISSUE THREAD

**Issue by kingname** [crawlab-team/crawlab#455]
**Is your feature request related to a problem? Please describe.**

Yes, I'd like my crawler restart when it crashed, no matter what the reason is.My Crawler is deployed at an aws machine out of china, it will retrive url from redis which is deployed in the mainland of china. sometimes my crawler will crash because of the network. in this case, I just want to restart my crawler.

**Describe the solution you'd like**

 I want to restart my crawler, just like the `--restart unless-stopped` in `docker run` command.

**Describe alternatives you've considered**

check the crawler every 5min, if it is crashed, restart a new job.

**Comment by tikazyq** [comment]
Thanks for Dalao's feedback!
