### ISSUE TITLE
删除超级用户后。。。

### ISSUE THREAD

**Issue by bestgopher** [crawlab-team/crawlab#456]
我把超级用户删除了，然后自己的普通用户无法创建新用户了。。。。
我只能在数据库修改，把普通用户的权限normal修改为admin。
是否加个验证机制，必须存在一个超级用户。避免没有超级用户的尴尬

**Comment by tikazyq** [comment]
为何要删超级用户😅




| |
张冶青 Yeqing Zhang
邮箱：tikazyq@163.com
|

签名由 网易邮箱大师 定制

在2020年01月16日 18:14，yangzai 写道：

我把超级用户删除了，然后自己的普通用户无法创建新用户了。。。。
我只能在数据库修改，把普通用户的权限normal修改为admin。
是否加个验证机制，必须存在一个超级用户。避免没有超级用户的尴尬

**Comment by bestgopher** [comment]
> 为何要删超级用户 | | 张冶青 Yeqing Zhang 邮箱：tikazyq@163.com | 签名由 网易邮箱大师 定制 在2020年01月16日 18:14，yangzai 写道： 我把超级用户删除了，然后自己的普通用户无法创建新用户了。。。。 我只能在数据库修改，把普通用户的权限normal修改为admin。 是否加个验证机制，必须存在一个超级用户。避免没有超级用户的尴尬 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

误删了

**Comment by tikazyq** [comment]
重启docker会自动加入admin账号，后面会加保护
