### ISSUE TITLE
【bug】关于定时任务设置的bug

### ISSUE THREAD

**Issue by jk50505k** [crawlab-team/crawlab#461]
1.定时任务的天的设置里具体天数的按钮不能点，底下从到的空里只能填1到12。手动写天的时候会自动改为* 
<img width="525" alt="WeChat86c418748206146ae8b36b1d4c873051" src="https://user-images.githubusercontent.com/38711478/72660903-281b0000-3a0f-11ea-9b2b-ccf9090949fa.png">
2.周的填写里出现重复两行
<img width="540" alt="WeChat7db05ceb357bd9eea2e383b609db45d7" src="https://user-images.githubusercontent.com/38711478/72661049-f7d46100-3a10-11ea-8886-c3053407ff8c.png">

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/pull/464/commits/47a9db024a26400cc2859866fac254ee9c6d5edf
