### ISSUE TITLE
主节点无法发布任务给非同一台服务器的工作节点，状态为待定

### ISSUE THREAD

**Issue by wxing0611** [crawlab-team/crawlab#470]
主节点无法发布任务给非同一台服务器的工作节点，前端显示状态未待定，查看日志，显示open : no such file or directory；
但进入对应服务器的docker查看代码已经同步过去，而且手动调度是可以正常跑起来的。

**Comment by tikazyq** [comment]
待我们优化好爬虫同步逻辑，这个问题应该就可以自然解决了

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/81edf9ab7240db5dee03a78ab47765f991951111

**Comment by tikazyq** [comment]
请观察一下
