### ISSUE TITLE
后端部署问题

### ISSUE THREAD

**Issue by Abraham-liuhai** [crawlab-team/crawlab#481]
各项成功编译后，启动crawlab却发现启动不了
nohup crawlab &
启动不成功

crawlab
crawlab/services.(*Scheduler).Start(0xc0001840b0, 0xc0001840b0, 0x1)
        /root/crawlab-master/backend/services/schedule.go:94 +0x14e
crawlab/services.InitScheduler(0xc00009a400, 0xdcee76)
        /root/crawlab-master/backend/services/schedule.go:227 +0xa3
main.main()
        /root/crawlab-master/backend/main.go:72 +0x35ba
2020/01/22 15:11:03 error start scheduler error: ObjectIDs must be exactly 12 bytes long (got 0)
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
crawlab/services.InitScheduler(0xc00009a400, 0xdcee76)
        /root/crawlab-master/backend/services/schedule.go:229 +0x167
main.main()
        /root/crawlab-master/backend/main.go:72 +0x35ba
2020/01/22 15:11:03 error init scheduler error:ObjectIDs must be exactly 12 bytes long (got 0)
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
main.main()
        /root/crawlab-master/backend/main.go:74 +0x364e
panic: ObjectIDs must be exactly 12 bytes long (got 0)

goroutine 1 [running]:
main.main()
        /root/crawlab-master/backend/main.go:75 +0x37fd

**Comment by tikazyq** [comment]
请参考 http://docs.crawlab.cn/QA/

**Comment by xingdavis** [comment]
最后是怎么解决呢？文档找不到答案呢
