### ISSUE TITLE
引入 save_item() 出错

### ISSUE THREAD

**Issue by malphitee** [crawlab-team/crawlab#482]
pip安装crawlab后，在代码中引入

from crawlab import save_item

时报错，找不到这个方法，我到源码里看也没找着，请问这个方法现在是可用的吗

**Comment by tikazyq** [comment]
报错发一下

**Comment by malphitee** [comment]
`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from crawlab import save_item
ImportError: cannot import name 'save_item' from 'crawlab' (/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/crawlab/__init__.py)`

**Comment by malphitee** [comment]
我看了下应该是安装成功了，我可以尝试着调  crawlab.Crawler.fetch()  之类的方法，说明这个库应该是装上了，但是进代码里没看到这个save_item方法是在哪定义的,全局搜索也找不到(在我本地开发的时候是用的venv，服务器上是直接全局装的库)

**Comment by malphitee** [comment]
抱歉，是我自己的问题，看文档不够仔细 

下面介绍 Scrapy 和一般 Python 爬虫与 Crawlab 集成的方式。

⚠️注意：请确保您已经通过 pip 安装了 crawlab-sdk。

这里有这么一段话，我就只看了github首页的那个文档
