### ISSUE TITLE
可配置爬虫转化为Scrapy自定义爬虫

### ISSUE THREAD

**Issue by libra146** [crawlab-team/crawlab#514]
**请描述该需求尝试解决的问题**
例如我需要将数据直接导入自己的数据库中，通过自定义 pipelines.py 文件的方式。
或者分页功能不能正确处理下一页的 URL，需要自定义URL处理函数。
因为目前我发现，每次点击保存都会将 scrapy 重新渲染，导致自定义配置丢失。（这里不知道理解的对不对）

**请描述您认为可行的解决方案**
添加一个在线模板修改功能。

**考虑过的替代方案**
目前没有替代方案。

**Comment by tikazyq** [comment]
可配置爬虫么

**Comment by libra146** [comment]
> 可配置爬虫么

仍然是scrapy，但是需要自定义一些东西。
或者说可不可以将可配置爬虫配置好，运行成功之后通过按钮手动转成自定义爬虫，然后在线修改一些配置。

**Comment by tikazyq** [comment]
> > 可配置爬虫么
> 
> 仍然是scrapy，但是需要自定义一些东西。
> 或者说可不可以将可配置爬虫配置好，运行成功之后通过按钮手动转成自定义爬虫，然后在线修改一些配置。

确实是一个比较好的解决方案，我们会在后续迭代中考虑的

**Comment by libra146** [comment]
> > > 可配置爬虫么
> > 
> > 
> > 仍然是scrapy，但是需要自定义一些东西。
> > 或者说可不可以将可配置爬虫配置好，运行成功之后通过按钮手动转成自定义爬虫，然后在线修改一些配置。
> 
> 确实是一个比较好的解决方案，我们会在后续迭代中考虑的

感谢。
