### ISSUE TITLE
宿主和docker容器时间一致，但是定时任务执行却相差8个小时。

### ISSUE THREAD

**Issue by Da-wukong** [crawlab-team/crawlab#546]
**Bug 描述**
宿主和docker容器时间一致，但是定时任务执行却相差8个小时。

**复现步骤**
该 Bug 复现步骤如下
1. 宿主/etc/localtime 设置为上海时区，docker 容器 /etc/localtime 也设置为上海时区，平台定时任务执行设置为0点执行，实际却是8点执行。
2. 容器的时间设置后crawlab执行爬虫任务未生效。
3. 重启容器不能解决。

**期望结果**
crawlab执行定时爬虫任务时间一致。

**截屏**
- cron表达式时间
![cron表达式时间](https://user-images.githubusercontent.com/29535531/74300331-6bf0f300-4d8a-11ea-86cc-060196bff951.png)
- 任务执行时间
![任务执行时间](https://user-images.githubusercontent.com/29535531/74300321-61cef480-4d8a-11ea-8f64-c519de57d1c3.png)

**Comment by tikazyq** [comment]
试试在传入环境变量的时候加入 `TZ=Asia/Shanghai`
