### ISSUE TITLE
只在Worker节点单独安装NPM包时,Worker节点搜索NPM包前端页面会返回500错误

### ISSUE THREAD

**Issue by Flonimc** [crawlab-team/crawlab#559]
**Bug 描述**
当只在一个worker上单独安装npm,而master上没装，前端在worker节点上搜索npm包的时候就会返回500错误如下:
{"status":"ok","message":"unauthorized","data":null,"error":"unauthorized"}
**复现步骤**
该 Bug 复现步骤如下
1. 只在worker节点下安装NPM
2. 在Woker节点下搜索NPM包
3. F12打开控制台,返回错误

**Comment by tikazyq** [comment]
原因跟 https://github.com/crawlab-team/crawlab/issues/560 是一样的
