### ISSUE TITLE
Add TODOs Badge

### ISSUE THREAD

**Issue by patrickdevivo** [crawlab-team/crawlab#562]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/crawlab-team/crawlab)](https://www.tickgit.com/browse?repo=github.com/crawlab-team/crawlab)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/crawlab-team/crawlab)](https://www.tickgit.com/browse?repo=github.com/crawlab-team/crawlab)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by tikazyq** [comment]
There is no need to add this badge in our README. Thanks
