### ISSUE TITLE
docker build构建image报错

### ISSUE THREAD

**Issue by JohnieXu** [crawlab-team/crawlab#563]
**Bug 描述**
运行`docker build` 命令时报node-gyp的错误，试过很多次

**复现步骤**
该 Bug 复现步骤如下
1. 执行`docker build -f ./Dockerfile -t tikazyq/crawlab:latest .`

**期望结果**
正常build生成image 能工作。

**截屏**
![截屏1](https://tva1.sinaimg.cn/large/0082zybply1gbzqsqw2ajj322r0u04ek.jpg)

**Comment by tikazyq** [comment]
`docker build -f ./Dockerfile.local -t tikazyq/crawlab:latest` 试试

**Comment by JohnieXu** [comment]
用`Dokcerfile.local`构建image成功了

**Comment by Zoupers** [comment]
我也遇到了一样的问题，，我将Dockerfile里面将该行改为
```
RUN npm install -g yarn \
    && yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass \
    && yarn install
```
然后就可以了，所以还是网的问题...
