### ISSUE TITLE
后台chan map报错

### ISSUE THREAD

**Issue by gyc0218** [crawlab-team/crawlab#565]
backend->utils->chan.go
1. go里面的map不支持并发，需要加锁；

**Comment by tikazyq** [comment]
什么时候会出现这个错误

**Comment by gyc0218** [comment]
没有特定的时间点。我有2个爬虫，A和B，这2个爬虫执行比较慢，每次执行大概需要60秒。A设置了3个定时任务，每分钟执行一次，B也是每分钟执行一次。程序在运行大概24小时左右，就会崩溃报错，提示的错误是map出现了并发。

**Comment by tikazyq** [comment]
可能哪里出现了data race，我们检查一下




| |
张冶青 Yeqing Zhang
邮箱：tikazyq@163.com
|

签名由 网易邮箱大师 定制

在2020年02月18日 15:46，hitman 写道：

没有特定的时间点。我有2个爬虫，A和B，这2个爬虫执行比较慢，每次执行大概需要60秒。A设置了3个定时任务，每分钟执行一次，B也是每分钟执行一次。程序在运行大概24小时左右，就会崩溃报错，提示的错误是map出现了并发。

**Comment by hantmac** [comment]
> 没有特定的时间点。我有2个爬虫，A和B，这2个爬虫执行比较慢，每次执行大概需要60秒。A设置了3个定时任务，每分钟执行一次，B也是每分钟执行一次。程序在运行大概24小时左右，就会崩溃报错，提示的错误是map出现了并发。

应该是同一个任务的TaskId相同，导致同时运行的时候map的key冲突了，在解决ing

**Comment by hantmac** [comment]
> 没有特定的时间点。我有2个爬虫，A和B，这2个爬虫执行比较慢，每次执行大概需要60秒。A设置了3个定时任务，每分钟执行一次，B也是每分钟执行一次。程序在运行大概24小时左右，就会崩溃报错，提示的错误是map出现了并发。

能否重复下你的操作，然后把报错日志发我们一下呀，这边不太好复现

**Comment by tikazyq** [comment]
duplicated in https://github.com/crawlab-team/crawlab/issues/515
