### ISSUE TITLE
Windows上直接部署爬虫的时区有问题

### ISSUE THREAD

**Issue by gyc0218** [crawlab-team/crawlab#566]
python爬虫执行的时候，环境变量的注入有问题，时区不正确，取出来的是UTC时间。添加TZ=“Asia/Shanghai”的环境变量也不起作用。

**Comment by tikazyq** [comment]
配置文件是怎样的？

**Comment by gyc0218** [comment]
api:
  address: "localhost:8000"
web:
  staticpath: "./dist"
mongo:
  host: localhost
  port: 27017
  db: crawlab_test
  username: ""
  password: ""
  authSource: "admin"
redis:
  address: localhost
  password: ""
  database: 1
  port: 6379
log:
  level: info
  path: "E:\\proj\\crawlab\\cmd\\crawlab\\logs\\crawlab"
  isDeletePeriodically: "N"
  deleteFrequency: "@hourly"
server:
  host: 0.0.0.0
  port: 8000
  master: "Y"
  secret: "crawlab"
  register:
    # mac地址 或者 ip地址，如果是ip，则需要手动指定IP
    type: "mac"
    ip: ""
  lang: # 安装语言环境, Y 为安装，N 为不安装，只对 Docker 有效
    python: "Y"
    node: "N"
spider:
  path: "E:\\proj\\crawlab\\cmd\\crawlab\\spiders"
task:
  workers: 4
other:
  tmppath: "E:\\proj\\crawlab\\cmd\\crawlab\\tmp"
version: 0.4.5
setting:
  allowRegister: "N"
notification:
  mail:
    server: ''
    port: ''
    senderEmail: ''
    senderIdentity: ''
    smtp:
      user: ''
      password: ''

**Comment by gyc0218** [comment]
![image](https://user-images.githubusercontent.com/7087754/75085698-a61a7b80-5566-11ea-8b4b-8bc58a69f572.png)

**Comment by tikazyq** [comment]
你是直接部署的？

**Comment by gyc0218** [comment]
是的

**Comment by tikazyq** [comment]
那看看本机时区是否正常

**Comment by gyc0218** [comment]
crawlab是部署在win server2016上，服务器的时区是正常的。特地编写了测试脚本，在服务器运行时区是上海，但是在crawlab上就是utc时间（脚本里直接设置了环境变量TZ为上海时区）。另外，测试的时候发现，crawlab的环境变量和操作系统本身的环境变量是隔离的，不知道是不是有问题。

**Comment by tikazyq** [comment]
既然是在win上部署，建议还是docker方便一些

**Comment by tikazyq** [comment]
接下来的版本将停止支持windows直接部署
