### ISSUE TITLE
建议增加爬虫相关配置备份功能

### ISSUE THREAD

**Issue by zaite** [crawlab-team/crawlab#571]
目前没有爬虫配置的备份功能，建议增加并可备份到本地，在使用过程中根据需求还原导入

**Comment by tikazyq** [comment]
是指哪些配置？

**Comment by zaite** [comment]
爬虫配置、环境变量、爬虫执行的文件

**Comment by tikazyq** [comment]
例如执行命令、结果集，存在数据库里的这些数据对吧

**Comment by zaite** [comment]
是的，关键配置能做到备份及还原对项目及爬虫部署来说就非常方便了

**Comment by tikazyq** [comment]
可以，后期会加入到 `Spiderfile` 中来配置，并加入导出功能，请关注后续开发

**Comment by tikazyq** [comment]
> 是的，关键配置能做到备份及还原对项目及爬虫部署来说就非常方便了

希望采用哪种方式备份或导出？

**Comment by zaite** [comment]
> > 是的，关键配置能做到备份及还原对项目及爬虫部署来说就非常方便了
> 
> 希望采用哪种方式备份或导出？

普遍的是文件形式，可读写，格式可以是项目本身的配置格式或者常见的数据格式都可以，如json这些
