### ISSUE TITLE
爬虫数据校验优化建议

### ISSUE THREAD

**Issue by zaite** [crawlab-team/crawlab#572]
可以否增加结果数据校验，也就是增量功能，如原任务中（较早已经完成的任务）已经爬取过的数据可以忽略，只爬取新数据，是否增量爬取采集可根据需求通过配置自主选择。

**Comment by tikazyq** [comment]
可以考虑

**Comment by tikazyq** [comment]
现在的增量抓取需要自己写逻辑判断，不过这个功能可以稍微改进一下集成到SDK里
