### ISSUE TITLE
在可配置爬虫中的内容抽取建议增加对HTML标签的抽取

### ISSUE THREAD

**Issue by beeagle2018** [crawlab-team/crawlab#578]

**Comment by hetianyi** [comment]
我针对这个追加了两个field参数，能够提取详情页有列表特征的数据
同时支持提取为HTML
https://github.com/hetianyi/crawlab/tree/array-field
将镜像替换为我的就可以使用：```hehety/crawlab:latest```

效果展示：
![image](https://user-images.githubusercontent.com/10386222/83492158-707e1a80-a4e5-11ea-8fd1-9d2a2144f2fd.png)
![image](https://user-images.githubusercontent.com/10386222/83492221-87bd0800-a4e5-11ea-97eb-066beabf9789.png)
