### ISSUE TITLE
建议增加采集内容去重及采集结果推送功能

### ISSUE THREAD

**Issue by beeagle2018** [crawlab-team/crawlab#579]
去重，可以考虑在某个时间段内去重，如1天内，3天内，7天内去重，以减轻系统压力

结果推送可以考虑，基于消息或者web等其他方案

**Comment by tikazyq** [comment]
如果我只支持永久去重功能，是否能满足你需求？

如果要支持1/3/7天去重，需要自己控制

**Comment by tikazyq** [comment]
已添加去重功能
