### ISSUE TITLE
用户权限

### ISSUE THREAD

**Issue by hichenyi** [crawlab-team/crawlab#583]
超级管理员用户与普通用户的区别在哪里, 能否在前端页面添加一些权限的功能按钮?

**Comment by tikazyq** [comment]
duplicated with https://github.com/crawlab-team/crawlab/issues/608

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/7e343cdde1a2540a28bcfdc08ea106a728218e54
