### ISSUE TITLE
worker无法连接

### ISSUE THREAD

**Issue by xlh001** [crawlab-team/crawlab#597]
**Bug 描述**
当使用docker-compose up -d 参数运行时，出现worker无法连接情况，worker容器出错被关闭。
使用docker-compose up 运行时未出现worker无法连接情况。

**复现步骤**
该 Bug 复现步骤如下
1. 使用docker-compose部署时，启用CRAWLAB_SERVER_LANG_NODE: "Y"参数，预装nodejs环境
2. docker-compose up -d 正确启动后
3. 访问登陆界面出现无法登陆情况，查看网络请求后发现后端访问503，worker错误停止运行

**期望结果**
docker-compose up -d 后台能正常运行crawlab

**截屏**
![3tEZX8.png](https://s2.ax1x.com/2020/02/25/3tEZX8.png)
![3tEmnS.png](https://s2.ax1x.com/2020/02/25/3tEmnS.png)
![3tEn0g.png](https://s2.ax1x.com/2020/02/25/3tEn0g.png)
![3tEE1P.png](https://s2.ax1x.com/2020/02/25/3tEE1P.png)

**Comment by tikazyq** [comment]
工作节点日志发一下

**Comment by tikazyq** [comment]
另外把主节点日志也发一下

**Comment by xlh001** [comment]
您好！非常抱歉仅保留了部分日志文件。
* Starting nginx nginx
   ...done.
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env: export GIN_MODE=release
 - using code: gin.SetMode(gin.ReleaseMode)

2020/02/25 18:41:18  info initialized config successfully
2020/02/25 18:41:18  info initialized log config successfully
2020/02/25 18:41:18  info periodically cleaning log is switched off
2020/02/25 18:41:19  info initialized MongoDB successfully
2020/02/25 18:41:19  info initialized Redis successfully
2020/02/25 18:41:19  info initialized task executor successfully
2020/02/25 18:41:19  info register type is :*register.MacRegister
2020/02/25 18:42:09 error cannot get current node
2020/02/25 18:42:09 error init node service error:cannot get current node
panic: cannot get current node

goroutine 1 [running]:
main.main()
 /go/src/app/main.go:106 +0x465a

**Comment by tikazyq** [comment]
可能是主节点没有启动导致的，请试一下主节点不预装nodejs，工作节点预装试试

**Comment by xlh001** [comment]
好的，晚些时候进行测试反馈。
