### ISSUE TITLE
可配置爬虫字段能不能加上url标志，这样相对路径的url可以转成绝对路径

### ISSUE THREAD

**Issue by heixiah** [crawlab-team/crawlab#598]
有些链接是相对路径的，现在可配置爬虫只能获取到相对路径，没法获取到绝对路径

**Comment by tikazyq** [comment]
可以获取吧，你是列表页么？

**Comment by heixiah** [comment]
比如说那个雪球网的可配置爬虫，我想获取爬取页面的url，就是那个url字段 ，它是个相对路径，我想获取绝对路径，现在获取不到

**Comment by tikazyq** [comment]
这是个需求，确实暂时还获取不到，等我们fix这个问题
