### ISSUE TITLE
nodejs爬虫无法运行

### ISSUE THREAD

**Issue by FrontMage** [crawlab-team/crawlab#599]
主要是两个问题，一个是worker不自带node，二个是如果打包node_modules压缩包就太大了无法上传，不打包就没法运行。实测19mb的zip就没法上传。

**Comment by tikazyq** [comment]
其实是可以运行node爬虫的。首先，你需要预装 node.js 的环境，在配置的时候设置 `CRAWLAB_SERVER_LANG_NODE` 环境变量为 `Y`，然后启动容器，等大概几分钟，就会将Node.js 装好。然后，你可以在 `节点详情` -> `安装` 中安装 Node.js 的依赖，这个依赖是全局的，你不需要将node_modules上传上来。希望能帮助到你

**Comment by FrontMage** [comment]
@tikazyq 感谢指点，试了下还是不行，点击安装node的包以后，例如`request-promise`页面显示安装完成，但是刷新页面已安装的包的时候还是没有。

**Comment by tikazyq** [comment]
你是docker还是直接部署

**Comment by FrontMage** [comment]
@tikazyq docker，克隆的master分支，然后`docker-compose up -d`

**Comment by tikazyq** [comment]
你进入到容器里，然后执行 `npm list -g|grep request` 看看

**Comment by FrontMage** [comment]
```
root@aa6f999cf045:/app/backend# npm list -g | grep request
│ │ ├── request@2.88.0 deduped
│ │ ├── request@2.88.0 deduped
│ ├─┬ request@2.88.0
root@aa6f999cf045:/app/backend#
```
@tikazyq

**Comment by tikazyq** [comment]
把显示的界面发出来看看

**Comment by FrontMage** [comment]
![Screenshot from 2020-02-29 13-03-44](https://user-images.githubusercontent.com/17007026/75601213-ff008b80-5af3-11ea-9939-9458353f0404.png)

**Comment by FrontMage** [comment]
经过测试，应该是`nvm`导致的全局安装的包不可见，目前我的解决方法是上传`package.json`然后手动进入容器安装依赖，另一方面由于默认安装了`8.12.0`但是这个版本不支持`async iterator`所以我手动安装了更新的版本。

`nvm`不work的原因是默认`nvm`会加几行到`.bashrc`里面用来载入它的一些环境变量和脚本，但是默认执行用的是`sh`而非`bash`所以应该是略有问题的。

**Comment by tikazyq** [comment]
@FrontMage 感谢反馈，我们会安排修复这个问题

**Comment by FrontMage** [comment]
close for inactive.
