### ISSUE TITLE
节点第三方模块安装失败导致  节点安装第三方部分无法使用

### ISSUE THREAD

**Issue by EisenbergTM** [crawlab-team/crawlab#609]
**Bug 描述**
例如，当节点安装scrapy-redis，pandas等安装时间较长等模块 时，如果安装失败，安装和查询模块功能不工作。

**期望结果**
能正常工作。

**截屏**
![image](https://user-images.githubusercontent.com/38349615/75665788-ae359200-5caf-11ea-9cbd-f904efb1c51b.png)
![image](https://user-images.githubusercontent.com/38349615/75665844-c4435280-5caf-11ea-88dd-ee84bbcbf74c.png)

**Comment by tikazyq** [comment]
已经通过RPC重构修复了，在develop上
