### ISSUE TITLE
容器内升级crawlab版本

### ISSUE THREAD

**Issue by Tang-1** [crawlab-team/crawlab#614]
感谢crawlab贡献者的付出 ，这是一个很棒的工具。

一个新的docker镜像远行代码需要配置所需环境，这需要一定时间。而还在成长的crawlab更新是常有的事。
希望能够实现在容器内部直接更新crawlab，不影响已配置好的环境。
这会帮助使用者减少升级成本。尤其对使用了几种语言做爬虫的公司，实现这一点更容易被接受并推广。

另一个建议： 其他的enhancement也有提到，在中大型公司内部对爬虫的管理权限尤其重要，同在技术部也存在不同的增删改查权限区分。上游/下游部门则仅关注数据结果和任务状态，对日志及程序细节则不会关注。若能优化权限管理功能，在管理层也更容易接受。

**Comment by hantmac** [comment]
仅升级crawlab本身这个我也想到了 @tikazyq , 以后升级的时候可以release一下crawlab的二进制文件

**Comment by tikazyq** [comment]
> 仅升级crawlab本身这个我也想到了 @tikazyq , 以后升级的时候可以release一下crawlab的二进制文件

好主意，其实只要更新二进制文件和静态文件就可以了👍
