### ISSUE TITLE
停止任务失败

### ISSUE THREAD

**Issue by lissh** [crawlab-team/crawlab#623]
**Bug 描述**
前端没有报错和异常，停止任务也提示停止了。刷新前端任务还在运行中，后端服务查看任务还在进行中。查看日志如截图。

**复现步骤**
该 Bug 复现步骤如下
1. 不好复现。
2. 
3. 

**期望结果**
查明下原因，貌似跟同步spiders 和redis连接有关

**截屏**
![image](https://user-images.githubusercontent.com/17311089/76196309-fe1ed680-6224-11ea-8758-880be8179253.png)

**Comment by tikazyq** [comment]
需要进一步解释一下

**Comment by YanhuiJessica** [comment]
您好，我也遇到了类似的问题，Scrapy 爬虫已经运行结束，但是任务的状态一直是`running`。
查看日志显示如下
```bash
...
2021-01-31 19:35:34 [scrapy.core.engine] INFO: Spider closed (finished)
正在更新日志...
```
卡在“正在更新日志…”
