### ISSUE TITLE
用框架可以实现视频、图片等文件下载和重命名吗？

### ISSUE THREAD

**Issue by wansuiye09** [crawlab-team/crawlab#639]
**请描述该需求尝试解决的问题**
例如，当 xxx 时，我总是被当前 xxx 的设计所困扰。

**请描述您认为可行的解决方案**
例如，添加 xxx 功能能够解决问题。

**考虑过的替代方案**
例如，如果用 xxx，也能解决该问题。

**Comment by tikazyq** [comment]
请进一步解释一下

**Comment by wansuiye09** [comment]
我想爬取视频网站的视频、缩略图及字幕文件，但是发现使用crawlab的可配置爬虫，无法实现文件下载功能，是不是必须再按照scrapy的思路去改脚本？此外，无法构建header的动态切换，每个爬虫只能有一个header。
