### ISSUE TITLE
GridFS错误导致Git同步后无法运行爬虫

### ISSUE THREAD

**Issue by wenxuyang** [crawlab-team/crawlab#640]
**Bug 描述**
当 运行爬虫的时候，出现
![image](https://user-images.githubusercontent.com/37622833/76821186-28394f80-6848-11ea-9b03-67915920f708.png)
并且日志信息为
![image](https://user-images.githubusercontent.com/37622833/76821222-44d58780-6848-11ea-8db7-6b8d79195d56.png)
但是之前配置的定时任务是正常运行的

**总结**
说是GridFS的错误？

**Comment by tikazyq** [comment]
duplicated in https://github.com/crawlab-team/crawlab/issues/643
