### ISSUE TITLE
请求你们计划什么时候发布1.0版本？

### ISSUE THREAD

**Issue by clown-0726** [crawlab-team/crawlab#642]
**请描述该需求尝试解决的问题**
例如，当 xxx 时，我总是被当前 xxx 的设计所困扰。

**请描述您认为可行的解决方案**
例如，添加 xxx 功能能够解决问题。

**考虑过的替代方案**
例如，如果用 xxx，也能解决该问题。

**Comment by tikazyq** [comment]
现在产品还没到发布 1.0 的时候，例如缺少权限管理等核心功能，不知道您需要什么样的功能？



在 2020-03-18 15:48:25，"Grassroot Infant" <notifications@github.com> 写道：

请描述该需求尝试解决的问题
例如，当 xxx 时，我总是被当前 xxx 的设计所困扰。

请描述您认为可行的解决方案
例如，添加 xxx 功能能够解决问题。

考虑过的替代方案
例如，如果用 xxx，也能解决该问题。
