### ISSUE TITLE
【Bug】"cannot find spider files, please re-upload" error

### ISSUE THREAD

**Issue by tikazyq** [crawlab-team/crawlab#643]
**Bug 描述**
当上传爬虫后，出现 "cannot find spider files, please re-upload" 错误

**复现步骤**
该 Bug 复现步骤如下
1. 上传爬虫
2. 运行爬虫

**期望结果**
不出现该错误。

**截屏**
![image](https://user-images.githubusercontent.com/3393101/77026930-d02d5500-69cf-11ea-947d-8e9f64c384f1.png)

**Comment by jerryliu306** [comment]
**Bug复现步骤:**
1. xx_spider已经存在，并且能够正常运行
2. 删除xx_spider，并且重新创建xx_spider，然后上传xx_spider.zip，提示上传成功，保存，提示保存成功。
3. 运行xx_spider，提示 "cannot find spider files, please re-upload" 错误

**问题查找结果：**
数据库表 files.files中存在xx_spider.zip文件，但是该爬虫文件的_id字段值在spiders表中file_id字段中并未找到对应值，并且新创建的spider对应的file_id在files.files中也不存在，推测是之前的爬虫删除后，files.files表中的爬虫文件未删除成功。为何新创建的爬虫上传爬虫文件成功，files.files中不存在爬虫文件的问题待查找！

**Comment by tikazyq** [comment]
临时解决方案: 重新上传爬虫

**Comment by tikazyq** [comment]
fixed

**Comment by tikazyq** [comment]
问题原因: 在爬虫详情中上传的时候，在GridFS上保存的文件名为上传文件名，因此如果多个爬虫共用一个上传文件名会导致找不到的问题。
解决方案: 用爬虫名称作为保存到GridFS上的文件名，保证文件不冲突。

**Comment by tikazyq** [comment]
临时解决方案：不要用同一个zip文件名上传，每个爬虫保证文件名不一样

**Comment by nicolasmeng** [comment]
可配置爬虫也是一样的，我选的163_news，按理说不需要上传文件的，也是这个错误

**Comment by nicolasmeng** [comment]
@tikazyq 忘了@ 你了

**Comment by fightingfish008** [comment]
经常遇到类似的问题。环境:一个主节点、九个工作节点。每次上传后如果遇到找不到都是把爬虫删掉。重新上传新的zip 文件。执行是可以实行。但是，如果换一另外的节点执行。就又报找不到文件的错了。
