### ISSUE TITLE
不懂原理的情况下，一个使用者的建议

### ISSUE THREAD

**Issue by huahaomei521** [crawlab-team/crawlab#644]
2020.3.18首次接触使用，本机测试
以下问题都是在不看代码原理的情况下，仅仅使用时，产生的建议
爬虫举例：A项目，导航栏出现5个分类（不同的URL，相同的结构），爬取A项目的5个分类下的列表
A_爬虫分类1  结果 result_a1
。。。。                .....
A_爬虫分类5          result_a2
1、可配置爬虫：里面的【结果】定义，是什么意思？看我上面举例，可以都定义为一个result_a吗，这样我**下载的CSV是这5个分类的汇总**
2、我建立了5个分类，在我点击每个任务分类的详情时，页面上方导航栏出现了5个TAG，但是名字都是【爬虫详情】，我想和线上的A项目网站进行条数对比，我得一个一个切换看，并不知道谁是谁，**能不能把上面打开的快速导航栏TAG改成爬虫的名称**
3、**可配置爬虫中，能不能增加一个默认值字段**，用以区分是哪个分类下的数据，例子：
A_爬虫分类1        定义一个type字段：默认值1
。。。。                .....
A_爬虫分类5         定义一个type字段：默认值5
这样我导入5个csv到mysql，能区分出来

总结：1、tag多了，都是xx详情，不知道谁是谁
2、可配置爬虫，增加默认值自定义项，此项不需要解析页面结构，是什么就是什么
3、5个分类下的同结构的列表，可以定义同一个结果集吗？并且只下载一次csv

**Comment by tikazyq** [comment]
1. 这个我们可以优化下；
2. 这个可以理解为抓取HTML为数据么；
3. 可以解释一下

**Comment by huahaomei521** [comment]
第二个问题：可以理解为，后续的清洗了，就是加了一个固定标识，来标识这个是哪一个分类下的数据，我写了5个爬虫，然后在csv里面各单独加了一列类型。。。。要是爬的时候，能自动加固定值字段多好啊（现实很骨感）
第三个问题：可以忽略，也是我比较懒的事。。。因为我爬了一个网站下面的5个不同url路径的数据（这些数据的结构是一样的，起的字段名也一样），我下载csv的时候，需要点开5个爬虫看结果，然后点下载，如果能一键下载5个，或者结果集中存的就是5个的数据

**Comment by tikazyq** [comment]
第二个问题，可以理解为你需要加一个字段来知道是哪个爬虫抓的么

**Comment by huahaomei521** [comment]
是的
