### ISSUE TITLE
python爬虫定义的utils包里面的内容无法上传成功, 改成util就可以

### ISSUE THREAD

**Issue by wenzidance** [crawlab-team/crawlab#646]
**Bug 描述**
例如，当打包上传爬虫时，utils包里面内容无法上传成功。

**复现步骤**
该 Bug 复现步骤如下
1. 把包名utils改成util就OK

**期望结果**
utils包里面的内容可以成功上传。

**截屏**
![截屏1](http://static-docs.crawlab.cn/login.png)
![image](https://user-images.githubusercontent.com/38269722/77051890-fb7f6680-6a06-11ea-8f68-c8f3a27158d3.png)
![image](https://user-images.githubusercontent.com/38269722/77051947-118d2700-6a07-11ea-91e8-05c76fa2d35b.png)

**Comment by tikazyq** [comment]
fixed
