### ISSUE TITLE
任务列表优化

### ISSUE THREAD

**Issue by liufengsoft** [crawlab-team/crawlab#648]
**Is your feature request related to a problem? Please describe.**
频繁的定时任务一段时间后会充斥整个任务列表，导致无法通过任务列表找到其他想要的任务。任务列表对其他爬虫没有太多意义了。

**Describe the solution you'd like**
可以自动折叠定时任务，在任务列表中只显示一个。

**Describe alternatives you've considered**
任务列表具有关键词模糊查询过滤功能，快速找到一个想要的任务。

**Comment by tikazyq** [comment]
现在可以在定时任务中查看相关的任务列表
