### ISSUE TITLE
长任务 爬虫重启 

### ISSUE THREAD

**Issue by EisenbergTM** [crawlab-team/crawlab#649]
## 场景：多节点分布式爬虫  git同步
*  使用节点 1，2，3，7，9，5
* git代码修改同步完
### 现有方式 
* 选定节点运行
![image](https://user-images.githubusercontent.com/38349615/77151638-53829f80-6ad1-11ea-9e8f-b3eda2a4ab39.png)
### 期望方式
* 我不记得之前运行的节点了，想在爬虫运行的时候点击‘重启’ 运行上次运行的命令以及节点
![image](https://user-images.githubusercontent.com/38349615/77152153-5336d400-6ad2-11ea-9143-99b5571fbba8.png)

**Comment by tikazyq** [comment]
图画得不错，重启功能正在开发中
