### ISSUE TITLE
不同用户之间实现隔离

### ISSUE THREAD

**Issue by 760363357** [crawlab-team/crawlab#653]
1. 建议设置用户工作空间的概念，不同的用户拥有完全独立的工作空间(爬虫, 定时任务,任务,统计等)
2. 可以从其他用户空间的爬虫fork到自己的空间下
3. 严格的权限管理，超级用户可以操作所有人的工作空间，普通的用户只能在自己的工作空间操作

**Comment by tikazyq** [comment]
duplicated with https://github.com/crawlab-team/crawlab/issues/608

**Comment by tikazyq** [comment]
fixed in https://github.com/crawlab-team/crawlab/commit/7e343cdde1a2540a28bcfdc08ea106a728218e54
