### ISSUE TITLE
节点角色/任务线程优化请求

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#654]
旧版本的节点角色管理 CRAWLAB_SERVER_MASTER 默认是 N，相对比较合理。
不知道从哪个版本开始变成默认为 Y 了(导致与说明文档不一致) ，建议退回到默认是 N，以避免不可以预期的其它麻烦。

另外并行任务线程工作方式有待优化，从开发组了解到节点会根据 CRAWLAB_TASK_WORKERS 的设置值创建相应的线程数，在每一秒同时进行轮询扫描，导致过高的 CPU 占用。
不知道开发组针对此问题有没有相应的优化策略。

**Comment by hantmac** [comment]
1. CRAWLAB_SERVER_MASTER  这个默认确实应该是N;
2. CRAWLAB_TASK_WORKERS 这个参数可能要根据自己机器的实际规格来定.
