### ISSUE TITLE
Install plugins on start / restart

### ISSUE THREAD

**Issue by LordVoodoo** [crawlab-team/crawlab#657]
For nodes I can install plugins using the GUI, in my case "pymysql". After restarting Docker, I need to re-install the plugin everytime.

I would like to give Crawlab Docker a comma separated list of plugins, which need to be installed on the node itself, e.g. "-CRAWLAB_NODE_PLUGINS=pymyslq"

An alternative would be to store the information of installed plugins in the configuration inside the addressed MongoDB and restore the plugin on restart. A switch, yes or no, in the configuration might be needed to manage exceptions, when Crawlab isn't starting caused by a plugin issue.

**Comment by hantmac** [comment]
Good idea 👍

**Comment by tikazyq** [comment]
Will the hot-upgrade feature enough to solve your problem. E.g. you don’t have to restart docket and could be able to upgrade inside the docket container

**Comment by LordVoodoo** [comment]
Well, I don’t use a dedicated server for Crawlab, runs along with several docker services like Smarthome, MySQL database, XMLTV, ...
A restart is mostly driven, when I change settings on different services.

**Comment by LordVoodoo** [comment]
I have managed to solve this issue by the following procedure:

1. Created a folder for Crawlab and placed a file named "Dockerfile" inside this folder.

Content of this Dockerfile:
```
FROM tikazyq/crawlab:latest
RUN pip install pymysql
```
2. Editing docker-compose.yml, section for crawlab:
```
crawlab: 
    build: ./crawlab
    container_name: Crawlab
    ...
```
Now the needed module pymysql is reinstalled on every docker restart.
