### ISSUE TITLE
增加日志错误报警

### ISSUE THREAD

**Issue by z10z10b10** [crawlab-team/crawlab#658]
1. 增加爬虫日志错误报警功能
2.日志错误最好在最近任务中体现状态，目前全是已完成，只有点击进去才能看见日志错误。
![image](https://user-images.githubusercontent.com/43260051/77744159-2e071000-7054-11ea-9536-4bc8c42c9a50.png)

**Comment by DQmyth** [comment]
同样的问题, 希望在状态栏里, 增加爬虫的运行结果, 比如正常/异常, 如果为异常, 点击就能看到报错的日志
![image](https://user-images.githubusercontent.com/42857639/79307495-95b0cc80-7f29-11ea-96a0-bc8f2d8b29f6.png)
