### ISSUE TITLE
运行几天后Argument list too long

### ISSUE THREAD

**Issue by XiaCo** [crawlab-team/crawlab#659]
**Bug 描述**
例如，运行几天后定时任务报 Argument list too long

**复现步骤**
该 Bug 复现步骤如下
1. 爬虫定时任务较多，并且每分钟运行多个
2. 一般在运行两三天后，出现这种情况

**期望结果**
修复

**补充**
1. 打印的env.PATH结果："PATH=/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/versions/node/v8.12.0/lib/node_modules:/root/.nvm/vers......"
2. /backend/services/task.go ExecuteShellCmd 调用了 SetEnv，SetEnv中的原因？

**Comment by tikazyq** [comment]
fixed on develop
