### ISSUE TITLE
scrapy爬虫去重bug

### ISSUE THREAD

**Issue by guoxianru** [crawlab-team/crawlab#674]
1、scrapy爬虫，设置md5字段覆盖去重
2、第一次正常运行，并取得结果
3、再次运行，报pymongo errors DuplicateKeyError错误，md5重复
`2020-04-02 14:29:51 [scrapy.core.scraper] ERROR Error processing {'data_sheet': 'http://www.casssemi.com/UpLoad/201909/CSD60P280%20data%20sheet%20V2.0.pdf',
40'id': '-30A',
41'md5': 'e7440230a866567c9a8fa5e42e5cc123',
42'package': 'TO-252',
43'part_number': 'CSD60P280',
44'vds': '-60V',
45'vgs': '±20V',
46'vth': '-1.8V'}
47Traceback (most recent call last):
48File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
49current.result = callback(current.result, *args, **kw)
50File "/usr/local/lib/python3.6/dist-packages/scrapy/utils/defer.py", line 154, in f
51return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
52File "/usr/local/lib/python3.6/dist-packages/crawlab/pipelines/__init__.py", line 9, in process_item
53col.save(item_dict)
54File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 3158, in save
55to_save, True, check_keys, manipulate, write_concern)
56File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 612, in _insert
57bypass_doc_val, session)
58File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 600, in _insert_one
59acknowledged, _insert_command, session)
60File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
61return self._retry_with_session(retryable, func, s, None)
62File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
63return func(session, sock_info, retryable)
64File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 597, in _insert_command
65_check_write_command_response(result)
66File "/usr/local/lib/python3.6/dist-packages/pymongo/helpers.py", line 221, in _check_write_command_response
67_raise_last_write_error(write_errors)
68File "/usr/local/lib/python3.6/dist-packages/pymongo/helpers.py", line 202, in _raise_last_write_error
69raise DuplicateKeyError(error.get("errmsg"), 11000, error)
70pymongo errors DuplicateKeyError: E11000 duplicate key error collection: crawlab_test.ks_test2 index: md5_1 dup key: { md5: "e7440230a866567c9a8fa5e42e5cc123" }`

**Comment by tikazyq** [comment]
感觉是key碰撞了，你再试一下呢？
