### ISSUE TITLE
关闭“是否为scrapy“开关，在等待一段时间后，又自动打开了

### ISSUE THREAD

**Issue by luzihang123** [crawlab-team/crawlab#676]
**Bug 描述**
关闭“是否为scrapy“开关，接着执行 pip install -r requirements.txt && scrapy crawl spider,项目正常运行，在等待一段时间后（30min-1h 之后），“是否为scrapy“开关又自动打开了，由于分布式，随机节点，没有安装依赖，项目不能再次启动。

**复现步骤**
该 Bug 复现步骤如下
1. 关闭“是否为scrapy“开关
2. 接着执行 pip install -r requirements.txt && scrapy crawl spider,项目正常运行
3. 在等待一段时间后（30min-1h 之后），“是否为scrapy“开关又自动打开了
4.由于分布式，随机节点，没有安装依赖，项目不能再次启动。
5.设置 CRAWLAB_SETTING_CHECKSCRAPY 为N，重新启动master
6.重新设置爬虫任务
7.在等待一段时间后（30min-1h 之后），“是否为scrapy“开关又自动打开了

**期望结果**
关闭“是否为scrapy“开关，任务稳定运行

**截屏**
已经设置 CRAWLAB_SETTING_CHECKSCRAPY 为N
还是会异常
![image](https://user-images.githubusercontent.com/16731803/78455601-db6fc880-76d1-11ea-97b2-67f731507afb.png)
![image](https://user-images.githubusercontent.com/16731803/78455609-ecb8d500-76d1-11ea-948a-da3a67f02196.png)

**Comment by tikazyq** [comment]
设计如此，不会fix

**Comment by gmzhang** [comment]
我也碰到了该问题。

特别是：

「是否为Scrapy」开关被自动打开后，执行命令就被改掉了。

执行命令有的就是启动一个文件，例如  ./start.sh。
