### ISSUE TITLE
邮箱无法正常发送

### ISSUE THREAD

**Issue by baidu367** [crawlab-team/crawlab#677]
Bug 描述
docker部署，邮箱配置正常，无法发送邮件。

复现步骤
该 Bug 复现步骤如下
1.修改docker-compose.yml文件，配置邮件基本设置
2. 启动docker服务
3. 设置消息通知（邮箱）

期望结果
1、正常接收邮件信息

**Comment by tikazyq** [comment]
请问是哪种情况下无法收到邮件？任务结束、或出现错误？

**Comment by yaziming** [comment]
@baidu367  ping
