### ISSUE TITLE
使用go build命令时，会产生错误

### ISSUE THREAD

**Issue by freezxin163** [crawlab-team/crawlab#679]
![图片](https://user-images.githubusercontent.com/15882429/78878267-ade59f00-7a84-11ea-8a3e-e345e5288dde.png)
# crawlab/services
services\task.go:186:10: undefined: syscall.Kill
services\task.go:292:42: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr

**Comment by xianyunyh** [comment]
syscall 是 [U|L]inx  系统下的命令，windows不支持
