### ISSUE TITLE
git項目同步的問題

### ISSUE THREAD

**Issue by jarvisaoieong** [crawlab-team/crawlab#680]
**Bug 描述**
爬蟲設定中，ssh的git項目地址，在代碼同步時，使用 非master 分支的話，會有bug
一時會報 reference not found， 多次按同步的話，可能會成功，但最終是 拉了 master分支

![image](https://user-images.githubusercontent.com/195635/78957711-b2f42e00-7b18-11ea-9097-b48868fbc636.png)

另外，https的git項目地址，在輸入了用戶密碼後，並没有觸發請求分支的ajax，必須重新更改一下git地址才會產生ajax請求，而且這請求會失敗，獲取不到分支清單。

**Comment by tikazyq** [comment]
暂时只支持master分支
