### ISSUE TITLE
 在节点里安装依赖中搜索不到包

### ISSUE THREAD

**Issue by daimiaopeng** [crawlab-team/crawlab#688]
如果输入的字符串前或后存在空格将搜索不到包，虽然手动输入有搜索建议，但是如果是复制粘贴的单词后面有空格将搜索不到，我觉得搜索时应该去掉前后面的空格来避免产生误会。

**Comment by tikazyq** [comment]
搜索哪个字符串会出问题？

**Comment by daimiaopeng** [comment]
比如说python中的requests后面有空格就搜索不到

**Comment by tikazyq** [comment]
这不是bug，应该是个优化issue

**Comment by daimiaopeng** [comment]
好吧，希望能考虑去掉前后的空格再搜索。
