### ISSUE TITLE
爬虫状态更新不及时的问题

### ISSUE THREAD

**Issue by DQmyth** [crawlab-team/crawlab#689]
**Bug 描述**
1.这是一个偶发的情况, 有时爬虫已经爬完了一段时间了, 但是状态显示仍为"进行中"

**截屏**
![image](https://user-images.githubusercontent.com/42857639/79314462-48862800-7f34-11ea-8317-e52a5a9ce393.png)
![image](https://user-images.githubusercontent.com/42857639/79314548-605dac00-7f34-11ea-94a8-2fbc57303466.png)

**Comment by tikazyq** [comment]
fixed
