### ISSUE TITLE
爬虫结果的下载csv功能的csv文件出现中文乱码

### ISSUE THREAD

**Issue by Ideals-L** [crawlab-team/crawlab#692]
爬虫结果的下载csv功能的csv文件出现中文乱码，应该是要增加utf-8格式的转码

**Comment by yaziming** [comment]
新版本已经修复了这个问题， 所以先关掉这个issue，如果还能重现乱码问题可以继续在该issuse下回复

**Comment by xiaomei628** [comment]
![image](https://user-images.githubusercontent.com/15361002/84493577-8ad0a900-acda-11ea-91e0-8f976a7f3c88.png)
我今天干docker安装试了下，下载的数据也是中文乱码

**Comment by xiaomei628** [comment]
@yaziming 
![image](https://user-images.githubusercontent.com/15361002/84493718-d2efcb80-acda-11ea-83a3-2eaa76d1840c.png)
我今天用docker安装了这个平台，试了下爬虫，数据下载下来也是乱码

**Comment by JQ-K** [comment]
> 新版本已经修复了这个问题， 所以先关掉这个issue，如果还能重现乱码问题可以继续在该issuse下回复

mac 打开网站下载还是乱码
