### ISSUE TITLE
部署到生成环境后，工作节点总是莫名的离线

### ISSUE THREAD

**Issue by wuwenrufeng** [crawlab-team/crawlab#693]
**Bug 描述**
当 部署到生成环境 时，工作节点过一段时间（3天左右）总会离线。这样会造成定时任务运行出错。
但工作节点的主机上的docker运行是正常的，怀疑是工作节点的心跳包通信有问题。

**复现步骤**
该 Bug 复现步骤如下
1. 部署生成环境
2. 运行
3. 工作节点离线

**期望结果**
工作节点不离线

**截屏**
![微信图片_20200420150635](https://user-images.githubusercontent.com/45844514/79723561-8f02ca80-8318-11ea-9c68-8122a5233b40.png)

**Comment by tikazyq** [comment]
可以看到离线的工作节点的日志么？

**Comment by yumen** [comment]
一样的问题，这个接口400，https://api.crawlab.cn/track?uid=  {status: "ok", message: "error", data: null, error: "invalid request"}
