### ISSUE TITLE
服务器无响应

### ISSUE THREAD

**Issue by see2** [crawlab-team/crawlab#697]
**Bug 描述**
在服务器上运行程序后，进入crawlab界面，但是服务器无响应。

**复现步骤**

- 正常安装程序
- 使用说明的docker-compose yml
- 打开in bound服务器8080端口

**期望结果**
能正常使用

**截屏**
![image](https://user-images.githubusercontent.com/11245233/79873025-1fc0cf80-8419-11ea-9767-d2443495c1ae.png)

**Comment by tikazyq** [comment]
docker logs master 看看后台日志

**Comment by mumusoo** [comment]
同样的问题：
f12 显示：
Access to XMLHttpRequest at 'localhost:8000/nodes' from origin 'http://localhost:8080' has been blocked

**Comment by yumen** [comment]
一样的问题，
这个接口400，https://api.crawlab.cn/track?uid= 
返回数据:{status: "ok", message: "error", data: null, error: "invalid request"}

**Comment by tikazyq** [comment]
> 一样的问题，
> 这个接口400，https://api.crawlab.cn/track?uid=
> 返回数据:{status: "ok", message: "error", data: null, error: "invalid request"}

这是埋点用的，不用管

**Comment by tikazyq** [comment]
> 同样的问题：
> f12 显示：
> Access to XMLHttpRequest at 'localhost:8000/nodes' from origin 'http://localhost:8080' has been blocked

后端起了么，日志是咋样的

**Comment by fengci** [comment]
使用文档中的 docker-compose.yml 配置启动。 登录提示请求https://api.crawlab.cn 状态400，然后页面提示是 `服务器无响应，请保证您的服务器正常运行。您也可以参考文档来解决这个问题（文档链接在下方）` 
`CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                            NAMES
28d4a17831b9        tikazyq/crawlab:latest   "/bin/bash /app/dock…"   18 minutes ago      Up 4 minutes        0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp   crawlab-master
c55d2c6f6eb8        tikazyq/crawlab:latest   "/bin/bash /app/dock…"   18 minutes ago      Up 4 minutes        8000/tcp, 8080/tcp                               crawlab-worker
f6ae7e1a2b2d        mongo:latest             "docker-entrypoint.s…"   19 minutes ago      Up 4 minutes        0.0.0.0:27017->27017/tcp                         crawlab_mongo_1
9fe9aeb89435        redis:latest             "docker-entrypoint.s…"   19 minutes ago      Up 4 minutes        0.0.0.0:6379->6379/tcp                           crawlab_redis_1`
