### ISSUE TITLE
0.4.10 的自動下載依賴功能導致cpu 100%

### ISSUE THREAD

**Issue by jarvisaoieong** [crawlab-team/crawlab#698]
**Bug 描述**
我的腳本是nodejs項目

一樣的任務，在 0.4.9下跑 cpu 長時間是 33%占用，升級到 0.4.10後，就直接上到100%
我做了測試，我把該節點的任務停了，而且也把worker節點的pod重啟，不跑任何任務，cpu 還是會保持在 90%到 100%

進入容器中去調查，發現是由于節點定時觸發npm install導致的，每分鐘都會觸發，導致cpu滿載

**复现步骤**
该 Bug 复现步骤如下
1. 準備一個nodejs項目，package.json有一些依賴
2. 進入worker節點，通過 top 命令觀察進程負載情況

**截屏**
![image](https://user-images.githubusercontent.com/195635/79939983-0d837780-8493-11ea-8eb5-caea1264dd05.png)
![image](https://user-images.githubusercontent.com/195635/79940028-2724bf00-8493-11ea-9290-ad8183a12471.png)

**Comment by hantmac** [comment]
resolved.
