### ISSUE TITLE
安装第三方依赖库之后更新镜像，docker-compose up时master容器启动后立即exit

### ISSUE THREAD

**Issue by mod3021** [crawlab-team/crawlab#699]
**Bug 描述**
为了安装第三方依赖库，我自己更新了镜像，当docker-compose up时，master容器启动后exit。

**复现步骤**
该 Bug 复现步骤如下
1. 原镜像生成容器，安装第三方库后commit，镜像更新为tikazyq/crawlab:latest
2. docker-compose up -d启动
3. docker ps -a 发现mongo和redis启动正常，master容器存在但是状态为exit

**期望结果**
希望能教一下怎么增加自己的第三方依赖库而不影响正常工作

**截屏**
![image](https://user-images.githubusercontent.com/29471284/79953795-02d6db80-84af-11ea-9e28-df6d0e3f0d08.png)

**Comment by tikazyq** [comment]
需要查看一下为什么exit

`docker-compose logs master`
