### ISSUE TITLE
redis报错问题

### ISSUE THREAD

**Issue by flyowl** [crawlab-team/crawlab#705]
**Bug 描述**
redis报错。在4.09版本安装都是正常的，结果感觉有点不稳定，升级啦最新的。

**复现步骤**
该 Bug 复现步骤如下
1.  安装节点  python包的时候出现的
parse redis://x:﻿****@*****:6379/2: net/url: invalid userinfo  

**截屏**

![image](https://user-images.githubusercontent.com/49393051/80170960-cd033580-861b-11ea-9082-6762385edd27.png)

![image](https://user-images.githubusercontent.com/49393051/80170951-ca084500-861b-11ea-88b7-4d5f70f54c2d.png)

![image](https://user-images.githubusercontent.com/49393051/80170943-c5dc2780-861b-11ea-9d6c-ae644219756a.png)

**Comment by tikazyq** [comment]
检查一下redis密码是否有特殊字符
