### ISSUE TITLE
使用git时, exit status 128错误

### ISSUE THREAD

**Issue by DQmyth** [crawlab-team/crawlab#707]
**Bug 描述**
当与git关联时, 会莫名的报错(只是报错,其他使用正常), 状态码: 500

**截屏**
![image](https://user-images.githubusercontent.com/42857639/80339495-58393100-8891-11ea-93c1-007338d1f1b7.png)
![image](https://user-images.githubusercontent.com/42857639/80339556-7d2da400-8891-11ea-8908-538c8964fc65.png)

**Comment by tikazyq** [comment]
这是什么时候触发的？

**Comment by DQmyth** [comment]
当为git项目时, 关闭标签或刷新页面时会出现
![image](https://user-images.githubusercontent.com/42857639/82167988-10398700-98f0-11ea-8973-be789c5002e1.png)
如: 关闭"任务详情"标签, 会回到"爬虫详情"标签,此时会报错
![image](https://user-images.githubusercontent.com/42857639/82168070-5262c880-98f0-11ea-9fb1-f79bb751cc8a.png)

**Comment by tikazyq** [comment]
> 当为git项目时, 关闭标签或刷新页面时会出现
> ![image](https://user-images.githubusercontent.com/42857639/82167988-10398700-98f0-11ea-8973-be789c5002e1.png)
> 如: 关闭"任务详情"标签, 会回到"爬虫详情"标签,此时会报错
> ![image](https://user-images.githubusercontent.com/42857639/82168070-5262c880-98f0-11ea-9fb1-f79bb751cc8a.png)

会不会影响git的功能？

**Comment by DQmyth** [comment]
> > 当为git项目时, 关闭标签或刷新页面时会出现
> > ![image](https://user-images.githubusercontent.com/42857639/82167988-10398700-98f0-11ea-8973-be789c5002e1.png)
> > 如: 关闭"任务详情"标签, 会回到"爬虫详情"标签,此时会报错
> > ![image](https://user-images.githubusercontent.com/42857639/82168070-5262c880-98f0-11ea-9fb1-f79bb751cc8a.png)
> 
> 会不会影响git的功能？

目前没有

**Comment by tikazyq** [comment]
那暂时不会考虑修复

**Comment by zgxv** [comment]
![image](https://user-images.githubusercontent.com/6904753/87024033-2e927380-c20b-11ea-87f3-0078a4d78281.png)
麻烦问下我这边一直拉不出分支，可能是什么原因。我试了ssh和http的方式都不可以

**Comment by tikazyq** [comment]
> ![image](https://user-images.githubusercontent.com/6904753/87024033-2e927380-c20b-11ea-87f3-0078a4d78281.png)
> 麻烦问下我这边一直拉不出分支，可能是什么原因。我试了ssh和http的方式都不可以

是docker部署？

**Comment by zgxv** [comment]
> > ![image](https://user-images.githubusercontent.com/6904753/87024033-2e927380-c20b-11ea-87f3-0078a4d78281.png)
> > 麻烦问下我这边一直拉不出分支，可能是什么原因。我试了ssh和http的方式都不可以
> 
> 是docker部署？

不是docker部署，问题解决了，在supervisor里启动的有问题，启动后拉取时有命令行交互，需输入yes
