### ISSUE TITLE
重启后节点变多

### ISSUE THREAD

**Issue by azhu949** [crawlab-team/crawlab#709]
**Bug 描述**
当 重启docker后，节点莫名其妙多加了两个，再次重启又多两个，并且节点里面什么都没有安装

**复现步骤**
该 Bug 复现步骤如下
1. docker-compose down
2. docker-compose up -d

**期望结果**
只保留最初的两个节点

**截屏**
![image](https://user-images.githubusercontent.com/51523658/80444994-c3443f80-8945-11ea-957a-ab0a0fb5c374.png)

**Comment by hantmac** [comment]
容器的ip是虚拟ip，每次重启都会变化的，这个不太好避免，只能手动删除重复的节点

azhu949 <notifications@github.com> 于2020年4月28日周二 上午11:49写道：

**Comment by azhu949** [comment]
![image](https://user-images.githubusercontent.com/51523658/80453196-5dae7e00-895a-11ea-89e5-b1d98a9ce5aa.png)
我也想删啊，但是不让我删的嘛！有四个的时候不能删，有六个的时候能删两个。。。

**Comment by hantmac** [comment]
只能删除离线的吧

**Comment by azhu949** [comment]
没看到按钮让节点离线

**Comment by azhu949** [comment]
同时删除redis和mgdb的node数据后解决，但是体验不太好！
