### ISSUE TITLE
关于用户之间py运行环境的隔离

### ISSUE THREAD

**Issue by DarcyOly** [crawlab-team/crawlab#717]
**请描述该需求尝试解决的问题**
测试了一下，用户之间的python环境不是隔离的
1、意味着部分爬虫之间包冲突可能导致部分爬虫失去运行能力；
2、有些老的爬虫仍然使用python2，没法直接移植；
3、部分爬虫用到了psutil包，但框架本身每次发布任务会重置psutil的版本，降级到1.2.1,导致这部分爬虫失效。

**请描述您认为可行的解决方案**
是否可以考虑集成virtualenv，任务发布中自行选择虚拟环境path，启动对应的py环境来安装所需环境与执行任务

**Comment by tikazyq** [comment]
可以实现，目前需要自定义，可以在docker内部生成虚拟环境，运行爬虫的时候指定路径就可以了

**Comment by DarcyOly** [comment]
有SDK来创建么？还是说要自己进容器来创建？

**Comment by tikazyq** [comment]
> 有SDK来创建么？还是说要自己进容器来创建？

SDK暂时不支持您的需求，您需要进入容器自己来操作

**Comment by DarcyOly** [comment]
非常感谢，做了个脚本一次性解决，脚本作为一个爬虫项目并作为public，这样就能根据用户自己的需求，自己创建环境并自动安装依赖。
不过由于是sh，会出现source环境失败。即使bash; source XXX也不行，请问有办法么？

**Comment by tikazyq** [comment]
> 非常感谢，做了个脚本一次性解决，脚本作为一个爬虫项目并作为public，这样就能根据用户自己的需求，自己创建环境并自动安装依赖。
> 不过由于是sh，会出现source环境失败。即使bash; source XXX也不行，请问有办法么？
> 
> ps. 最后通过 /bin/bash -c "source XXX ..." 的方法启动了，不过好麻烦，不知道能不能有简单点的办法？

最好的办法是指定virtualenv的python路径，不要用`source`或者`activate`，这是最简单的了

**Comment by DarcyOly** [comment]
噢噢，确实如此。不过考虑到我这边是mrq起的分布式，context会取好几个py环境变量。。。。我还是老老实实source吧。
非常感谢了
