### ISSUE TITLE
设置页面点击“允许发送统计信息”后，sendEv函数中的window._hmt.push报错

### ISSUE THREAD

**Issue by WangDeTao** [crawlab-team/crawlab#718]
**Bug 描述**
设置页面点击“允许发送统计信息”后，sendEv函数中的window._hmt为undefined，此时window._hmt.push报错。

**复现步骤**
该 Bug 复现步骤如下
1. 初始登录，点击设置页面，点击允许发送统计信息按钮
2. 点击项目-添加项目按钮

**期望结果**
判断为undefined时=[]。

**截屏**
![image](https://user-images.githubusercontent.com/19422300/81143878-7b589480-8fa5-11ea-9e3c-19fc85b8a16d.png)
![image](https://user-images.githubusercontent.com/19422300/81143897-89a6b080-8fa5-11ea-8c70-e35bb43e7045.png)

**Comment by tikazyq** [comment]
估计是内网环境，无法访问百度统计下载sdk导致的，建议关闭发送统计
