### ISSUE TITLE
auth问题导致了非日志页面会不停的报错，报错内容为not found

### ISSUE THREAD

**Issue by DarcyOly** [crawlab-team/crawlab#719]
**Bug 描述**
进行长任务（通过redis做了分布式，爬虫master长期等待任务，不会集成result到平台，直接入库），期间如果离开滚动日志页面的话（日志页面正常），譬如回到爬虫页面，由于爬虫处于运行中，api在不断获取任务的执行状态，出现not found的弹窗报错，而且不停的报错，log日志显示是auth问题，麻烦作者看一下，谢谢，日志放在评论区了。

**复现步骤**
该 Bug 复现步骤如下
1. 通过bash -c 执行虚拟环境激活等操作，启动爬虫
2. 离开日志页面
3. 出现not found不间断的报错

**Comment by DarcyOly** [comment]
master    | created by net/http.(*Server).Serve
master    | 	/usr/local/go/src/net/http/server.go:2884 +0x2f4
master    | goroutine 462845 [running]:
master    | runtime/debug.Stack(0x0, 0x0, 0x0)
master    | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
master    | runtime/debug.PrintStack()
master    | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
master    | crawlab/model.GetTask(0xc00044227b, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
master    | 	/go/src/app/model/task.go:196 +0x2cb
master    | crawlab/routes.GetTask(0xc0004440b0)
master    | 	/go/src/app/routes/task.go:87 +0xaa
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0004440b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | crawlab/middlewares.AuthorizationMiddleware.func1(0xc0004440b0)
master    | 	/go/src/app/middlewares/auth.go:46 +0x200
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0004440b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | crawlab/middlewares.CORSMiddleware.func1(0xc0004440b0)
master    | 	/go/src/app/middlewares/cors.go:17 +0x3d3
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0004440b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc0004440b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/recovery.go:83 +0x5a
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0004440b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0004440b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/logger.go:240 +0xe1
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0004440b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00033a000, 0xc0004440b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 +0x5b2
master    | github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00033a000, 0x1190420, 0xc00057e1c0, 0xc0001ecf00)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 +0x134
master    | net/http.serverHandler.ServeHTTP(0xc0004e31e0, 0x1190420, 0xc00057e1c0, 0xc0001ecf00)
master    | 	/usr/local/go/src/net/http/server.go:2774 +0xa8
master    | net/http.(*conn).serve(0xc000641040, 0x11941e0, 0xc0009a0780)
master    | 	/usr/local/go/src/net/http/server.go:1878 +0x851
master    | created by net/http.(*Server).Serve
master    | 	/usr/local/go/src/net/http/server.go:2884 +0x2f4
master    | goroutine 462847 [running]:
master    | runtime/debug.Stack(0x0, 0x0, 0x0)
master    | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
master    | runtime/debug.PrintStack()
master    | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
master    | crawlab/model.GetTask(0xc0005f654b, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
master    | 	/go/src/app/model/task.go:196 +0x2cb
master    | crawlab/services.GetTaskLog(0xc0005f654b, 0x18, 0xc0005f6568, 0x0, 0x1, 0x1388, 0x18, 0xc003726b01, 0x30, 0x30, ...)
master    | 	/go/src/app/services/task.go:704 +0x50
master    | crawlab/routes.GetTaskLog(0xc0005420b0)
master    | 	/go/src/app/routes/task.go:248 +0x128
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0005420b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | crawlab/middlewares.AuthorizationMiddleware.func1(0xc0005420b0)
master    | 	/go/src/app/middlewares/auth.go:46 +0x200
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0005420b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | crawlab/middlewares.CORSMiddleware.func1(0xc0005420b0)
master    | 	/go/src/app/middlewares/cors.go:17 +0x3d3
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0005420b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc0005420b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/recovery.go:83 +0x5a
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0005420b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0005420b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/logger.go:240 +0xe1
master    | github.com/gin-gonic/gin.(*Context).Next(0xc0005420b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00033a000, 0xc0005420b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 +0x5b2
master    | github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00033a000, 0x1190420, 0xc0000b6000, 0xc003c8e400)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 +0x134
master    | net/http.serverHandler.ServeHTTP(0xc0004e31e0, 0x1190420, 0xc0000b6000, 0xc003c8e400)
master    | 	/usr/local/go/src/net/http/server.go:2774 +0xa8
master    | net/http.(*conn).serve(0xc000641400, 0x11941e0, 0xc0005ea280)
master    | 	/usr/local/go/src/net/http/server.go:1878 +0x851
master    | created by net/http.(*Server).Serve
master    | 	/usr/local/go/src/net/http/server.go:2884 +0x2f4
master    | [GIN] 2020/05/07 - 01:29:17 | 200 |    11.52329ms |       127.0.0.1 | GET      /spiders/5eb23fd923ba58001f3ff4f8/tasks
master    | 2020/05/07 01:29:19  info get task error: not found, id: 5eb23fd923ba58001f3ff4f8
master    | 2020/05/07 01:29:19  info get task error: not found, id: 5eb23fd923ba58001f3ff4f8
master    | 2020/05/07 01:29:19  info get task error: not found, id: 5eb23fd923ba58001f3ff4f8
master    | goroutine 463052 [running]:
master    | runtime/debug.Stack(0x0, 0x0, 0x0)
master    | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
master    | runtime/debug.PrintStack()
master    | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
master    | [GIN] 2020/05/07 - 01:29:19 | 500 |    3.299276ms |       127.0.0.1 | GET      /tasks/5eb23fd923ba58001f3ff4f8/results?page_num=1&page_size=10
master    | crawlab/model.GetTask(0xc00046e00b, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
master    | 	/go/src/app/model/task.go:196 +0x2cb
master    | crawlab/routes.GetTaskResults(0xc003ed60b0)
master    | 	/go/src/app/routes/task.go:287 +0x119
master    | github.com/gin-gonic/gin.(*Context).Next(0xc003ed60b0)
master    | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a
master    | crawlab/middlewares.AuthorizationMiddleware.func1(0xc003ed60b0)
master    | [GIN] 2020/05/07 - 01:29:19 | 500 |    3.464388ms |       127.0.0.1 | GET      /tasks/5eb23fd923ba58001f3ff4f8
master    | [GIN] 2020/05/07 - 01:29:19 | 500 |    3.539297ms |       127.0.0.1 | GET      /tasks/5eb23fd923ba58001f3ff4f8/log?keyword=&page_num=1&page_size=5000

**Comment by tikazyq** [comment]
感觉是前端问题，传入 `task_id` 为 `undefined`

**Comment by DarcyOly** [comment]
请问我要怎么解决呢？我试过重新登录，刷新auth，f12看见调用的api路径上tasks确实是undefined，但post参数中是有正确的task_id的，是不是页面渲染出的访问接口拼接有问题？特别是对功能性的无结果爬虫
