### ISSUE TITLE
文件总是异常删除

### ISSUE THREAD

**Issue by kaich** [crawlab-team/crawlab#739]
**Bug 描述**
上传爬虫文件，刷新页面之后文件不存在。

**复现步骤**
添加爬虫的的三类情况：
该 Bug 复现步骤如下
1. 先把名字之类的填写好，然后上传爬虫zip包。爬虫运行之后一直存在。
2. 先上传zip包，再填写名字等，运行之后爬虫文件就被删除了。
3. 只填写名字等信息，不上传zip包，点击保存。再在详情中上传zip包，点击运行，爬虫文件不存在。

**期望结果**
上传的文件能正常存在

**Comment by tikazyq** [comment]
用 CLI 工具能否上传成功？

**Comment by kaich** [comment]
@tikazyq 这个我没有试

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
