### ISSUE TITLE
ValueError: Missing scheme in request url: get_real_url

### ISSUE THREAD

**Issue by fofocx** [crawlab-team/crawlab#740]
**Bug 描述**
使用可配置爬虫，一个抓取页面内容是单独页面不设置列表内容，在找到的链接后面使用下一个阶段，运行时会报错 ValueError: Missing scheme in request url: get_real_url。
原因是在文件中找到scrapy.py，这条代码中的scrapy.Request调用时，url需要获取get_real_url解析过的真实地址，然而此处的函数却被双引号包住导致url传参变成了"get_real_url(response, item[xxx])"，Request不能识别这个地址
暂时通过勾选列表，用xpath 的//body或/html这样肯定不会出现第二个的绕过了
version: 0.4.10 docker镜像

**复现步骤**
该 Bug 复现步骤如下
1. 进入可配置爬虫配置页面
2. 阶段添加一个非列表页面，清除列表选择框
3. 在链接属性后面配置下一阶段

**期望结果**
下一阶段能工作。get_real_url函数不要被双引号包住。

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
