### ISSUE TITLE
请问接口 swagger 的地址是不是崩了

### ISSUE THREAD

**Issue by haimang** [crawlab-team/crawlab#742]
请问接口 swagger 的地址是不是崩了。

502 Bad Gateway

**Comment by hantmac** [comment]
@haimang  不是，swagger 功能目前官网还没上线，可以在 develop 分支查看

**Comment by haimang** [comment]
哦哦，那请问，哪里有 API 的独立文档么？

**Comment by hantmac** [comment]
> 哦哦，那请问，哪里有 API 的独立文档么？

https://docs.crawlab.cn/zh/Api/
