### ISSUE TITLE
本机搭建worker节点时，redis的nodes没有hostname字段

### ISSUE THREAD

**Issue by fengci** [crawlab-team/crawlab#746]
**Bug 描述**
在使用docker-compose搭建环境的时候，远程启用了master节点，
然后本地使用了worker节点 。master节点能看到子节点。但是获取不到语言安装
查看了redis的nodes数据发现本地worker节点没有hostname

![image](https://user-images.githubusercontent.com/13860628/82830180-9bfe7500-9ee7-11ea-8520-80222fb1ab26.png)

**Comment by tikazyq** [comment]
worker用的是哪种注册方式？

**Comment by fengci** [comment]
> worker用的是哪种注册方式？

默认的应该是 mac

**Comment by tikazyq** [comment]
> > worker用的是哪种注册方式？
> 
> 默认的应该是 mac

后台有报错么

**Comment by fengci** [comment]
> > > worker用的是哪种注册方式？
> > 
> > 
> > 默认的应该是 mac
> 
> 后台有报错么

mater 有 rpc报错
![image](https://user-images.githubusercontent.com/13860628/82851757-67180f80-9f33-11ea-8d2d-31ec99a3e53a.png)

**Comment by fengci** [comment]
我worker 和 master 不在同一个网络中，但是我是共用一份 redis 和 mongodb 的。

**Comment by fengci** [comment]
最后通过自己打包dockerfile正常了。不清楚什么问题。不晓得是不是电脑抽风了。
