### ISSUE TITLE
爬取的结果数据可保存在mysql中吗

### ISSUE THREAD

**Issue by jonahzheng** [crawlab-team/crawlab#754]
**请描述该需求尝试解决的问题**
因为全文检索的系统的数据库是用mysql，所以想爬取的数据能直接到mysql中，这样就不需要再从mongodb导到mysql了

**请描述您认为可行的解决方案**
增加统一的数据库配置接口

**考虑过的替代方案**
例如，如果用 xxx，也能解决该问题。

**Comment by tikazyq** [comment]
Crawlab Pro（专业版）已经开发了这个功能，请关注后续发布



在 2020-06-01 15:58:37，"jonah zheng" <notifications@github.com> 写道：

请描述该需求尝试解决的问题
例如，当 xxx 时，我总是被当前 xxx 的设计所困扰。
因为全文检索的系统的数据库是用mysql，所以想爬取的数据能直接到mysql中，这样就不需要再从mongodb导到mysql了

请描述您认为可行的解决方案
例如，添加 xxx 功能能够解决问题。
增加统一的数据库配置接口

考虑过的替代方案
例如，如果用 xxx，也能解决该问题。

**Comment by jonahzheng** [comment]
多谢多谢
