### ISSUE TITLE
定时任务不支持 字符形式定时创建, 比如: L

### ISSUE THREAD

**Issue by wenzidance** [crawlab-team/crawlab#758]
错误内容: 
![image](https://user-images.githubusercontent.com/38269722/83529686-41839b00-a51d-11ea-9147-e4a27b596385.png)
规则:

**Comment by wenzidance** [comment]
![image](https://user-images.githubusercontent.com/38269722/83529808-7263d000-a51d-11ea-9b25-02f310d631ab.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
