### ISSUE TITLE
node爬虫配置问题

### ISSUE THREAD

**Issue by Tang-1** [crawlab-team/crawlab#760]
**Bug 描述**
上传的nodejs爬虫没有node_modules文件夹，手动npm install后会在当前目录安装好环境并生成node_modules文件夹。但过一段时间这个文件夹会被清理掉，导致nodejs爬虫无法运行

**复现步骤**
该 Bug 复现步骤如下
1. 上传一个nodejs爬虫（但不上传node_modules文件夹）
2. 爬虫目录下执行npm install
3. 等待一会，node_modules文件会被删除

**期望结果**
nodejs爬虫很多时候是项目内有单独的环境。
希望可以在运行前自动执行npm install 并保证node_modules文件夹不会被清理

**Comment by tikazyq** [comment]
用全局安装，可以尝试[自动安装依赖](https://docs.crawlab.cn/zh/Spider/AutoInstallDeps.html)

**Comment by yaziming** [comment]
全局安装或者使用打包工具 [ncc](https://github.com/vercel/ncc) or [pkg](https://github.com/vercel/pkg)

**Comment by Tang-1** [comment]
感谢   我试试
