### ISSUE TITLE
添加scrapy爬虫 点击运行 无法选择爬虫显示No data

### ISSUE THREAD

**Issue by MambaInVeins** [crawlab-team/crawlab#761]
我用cli将包含scrapy.cfg的根目录crawlab upload 但到web界面尝试运行 无法选择爬虫 显示No data，怎么处理，求助！

**Comment by tikazyq** [comment]
需要安装依赖

**Comment by StudyExchange** [comment]
我昨天和今天也是遇到类似的问题，scrapy爬虫无法正常使用。zip文件上传之后，过会儿文件就全没了，显示no data。十次发布爬虫的操作，能成功发布一个可用的爬虫。

**Comment by tikazyq** [comment]
试一下用 CLI 操作

**Comment by MambaInVeins** [comment]
想问一下 爬虫上传到哪个目录下了 我使用的是cli操作

**Comment by MambaInVeins** [comment]
依赖安装有参考文档吗？

**Comment by tikazyq** [comment]
https://docs.crawlab.cn/zh/SDK/CLI.html

**Comment by StudyExchange** [comment]
希望优先修一下可视化的网页操作界面吧！

**Comment by StudyExchange** [comment]
在如此高频使用的场景，为什么会有这么直接的BUG呢？

**Comment by tikazyq** [comment]
> 我昨天和今天也是遇到类似的问题，scrapy爬虫无法正常使用。zip文件上传之后，过会儿文件就全没了，显示no data。十次发布爬虫的操作，能成功发布一个可用的爬虫。

针对这个问题已经新开 bug issue https://github.com/crawlab-team/crawlab/issues/775 ，请关注后续修复情况

**Comment by nqzhang** [comment]
这bug.......  触目惊心...
