### ISSUE TITLE
可配置爬虫，在界面上对进行修改，提示保存成功，然而并没有

### ISSUE THREAD

**Issue by sniperyen** [crawlab-team/crawlab#765]
**请描述该需求尝试解决的问题**
当我修改可配置爬虫的代码时候，提示保存成功，但我运行的时候发现并没有生效；查看代码时候，发现我的修改被覆盖掉了。

**请描述您认为可行的解决方案**
可配置爬虫的代码可以被修改，但这时候类型应该转换为自定义爬虫。
给用户一个是否继续的提示，而不是傻乎乎的修改后，却没有生效。

**Comment by tikazyq** [comment]
可配置爬虫不能直接更改，如果需要更改代码，需要转换为自定义爬虫之后才能更改
