### ISSUE TITLE
可配置爬虫，启动报错  error create file error: open /app/spiders/baidu/md5.txt

### ISSUE THREAD

**Issue by sniperyen** [crawlab-team/crawlab#770]
**Bug 描述**
用百度那个模板，创建了一个可配置爬虫，什么都没改，启动时候报如下错误
`
crawlab-worker | 2020/06/04 02:14:00  info start sync spider to local, total: 4
crawlab-worker | 2020/06/04 02:15:00  info start sync spider to local, total: 3
crawlab-worker | 2020/06/04 02:15:20 error create file error: open /app/spiders/baidu/md5.txt: no such file or directory, file_name: /app/spiders/baidu/md5.txt
crawlab-worker | goroutine 1609 [running]:
crawlab-worker | runtime/debug.Stack(0x0, 0x0, 0x0)
crawlab-worker | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
crawlab-worker | runtime/debug.PrintStack()
crawlab-worker | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
crawlab-worker | crawlab/utils.OpenFile(0xc000623380, 0x1a, 0xc00070f628)
crawlab-worker | 	/go/src/app/utils/file.go:51 +0x145
crawlab-worker | crawlab/utils.ReadFileOneLine(0xc000623380, 0x1a, 0x0, 0x0)
crawlab-worker | 	/go/src/app/utils/file.go:27 +0x5b
crawlab-worker | crawlab/utils.GetSpiderMd5Str(0xc000623380, 0x1a, 0x2, 0xc000623380)
crawlab-worker | 	/go/src/app/utils/file.go:39 +0x39
crawlab-worker | crawlab/services.SpiderFileCheck(0xc000038510, 0x24, 0xc000451310, 0xc, 0xbfae180e00990073, 0x23404e7029, 0x18dd4e0, 0x0, 0x0, 0x0, ...)
crawlab-worker | 	/go/src/app/services/task.go:695 +0x412
crawlab-worker | crawlab/services.ExecuteTask(0x1)
crawlab-worker | 	/go/src/app/services/task.go:577 +0xce1
crawlab-worker | crawlab/services.GetExecuteTaskFunc.func1()
crawlab-worker | 	/go/src/app/services/task.go:429 +0x2a
crawlab-worker | crawlab/lib/cron.FuncJob.Run(0xc00046e280)
crawlab-worker | 	/go/src/app/lib/cron/cron.go:131 +0x25
crawlab-worker | crawlab/lib/cron.(*Cron).startJob.func1(0xc0004b20a0, 0x117a7c0, 0xc00046e280)
crawlab-worker | 	/go/src/app/lib/cron/cron.go:307 +0x5f
crawlab-worker | created by crawlab/lib/cron.(*Cron).startJob
crawlab-worker | 	/go/src/app/lib/cron/cron.go:305 +0x73
crawlab-worker | 2020/06/04 02:15:20 error read file error: invalid argument
crawlab-worker | 2020/06/04 02:15:20  info [Worker 1] start task (id:568bde1e-4e87-40d0-a257-ca2d0003f028)
crawlab-worker | 2020/06/04 02:15:20  info cwd: /app/spiders/baidu
crawlab-worker | 2020/06/04 02:15:20  info cmd: scrapy crawl config_spider
crawlab-worker | 2020/06/04 02:15:20 error wait process finish error: exit status 1
crawlab-worker | goroutine 1609 [running]:
crawlab-worker | runtime/debug.Stack(0x0, 0x0, 0x0)
crawlab-worker | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
crawlab-worker | runtime/debug.PrintStack()
crawlab-worker | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
crawlab-worker | crawlab/services.WaitTaskProcess(0xc0001162c0, 0xc000038510, 0x24, 0xc000451310, 0xc, 0xbfae180e00990073, 0x23404e7029, 0x18dd4e0, 0x0, 0x0, ...)
crawlab-worker | 	/go/src/app/services/task.go:311 +0x15c
crawlab-worker | crawlab/services.ExecuteShellCmd(0xff009b, 0x1a, 0xc000646e20, 0x12, 0xc000038510, 0x24, 0xc000451310, 0xc, 0xbfae180e00990073, 0x23404e7029, ...)
crawlab-worker | 	/go/src/app/services/task.go:390 +0xb25
crawlab-worker | crawlab/services.ExecuteTask(0x1)
crawlab-worker | 	/go/src/app/services/task.go:611 +0x11ec
crawlab-worker | crawlab/services.GetExecuteTaskFunc.func1()
crawlab-worker | 	/go/src/app/services/task.go:429 +0x2a
crawlab-worker | crawlab/lib/cron.FuncJob.Run(0xc00046e280)
crawlab-worker | 	/go/src/app/lib/cron/cron.go:131 +0x25
crawlab-worker | crawlab/lib/cron.(*Cron).startJob.func1(0xc0004b20a0, 0x117a7c0, 0xc00046e280)
crawlab-worker | 	/go/src/app/lib/cron/cron.go:307 +0x5f
crawlab-worker | created by crawlab/lib/cron.(*Cron).startJob
crawlab-worker | 	/go/src/app/lib/cron/cron.go:305 +0x73
crawlab-worker | 2020/06/04 02:15:20 error exit error, exit code: 1
crawlab-worker | 2020/06/04 02:15:20 error [Worker 1] exit status 1
`

**Comment by tikazyq** [comment]
似乎是工作节点同步出了问题

**Comment by tikazyq** [comment]
如何配置的？

**Comment by sniperyen** [comment]
删除又重建了下，问题没有了。
