### ISSUE TITLE
当项目在linux服务器上启动以后，无法在远端打开前端。机器能ping通，没有问题

### ISSUE THREAD

**Issue by OnePunchMann** [crawlab-team/crawlab#771]
**Bug 描述**
例如，当 xxx 时，xxx 功能不工作。

**复现步骤**
该 Bug 复现步骤如下
1. 
2. 
3. 

**期望结果**
xxx 能工作。

**截屏**
![截屏1](http://static-docs.crawlab.cn/login.png)

**Comment by tikazyq** [comment]
请描述一下复现步骤，并去掉敏感信息之后发一下配置
