### ISSUE TITLE
修改ssh私钥的命名

### ISSUE THREAD

**Issue by Kelvin945** [crawlab-team/crawlab#774]
**请描述该需求尝试解决的问题**
启动crawlab时会默认创建ssh 私钥，如果用户已有同名私钥则会请求覆盖私钥。

**请描述您认为可行的解决方案**
由于是初次使用，不知道生成的私钥会用在什么功能。
是否可以生成如id_rsa_crawlab的文件名然后用ssh config文件进行管理？

**Comment by tikazyq** [comment]
好主意，我们后续优化下，这是用来同步git的




| |
张冶青 Yeqing Zhang
邮箱：tikazyq@163.com
|

签名由 网易邮箱大师 定制

在2020年06月04日 18:28，Kelvin 写道：

请描述该需求尝试解决的问题
启动crawlab时会默认创建ssh 私钥，如果用户已有同名私钥则会请求覆盖私钥。

请描述您认为可行的解决方案
由于是初次使用，不知道生成的私钥会用在什么功能。
是否可以生成如id_rsa_crawlab的文件名然后用ssh config文件进行管理？
