### ISSUE TITLE
【需求汇总】请大家在这个 Issue 中提优化反馈

### ISSUE THREAD

**Issue by tikazyq** [crawlab-team/crawlab#776]

**Comment by chenjiawei514** [comment]
关于爬虫的上传部署，不知道能不能增加git等方式的代码上传，这样每次重启能自动拉取最新代码去跑

**Comment by tikazyq** [comment]
请参考这个文档 https://docs.crawlab.cn/zh/CI/Git.html

**Comment by selerisjava** [comment]
爬虫详情的scrapy配置，能不能支持读取多种配置文件。我看了下源码，目前只读取了default配置。default一般为本地配置，放服务器上面老是解析报错。

**Comment by selerisjava** [comment]
![image](https://user-images.githubusercontent.com/20785332/86078188-20807c80-bac0-11ea-8640-12374a148b2a.png)
![image](https://user-images.githubusercontent.com/20785332/86078216-30985c00-bac0-11ea-9c3b-2d6d703b51aa.png)
访问scrapy配置页面总是有这种错误，但是爬虫可以正常运行。

**Comment by selerisjava** [comment]
git里面不能切换分支，选择其他分支后，仍然自动切换到master。这种问题怎么解决呢

**Comment by selerisjava** [comment]
git使用ssh拉取代码，出现以下错误 first path segment in URL cannot contain colon

**Comment by tikazyq** [comment]
@selerisjava 可以在新开的issue里详细描述一下

**Comment by larryliao** [comment]
从git下拉代码能只指定一个目录吗？有很多爬虫代码不多，几十个爬虫就有几十个git库，配置起来有点烦

**Comment by tikazyq** [comment]
> 从git下拉代码能只指定一个目录吗？有很多爬虫代码不多，几十个爬虫就有几十个git库，配置起来有点烦

不好意思，暂时不支持，您可以考虑配合 CLI 工具来上传爬虫代码

**Comment by charm-v** [comment]
![image](https://user-images.githubusercontent.com/16677106/89619238-3738a100-d8c0-11ea-88e3-21b9049a0a7b.png)

报错，打开链接显示
{"status":"ok","message":"unauthorized","data":null,"error":"unauthorized"}

爬虫代码是通过cli方式上传的
服务器运行scrapy crawl spider_name正常

**Comment by diaozhegenyan** [comment]
![image](https://user-images.githubusercontent.com/67667794/89721482-8f7eb880-da10-11ea-9290-e08b3e6e06d5.png)
初始化node失败 是什么原因啊？   配置那改ip也不行。

**Comment by tikazyq** [comment]
> 始化node失败 是什么原因啊？ 配置那改ip也不行。

怎么配置的？看起来像配置问题

**Comment by diaozhegenyan** [comment]
不清楚呢，重新弄了  现在可以了。

**Comment by zhuangdx** [comment]
Failed to launch the browser process
![image](https://user-images.githubusercontent.com/16098983/91146516-92a0c680-e6e9-11ea-9a6e-6393f899cab8.png)

**Comment by tikazyq** [comment]
> Failed to launch the browser process
> ![image](https://user-images.githubusercontent.com/16098983/91146516-92a0c680-e6e9-11ea-9a6e-6393f899cab8.png)

估计是没有安装相应的库导致的，可以搜索一下“ubuntu puppeteer docker"

**Comment by stone0311** [comment]
scrapy项目上传，爬虫解压的逻辑
在后台创建文件的目录树：
└── test2
    ├── md5.txt
    ├── scrapy.cfg
    └── test2
        ├── __init__.py
        ├── __pycache__
        │   ├── __init__.cpython-38.pyc
        │   └── settings.cpython-38.pyc
        ├── items.py
        ├── middlewares.py
        ├── pipelines.py
        ├── settings.py
        └── spiders
上传文件自动解压的目录树：
└── test_spider
    ├── md5.txt
    └── test_spider
        ├── scrapy.cfg
        └── test_spider
            ├── __init__.py
            ├── __pycache__
            ├── items.py
            ├── middlewares.py
            ├── pipelines.py
            ├── settings.py
            └── spiders
多创建了一层文件夹

**Comment by tikazyq** [comment]
> scrapy项目上传，爬虫解压的逻辑
> 正常在本地打包项目，如果进入项目中进行压缩感觉有些反人类的操作
> 在后台创建文件的目录树：
> 
> ```shell
> └── test2
>     ├── md5.txt
>     ├── scrapy.cfg
>     └── test2
>         ├── __init__.py
>         ├── __pycache__
>         │   ├── __init__.cpython-38.pyc
>         │   └── settings.cpython-38.pyc
>         ├── items.py
>         ├── middlewares.py
>         ├── pipelines.py
>         ├── settings.py
>         └── spiders
> ```
> 
> ```shell
> 上传文件自动解压的目录树：
> └── test_spider
>     ├──  md5.txt
>     └──  test_spider
>         ├──  scrapy.cfg
>         └── test_spider
>             ├── __init__.py
>             ├── __pycache__
>             ├── items.py
>             ├── middlewares.py
>             ├── pipelines.py
>             ├── settings.py
>             └── spiders
> ```
> 
> 多创建了一层文件夹

请关注这个 issue https://github.com/crawlab-team/crawlab/issues/836

**Comment by nieweiming** [comment]
我发现依赖库安装不能指定版本，然后就是pip源没换国内的。

**Comment by LBatsoft** [comment]
建议添加日志下载功能

**Comment by seekerliu** [comment]
优化建议
1、建议消息通知方式增加自定义回调接口

**Comment by seekerliu** [comment]
优化建议：
1、建议消息通知增加自定义的Webhook地址，目前系统中只能在每个爬虫里面都设置一遍webhook地址

**Comment by vegaviazhang** [comment]
请问一下开发大佬，在使用selenium时候如何配置驱动的路径executable_path呢？

**Comment by CL545740896** [comment]
建议增加请求等待的Loading 效果

**Comment by CL545740896** [comment]
页面打开CPU 占用率很高,经常会发生卡死界面,需要优化

**Comment by CL545740896** [comment]
获取请求返回的数据 经常也会出现报错

**Comment by eheh-org** [comment]
1. 同一个爬虫，创建多个参数不同爬虫任务，期望这些爬虫任务可以简单分组。

**Comment by KevinLiou** [comment]
請問docker images可以支援ARM CPU版本嗎

**Comment by kasheemlew** [comment]
修改用户密码后，已使用这个账号登录的用户不需要重新登录，仍然可以继续正常操作。建议对修改密码后的账号重新验证

**Comment by BuGoNee** [comment]
我需要将自己封装的一个包添加到crawlab依赖里面。
比如items会被若干个不同scrapy project用到，所以抽象成为一个ours_common库里面，且具体project里面会import到

**Comment by gaygayboy** [comment]
今天crawlab突然就一直502，也不知道什么原因

**Comment by nieweiming** [comment]
任务假活状态有待优化 +1

**Comment by 0utman1** [comment]
请问自动提取功能新版有集成吗？爬取大量类似网站需要这个

**Comment by kuangcaibao** [comment]
同一个Spider中配置多个任务（通过参数区分），在多 runner 情形下，经常会报文件缺失错误。设置为1个runner则不报错。
![image](https://user-images.githubusercontent.com/4852014/130548722-efc051e6-fb76-4517-af11-26a1c5e56a0a.png)
![image](https://user-images.githubusercontent.com/4852014/130548967-d28b5615-92f8-43bd-a40b-367df35d8244.png)
![image](https://user-images.githubusercontent.com/4852014/130548809-a962ea64-0658-4e4c-b6d4-b7885d7f9941.png)
![image](https://user-images.githubusercontent.com/4852014/130548861-363ae980-a285-404b-a90f-fdf69e73b11a.png)

**Comment by motingjun** [comment]
爬虫任务起来后，开任务日志一直卡着是什么原因？
![image](https://user-images.githubusercontent.com/43468078/131211882-4479289b-e14a-4744-a5a2-88718b8841f8.png)

**Comment by lordqyxz** [comment]
1.  建议增加服务器分组功能，可以快速将应用部署到特定集群。
2.  建议增加对应用，节点的资源占用情况的简单统计功能。
- 在服务器配置不一致的情况下，提高服务器利用率。

**Comment by CrazyMouse** [comment]
> 在使用docker容器安装部署crawlab中，建议docker容器增加挂载目录，否则下载文件时需要使用docker cp 将下载到容器中的文件拷贝到宿主机，很麻烦。

这个属于docker 自身的属性吧，配置一下volumn映射就可以了

**Comment by QingYu2017** [comment]
是否可以提供数据**导出**/**迁移**/**备份**功能？比如文件方式导出**Spider**/**Task**/**Schedule**，谢谢

**Comment by Cccold** [comment]
> 請問docker image可以支援ARM CPU版本嗎

联系我吧我有自己打包的镜像

**Comment by haoweicrushu** [comment]
> > 請問docker image可以支援ARM CPU版本嗎
> 
> 联系我吧我有自己打包的镜像

请问您怎麽打包的，我打包完都会出错误 能跟您要个示例吗

**Comment by jjzhoujun** [comment]
建议scrapy项目能够结合scrapyd服务（或做成插件可以选择性添加），提供一键打包发布及爬虫间的REST接口调用

**Comment by castle-boom** [comment]
建议自动为每个爬虫的结果collection构建task_id 的索引

**Comment by JunBa0** [comment]
v0.6 爬虫文件如何迁移到其他服务器并正确运行？需要同时使用同一个MongoDB？

**Comment by Yanbuc** [comment]
* 1: olap 不完善，例如：删除项目，但是项目下爬虫不删除。
* 2: 前端显示 爬虫列表，看了下 大概的逻辑是 查询所有的爬虫 查询所有的项目，然后前端做数据匹配，把爬虫的项目Id 和 项目的名字对应上

**Comment by Cccold** [comment]
> > > 請問docker image可以支援ARM CPU版本嗎
> > 
> > 
> > 联系我吧我有自己打包的镜像
> 
> 请问您怎麽打包的，我打包完都会出错误 能跟您要个示例吗
menghan426@gmail.com联系我吧，0.6版本最近我也整出来了，想给官方提pr，不会提～

**Comment by stormsha** [comment]
优化建议：指定部分节点根据负载随机派发任务功能

当我有多个项目运行环境不同，完全没必要把所有节点都部署为相同的环境，可以根据不同项目需求创建相应的节点与节点数量，相当于项目分组管理，这样更利于多项目管理。
指定部分节点根据负载随机派发任务功能在此情境下就很有必要，期待作者能安排上线

**Comment by ruanshengbin** [comment]
> > > > 請問docker image可以支援ARM CPU版本嗎
> > > 
> > > 
> > > 联系我吧我有自己打包的镜像
> > 
> > 
> > 请问您怎麽打包的，我打包完都会出错误 能跟您要个示例吗
> > [menghan426@gmail.com](mailto:menghan426@gmail.com)联系我吧，0.6版本最近我也整出来了，想给官方提pr，不会提～
主要是编译go编写的backend工程
1、go安装包下载：选择适合的版本
https://go.dev/dl/
2、go基础环境配置：修改“/etc/bashrc”文件添加
export GOROOT=/iflytek/soft/go1.15.6
export GOPATH=/iflytek/soft/gopath
export PATH==$PATH:$GOPATH/bin:$GOROOT/bin
export GOPROXY=https://mirrors.aliyun.com/goproxy/
3、 编译生成可执行文件：需要联网编译（要拉去工程依赖库，GOPATH对应的目录会生成一些编译过程的依赖库），进入crawlab的backend执行命令，-o为编译后的文件名
CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o crawlab main.go

**Comment by TDxhfeng** [comment]
![image](https://github.com/crawlab-team/crawlab/assets/64594937/bfaab860-5eaf-409f-894a-9a0bf998f031)
如何实现？
