### ISSUE TITLE
go isntall 安装失败

### ISSUE THREAD

**Issue by zzk1314** [crawlab-team/crawlab#779]
**Bug 描述**
按照”直接部署“这个文档进行部署。
在执行到后端部署时出现问题。

**复现步骤**
该 Bug 复现步骤如下
1. GOPATH目录为 /data/deploy/go
2. 将backend目录移动到 /data/deploy/go/src 并改名为crawlab
3. 在/data/deploy/go/src/crawlab执行 go install ./...
4. 报错
# crawlab/database
database/redis.go:194:12: undefined: strings.ReplaceAll

**期望结果**
go install 安装完成

**Comment by tikazyq** [comment]
```bash
git clone https://github.com/crawlab-team/crawlab
cd crawlab/backend
go install ./...
```
