### ISSUE TITLE
系统运行几天就登录不进去，定时任务也无法运行

### ISSUE THREAD

**Issue by orienthong** [crawlab-team/crawlab#782]
**Bug 描述**
系统刚开始运行正常，有多个定时任务，但是过了几天，定时任务就无法运行，并且系统管理员后台可以打开，但是登录不进去，显示**[401] Incorrect username or password**

**Comment by tikazyq** [comment]
后台日志发一下

**Comment by hantmac** [comment]
怀疑是 mongodb 挂了导致的

**Comment by orienthong** [comment]
@tikazyq 哪个地方的后台日志
