### ISSUE TITLE
【BUG】错误日志重复记录问题

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#783]
**Bug 描述**
例如，当 运行长任务 时，日志记录 功能工作不正常，存在同一条错误日志重复记录的问题。

**复现步骤**
该 Bug 复现步骤如下
1. 运行一个长任务
2. 当长任务存在 error 报错时，日志管理会记录错误
3. 累计一段时间后， mongodb 会持续重复记录该条错误日志

**期望结果**
日志管理 能正常工作。

**截屏**
![toP1Zd.png](https://s1.ax1x.com/2020/06/10/toP1Zd.png)

[#768](https://github.com/crawlab-team/crawlab/issues/768) 此 issue 的重复项应该也是存在重复记录的问题

2020/06/18 更新：
~~不止是错误日志会重复记录，就算是正常日志也会重复记录，可能是日志采集的时候没做去重逻辑直接入库了。~~
删除已完成的任务并不会删除对应 nongodb 里的日志

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
