### ISSUE TITLE
直接安装的方式  后端启动错误

### ISSUE THREAD

**Issue by Doyus** [crawlab-team/crawlab#785]
[![image](https://user-images.githubusercontent.com/37011721/84340907-612d5a00-abd4-11ea-888f-f84c0fb24e43.png)
](url)

[![image](https://user-images.githubusercontent.com/37011721/84340975-920d8f00-abd4-11ea-9cfe-695b8a639aa5.png)
](url)

**Comment by tikazyq** [comment]
mongo 验证没通过

**Comment by Doyus** [comment]
[
![image](https://user-images.githubusercontent.com/37011721/84356585-f6414a80-abf6-11ea-889d-42a8e1896314.png)
](url)

[![image](https://user-images.githubusercontent.com/37011721/84356765-402a3080-abf7-11ea-8b41-7fb93702d60c.png)](url)


[
![image](https://user-images.githubusercontent.com/37011721/84357117-baf34b80-abf7-11ea-88f0-2a45a30c36a0.png)
](url)


搜索了一下说是要在代码里改？加参数？对go不了解

**Comment by tikazyq** [comment]
加微信咨询 tikazyq1
