### ISSUE TITLE
csv数据导出的字段顺序，能不能和插入时的顺序一下

### ISSUE THREAD

**Issue by xiaomei628** [crawlab-team/crawlab#786]
csv数据导出的字段顺序，能不能和插入时的顺序一下，现在好像是每一次导出，每一次的字段排序都不一样
![image](https://user-images.githubusercontent.com/15361002/84644657-08422680-af32-11ea-92fe-a05870af95ee.png)
![image](https://user-images.githubusercontent.com/15361002/84644801-39225b80-af32-11ea-914c-a27aa50169c5.png)

插入时候的顺序：
![image](https://user-images.githubusercontent.com/15361002/84644726-21e36e00-af32-11ea-9bb5-4b39dd06f035.png)

**Comment by tikazyq** [comment]
这个取决于mongo，不是很好实现，暂时不修复

**Comment by xiaomei628** [comment]
那我自己先改个对columns数组的排序，来保证列表的固定性
