### ISSUE TITLE
普通爬虫上传zip文件提示unauthorized

### ISSUE THREAD

**Issue by yumen** [crawlab-team/crawlab#788]
普通爬虫上传zip文件提示unauthorized,
Request URL: http://10.10.10.188:8080/api/spiders/5eeb02f9bcbf0b0018989548/upload
Request Method: POST
Status Code: 401 Unauthorized

返回数据
{status: "ok", message: "unauthorized", data: null, error: "unauthorized"}

**Comment by tikazyq** [comment]
登录了么？

**Comment by yumen** [comment]
> 登录了么？

登录了,并且上个月部署在另1个环境的可以正常上传,无法上传的是昨天docker部署的,是不是更新出了bug.

**Comment by tikazyq** [comment]
请描述一下复现步骤

**Comment by yumen** [comment]
> 请描述一下复现步骤

登录admin账号,点击左侧爬虫图标,添加爬虫,在自定义中设置爬虫相关配置,点上传,然后报错.

**Comment by tikazyq** [comment]
请暂时用 [CLI 工具](https://docs.crawlab.cn/zh/SDK/CLI.html) 上传爬虫

**Comment by tikazyq** [comment]
准备在下个版本取消zip文件上传功能
