### ISSUE TITLE
exit status 1 

### ISSUE THREAD

**Issue by WickedMonkey95** [crawlab-team/crawlab#790]
**Bug 描述**
使用docker部署成功后，上传scrapy爬虫，spider和pipeline不显示内容

**复现步骤**
该 Bug 复现步骤如下
1. 初次部署
2. 上传scrapy爬虫
3. 查看任务时没有spider 和pipeline，并报错 exit status 1 

**期望结果**
scrapy爬虫能在crawlab正常运行。

**截屏**
![image](https://user-images.githubusercontent.com/40019763/85198289-22a54700-b31a-11ea-936e-87cc203c5eac.png)

**Comment by tikazyq** [comment]
很可能是依赖没安装

https://docs.crawlab.cn/zh/QA/ 最后一个问题

**Comment by WickedMonkey95** [comment]
安装完依赖已经解决问题，谢谢！
