### ISSUE TITLE
【BUG】Crawlab 容器镜像节点异常重启

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#793]
**Bug 描述**
例如，当 Crawlab 使用容器化部署方案是，会出现偶发性的节点异常重启事件，导致长任务异常结束。

日志里最大嫌疑人为：
panic: runtime error: invalid memory address or nil pointer dereference
signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a36de

此处好像是一处指针声明及赋值引用异常
另外还有其它一些小报错，不知道影响大不大

另外，容器节点同时跑了大概 15 个左右的长任务
平均每分钟会调起 3 个左右的”阅后即焚“任务
不清楚是否有影响

Crawlab 版本：v0.4.10

**复现步骤**
该 Bug 复现步骤如下
1. 使用 Docker 容器化方案部署多个 Crawlab 节点；
2. 运行 N 个长任务；
3. 等待一段事件(可能是几分钟至几天)；
4. 容器出现异常重启现象。

**期望结果**
Crawlab 容器能稳定运行。

**日志**
[dumps_logs](http://ge.tt/9VVvaC53)
此日志分享文件仅有30天有效存活时间，请务必提前下载保存备用
还有就是国内访问速度不理想，可...

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开

**Comment by thachnv92** [comment]
I just got this bug with v0.6.0-1.
Pls reopen this issue.

**Comment by thachnv92** [comment]
@zkqiang
I just got this bug with v0.6.0-1.
Pls reopen this issue.
