### ISSUE TITLE
使用admin登录后，很快会自动退出

### ISSUE THREAD

**Issue by terryzwt** [crawlab-team/crawlab#795]
**Bug 描述**
1. 部署系统
2. 使用默认帐号amdin/admin登录
3. 随机浏览页面，用户会自动退出

**复现步骤**
该 Bug 复现步骤如下
1. 基于docker部署
2. 使用默认帐号amdin/admin登录
3. 随机浏览页面，用户会自动退出

**期望结果**

**Comment by tikazyq** [comment]
有后台日志么
