### ISSUE TITLE
git使用ssh拉取代码，出现以下错误 first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by tikazyq** [crawlab-team/crawlab#797]
git使用ssh拉取代码，出现以下错误 first path segment in URL cannot contain colon

_Originally posted by @selerisjava in https://github.com/crawlab-team/crawlab/issues/776#issuecomment-651636453_

**Comment by selerisjava** [comment]
![Uploading image.png…]()
填入git的ssh后，选择任意分支，点击保存按钮，然后点同步，出现这类错误

**Comment by tikazyq** [comment]
这里用了分号么？
