### ISSUE TITLE
不能使用非crawlab里面mongodb么?

### ISSUE THREAD

**Issue by 52Lau** [crawlab-team/crawlab#798]
不能使用非crawlab里面mongodb么?

**Comment by tikazyq** [comment]
Crawlab 专业版可以，支持多种数据源

https://docs.crawlab.cn/zh/DataSource/

**Comment by 52Lau** [comment]
“脚本是用 Crawlab SDK 的 save_item 保存结果数据”这个才会吧?
可以这个不是使用Crawlab的save_item,就是在文件里面自己写的一个连接
![image](https://user-images.githubusercontent.com/37538641/86195421-736f3800-bb83-11ea-9cca-7071ca5024d9.png)
这种也不能么?

**Comment by tikazyq** [comment]
如果了解原理的话，可以自己重写SDK来满足你的需求

**Comment by 52Lau** [comment]
不管哪一个版本,如果我想用mongo或者其他的东西,自己想写一点其他的逻辑,比如查询都不能吧

**Comment by tikazyq** [comment]
> 不管哪一个版本,如果我想用mongo或者其他的东西,自己想写一点其他的逻辑,比如查询都不能吧

不理解，请解释一下

**Comment by wo10378931** [comment]
> 不管哪一个版本,如果我想用mongo或者其他的东西,自己想写一点其他的逻辑,比如查询都不能吧

可以自己部署一个mongodb实例

**Comment by 0utman1** [comment]
> “脚本是用 Crawlab SDK 的 save_item 保存结果数据”这个才会吧?
> 可以这个不是使用Crawlab的save_item,就是在文件里面自己写的一个连接
> ![image](https://user-images.githubusercontent.com/37538641/86195421-736f3800-bb83-11ea-9cca-7071ca5024d9.png)
> 这种也不能么?

这种应该可以吧，自己写一个工具类，随便哪个数据库都可存，不过save_items这个步骤会不会有问题?
