### ISSUE TITLE
创建爬虫的时候如何取执行Linux服务器的命令

### ISSUE THREAD

**Issue by yeafel666** [crawlab-team/crawlab#799]
我测试了一下，在本机上传之后可以执行python和java项目，我部署在linux上，可以执行本机的命令吗，比如我想通过ssh远程去启动另外一台服务器的服务。目前看来是只能执行此项目上支持的命令。

**Comment by tikazyq** [comment]
docker不行，需要在docker里安装环境

**Comment by yeafel666** [comment]
谢谢，我忽略了是使用docker部署的，我在docker中安装了ssh等服务，现在是可以远程执行了。
