### ISSUE TITLE
win10系统下，部署成功后，新建可配置爬虫无法运行，日志路径报错

### ISSUE THREAD

**Issue by 123wuyu** [crawlab-team/crawlab#80]
win10系统，用直接部署方式部署成功了，新建可配置爬虫无法运行，日志路径报错，错误：[WinError 267] 目录名称无效。  修改setting里的PROJECT_LOGS_FOLDER = 'C:\\var\\log\\crawlab'，无效

**Comment by klren0312** [comment]
# 斜杠反着来试试?
**C:/var/log/crawlab**

**Comment by tikazyq** [comment]
您加两个斜杠试试？

**Comment by Zerorigin** [comment]
有个东西叫 Docker for Windows，非常方便，你可以试试。
