### ISSUE TITLE
待定任务太多，定时任务无法正常，影响业务。

### ISSUE THREAD

**Issue by luzihang123** [crawlab-team/crawlab#800]
**请描述该需求尝试解决的问题**
待定任务太多，定时任务无法正常，影响业务。

**请描述您认为可行的解决方案**
能否在文档，完善下待定的描述，定时任务无法正常，调度平台的作用就没了，这个坑好深

**Comment by tikazyq** [comment]
增大这个环境变量，重启服务器

`CRAWLAB_TASK_WORKER`

**Comment by luzihang123** [comment]
> 增大这个环境变量，重启服务器
> 
> `CRAWLAB_TASK_WORKER`

任务太多，重启之前，已经把任务迁到调度平台了。重启一次，挺麻烦。希望在稳定着重说明，减少入坑的人。

**Comment by tikazyq** [comment]
> > 增大这个环境变量，重启服务器
> > `CRAWLAB_TASK_WORKER`
> 
> 任务太多，重启之前，已经把任务迁到调度平台了。重启一次，挺麻烦。希望在文档着重说明，减少入坑的人。

感谢反馈，后续我们会优化这个的，可能考虑把相关的参数放到数据库里配置
