### ISSUE TITLE
创建爬虫失败，服务端报错 500

### ISSUE THREAD

**Issue by kingzeus** [crawlab-team/crawlab#809]
**Bug 描述**
例如，创建爬虫时，显示“请求错误 500: http://127.0.0.1:8080/api/spiders,服务器发生错误，请检查服务器。”

**复现步骤**
该 Bug 复现步骤如下
1. 全新 docker 环境
2. 创建 名为“test”的项目
2. 在该项目下创建名为“test”的爬虫
3. 报错“请求错误 500: http://127.0.0.1:8080/api/spiders,服务器发生错误，请检查服务器。”

**期望结果**
正常创建。

**截屏**
![image](https://user-images.githubusercontent.com/2177109/88002683-aa5abd00-cb35-11ea-81ca-bc91b485606b.png)

![image](https://user-images.githubusercontent.com/2177109/88002638-9020df00-cb35-11ea-9326-d8eddff972e9.png)
![image](https://user-images.githubusercontent.com/2177109/88002757-db3af200-cb35-11ea-87e2-9787622e27fa.png)

**Comment by tikazyq** [comment]
爬虫名称已经存在了
