### ISSUE TITLE
直接部署的时候运行crawlab，提示找不到api/release/latest文件

### ISSUE THREAD

**Issue by simplemrchen** [crawlab-team/crawlab#815]
所有的环境都构建好，运行服务的时候正常，在浏览器上访问ip：8080时候，出现错误，查看nginx日志，提示找不到文件，如下
前端显示
请求错误404 http://192.168.xx.xxx:8080/api/releases/latest,发出的请求时针对不存在的记录，服务器没有进行操作
请求错误404 http://192.168.xx.xxx:8080/api/setting,发出的请求时针对不存在的记录，服务器没有进行操作
nginx错误日志如下
2020/07/29 09:38:53 [error] 18662#18662: *25 open() "/root/crawlab/frontend/dist/api/releases/latest" failed (2: No such file or directory), client: 192.168.42.1, server: dev.crawlab.com, request: "GET /api/releases/latest HTTP/1.1", host: "192.168.xx.xxx:8080", referrer: "http://192.168.xx.xxx:8080/"
2020/07/29 09:38:53 [error] 18662#18662: *25 open() "/root/crawlab/frontend/dist/api/setting" failed (2: No such file or directory), client: 192.168.xx.1, server: dev.crawlab.com, request: "GET /api/setting HTTP/1.1", host: "192.168.xx.xxx:8080", referrer: "http://192.168.xx.xxx:8080/"

**Comment by tikazyq** [comment]
把 /api 去掉
