### ISSUE TITLE
【BUG】请求错误 500: http://192.168.0.8:58080/api/xxxxxxxx,服务器发生错误，请检查服务器。

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#816]
**Bug 描述**
Version:0.5.0
例如，当进入爬虫详情页时，部分接口无法正常工作。

**复现步骤**
该 Bug 复现步骤如下
1. 进入任意一个爬虫详情页
2. toast 冒泡提示此错误 “请求错误 500: http://192.168.0.8:58080/api/git/commits?spider_id=5f1952ede7b4700057dbd711,服务器发生错误，请检查服务器。”

**期望结果**
Crawlab 的接口能正常工作。

**截屏**
![aeII2R.png](https://s1.ax1x.com/2020/07/29/aeII2R.png)

***日志***
[GIN] 2020/07/29 - 17:52:15 | 500 |    2.533521ms |       127.0.0.1 | GET      "/git/commits?spider_id=5f1952ede7b4700057dbd711"
[GIN] 2020/07/29 - 17:52:15 | 200 |    2.502149ms |       127.0.0.1 | GET      "/spiders/5f1952ede7b4700057dbd711/dir"
        /go/src/app/middlewares/auth.go:46 +0x1ca
github.com/gin-gonic/gin.(*Context).Next(0xc0048fe780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab/middlewares.CORSMiddleware.func1(0xc0048fe780)
        /go/src/app/middlewares/cors.go:17 +0x39b
github.com/gin-gonic/gin.(*Context).Next(0xc0048fe780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc0048fe780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 +0x60
github.com/gin-gonic/gin.(*Context).Next(0xc0048fe780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0048fe780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0xe1
github.com/gin-gonic/gin.(*Context).Next(0xc0048fe780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001dc3c0, 0xc0048fe780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x666
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001dc3c0, 0x13cca40, 0xc0024487e0, 0xc004c23e00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc00046e1c0, 0x13cca40, 0xc0024487e0, 0xc004c23e00)
        /usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc001c43a40, 0x13d2440, 0xc004a401c0)
        /usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2962 +0x35c

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
