### ISSUE TITLE
【BUG】爬虫配置 Git 仓库时报错

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#817]
**Bug 描述**
Version：0.5.0
例如，当在 爬虫得 Git 配置选项卡界面配置 Git 设置时，无法正常进行设置。

**复现步骤**
该 Bug 复现步骤如下
1. 新建一个空的 Git 爬虫
2. 切换到爬虫 Git 选项卡界面
3. 填写 Git 仓库 Url 地址后，点击页面其它空白处等待 branches 下拉框展示
4. 出现此报错 请求错误 500: http://192.168.0.8:58080/api/git/branches?url=git@example_com.git&username=&password=,服务器发生错误，请检查服务器。“”

**期望结果**
Git 配置功能能正常工作。

**截屏**
![anDsRU.png](https://s1.ax1x.com/2020/07/30/anDsRU.png)

**日志**
[GIN] 2020/07/30 - 10:48:59 | 500 |  2.324410683s |       127.0.0.1 | GET      "/git/branches?url=git@example_com.git&username=&password="
2020/07/30 10:49:01 error 5f2234e3726551005809907f already exists. removing...

日志看起来非常正常

Version：0.5.1
此版本报错信息如下
请求错误 500: http://192.168.0.8:58080/api/git/branches?url=git@example.com:python:example_project.git&username=&password=. ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
