### ISSUE TITLE
【BUG】已删除节点的任务日志不会在左侧的任务总表显示

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab#819]
**Bug 描述**
Version：0.5.1
例如，当 在任务界面 时， 任务展示功能和预期有出入。

**复现步骤**
该 Bug 复现步骤如下
1. 在特定节点运行任意任务后，关闭该节点
2. 在此节点离线后，将该节点从节点列表剔除
3. 切回对应任务的爬虫详情页面，可以看到前面运行的特定任务
4. 切换到任务界面，选择爬虫任务的全部节点及全部任务，不会展示已删除节点的任务

**期望结果**
任务 列表能正常展示所筛选的任务。

**截屏**
没有截屏

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
