### ISSUE TITLE
前端页面展示太慢

### ISSUE THREAD

**Issue by yangliwei1985** [crawlab-team/crawlab#82]
前端所有页面刷新不及时 需要过好久才能展示出来

**Comment by tikazyq** [comment]
可以说详细一点么

**Comment by wo10378931** [comment]
Nginx的配置文件添加gzip：
	gzip on;
	gzip_min_length 1k;
	gzip_buffers 4 16k;
	#gzip_http_version 1.0;
	gzip_comp_level 2;
	gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
	gzip_vary off;
	gzip_disable "MSIE [1-6]\.";
