### ISSUE TITLE
Frontend界面中关闭标签页时会出现重复标签

### ISSUE THREAD

**Issue by lsyer** [crawlab-team/crawlab#824]
**Bug 描述**
当打开多个标签页，再关闭当前标签页时，toLastView函数将会根据访问顺序定位到最后一个访问的标签页并显示。
但没有判断最后一个访问的标签页是否在标签导航处有tag，而是直接使用this.$router.push(latestView)新建一个标签，导致标签页重复。

**Comment by tikazyq** [comment]
感谢反馈，非常犀利，如果能提PR是最好了
