### ISSUE TITLE
docker成功后无法登录

### ISSUE THREAD

**Issue by vikingshu** [crawlab-team/crawlab#826]
**Bug 描述**
按文档进行docker部署成功后，登录不成功，开始提示“401未授权”，第二天又提示“您的网络发生异常，无法连接服务器”，请问哈这个是要授权才能使用吗

**复现步骤**
该 Bug 复现步骤如下
1. 
2. 
3. 

**期望结果**
xxx 能工作。

**截屏**
![image](https://user-images.githubusercontent.com/54694402/89756951-7b24e380-db16-11ea-9075-e1eb8c2a8053.png)
![image](https://user-images.githubusercontent.com/54694402/89756963-82e48800-db16-11ea-8519-d250cad4806f.png)

![截屏1](http://static-docs.crawlab.cn/login.png)

**Comment by tikazyq** [comment]
`docker logs <container_name>` 查看一下日志

**Comment by vikingshu** [comment]
> `docker logs <container_name>` 查看一下日志

前端没发请求

**Comment by vikingshu** [comment]
![image](https://user-images.githubusercontent.com/54694402/89757525-1b2f3c80-db18-11ea-9b16-3eda5d8fd2f0.png)
![image](https://user-images.githubusercontent.com/54694402/89757591-487bea80-db18-11ea-9d5d-794af3fe64e3.png)

**Comment by tikazyq** [comment]
这个错误应该不会造成无法登录的问题

**Comment by vikingshu** [comment]
之成功登录过一次，然后就报 401，现在就一直报服务器无法连接，不晓得是不是哪里没有配置好

**Comment by vikingshu** [comment]
点击登录时，前端输出 Cannot read property 'status' of undefined，而且并没有发后端发送请求

**Comment by tikazyq** [comment]
加微信 tikazyq1 拉群讨论

**Comment by Miracle804** [comment]
我也遇到了这种情况，有解决办法吗
