### ISSUE TITLE
数据存储

### ISSUE THREAD

**Issue by Bear-Kevin** [crawlab-team/crawlab#827]
对于爬取到的数据，是否可以自己配置需要的数据库进行存储，目前非专业版中好像只能使用mongodb进行存储

**Comment by zkqiang** [comment]
是的，非专业版默认是使用 mongodb，可以将存储的逻辑直接写在爬虫里即可

**Comment by Bear-Kevin** [comment]
多谢指点，但是目前还在考虑是否采用这个平台，不知道您是否有其他推荐的，最好是python语言构建的，谢谢！

**Comment by zkqiang** [comment]
这个和管理平台关系不大，你完全可以自己使用 python 编写爬虫（包括存储数据库的部分），然后部署到 crawlab 来管理

**Comment by Bear-Kevin** [comment]
后期想基于这种现有的平台做一些修改，添加一些自定义的部分，所以在考虑是否选择其他平台

**Comment by zkqiang** [comment]
scrapyd+scrapydweb

**Comment by Bear-Kevin** [comment]
好的，我去详细了解一下，非常感谢！
