### ISSUE TITLE
在节点里安装依赖中搜索不到包  requests_toolbelt

### ISSUE THREAD

**Issue by AndrewAndrea** [crawlab-team/crawlab#837]
空格我都删除了，源没有这个包，搜索不到
![image](https://user-images.githubusercontent.com/35560234/92203690-5c670200-eeb4-11ea-9d90-87252470a302.png)

这个只能去单独安装吗

**Comment by tikazyq** [comment]
requests-toolbelt

**Comment by AndrewAndrea** [comment]
额，，，好吧！非常感谢！ 有点蠢了！
