### ISSUE TITLE
crawlab does not send mail in k8s deployment

### ISSUE THREAD

**Issue by sickcrow** [crawlab-team/crawlab#840]
**Describe the bug**
crawlab does not send mail in k8s deployment

**To Reproduce**
I configure config.yml and add the lines of my relay server

**Expected behavior**
I configure the sending to my mail through the gui for when a task finishes send mail

**Screenshots**
![image](https://user-images.githubusercontent.com/56140011/92667720-17dbcc00-f2e3-11ea-88e3-4d0c69cb8309.png)
Config map (config.yml in kubernetes)
![image](https://user-images.githubusercontent.com/56140011/92668004-f16a6080-f2e3-11ea-9476-f5a2d83f6ade.png)

sorry for my english

**Comment by tikazyq** [comment]
Would you check your log if crawlab backend failed to send mails.

**Comment by sickcrow** [comment]
> Would you check your log if crawlab backend failed to send mails.

![image](https://user-images.githubusercontent.com/56140011/92677653-b162a800-f2fa-11ea-92e2-2c5c6c1579ec.png)
my relay is without authentication. authenticate by ip

**Comment by tikazyq** [comment]
I guess your SMTP server config in your system environment variables are not configured correctly. Please refer to https://docs.crawlab.cn/en/Config/ for more detail.

**Comment by sickcrow** [comment]
> I guess your SMTP server config in your system environment variables are not configured correctly. Please refer to https://docs.crawlab.cn/en/Config/ for more detail.

thank you very much for your help
setting it by variables, now I see this "error"
![image](https://user-images.githubusercontent.com/56140011/92684895-ed9f0400-f30c-11ea-9208-d93c4078252f.png)
![image](https://user-images.githubusercontent.com/56140011/92685016-35be2680-f30d-11ea-8358-5f871d863814.png)

our mail server authenticates by ip, not by user (relay)

**Comment by tikazyq** [comment]
I think even if you don't authenticate by user, you still need to set it as an environment variable, otherwise Crawlab will complain it is empty.

**Comment by sickcrow** [comment]
> I think even if you don't authenticate by user, you still need to set it as an environment variable, otherwise Crawlab will complain it is empty.

now the error is another
![image](https://user-images.githubusercontent.com/56140011/92733371-ffed6200-f34d-11ea-80e3-7b4f1a64386e.png)
![image](https://user-images.githubusercontent.com/56140011/92733418-0e3b7e00-f34e-11ea-81c5-fc66675019b2.png)
I am not sure if I am filling in the variable correctly or why it is not taking it

**Comment by tikazyq** [comment]
Alright, I think the documentation has a typo here. It should be `CRAWLAB_NOTIFICATION_MAIL_SENDERIDENTITY` instead of `CRAWLAB_NOTIFICATION_MAIL_SENDEREIDENTITY`.

**Comment by sickcrow** [comment]
> Alright, I think the documentation has a typo here. It should be `CRAWLAB_NOTIFICATION_MAIL_SENDERIDENTITY` instead of `CRAWLAB_NOTIFICATION_MAIL_SENDEREIDENTITY`.

Thanks. error now is:
2020/09/10 23:58:09  info process received signal: finish
2020/09/10 23:58:09  info [Worker 15] task (id:a2f0e389-22bc-41bf-8a31-eb334c5c4a04) finished. elapsed:537.708455 sec
**2020/09/10 23:58:09 error unencrypted connection**
my smtp relay (mailserver) run on port 25 and is no user auth only client private ip
thank you very much for your help. I hope it can be solved. It is the only thing that remains pending, everything else works wonderfully

**Comment by tikazyq** [comment]
I think "unencrypted connection" may indicate that smtp module won't allow plain-text communication. Instead, it requires some sort of encryption mechanisms such as HTTPS or authentication involved. I would suggest you consult with your mail server provider and ask for the guidance.

**Comment by sickcrow** [comment]
> I think "unencrypted connection" may indicate that smtp module won't allow plain-text communication. Instead, it requires some sort of encryption mechanisms such as HTTPS or authentication involved. I would suggest you consult with your mail server provider and ask for the guidance.

As an example in rancher I configure my mailserver to port 25 and disable the TLS option. There is no option to do the same with some variable?
The mail server is exchange and is used as a relay without authentication only by private ip
thanks!

**Comment by sickcrow** [comment]
probably configure mailu on cluster k8s to test this. If you solve this problem please let me know
thanks for your help
