### ISSUE TITLE
修改爬虫中的文件保存失败

### ISSUE THREAD

**Issue by whorace97** [crawlab-team/crawlab#843]
**Bug 描述**
例如，当 修改爬虫中的文件 时，保存 功能出现问题。

**复现步骤**
我经常在crawlab上进行文件的修改和调试，后来突然出现修改文件失败的情况，即插入、删除某行或者修改某个字符后，点击保存，会同时弹出两个提示，一个是错误提示，一个提示文件保存成功，但如果跳转到其他地方又跳转回来后，发现文件实际上没有被修改掉。

**期望结果**
修改文件后 能正常保存。

**截屏**
![image](https://user-images.githubusercontent.com/26036823/92897806-14198800-f450-11ea-8fc3-1031e3cdafa0.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
