### ISSUE TITLE
点击Scrapy爬虫的设置标签，出现Config File "config" Not Found错误

### ISSUE THREAD

**Issue by codetomakechange** [crawlab-team/crawlab#844]
**Bug 描述**
例如，当通过Web界面新建一个Scrapy类型的爬虫时， 点击Scrapy 标签，返回错误信息：
请求错误 500: http://127.0.0.1:8000/spiders/********/scrapy/settings. 
2020/09/11 21:46:03 error init config error:Config File "config" Not Found in "[/app/spiders/news/conf]" panic: Config File "config" Not Found in "[/app/spiders/news/conf]" goroutine 1 [running]: main.main() /usr/local/crawlab/backend/main.go:51 +0x4c3d

items、pipelines都是报类似错误。而这个scrapy工程中并没有conf文件夹。
详细的日志输出如下：
goroutine 1 [running]:
main.main()
        /usr/local/crawlab/backend/main.go:51 +0x4c3d

goroutine 552 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x25
crawlab/services.GetScrapySettings(0xc0016e94b4, 0xc, 0xc0016e94c8, 0x4, 0xc0016e94e0, 0x4, 0xc0016e94f0, 0xa, 0xc0016e9504, 0xc, ...)
        /usr/local/crawlab/backend/services/scrapy.go:59 +0x3f5
crawlab/routes.GetSpiderScrapySettings(0xc001ca60f0)
        /usr/local/crawlab/backend/routes/spider.go:1626 +0x15a
github.com/gin-gonic/gin.(*Context).Next(0xc001ca60f0)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab/middlewares.AuthorizationMiddleware.func1(0xc001ca60f0)
        /usr/local/crawlab/backend/middlewares/auth.go:46 +0x1df
github.com/gin-gonic/gin.(*Context).Next(0xc001ca60f0)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab/middlewares.CORSMiddleware.func1(0xc001ca60f0)
        /usr/local/crawlab/backend/middlewares/cors.go:17 +0x3a7
github.com/gin-gonic/gin.(*Context).Next(0xc001ca60f0)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc001ca60f0)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 +0x65
github.com/gin-gonic/gin.(*Context).Next(0xc001ca60f0)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc001ca60f0)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0xe5
github.com/gin-gonic/gin.(*Context).Next(0xc001ca60f0)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0000c43c0, 0xc001ca60f0)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x67a
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0000c43c0, 0x13a03c0, 0xc0017ac620, 0xc001d61600)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0003f4000, 0x13a03c0, 0xc0017ac620, 0xc001d61600)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0016a6b40, 0x13a5940, 0xc001c2a9c0)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c

**复现步骤**
该 Bug 复现步骤如下
1. 通过直接部署的方式在Centos7上安装crawlab
2. 通过web界面新建爬虫，上传zip文件，并勾选“是否为Scrapy”
3. 查看爬虫详情，点击“Scrapy设置”

另：直接在CentOS的终端中使用， scrapy crawl 可以执行成功。

**截屏**
![截图](https://user-images.githubusercontent.com/24477672/92933775-3ffd3380-f479-11ea-8e62-cbc0731292d8.jpg)

**Comment by tikazyq** [comment]
参考 https://docs.crawlab.cn/zh/Config/

**Comment by codetomakechange** [comment]
> 
> 
> 参考 https://docs.crawlab.cn/zh/Config/

不太清楚和yaml文件哪个配置项有关。目前以普通爬虫方式运行正常。

**Comment by paperen** [comment]
我也遇到一样的问题 @tikazyq 
一开始是报
`
[GIN] 2020/10/21 - 15:27:44 | 500 |    3.243411ms |       127.0.0.1 | GET      "/spiders/5f8fde944402fb21d68912e6/scrapy/pipelines"
2020/10/21 15:27:44 error exec: "crawlab": executable file not found in $PATH
2020/10/21 15:27:44 error `

然后自己将crawlab所在的目录加到环境变量中，再执行就出现跟楼主一样的情况
![error](https://user-images.githubusercontent.com/839191/96697258-4a86e300-13be-11eb-8c22-bc5b6e7916a2.png)

**Comment by paperen** [comment]
@codetomakechange 兄弟 我解决了，我看了源码发现原来是通过命令行`crawlab items`执行的
`
func GetScrapyItems(s model.Spider) (res []map[string]interface{}, err error) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	cmd := exec.Command("crawlab", "items")
	cmd.Dir = s.Src
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		log.Errorf(err.Error())
`

然后自己在终端上输入crawlab items发现会自动给关联到build出来的crawlab执行文件，很明显是有问题
![error](https://user-images.githubusercontent.com/839191/96699948-6fc92080-13c1-11eb-999f-ea5f12658eb3.png)


难道这个需要pip install？所以我尝试`pip install crawlab`
再执行crawlab items这回就ok了~~
![error](https://user-images.githubusercontent.com/839191/96700119-a9019080-13c1-11eb-847b-377c7854263b.png)


PS：如果pip install后crawlab还是不行，可以尝试`find / -name crawlab`，看下python的bin中是否有，有的话用绝对路径执行看下，比如：`/usr/local/python3.7/bin/crawlab`

那之后就简单了配置一下软链`ln -s /usr/local/python3.7/bin/crawlab /usr/bin/crawlab`

**Comment by 17186765070** [comment]
> @codetomakechange兄弟我解决了，我分析原始发现原来是通过命令行`crawlab items`执行的
> `
> 
> ```
> cmd := exec.Command("crawlab", "items")
> cmd.Dir = s.Src
> cmd.Stdout = &stdout
> cmd.Stderr = &stderr
> if err := cmd.Run(); err != nil {
> 	log.Errorf(err.Error())
> ```
> 
> `
> 
> 然后在自己终端上输入crawlab项目发现会自动关联到build出来的crawlab执行文件，很明显是有问题
> ![错误](https://user-images.githubusercontent.com/839191/96699948-6fc92080-13c1-11eb-999f-ea5f12658eb3.png)
> 
> 难道这个需要pip install？所以我`pip install crawlab`
> 试试再执行crawlab items这回就ok了~~
> ![错误](https://user-images.githubusercontent.com/839191/96700119-a9019080-13c1-11eb-847b-377c7854263b.png)
> 
> PS：如果不是，pip install后crawlab还是不行，可以`find / -name crawlab`尝试尝试，看下python的bin中是否有，有什么用绝对路径执行看下，比如：`/usr/local/python3.7/bin/crawlab`
> 
> 那之后就简单了配置一下软链`ln -s /usr/local/python3.7/bin/crawlab /usr/bin/crawlab`

我在pip install 后，找不到安装后的可执行文件（crawlab）；python/bin中也找不到，只在site-packages中找到一些.py文件 。
![image](https://user-images.githubusercontent.com/84702815/131299564-89a1bf3e-4f58-402e-ba18-8183bf902c7f.png)

**Comment by Di-Zayn** [comment]
@paperen 你好，我也遇到了相同的问题。我也是将crawlab的目录加入到了环境变量中，之后发现crawlab命令定位到了go build编译好的exe文件上。但我使用pip install crawlab后并没有解决问题，被安装的crawlab被放在了/home/me/.lcoal/python3.6/lib/site-packages/crawlab中，不是可执行的文件。请问你当时的详细步骤是怎样的？
