### ISSUE TITLE
两个环境，依赖包名有问题

### ISSUE THREAD

**Issue by qingfengfenga** [crawlab-team/crawlab#852]
一个大写无法导入，一个小写无法导入

两个环境使用同一镜像

正常环境
![image](https://user-images.githubusercontent.com/41416092/94354665-07cc3680-00b0-11eb-9b34-213652906bac.png)

有问题的hu环境，无法调用 DBUtils 包
![image](https://user-images.githubusercontent.com/41416092/94354670-17e41600-00b0-11eb-9dfc-7cb1fc7c6c5f.png)

**Comment by tikazyq** [comment]
这是第三方依赖还是本地依赖？

**Comment by qingfengfenga** [comment]
> 这是第三方依赖还是本地依赖？

具体是第三方还是本地我不太清楚，是在web里面搜索安装的
![image](https://user-images.githubusercontent.com/41416092/94380986-3eff1e00-016a-11eb-98c2-9a5cbedb12eb.png)

**Comment by tikazyq** [comment]
分别在各节点里执行 `pip freeze`

**Comment by qingfengfenga** [comment]
> 分别在各节点里执行 `pip freeze`
master
![image](https://user-images.githubusercontent.com/41416092/94388075-8db6b300-017e-11eb-937f-9fb48d587890.png)

worker1
![image](https://user-images.githubusercontent.com/41416092/94388097-9ad3a200-017e-11eb-9822-ff4fdc6ab9db.png)

worker2
![image](https://user-images.githubusercontent.com/41416092/94388104-a1621980-017e-11eb-82c2-fc439116383a.png)

**Comment by qingfengfenga** [comment]
非常感谢回复，这个问题刚刚已经解决了，应该是依赖包的兼容问题，目前最新安装的是2.0，手动降为1.3就可以了。
