### ISSUE TITLE
关于git无法同步http协议的bug

### ISSUE THREAD

**Issue by Richardchia** [crawlab-team/crawlab#859]
使用http协议时，无法连接同步指定端口的地址，查看源码后，发现问题存在于后台代码中与git相关部分中
![image](https://user-images.githubusercontent.com/32747459/96545740-88f7a180-12db-11eb-9cba-692e8e997131.png)
此处Hostname()函数不带指定端口，导致连接时，会以默认80端口连接，出现报错

**Comment by hantmac** [comment]
fixed.
