### ISSUE TITLE
windows 重啟後之前上傳的爬蟲沒有保存下來

### ISSUE THREAD

**Issue by john-data-chen** [crawlab-team/crawlab#865]
**Bug 描述**
Windows 重啟後之前上傳的爬蟲跟執行結果都沒有保存下來

**复现步骤**
该 Bug 复现步骤如下
1. 在 windows 10 上用 docker-compose up-d 架設 crawlab 0.5.1，將 yml 裡 volumes 的 # 號都去除
2. 上傳爬蟲，保存跟執行，看到任務有結果
3. 關閉 docker 重啟 windows 10

**期望结果**
之前上傳的爬蟲跟執行結果在 windows 重啟後仍然存在

**Comment by tikazyq** [comment]
很可能是没有持久化，在 `docker-compose.yml` 里 mongo 里加入 `volumes`

**Comment by john-data-chen** [comment]
> 很可能是没有持久化，在 `docker-compose.yml` 里 mongo 里加入 `volumes`
我有將 volumes 的 # 號去掉了

  mongo:
    image: mongo:latest
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - "/opt/crawlab/mongo/data/db:/data/db"  # make data persistent 持久化
    ports:
      - "27017:27017"  # expose port to host machine 暴露接口到宿主机

**Comment by tikazyq** [comment]
您可以检查一下mongo里的数据是否都还在

**Comment by john-data-chen** [comment]
> 您可以检查一下mongo里的数据是否都还在

重啟前，mongo 裡面爬蟲跟任務數據有寫進去
重啟後，mongo 的爬蟲跟任務數據都消失了

**Comment by tikazyq** [comment]
能否贴一下相关的数据截图或日志
