### ISSUE TITLE
部署到阿里云K8S，前端界面经常报错

### ISSUE THREAD

**Issue by chinamickey** [crawlab-team/crawlab#866]
chunk-vendors.a38769f1.js:79 GET http://dmp-dev.fpi-inc.site/api/stats/home 500 (Internal Server Error)
(anonymous) @ chunk-vendors.a38769f1.js:79
e.exports @ chunk-vendors.a38769f1.js:79
e.exports @ chunk-vendors.a38769f1.js:41
Promise.then (async)
s.request @ chunk-vendors.a38769f1.js:1
i.forEach.s.<computed> @ chunk-vendors.a38769f1.js:1
(anonymous) @ chunk-vendors.a38769f1.js:1
m @ app.fbc1a293.js:1
created @ chunk-835c2710.793c0931.js:1
nt @ chunk-vendors.a38769f1.js:32
jn @ chunk-vendors.a38769f1.js:32
e._init @ chunk-vendors.a38769f1.js:32
o @ chunk-vendors.a38769f1.js:32
an @ chunk-vendors.a38769f1.js:32
init @ chunk-vendors.a38769f1.js:32
n @ chunk-vendors.a38769f1.js:32
p @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni @ chunk-vendors.a38769f1.js:32
En @ chunk-vendors.a38769f1.js:32
wi.$mount @ chunk-vendors.a38769f1.js:32
init @ chunk-vendors.a38769f1.js:32
p @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
y @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni @ chunk-vendors.a38769f1.js:32
En @ chunk-vendors.a38769f1.js:32
wi.$mount @ chunk-vendors.a38769f1.js:32
init @ chunk-vendors.a38769f1.js:32
p @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
y @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
y @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni @ chunk-vendors.a38769f1.js:32
En @ chunk-vendors.a38769f1.js:32
wi.$mount @ chunk-vendors.a38769f1.js:32
init @ chunk-vendors.a38769f1.js:32
n @ chunk-vendors.a38769f1.js:32
p @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
S @ chunk-vendors.a38769f1.js:32
H @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni.run @ chunk-vendors.a38769f1.js:32
Yn @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
lt @ chunk-vendors.a38769f1.js:32
Promise.then (async)
at @ chunk-vendors.a38769f1.js:32
pt @ chunk-vendors.a38769f1.js:32
ei @ chunk-vendors.a38769f1.js:32
ni.update @ chunk-vendors.a38769f1.js:32
me.notify @ chunk-vendors.a38769f1.js:32
set @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
Qe.updateRoute @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
$e @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
Promise.then (async)
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
Ie @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
v @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ app.fbc1a293.js:1
v @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
$e @ chunk-vendors.a38769f1.js:61
Qe.confirmTransition @ chunk-vendors.a38769f1.js:61
Qe.transitionTo @ chunk-vendors.a38769f1.js:61
zt.init @ chunk-vendors.a38769f1.js:61
beforeCreate @ chunk-vendors.a38769f1.js:61
nt @ chunk-vendors.a38769f1.js:32
jn @ chunk-vendors.a38769f1.js:32
e._init @ chunk-vendors.a38769f1.js:32
wi @ chunk-vendors.a38769f1.js:32
56d7 @ app.fbc1a293.js:1
c @ app.fbc1a293.js:1
0 @ app.fbc1a293.js:1
c @ app.fbc1a293.js:1
a @ app.fbc1a293.js:1
(anonymous) @ app.fbc1a293.js:1
(anonymous) @ app.fbc1a293.js:1
Show 34 more frames
chunk-835c2710.793c0931.js:1 Uncaught (in promise) TypeError: Cannot read property 'overview' of undefined
    at chunk-835c2710.793c0931.js:1
(anonymous) @ chunk-835c2710.793c0931.js:1
Promise.then (async)
created @ chunk-835c2710.793c0931.js:1
nt @ chunk-vendors.a38769f1.js:32
jn @ chunk-vendors.a38769f1.js:32
e._init @ chunk-vendors.a38769f1.js:32
o @ chunk-vendors.a38769f1.js:32
an @ chunk-vendors.a38769f1.js:32
init @ chunk-vendors.a38769f1.js:32
n @ chunk-vendors.a38769f1.js:32
p @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni @ chunk-vendors.a38769f1.js:32
En @ chunk-vendors.a38769f1.js:32
wi.$mount @ chunk-vendors.a38769f1.js:32
init @ chunk-vendors.a38769f1.js:32
p @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
y @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni @ chunk-vendors.a38769f1.js:32
En @ chunk-vendors.a38769f1.js:32
wi.$mount @ chunk-vendors.a38769f1.js:32
init @ chunk-vendors.a38769f1.js:32
p @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
y @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
y @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni @ chunk-vendors.a38769f1.js:32
En @ chunk-vendors.a38769f1.js:32
wi.$mount @ chunk-vendors.a38769f1.js:32
init @ chunk-vendors.a38769f1.js:32
n @ chunk-vendors.a38769f1.js:32
p @ chunk-vendors.a38769f1.js:32
d @ chunk-vendors.a38769f1.js:32
S @ chunk-vendors.a38769f1.js:32
H @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni.run @ chunk-vendors.a38769f1.js:32
Yn @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
lt @ chunk-vendors.a38769f1.js:32
Promise.then (async)
at @ chunk-vendors.a38769f1.js:32
pt @ chunk-vendors.a38769f1.js:32
ei @ chunk-vendors.a38769f1.js:32
ni.update @ chunk-vendors.a38769f1.js:32
me.notify @ chunk-vendors.a38769f1.js:32
set @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
Qe.updateRoute @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
$e @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
Promise.then (async)
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
Ie @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
v @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
(anonymous) @ app.fbc1a293.js:1
v @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:61
$e @ chunk-vendors.a38769f1.js:61
Qe.confirmTransition @ chunk-vendors.a38769f1.js:61
Qe.transitionTo @ chunk-vendors.a38769f1.js:61
zt.init @ chunk-vendors.a38769f1.js:61
beforeCreate @ chunk-vendors.a38769f1.js:61
nt @ chunk-vendors.a38769f1.js:32
jn @ chunk-vendors.a38769f1.js:32
e._init @ chunk-vendors.a38769f1.js:32
wi @ chunk-vendors.a38769f1.js:32
56d7 @ app.fbc1a293.js:1
c @ app.fbc1a293.js:1
0 @ app.fbc1a293.js:1
c @ app.fbc1a293.js:1
a @ app.fbc1a293.js:1
(anonymous) @ app.fbc1a293.js:1
(anonymous) @ app.fbc1a293.js:1
Show 28 more frames
chunk-vendors.a38769f1.js:79 PUT http://dmp-dev.fpi-inc.site/api/actions net::ERR_CONNECTION_RESET
(anonymous) @ chunk-vendors.a38769f1.js:79
e.exports @ chunk-vendors.a38769f1.js:79
e.exports @ chunk-vendors.a38769f1.js:41
Promise.then (async)
s.request @ chunk-vendors.a38769f1.js:1
i.forEach.s.<computed> @ chunk-vendors.a38769f1.js:1
(anonymous) @ chunk-vendors.a38769f1.js:1
g @ app.fbc1a293.js:1
(anonymous) @ app.fbc1a293.js:1
x @ chunk-vendors.a38769f1.js:61
(anonymous) @ chunk-vendors.a38769f1.js:61
M.forEach.e.<computed> @ chunk-vendors.a38769f1.js:61
i @ chunk-vendors.a38769f1.js:1
c @ chunk-vendors.a38769f1.js:1
Promise.then (async)
i @ chunk-vendors.a38769f1.js:1
c @ chunk-vendors.a38769f1.js:1
Promise.then (async)
i @ chunk-vendors.a38769f1.js:1
c @ chunk-vendors.a38769f1.js:1
(anonymous) @ chunk-vendors.a38769f1.js:1
(anonymous) @ chunk-vendors.a38769f1.js:1
mounted @ app.fbc1a293.js:1
nt @ chunk-vendors.a38769f1.js:32
jn @ chunk-vendors.a38769f1.js:32
insert @ chunk-vendors.a38769f1.js:32
V @ chunk-vendors.a38769f1.js:32
(anonymous) @ chunk-vendors.a38769f1.js:32
An.e._update @ chunk-vendors.a38769f1.js:32
i @ chunk-vendors.a38769f1.js:32
ni.get @ chunk-vendors.a38769f1.js:32
ni @ chunk-vendors.a38769f1.js:32
En @ chunk-vendors.a38769f1.js:32
wi.$mount @ chunk-vendors.a38769f1.js:32
e._init @ chunk-vendors.a38769f1.js:32
wi @ chunk-vendors.a38769f1.js:32
56d7 @ app.fbc1a293.js:1
c @ app.fbc1a293.js:1
0 @ app.fbc1a293.js:1
c @ app.fbc1a293.js:1
a @ app.fbc1a293.js:1
(anonymous) @ app.fbc1a293.js:1
(anonymous) @ app.fbc1a293.js:1

**Comment by tikazyq** [comment]
这是后端错误，需要查看docker日志
