### ISSUE TITLE
Crawlab config deleted after 2 or 4 days

### ISSUE THREAD

**Issue by LordVoodoo** [crawlab-team/crawlab#874]
Hello,

I have a Crawlab 0.5.1 instance running on Docker, after setting it up, within 2 to 4 days, I cannot access the instance anymore.
I found out, that a DropDatabase command is executed, deleting a collection “crawlab_test” or “crawlab_config”.

In the Crawlab log, I noticed the following error:

2020/11/04 03:42:00 error context deadline exceeded (Client.Timeout or context cancellation while reading body
(Several attemps)
2020/11/04 05:15:12 error Get "https://pypi.tuna.tsinghua.edu.cn/simple": net/http: TLS handshake timeout

On a 2nd device, the older 0.4.1 runs without issues.

Any help would be great.

**Comment by tikazyq** [comment]
I don't think Crawlab code would allow dropping a database like that. It must be something off on your side. Please double check.

**Comment by LordVoodoo** [comment]
That’s what I thought as well. After going to MongoDB, which runs exclusively for Crawlab, I noticed:

`
{"t":{"$date":"2020-11-03T08:02:46.854+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn1293","msg":"dropDatabase - starting","attr":{"db":"READ_ME_TO_RECOVER_YOUR_DATA"}},
{"t":{"$date":"2020-11-03T08:02:46.860+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"READ_ME_TO_RECOVER_YOUR_DATA","namespace":"READ_ME_TO_RECOVER_YOUR_DATA.README"}},
{"t":{"$date":"2020-11-03T08:02:46.983+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn1293","msg":"dropDatabase","attr":{"db":"READ_ME_TO_RECOVER_YOUR_DATA","numCollectionsDropped":1}},
{"t":{"$date":"2020-11-03T08:02:46.989+00:00"},"s":"I",  "c":"COMMAND",  "id":51803,   "ctx":"conn1293","msg":"Slow query","attr":{"type":"command","ns":"READ_ME_TO_RECOVER_YOUR_DATA","command":{"dropDatabase":1,"lsid":{"id":{"$uuid":"b1bfe219-d72f-44ba-af76-fc496ec1ed5c"}},"$db":"READ_ME_TO_RECOVER_YOUR_DATA","$readPreference":{"mode":"primary"}},"numYields":0,"reslen":80,"locks":{"ParallelBatchWriterMode":{"acquireCount":{"r":1}},"ReplicationStateTransition":{"acquireCount":{"w":1}},"Global":{"acquireCount":{"w":1}},"Database":{"acquireCount":{"W":1}},"Mutex":{"acquireCount":{"r":1}}},"flowControl":{"acquireCount":1,"timeAcquiringMicros":4},"storage":{},"protocol":"op_msg","durationMillis":134}},
{"t":{"$date":"2020-11-03T08:02:47.251+00:00"},"s":"I",  "c":"COMMAND",  "id":51803,   "ctx":"conn1293","msg":"Slow query","attr":{"type":"command","ns":"admin.$cmd","command":{"dropDatabase":1,"lsid":{"id":{"$uuid":"b1bfe219-d72f-44ba-af76-fc496ec1ed5c"}},"$db":"admin","$readPreference":{"mode":"primary"}},"numYields":0,"ok":0,"errMsg":"Dropping the 'admin' database is prohibited.","errName":"IllegalOperation","errCode":20,"reslen":136,"locks":{},"protocol":"op_msg","durationMillis":219}},
{"t":{"$date":"2020-11-03T08:02:47.288+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn1293","msg":"dropDatabase - starting","attr":{"db":"config"}},
{"t":{"$date":"2020-11-03T08:02:47.288+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"config","namespace":"config.system.sessions"}},
{"t":{"$date":"2020-11-03T08:02:47.316+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn1293","msg":"dropDatabase","attr":{"db":"config","numCollectionsDropped":1}},
{"t":{"$date":"2020-11-03T08:02:47.353+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn1293","msg":"dropDatabase - starting","attr":{"db":"crawlab_test"}},
{"t":{"$date":"2020-11-03T08:02:47.353+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.tasks"}},
{"t":{"$date":"2020-11-03T08:02:47.353+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.nodes"}},
{"t":{"$date":"2020-11-03T08:02:47.353+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.logs"}},
{"t":{"$date":"2020-11-03T08:02:47.355+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.schedules"}},
{"t":{"$date":"2020-11-03T08:02:47.356+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.actions"}},
{"t":{"$date":"2020-11-03T08:02:47.356+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.files.chunks"}},
{"t":{"$date":"2020-11-03T08:02:47.356+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.files.files"}},
{"t":{"$date":"2020-11-03T08:02:47.357+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.challenges"}},
{"t":{"$date":"2020-11-03T08:02:47.357+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.error_logs"}},
{"t":{"$date":"2020-11-03T08:02:47.359+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.results_barchart"}},
{"t":{"$date":"2020-11-03T08:02:47.359+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.spiders"}},
{"t":{"$date":"2020-11-03T08:02:47.359+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"crawlab_test","namespace":"crawlab_test.users"}},
{"t":{"$date":"2020-11-03T08:02:47.637+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn1293","msg":"dropDatabase","attr":{"db":"crawlab_test","numCollectionsDropped":12}},
{"t":{"$date":"2020-11-03T08:02:47.637+00:00"},"s":"I",  "c":"COMMAND",  "id":51803,   "ctx":"conn1293","msg":"Slow query","attr":{"type":"command","ns":"crawlab_test","command":{"dropDatabase":1,"lsid":{"id":{"$uuid":"b1bfe219-d72f-44ba-af76-fc496ec1ed5c"}},"$db":"crawlab_test","$readPreference":{"mode":"primary"}},"numYields":0,"reslen":64,"locks":{"ParallelBatchWriterMode":{"acquireCount":{"r":1}},"ReplicationStateTransition":{"acquireCount":{"w":1}},"Global":{"acquireCount":{"w":1}},"Database":{"acquireCount":{"W":1}},"Mutex":{"acquireCount":{"r":1}}},"flowControl":{"acquireCount":1,"timeAcquiringMicros":3},"storage":{},"protocol":"op_msg","durationMillis":284}},
{"t":{"$date":"2020-11-03T08:02:47.673+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn1293","msg":"dropDatabase - starting","attr":{"db":"local"}},
{"t":{"$date":"2020-11-03T08:02:47.674+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn1293","msg":"dropDatabase - dropping collection","attr":{"db":"local","namespace":"local.startup_log"}},
{"t":{"$date":"2020-11-03T08:02:47.699+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn1293","msg":"dropDatabase","attr":{"db":"local","numCollectionsDropped":1}} `

**Comment by tikazyq** [comment]
Your database has been hacked...

**Comment by LordVoodoo** [comment]
Well, that’s what I thought as well at first. So I put the MongoDB to an internal net without any connection to the docker network running the NGINX proxy.

What else to do to secure the database.
Password is more than 20 characters, created by a password generator.

**Comment by tikazyq** [comment]
I think you should not expose the database port to external network.

**Comment by LordVoodoo** [comment]
If checked again the settings in the environmental settings and changed to an even stronger one.
Hopefully it works out now.
