### ISSUE TITLE
Add an input to filter the schedules list

### ISSUE THREAD

**Issue by franciscohanna92** [crawlab-team/crawlab#877]
**Is your feature request related to a problem? Please describe.**
I have lots of schedules running and navigating the schedules list the has become really tedious since the table is not paginated and no filters are available.

**Describe the solution you'd like**
Adding an input to perform a client side fitlering will be enough for the moment. Later on, this can be expanded to support other filters (Run type, Node, Spider, etc)

**Describe alternatives you've considered**
I've considered adding server-side filtering, but this could take more time. If it's only client-side rendering, I can open a PR myself, while I get more comfortable with the codebase. My goal is to keep improving this schedules view, since it's the most important one for me.

**Comment by tikazyq** [comment]
Good idea! You more welcome to submit a PR rather than wait for the update, which might take forever. But we are definitely working on something to improve this project better.
