### ISSUE TITLE
定时任务执行失败

### ISSUE THREAD

**Issue by luqinghui** [crawlab-team/crawlab#878]
新建一个定时任务之后，直接点击操作栏中的运行，可以执行成功，但是等它到定时时间自动运行的时候却失败了。
![image](https://user-images.githubusercontent.com/5338140/100035345-e631c600-2e38-11eb-8e0c-26d6e0865f5f.png)
![image](https://user-images.githubusercontent.com/5338140/100035363-f3e74b80-2e38-11eb-8bcb-6c4d6eceba71.png)
自动调度的时候不知道为什么程序好像自己添加了几个参数，而建定时任务的时候并没有填写参数。

**Comment by tikazyq** [comment]
是可配置爬虫么？

**Comment by luqinghui** [comment]
> 是可配置爬虫么？

点了添加爬虫，我记得应该是在自定义tab中填写了一些内容后，又转到可配置tab选了模版，这样会出问题吗😂

**Comment by tikazyq** [comment]
重新再创建试一下吧

**Comment by luqinghui** [comment]
> 重新再创建试一下吧

我试过新添加爬虫，不知道为什么今天新建爬虫的时候，文件中只有spiderfile。之前添加的爬虫都会生成代码
新建的
![image](https://user-images.githubusercontent.com/5338140/100037723-b46f2e00-2e3d-11eb-9f4e-fa1fc12198f9.png)

以前的
![image](https://user-images.githubusercontent.com/5338140/100037872-f9936000-2e3d-11eb-89ef-cdbbbbd35bb5.png)

**Comment by tikazyq** [comment]
保存一下试试

**Comment by luqinghui** [comment]
> 保存一下试试

好的谢谢
