### ISSUE TITLE
爬虫模块分页问题

### ISSUE THREAD

**Issue by oldbabydriver** [crawlab-team/crawlab#880]
勾选显示100条数据的选项后，这个页面偶尔会在100条和10之间反复切换。不稳定。
除此之外，在选择页面显示10条，然后查看下一页或者某一页的时候，页面会在第一页和某一页之间反复切换，我选择了第三页，实际上页面展示的是第一页：

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
