### ISSUE TITLE
怎样运行多层目录结构下面的爬虫

### ISSUE THREAD

**Issue by chaowangwj** [crawlab-team/crawlab#882]
怎样运行多层目录结构下面的爬虫？项目迁移过来，一个目录下有多个爬虫，然后怎样 运行到指定目录去运行爬虫

**Comment by tikazyq** [comment]
cd /path/to/spider && scrapy crawl <spider_name>



在 2020-11-27 14:16:32，"chaowangwj" <notifications@github.com> 写道：

怎样运行多层目录结构下面的爬虫？项目迁移过来，一个目录下有多个爬虫，然后怎样 运行到指定目录去运行爬虫
