### ISSUE TITLE
重启子节点后 部分爬虫无法同步成功且导致这部分爬虫scrapy状态改变

### ISSUE THREAD

**Issue by Tan6668** [crawlab-team/crawlab#886]
1.多节点部署后，更新某个爬虫，部分子节点上同步失败，还保留的是以前的爬虫信息
2.重启某个子节点后，部分爬虫无法同步成功，并且会将同步失败的原本默认scrapy 状态为是的改为否

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
