### ISSUE TITLE
分布式爬虫任务，显示异常但实际仍在后台运行

### ISSUE THREAD

**Issue by mkdir700** [crawlab-team/crawlab#897]
**Bug 描述**
k8s上部署分布式爬虫
同一个scrapy任务多节点运行，一段时间后，后台任务显示异常但实际仍在后台运行。

**复现步骤**
该 Bug 复现步骤如下
1. 多节点运行同一个scrapy爬虫
2. 等待一段时间，可能几天

**期望结果**
1. 查询任务异常原因
2. 手动结束工作节点的爬虫任务

**截屏**

![image](https://user-images.githubusercontent.com/56359329/104082458-5ec9d600-5271-11eb-8220-943bb5224794.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
