### ISSUE TITLE
百万级日志数据时，正则匹配导致CPU负载过高

### ISSUE THREAD

**Issue by mkdir700** [crawlab-team/crawlab#900]
**Bug 描述**
爬虫任务过多时，对日志进行正则表达式，会造成高CPU负载。

设置了定时删除日志，但是没有效果

**复现步骤**

该 Bug 复现步骤如下

1. logs表数据量百万级别时
2. 打开任务列表页面，此时会遍历做正则查询（非常耗费性能）

**期望结果**

关闭正则匹配

**Comment by tikazyq** [comment]
下个版本会提供选择日志储存媒介的功能，mongo存日志开销会比较大，建议检查一下logs集合的索引是否正常

**Comment by mkdir700** [comment]
> 下个版本会提供选择日志储存媒介的功能，mongo存日志开销会比较大，建议检查一下logs集合的索引是否正常

支持！加油！
