### ISSUE TITLE
pip install crawlab 报错

### ISSUE THREAD

**Issue by 03128crz** [crawlab-team/crawlab#903]
Requirement already satisfied: zipp>=0.5 in d:\anaconda3\lib\site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7->crawlab) (3.4.0)
Building wheels for collected packages: crawlab
  Building wheel for crawlab (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Cai\\AppData\\Local\\Temp\\pip-install-w6n7l82g\\crawlab\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ca
i\\AppData\\Local\\Temp\\pip-install-w6n7l82g\\crawlab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file
__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Cai\AppData\Local\Temp\pip-wheel-_v0gqb82'
       cwd: C:\Users\Cai\AppData\Local\Temp\pip-install-w6n7l82g\crawlab\
  Complete output (89 lines):
  setup.py entered
  $PATH=D:\Anaconda3;D:\Anaconda3\Library\mingw-w64\bin;D:\Anaconda3\Library\usr\bin;D:\Anaconda3\Library\bin;D:\Anaconda3\Scripts;D:\Anaconda3\bin;D:\anaconda3\condabin;D:\Xshell 6;C:\Windows\system32;C:\Wind
ows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;D:\Anaconda3;E:\apache-maven-3.6.3\bin;D:\Git\cmd;D:\nodejs;E:\chromedriver;D:\jdk1.8.0_151\bin;D:\gradle-6.0
.1\bin;D:\nodejs1;C:\Program Files (x86)\Yarn\bin;C:\Users\Cai\AppData\Local\Microsoft\WindowsApps;D:\Microsoft VS Code\bin;C:\Users\Cai\AppData\Local\Programs\Fiddler;C:\Users\Cai\AppData\Local\Yarn\bin
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\crawlab
  copying crawlab\context_manager.py -> build\lib\crawlab
  copying crawlab\crawler.py -> build\lib\crawlab
  copying crawlab\magic_crawler.py -> build\lib\crawlab
  copying crawlab\proxy.py -> build\lib\crawlab
  copying crawlab\settings.py -> build\lib\crawlab
  copying crawlab\utils.py -> build\lib\crawlab
  copying crawlab\widgets.py -> build\lib\crawlab
  copying crawlab\_version.py -> build\lib\crawlab
  copying crawlab\__init__.py -> build\lib\crawlab
  running egg_info
  writing crawlab.egg-info\PKG-INFO
  writing dependency_links to crawlab.egg-info\dependency_links.txt
  writing requirements to crawlab.egg-info\requires.txt
  writing top-level names to crawlab.egg-info\top_level.txt
  reading manifest file 'crawlab.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'crawlab.egg-info\SOURCES.txt'
  creating build\lib\crawlab\static
  copying crawlab\static\extension.js -> build\lib\crawlab\static
  copying crawlab\static\index.js -> build\lib\crawlab\static
  copying crawlab\static\index.js.map -> build\lib\crawlab\static
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\crawlab
  copying build\lib\crawlab\context_manager.py -> build\bdist.win-amd64\wheel\.\crawlab
  copying build\lib\crawlab\crawler.py -> build\bdist.win-amd64\wheel\.\crawlab
  copying build\lib\crawlab\magic_crawler.py -> build\bdist.win-amd64\wheel\.\crawlab
  copying build\lib\crawlab\proxy.py -> build\bdist.win-amd64\wheel\.\crawlab
  copying build\lib\crawlab\settings.py -> build\bdist.win-amd64\wheel\.\crawlab
  creating build\bdist.win-amd64\wheel\crawlab\static
  copying build\lib\crawlab\static\extension.js -> build\bdist.win-amd64\wheel\.\crawlab\static
  copying build\lib\crawlab\static\index.js -> build\bdist.win-amd64\wheel\.\crawlab\static
  copying build\lib\crawlab\static\index.js.map -> build\bdist.win-amd64\wheel\.\crawlab\static
  copying build\lib\crawlab\utils.py -> build\bdist.win-amd64\wheel\.\crawlab
  copying build\lib\crawlab\widgets.py -> build\bdist.win-amd64\wheel\.\crawlab
  copying build\lib\crawlab\_version.py -> build\bdist.win-amd64\wheel\.\crawlab
  copying build\lib\crawlab\__init__.py -> build\bdist.win-amd64\wheel\.\crawlab
  running install_data
  creating build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data
  creating build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data\data
  creating build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data\data\share
  creating build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data\data\share\jupyter
  creating build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data\data\share\jupyter\nbextensions
  creating build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data\data\share\jupyter\nbextensions\crawlab
  copying crawlab\static\extension.js -> build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data\data\share\jupyter\nbextensions\crawlab
  copying crawlab\static\index.js -> build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data\data\share\jupyter\nbextensions\crawlab
  copying crawlab\static\index.js.map -> build\bdist.win-amd64\wheel\crawlab-0.1.0a8.data\data\share\jupyter\nbextensions\crawlab
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Cai\AppData\Local\Temp\pip-install-w6n7l82g\crawlab\setup.py", line 182, in <module>
      setup(**setup_args)
    File "D:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 326, in run
      self.run_command('install')
    File "D:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
      return orig.install.run(self)
    File "D:\Anaconda3\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "D:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Anaconda3\lib\distutils\command\install_data.py", line 56, in run
      dir = convert_path(f[0])
    File "D:\Anaconda3\lib\distutils\util.py", line 112, in convert_path
      raise ValueError("path '%s' cannot end with '/'" % pathname)
  ValueError: path 'etc/jupyter/nbconfig/notebook.d/' cannot end with '/'
  ----------------------------------------
  ERROR: Failed building wheel for crawlab
  Running setup.py clean for crawlab
Failed to build crawlab
Installing collected packages: crawlab
    Running setup.py install for crawlab ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Cai\\AppData\\Local\\Temp\\pip-install-w6n7l82g\\crawlab\\setup.py'"'"'; __file__='"'"'C:\\Users\\
Cai\\AppData\\Local\\Temp\\pip-install-w6n7l82g\\crawlab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __fi
le__, '"'"'exec'"'"'))' install --record 'C:\Users\Cai\AppData\Local\Temp\pip-record-ng4gu5z0\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda3\Include\crawlab'
         cwd: C:\Users\Cai\AppData\Local\Temp\pip-install-w6n7l82g\crawlab\
    Complete output (56 lines):
    setup.py entered
    $PATH=D:\Anaconda3;D:\Anaconda3\Library\mingw-w64\bin;D:\Anaconda3\Library\usr\bin;D:\Anaconda3\Library\bin;D:\Anaconda3\Scripts;D:\Anaconda3\bin;D:\anaconda3\condabin;D:\Xshell 6;C:\Windows\system32;C:\Wi
ndows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;D:\Anaconda3;E:\apache-maven-3.6.3\bin;D:\Git\cmd;D:\nodejs;E:\chromedriver;D:\jdk1.8.0_151\bin;D:\gradle-6
.0.1\bin;D:\nodejs1;C:\Program Files (x86)\Yarn\bin;C:\Users\Cai\AppData\Local\Microsoft\WindowsApps;D:\Microsoft VS Code\bin;C:\Users\Cai\AppData\Local\Programs\Fiddler;C:\Users\Cai\AppData\Local\Yarn\bin
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\crawlab
    copying crawlab\context_manager.py -> build\lib\crawlab
    copying crawlab\crawler.py -> build\lib\crawlab
    copying crawlab\magic_crawler.py -> build\lib\crawlab
    copying crawlab\proxy.py -> build\lib\crawlab
    copying crawlab\settings.py -> build\lib\crawlab
    copying crawlab\utils.py -> build\lib\crawlab
    copying crawlab\widgets.py -> build\lib\crawlab
    copying crawlab\_version.py -> build\lib\crawlab
    copying crawlab\__init__.py -> build\lib\crawlab
    running egg_info
    writing crawlab.egg-info\PKG-INFO
    writing dependency_links to crawlab.egg-info\dependency_links.txt
    writing requirements to crawlab.egg-info\requires.txt
    writing top-level names to crawlab.egg-info\top_level.txt
    reading manifest file 'crawlab.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'crawlab.egg-info\SOURCES.txt'
    creating build\lib\crawlab\static
    copying crawlab\static\extension.js -> build\lib\crawlab\static
    copying crawlab\static\index.js -> build\lib\crawlab\static
    copying crawlab\static\index.js.map -> build\lib\crawlab\static
    running install_lib
    running install_data
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Cai\AppData\Local\Temp\pip-install-w6n7l82g\crawlab\setup.py", line 182, in <module>
        setup(**setup_args)
      File "D:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "D:\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "D:\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:\Anaconda3\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "D:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Anaconda3\lib\distutils\command\install_data.py", line 56, in run
        dir = convert_path(f[0])
      File "D:\Anaconda3\lib\distutils\util.py", line 112, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'etc/jupyter/nbconfig/notebook.d/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Cai\\AppData\\Local\\Temp\\pip-install-w6n7l82g\\crawlab\\setup.p
y'"'"'; __file__='"'"'C:\\Users\\Cai\\AppData\\Local\\Temp\\pip-install-w6n7l82g\\crawlab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');
f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Cai\AppData\Local\Temp\pip-record-ng4gu5z0\install-record.txt' --single-version-externally-managed --compile --install-header
s 'D:\Anaconda3\Include\crawlab' Check the logs for full command output.

**Comment by tikazyq** [comment]
pip install crawlab-sdk
