### ISSUE TITLE
go的爬虫用不了，而且现在也不能安装依赖  用的docker安装方式

### ISSUE THREAD

**Issue by cumthxy** [crawlab-team/crawlab#906]
goroutine 976 [running]:
worker    | runtime/debug.Stack(0x0, 0x0, 0x0)
worker    | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
worker    | runtime/debug.PrintStack()
worker    | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
worker    | crawlab/services.WaitTaskProcess(0xc001746000, 0xc001c7db00, 0x24, 0xc000038460, 0xc, 0xbfff59a7c06d04ed, 0x7c373c24a, 0x2b4d4c0, 0x0, 0x0, ...)
worker    | 	/go/src/app/services/task.go:322 +0x17b
worker    | crawlab/services.ExecuteShellCmd(0xc001c7db30, 0x25, 0xc000038b80, 0xc, 0xc001c7db00, 0x24, 0xc000038460, 0xc, 0xbfff59a7c06d04ed, 0x7c373c24a, ...)
worker    | 	/go/src/app/services/task.go:393 +0xbf8
worker    | crawlab/services.ExecuteTask(0x0)
worker    | 	/go/src/app/services/task.go:607 +0xb98
worker    | crawlab/services.GetExecuteTaskFunc.func1()
worker    | 	/go/src/app/services/task.go:412 +0x2a
worker    | crawlab/lib/cron.FuncJob.Run(0xc0001ed5e0)
worker    | 	/go/src/app/lib/cron/cron.go:131 +0x25
worker    | crawlab/lib/cron.(*Cron).startJob.func1(0xc0000b7860, 0x138c1e0, 0xc0001ed5e0)
worker    | 	/go/src/app/lib/cron/cron.go:307 +0x65
worker    | created by crawlab/lib/cron.(*Cron).startJob
worker    | 	/go/src/app/lib/cron/cron.go:305 +0x73
worker    | 2021/02/05 15:13:54 error exit error, exit code: 100
worker    | 2021/02/05 15:13:54 error [Worker 0] exit status 100

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
