### ISSUE TITLE
中文长日志输出问题会导致crawlab运行中止且没有错误日志

### ISSUE THREAD

**Issue by eliaozi** [crawlab-team/crawlab#907]
**Describe the bug**
中文长日志输出问题会导致crawlab运行中止且没有错误日志

**To Reproduce**
命令`python3 website/abc99.py`直接打印request请求返回的response.content日志，会导致输出日志长度（或许是中文编码）问题异常中止且没有错误日志。
命令`python3 website/abc99.py >abc99.log`输出到文件一切正常。

**Expected behavior**
输出中文长日志应该正常运行

**Screenshots**

**Comment by tikazyq** [comment]
日志是啥，可以发出来

**Comment by eliaozi** [comment]
日志文件如下
`simple post raw https://index.sci99.com/api/zh-cn/dataitem/datavalue
start post...
dumped data:b'{"type": "1", "path1": "\xe9\x80\xa0\xe7\xba\xb8\xe8\xa1\x8c\xe4\xb8\x9a\xe4\xbb\xb7\xe6\xa0\xbc\xe6\x8c\x87\xe6\x95\xb0", "path2": "", "path3": "", "path4": "", "level": 0, "hy": "\xe9\x80\xa0\xe7\xba\xb8"}'
success:200 https://index.sci99.com/api/zh-cn/dataitem/datavalue
encoding none
1.200
2.utf-8
2.1 response text {"DataItem":{"DataTypeID":201,"DataName":"造纸行业价格指数","DIID":58222,"DItemDTypeID":"848","Digits":2,"Level":1,"ClassID":null,"URL":"https://paper.sci99.com/","ProductName":"造纸","Fpname":"造纸","ProductID":0,"ProductType":0,"AnnexURL":"/datastore/annex/58222.pdf","NewsSccids":"1986,1996,2001,2002,2011,2012,2963,2006,2007","AnalyzeSccids":"2013,1988,1989,1990,1993,1994,1995,1998,1999,2000,2008,2009,2010,2003,2004,2005"},"List":[{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1375.76,"Change":24.36,"ChangeRate":1.8,"DataDate":"2021/02/22","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1351.39,"Change":13.36,"ChangeRate":1.0,"DataDate":"2021/02/19","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1338.04,"Change":2.33,"ChangeRate":0.17,"DataDate":"2021/02/18","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1335.71,"Change":0.06,"ChangeRate":0.0,"DataDate":"2021/02/10","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1335.65,"Change":1.14,"ChangeRate":0.09,"DataDate":"2021/02/09","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1334.51,"Change":0.15,"ChangeRate":0.01,"DataDate":"2021/02/08","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1334.36,"Change":0.83,"ChangeRate":0.06,"DataDate":"2021/02/05","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1333.53,"Change":-0.11,"ChangeRate":-0.01,"DataDate":"2021/02/04","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1333.64,"Change":-1.62,"ChangeRate":-0.12,"DataDate":"2021/02/03","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1335.27,"Change":0.0,"ChangeRate":0.0,"DataDate":"2021/02/02","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1335.27,"Change":5.41,"ChangeRate":0.41,"DataDate":"2021/02/01","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1329.86,"Change":3.02,"ChangeRate":0.23,"DataDate":"2021/01/29","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1326.84,"Change":2.39,"ChangeRate":0.18,"DataDate":"2021/01/28","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1324.45,"Change":2.7,"ChangeRate":0.2,"DataDate":"2021/01/27","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1321.76,"Change":5.34,"ChangeRate":0.41,"DataDate":"2021/01/26","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false},{"DataName":"造纸行业价格指数","DIID":58222,"DataTypeID":201,"MDataValue":1316.42,"Change":null,"ChangeRate":null,"DataDate":"2021/01/25","ChangeValue":null,"ChangePercent":null,"Level":0,"Fpname":null,"IsHasExplain":false}],"News":{"news":[{"NewsKey":37563247,"Title":"山东天地缘纸业瓦楞纸价格快报","Pubtime":"2021-02-23T09:44:50.21"},{"NewsKey":37563174,"Title":"河北鼎泰纸业瓦楞纸价格上调","Pubtime":"2021-02-23T09:43:32.243"},{"NewsKey":37563111,"Title":"河南新乡鸿泰纸业白板纸价格快讯","Pubtime":"2021-02-23T09:42:01.693"},{"NewsKey":37563060,"Title":"广东理文造纸箱板纸价格快讯","Pubtime":"2021-02-23T09:41:01.917"},{"NewsKey":37562936,"Title":"湖北长江汇丰纸业白废采购价格上调","Pubtime":"2021-02-23T09:38:53.04"}],"analyze":[{"NewsKey":37561430,"Title":"纸浆——木浆市场早间提示（20210223）","Pubtime":"2021-02-23T08:59:22.82"},{"NewsKey":37561375,"Title":"废纸——国废报纸市场早间提示（20210223）","Pubtime":"2021-02-23T08:57:36.457"},{"NewsKey":37561307,"Title":"废纸——国废黄板纸市场早间提示（20210223）","Pubtime":"2021-02-23T08:55:40"},{"NewsKey":37561242,"Title":"纸浆——非木浆市场早间提示（20210223）","Pubtime":"2021-02-23T08:53:45.79"},{"NewsKey":37561080,"Title":"废纸——国废书本纸早间提示（20210223）","Pubtime":"2021-02-23T08:50:05"}]}}`

其中2.1 response text这行会导致脚本异常中止且没有日志

**Comment by tikazyq** [comment]
日志目前是写到mongo里的，可能是内容太长了导致写入失败。下个版本会迁移到其他储存媒介，这个问题应该就可以解决了

**Comment by eliaozi** [comment]
测试了一下，还真是这个问题，我把日志粘贴到logs collection发现报错了。
<img width="1007" alt="WX20210223-213257@2x" src="https://user-images.githubusercontent.com/4178650/108850820-bacc9c00-761e-11eb-841b-4fef64116dac.png">

**Comment by tikazyq** [comment]
建议输出尽可能少的日志，防止报错

**Comment by eliaozi** [comment]
现在通过关闭长日志输出来规避运行中止问题。感谢支持
