### ISSUE TITLE
新搭建的crawlab项目，没有爬虫任务的情况下，正常运行17小时后，cpu占用过高

### ISSUE THREAD

**Issue by yonggithub** [crawlab-team/crawlab#908]
**请描述该需求尝试解决的问题**
如题，cpu占用异常
![image](https://user-images.githubusercontent.com/25076827/108800136-49b0c880-75cd-11eb-994e-310a20c8f4bb.png)

**请描述您认为可行的解决方案**
1. 减少不必要的后台任务，提高运行资源占用的稳定性
2. 重启容器后，发现问题暂时有改善
谢谢

**考虑过的替代方案**
暂无

**Comment by yonggithub** [comment]
补充回答：
以下是我其他容器的cpu占用情况，之前一直用tfschedule 作为分布式任务系统，最近尝试crawlab.发现确实不错。功能比tfschedule丰富不少。不过crawlab硬件资源占用多且不稳定，cpu占用不断在10%-50%之间变动。而tfschedule稳定在3.75%。
希望作者可以考虑优化下crawlab的资源占用问题，望采纳谢谢。祝crawlab越做越好。

![image](https://user-images.githubusercontent.com/25076827/108800521-5681ec00-75ce-11eb-9f28-703d17ba558f.png)

**Comment by tikazyq** [comment]
和数据库是在同一个机器上么？

**Comment by yonggithub** [comment]
> 和数据库是在同一个机器上么？

是呀，现在正常情况下3.8%左右，挂两个python调度，都是1分钟执行一次的。发现cpu时不时会冲上50%，极少时候会冲上100%。大部分时候都是3.8%。

**Comment by tikazyq** [comment]
可能是worker定期获取任务导致的，可以降低单个节点worker数量试试
