### ISSUE TITLE
复制git同步的爬虫不会自动更新

### ISSUE THREAD

**Issue by JQ-K** [crawlab-team/crawlab#910]
**Bug 描述**
当复制一份git同步的爬虫，如果内容更新了 原同步爬虫会更新，但是复制的爬虫不会更新

**复现步骤**
该 Bug 复现步骤如下
1. 使用git同步，开启自动自动同步
2. 复制一个新爬虫
3. git 内容更新 复制的爬虫不会更新

**期望结果**
复制的爬虫能和源爬虫一样随git 自动更新

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
