### ISSUE TITLE
提示您的网络发生异常，无法连接服务器

### ISSUE THREAD

**Issue by fengfumin** [crawlab-team/crawlab#911]
Request URL: http://10.0.0.101:8000/nodes/6039c407dea1b3001b875b47/langs
Request Method: OPTIONS
Status Code: 204 No Content

打开节点
一直有请求发送端口：8000/nodes/6039c407dea1b3001b875b47/langs 然后有状态204,200，还有失败的，页面提示您的网络发生异常，无法连接服务器

工作节点显示不了安装的语言，都是空白

**Comment by tikazyq** [comment]
有主节点日志么？

**Comment by CatAtHome** [comment]
我也遇到同样的问题 主节点日志怎么看？

**Comment by tikazyq** [comment]
查看节点日志方法: 
1. 通过 `docker ps` 查看容器，获取容器名称
2. 执行命令 `docker logs --tail <行数> <容器名称>` 查看日志

**Comment by CatAtHome** [comment]
2021/03/04 14:02:53 error RpcClientFunc error: redigo: nil returned
goroutine 23084 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x25
crawlab/services/rpc.ClientFunc.func1(0x0, 0x0, 0x1204b56, 0x8, 0xc00071894b, 0x18, 0xc002880840, 0x3c, 0x0, 0x0, ...)
        /go/src/app/services/rpc/base.go:44 +0x627
crawlab/services/rpc.(*GetLangService).ClientHandle(0xc00279b200, 0xc00279b200, 0x11ffe91, 0x4, 0xc0025cc508)
        /go/src/app/services/rpc/get_lang.go:28 +0x84
crawlab/services/rpc.GetLangRemote(0xc00071894b, 0x18, 0x1209790, 0xd, 0x1208b2c, 0xc, 0xc000692220, 0x2, 0x2, 0x0, ...)
        /go/src/app/services/rpc/get_lang.go:76 +0x1d8
crawlab/services.GetLangInstallStatus(0xc00071894b, 0x18, 0x1209790, 0xd, 0x1208b2c, 0xc, 0xc000692220, 0x2, 0x2, 0x0, ...)
        /go/src/app/services/system.go:99 +0x438
crawlab/services.GetLangList(0xc00071894b, 0x18, 0x1, 0x11fee2f, 0x2)
        /go/src/app/services/system.go:71 +0x13e
crawlab/routes.GetLangList(0xc0005ca780)
        /go/src/app/routes/system.go:33 +0xb0
github.com/gin-gonic/gin.(*Context).Next(0xc0005ca780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab/middlewares.AuthorizationMiddleware.func1(0xc0005ca780)
        /go/src/app/middlewares/auth.go:46 +0x1df
github.com/gin-gonic/gin.(*Context).Next(0xc0005ca780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab/middlewares.CORSMiddleware.func1(0xc0005ca780)
        /go/src/app/middlewares/cors.go:17 +0x3a7
github.com/gin-gonic/gin.(*Context).Next(0xc0005ca780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc0005ca780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 +0x65
github.com/gin-gonic/gin.(*Context).Next(0xc0005ca780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0005ca780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0xe5
github.com/gin-gonic/gin.(*Context).Next(0xc0005ca780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00015e280, 0xc0005ca780)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x67a
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00015e280, 0x13a0b00, 0xc0002249a0, 0xc0023b4a00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0002240e0, 0x13a0b00, 0xc0002249a0, 0xc0023b4a00)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0019f7ae0, 0x13a6080, 0xc0025a0600)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
2021/03/04 14:02:53 error RpcClientFunc error: redigo: nil returned
goroutine 21266 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x25
crawlab/services/rpc.ClientFunc.func1(0x0, 0x0, 0x1204b56, 0x8, 0xc00198c74b, 0x18, 0xc0027ce180, 0x3c, 0x0, 0x0, ...)
        /go/src/app/services/rpc/base.go:44 +0x627
crawlab/services/rpc.(*GetLangService).ClientHandle(0xc0028339e0, 0xc0028339e0, 0x11ffe91, 0x4, 0xc00264ebc8)
        /go/src/app/services/rpc/get_lang.go:28 +0x84
crawlab/services/rpc.GetLangRemote(0xc00198c74b, 0x18, 0x1202c4c, 0x7, 0x12034b1, 0x7, 0xc0006bc700, 0x2, 0x2, 0x0, ...)
        /go/src/app/services/rpc/get_lang.go:76 +0x1d8
crawlab/services.GetLangInstallStatus(0xc00198c74b, 0x18, 0x1202c4c, 0x7, 0x12034b1, 0x7, 0xc0006bc700, 0x2, 0x2, 0x0, ...)
        /go/src/app/services/system.go:99 +0x438
crawlab/services.GetLangList(0xc00198c74b, 0x18, 0x1, 0x11fee2f, 0x2)
        /go/src/app/services/system.go:71 +0x13e
crawlab/routes.GetLangList(0xc001e5cc30)
        /go/src/app/routes/system.go:33 +0xb0
github.com/gin-gonic/gin.(*Context).Next(0xc001e5cc30)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab/middlewares.AuthorizationMiddleware.func1(0xc001e5cc30)
        /go/src/app/middlewares/auth.go:46 +0x1df
github.com/gin-gonic/gin.(*Context).Next(0xc001e5cc30)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab/middlewares.CORSMiddleware.func1(0xc001e5cc30)
        /go/src/app/middlewares/cors.go:17 +0x3a7
github.com/gin-gonic/gin.(*Context).Next(0xc001e5cc30)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc001e5cc30)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 +0x65
github.com/gin-gonic/gin.(*Context).Next(0xc001e5cc30)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc001e5cc30)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0xe5
github.com/gin-gonic/gin.(*Context).Next(0xc001e5cc30)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00015e280, 0xc001e5cc30)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x67a
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00015e280, 0x13a0b00, 0xc001977a40, 0xc002b81a00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0002240e0, 0x13a0b00, 0xc001977a40, 0xc002b81a00)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0004ee460, 0x13a6080, 0xc0022ca600)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
[GIN] 2021/03/04 - 14:02:53 | 200 |          8m4s |       127.0.0.1 | GET      "/nodes/604073727fb11b002184b3b6/langs"
[GIN] 2021/03/04 - 14:02:53 | 200 |    3.527274ms |       127.0.0.1 | GET      "/nodes/604073687fb11b002184b3a3/langs"

**Comment by tikazyq** [comment]
看起来没啥问题

**Comment by CatAtHome** [comment]
可是为什么加载不了工作节点的信息

**Comment by CatAtHome** [comment]
主节点内部nginx日志返回的状态码不是200而是499

**Comment by CatAtHome** [comment]
2021/03/04 15:33:37  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:38  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:39  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:40  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:41  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:42  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:43  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:44  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:45  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:46  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:47  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:48  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:49  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:50  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:51  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:52  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:53  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:54  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:55  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:56  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:57  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:58  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:33:59  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:34:00  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:34:01  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:34:02  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:34:03  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:34:04  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:34:05  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:34:06  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
2021/03/04 15:34:07  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
这个是工作节点日志

**Comment by holding-on** [comment]
请问你的问题解决了吗

**Comment by holding-on** [comment]
请问你的问题解决了吗

**Comment by tikazyq** [comment]
可以删掉mongo里的nodes后重启主节点

**Comment by holding-on** [comment]
请问具体该怎么操作呢？

**Comment by holding-on** [comment]
请问具体该怎么操作呢

**Comment by sjsongsong** [comment]
请问针对工作节点warn Get current node info from database failed. Will after 1.000000 seconds, try again. error=not found的这个问题，是否解决了那？发现问题在于mongo始终接受不到工作节点的信息，手动写入节点信息后，节点状态始终为offline，无法使用。不知道对此是否有解决办法？
