### ISSUE TITLE
更改用户密码之后已经登录的用户仍然在线

### ISSUE THREAD

**Issue by DearXB** [crawlab-team/crawlab#913]
**Bug 描述**
更改了admin的密码，应该是已经登录的admin用户强制退出重新登录，但是此用户任然在线，并且可以在次更改密码。

**截屏**
![截屏1](http://static-docs.crawlab.cn/login.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
