### ISSUE TITLE
当任务发生错误时，不能实时发送消息

### ISSUE THREAD

**Issue by haidongsong** [crawlab-team/crawlab#914]
**请描述该需求尝试解决的问题**
当任务发生错误时，要实时接收到消息。

**请描述您认为可行的解决方案**
例如，添加 xxx 功能能够解决问题。

**考虑过的替代方案**
例如，如果用 xxx，也能解决该问题。

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
