### ISSUE TITLE
当任务结束，错误数未正确统计

### ISSUE THREAD

**Issue by haidongsong** [crawlab-team/crawlab#915]
**Bug 描述**
当任务结束，错误数未正确统计，而且错误发生的时候，不会实时给我发送消息。

实际上是有错误的
**截屏**
![image](https://user-images.githubusercontent.com/20490635/109643791-adb82b80-7b8f-11eb-92b6-2a374a3467d8.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
