### ISSUE TITLE
BUG: 无法在Web界面上安装语言，Driver

### ISSUE THREAD

**Issue by HaoKunT** [crawlab-team/crawlab#917]
**Bug 描述**
无法在Web界面上安装语言，Driver，报错如下：

```
start task error: fork/exec /usr/bin/sh: no such file or directory
```

**复现步骤**
该 Bug 复现步骤如下
1. 在`节点-安装`中，选择安装一个新的语言

**期望结果**
安装成功

**版本**
0.5.1

**截屏**
![image](https://user-images.githubusercontent.com/16379361/109931924-7a4add80-7d04-11eb-9d14-7cf8bd309d0d.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
