### ISSUE TITLE
how can i make to run my crawler on crawlab web ?

### ISSUE THREAD

**Issue by doi-h** [crawlab-team/crawlab#920]
i have found scrapy dashboard. and i found crawlab it looked better than others.

before i pay to use premium service of crawlab, i wanted to check if my crawler code can work well on crawlab dashboard or not. but there is some issue.
if you don't mind, can you tell me your advice ?

my code tree is this. i made .zip from red dot(jeonjuevent) to other red dot(scrapy.cfg).

![image](https://user-images.githubusercontent.com/60310091/110627315-2ac54f80-81e5-11eb-9cfd-15f0a6c8f6c6.png)

then i upload it on crawlab dashboard. like this.

![image](https://user-images.githubusercontent.com/60310091/110626345-f2714180-81e3-11eb-9e62-c940f4496d51.png)

then i tried to run it. like this. but it showed. there is 'no module named 'selenium'

![image](https://user-images.githubusercontent.com/60310091/110626905-a8d52680-81e4-11eb-991c-f7e6b768acb1.png)

so, i added 'selenium' in Dockerfile and Dockerfile.local in crawlab code. like this.
even in .zip file there is requirements.txt that involve selenium.
```
RUN pip install scrapy pymongo bs4 requests crawlab-sdk scrapy-splash selenium
RUN pip install scrapy pymongo bs4 requests crawlab-sdk scrapy-splash selenium -i https://pypi.tuna.tsinghua.edu.cn/simple
```
but it kept to show same error.

and if i dont check Is Scrapy(green button) it showed same error on the log.

i cant find how so solve this problem.

can you help me?

**Comment by tikazyq** [comment]
I think the reason of this exception is quite clear here: `No module named 'selenium'`. This is because you haven't installed the correct dependencies such as selenium, chromedriver, etc. Please refer to the documentation to install dependencies before running crawlers. 

If you have any further question, please contact my on Wechat, and my ID is tikazyq1

**Comment by doi-h** [comment]
thank you for your comment.  i will send msg on Wechat.

**Comment by tikazyq** [comment]
Can I close this issue?

**Comment by doi-h** [comment]
yes!
