### ISSUE TITLE
how can i deploy crawlab dashboard on AWS EC2 or AWS EB ?

### ISSUE THREAD

**Issue by doi-h** [crawlab-team/crawlab#922]
my crawler can work on crawlab dashborad thx! so collected data can enter to mongodb atlas.

and i wonder how to deploy this crawler+crawlab dashboard on AWS EC2 or AWS EB.

i considered this page.
https://docs.crawlab.cn/en/CI/ 
https://docs.crawlab.cn/en/CI/Git.html

but i cant find how to deploy crawlab dashboard + my scrapy code on EC2 or EB ....

plz can you help me ?

**Comment by tikazyq** [comment]
this might not be a bug.

**Comment by doi-h** [comment]
oh... sorry ta that's not bug. that is question...
