### ISSUE TITLE
Crawlab leaks git credentials to webhooks

### ISSUE THREAD

**Issue by palle-k** [crawlab-team/crawlab#923]
**Describe the bug**  
When configuring a spider with is git set to true and then using a username and password for git access, the credentials are leaked to web hooks.

**To Reproduce**  
1. Create a spider
2. Set is git to true
3. In the git configuration, enter a git username and password
4. Add a web hook for the spider
5. Run the spider

**Expected Behavior**  
Credentials should not be sent to the web hook.

**Actual Behavior**  
The web hook receives the username **and password** that have been set as the git credentials.

**Comment by tikazyq** [comment]
Sharp eye! This is well noted.
