### ISSUE TITLE
Incorrect result count reported to webhook

### ISSUE THREAD

**Issue by palle-k** [crawlab-team/crawlab#924]
**Describe the bug**  
When a spider completes and a webhook is triggered, the `result_count` property is 0 instead of the actual number of results.

**To Reproduce**  
1. Create a new spider
2. Add a web hook for the spider
3. Run the spider

**Expected Behavior**  
The result count reported on the user interface should match the result count reported to the webhook.

**Notes**  
- The crawler was a short running job that produced 6 results in 2 seconds.
- Tried with latest master and 0.5.1 release

**Comment by tikazyq** [comment]
It could be a **short task** issue. But will double check. Thanks for the bug report.
