### ISSUE TITLE
Anomaly detection does not report errors

### ISSUE THREAD

**Issue by palle-k** [crawlab-team/crawlab#925]
**Describe the bug**  
When running a task that completes with at least one error log output, the task is not marked as having any anomalies (as shown in the documentation) and an `error_log_count` of 0 is reported to web hooks.

The following messages have been logged:

```
Traceback (most recent call last):
ValueError: fake value error
2021-03-16 20:24:39 [root] ERROR this is some logged error message
```

The messages are highlighted in red and partially underlined in the task log shown on the Crawlab interface, indicating that they should have been detected as anomalies.

**To Reproduce**  
1. Create a spider that produces some error log messages
2. Optional: Add a web hook to the spider
3. Run the spider

**Expected behavior**  
The task should be reported as having produced an anomaly.

**Notes**  
- The task was short running with a total run time of 2 seconds.
- Tried with latest master and 0.5.1 release

**Comment by tikazyq** [comment]
It could be **short issue** thing. You can try longer tasks, just in case.
