### ISSUE TITLE
关于scrapy-redis的问题

### ISSUE THREAD

**Issue by ykiller2012** [crawlab-team/crawlab#926]
如果爬虫代码中本身使用了scrapy-redis，是否和平台自身的redis调度产生冲突，或者说爬虫代码中使用通用框架scrapy即可，无需使用redis-scrapy

**Comment by tikazyq** [comment]
不会冲突，可以自定义的

**Comment by ykiller2012** [comment]
> 不会冲突，可以自定义的

好的，谢谢
