### ISSUE TITLE
缺少依赖bug

### ISSUE THREAD

**Issue by nieweiming** [crawlab-team/crawlab#927]
**Bug 描述**
例如，当爬虫类型为scrapy时，在爬虫类中定义成员，执行execjs方法，出现bug。

**复现步骤**
该 Bug 复现步骤如下
1. 编写一个爬虫类， 在类中写一个类级成员属性，其为用execjs执行的结果，哪怕执行一个空字符串；
2. 节点安装execjs库：pip install pyexecjs;
3. crawlab检查代码时会报异常：请检查您的代码是否缺少依赖；
4. 线下运行没问题，依赖也安装了；
5. 由于crawlab检查异常，没法执行运行操作；

**期望结果**
能工作。

**截屏**
![image](https://user-images.githubusercontent.com/38031792/111448379-51393c80-8749-11eb-88c0-2015ab255f23.png)

![image](https://user-images.githubusercontent.com/38031792/111448443-601fef00-8749-11eb-8cad-ce29fc7eda69.png)

![image](https://user-images.githubusercontent.com/38031792/111449182-1d124b80-874a-11eb-9920-f0b637785823.png)

![image](https://user-images.githubusercontent.com/38031792/111448619-8f366080-8749-11eb-9655-0d25554d866d.png)

**Comment by tikazyq** [comment]
后台报错了么

**Comment by nieweiming** [comment]
> 后台报错了么

docker部署的，怎么看后台？

**Comment by tikazyq** [comment]
docker logs <容器名>

**Comment by nieweiming** [comment]
> docker logs <容器名>

这是前端的错误提示：
![image](https://user-images.githubusercontent.com/38031792/111566890-f818e980-87d8-11eb-8f88-f03a803c4116.png)


这是docker logs 中的日志：
![image](https://user-images.githubusercontent.com/38031792/111566727-a96b4f80-87d8-11eb-9be0-13906909de6e.png)


好像看不到什么信息。

yaml文件中配置的日志路径也没有日志文件输出，进入docker里面的路径也没有日志。

其他方式可以看到更详细的错误提示？
