### ISSUE TITLE
关于批量执行爬虫时不能写入参数以及批量建立爬虫定时任务是不能写入参数

### ISSUE THREAD

**Issue by MrFue** [crawlab-team/crawlab#928]
参数框能点击，不能写入任何数据进去
![image](https://user-images.githubusercontent.com/44761591/111579959-d710c280-87f1-11eb-9577-8a353a55a891.png)

![image](https://user-images.githubusercontent.com/44761591/111580052-f576be00-87f1-11eb-829b-799673c825db.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
