### ISSUE TITLE
crawlab如何使用http代理？

### ISSUE THREAD

**Issue by ykiller2012** [crawlab-team/crawlab#929]
由于某些原因，需要将crawlab部署在没有外网的机器A上，但是crawlab似乎需要外网来安装一些依赖或者是下载一些文档，此时，我有另一台机器B是可以接入外网的，在这台机器B上我配置了http代理服务，那么请问如何在crawlab中配置我这个机器B上的http代理，使得crawlab服务可以访问外网？

**Comment by tikazyq** [comment]
能详细说一下哪些服务是需要代理的？

**Comment by ykiller2012** [comment]
> 能详细说一下哪些服务是需要代理的？

是需要整个crawlab服务容器通过代理访问外网，目前应该在docker上配置，谢谢了

**Comment by tikazyq** [comment]
这不是crawlab关注的范畴，你可以通过全局设置环境变量等方式来实现
