### ISSUE TITLE
Worker restart after random time.

### ISSUE THREAD

**Issue by huyhandes** [crawlab-team/crawlab#930]
I was deploy the k8s of crawlab and after a random range of time, my k8s pod auto terminating and created new one.
The only error log I found is in the following image:
<img width="473" alt="Screen Shot 2021-03-20 at 11 01 05 AM" src="https://user-images.githubusercontent.com/43632522/111858561-98534780-896c-11eb-91f8-2f4b7cd4ed44.png">

**Comment by tikazyq** [comment]
is there any other error logs?

**Comment by huyhandes** [comment]
The log is repeatedly appear over time.
<img width="522" alt="Screen Shot 2021-03-20 at 2 30 14 PM" src="https://user-images.githubusercontent.com/43632522/111862614-e2e2bd00-8988-11eb-92d7-9792d403d59c.png">

**Comment by tikazyq** [comment]
seems it's not the real error that caused the breakdown. can you repeat?

**Comment by huyhandes** [comment]
I'm just deploy the k8s worker, then let it stay there without running any process on that worker, but the k8s still randomly terminating my pod then redeploy the new one.
