### ISSUE TITLE
使用docker-compose部署，访问前端页面请求404

### ISSUE THREAD

**Issue by githubwst** [crawlab-team/crawlab#931]
**Bug 描述**
访问前端页面时，会有两个请求404

**复现步骤**
该 Bug 复现步骤如下
1. 使用官方文档中的ym启动docker-compose
2. 访问前端页面
3. 弹出请求失败404

**期望结果**
xxx 能工作。

**截屏**
![image](https://user-images.githubusercontent.com/26899426/111946464-844b4980-8b16-11eb-84b8-f4ef54684535.png)

**Comment by tikazyq** [comment]
去掉配置文件中的api address
