### ISSUE TITLE
运行 报 OSError: could not get source code

### ISSUE THREAD

**Issue by JQ-K** [crawlab-team/crawlab#932]
**Bug 描述**
当在测试环境没有使用crawlab 部署运行时正常运行
当使用crawlab 运行时 中间会弹出报错 ：OSError: could not get source code

**期望结果**
crawlab 和测试环境运行一致

**截屏**
![image](https://user-images.githubusercontent.com/14874834/111971307-2a0eb080-8b37-11eb-8576-622d649803f0.png)
![image](https://user-images.githubusercontent.com/14874834/111971383-3e52ad80-8b37-11eb-9e75-ff75b4433eda.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
