### ISSUE TITLE
个别任务不能停止。提示：您的网络发生异常，无法连接服务器

### ISSUE THREAD

**Issue by liziqiang0523** [crawlab-team/crawlab#936]
**Bug 描述**
例如，当 点开进行中的任务 时，停止  功能不工作。

**复现步骤**
该 Bug 复现步骤如下
1. 
2. 
3. 

**期望结果**
停止任务 能正常工作工作。

**截屏**
![截屏1](http://static-docs.crawlab.cn/login.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
