### ISSUE TITLE
前端登录页面报错404

### ISSUE THREAD

**Issue by ykiller2012** [crawlab-team/crawlab#938]
**Bug 描述**
docker-compose部署完毕后，浏览器输入地址后，http://10.36.0.137:10000/127.0.0.1:8000/releases/latest 404 not defined，
yml文件
version: '3.8'
services:
    crawlab-master:
        image: tikazyq/crawlab:latest
        container_name: crawlab-master
        environment:
            CRAWLAB_API_ADDRESS: "127.0.0.1:8000"
            CRAWLAB_SERVER_MASTER: "Y"
            CRAWLAB_MONGO_HOST: "crawlab-mongo"
            CRAWLAB_MONGO_DB: "crawlab_db"
            CRAWLAB_MONGO_PORT: "27017"
            CRAWLAB_MONGO_USERNAME: "root"
            CRAWLAB_MONGO_PASSWORD: "root"
            CRAWLAB_MONGO_AUTHSOURCE: "admin"
            CRAWLAB_REDIS_ADDRESS: "crawlab-redis"
            CRAWLAB_REDIS_PORT: "6379"
            CRAWLAB_REDIS_DATABASE: "1"
            CRAWLAB_REDIS_PASSWORD: "abc"
            SPLASH_URL: "http://crawlab-splash:8050"
            GIN_MODE: "release"
            http_proxy: "http://10.33.32.14:8888"
            https_proxy: "http://10.33.32.14:8888"
            #CRAWLAB_SERVER_REGISTER_TYPE: "ip"
            #CRAWLAB_SERVER_REGISTER_IP: "127.0.0.1"
        volumes:
            - ${PWD}/data/.config:/root/.config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "10000:8080" # frontend
            - "10001:8000" # backend
        networks:
            - crawlab
        depends_on:
            - crawlab-mongo
            - crawlab-redis
            - crawlab-splash

**复现步骤**
浏览器请求登录页面，即可弹出错误，查看crawlab容器日志，未发现任何错误，如截图

**期望结果**
登录页面不弹出任何错误

**截屏**
![image](https://user-images.githubusercontent.com/17539950/112459790-3003cc00-8d99-11eb-9136-7518f5126cc0.png)
![image](https://user-images.githubusercontent.com/17539950/112459828-3abe6100-8d99-11eb-86e6-1c983ad8bab5.png)
![image](https://user-images.githubusercontent.com/17539950/112459935-56c20280-8d99-11eb-9fe2-76a25aa2e4c0.png)

**Comment by hantmac** [comment]
检查下 mongodb

**Comment by tikazyq** [comment]
`CRAWLAB_API_ADDRESS: "127.0.0.1:8000"` 这一行去掉

**Comment by ykiller2012** [comment]
> `CRAWLAB_API_ADDRESS: "127.0.0.1:8000"` 这一行去掉
 去掉之后好了，谢谢
