### ISSUE TITLE
上传scrapy爬虫项目后，点击“配置scrapy”报错

### ISSUE THREAD

**Issue by ykiller2012** [crawlab-team/crawlab#939]
**Bug 描述**
上传scrapy爬虫项目后，点击“配置scrapy”时报错
docker-compose.yaml如截图所示

**复现步骤**
该 Bug 复现步骤如下
1. docker-compose启动服务
2. crawlab upload上传爬虫成功
3. 通过浏览器UI在“爬虫”->"scrapy配置"中报错，如图
4. 查看crawlab容器日志如图

**期望结果**
scrapy工程可以正常配置。

**截屏**
![image](https://user-images.githubusercontent.com/17539950/112951159-a45db700-916d-11eb-9857-dc568b476a02.png)
![image](https://user-images.githubusercontent.com/17539950/112951218-b17aa600-916d-11eb-893d-e5fc562ca374.png)
![image](https://user-images.githubusercontent.com/17539950/112951453-f43c7e00-916d-11eb-93b5-8589fd97d905.png)

**Comment by ykiller2012** [comment]
爬虫已经上传成功
![image](https://user-images.githubusercontent.com/17539950/112952993-a9bc0100-916f-11eb-8cfc-2db4538b4fb8.png)
进入crawlab容器也可以看到此目录
![image](https://user-images.githubusercontent.com/17539950/112953121-c9532980-916f-11eb-81b4-270e66932705.png)
但是日志却报错Not Found此目录
![image](https://user-images.githubusercontent.com/17539950/112952904-94df6d80-916f-11eb-9d96-2491ffa2acbe.png)

**Comment by eethan212** [comment]
我也有同样的问题 我的scrapy settings的内容是
![image](https://user-images.githubusercontent.com/50071772/117630153-7bd5cd80-b1ad-11eb-8af7-840794ec27d3.png)

**Comment by eethan212** [comment]
> 我也有同样的问题 我的scrapy settings的内容是
> ![image](https://user-images.githubusercontent.com/50071772/117630153-7bd5cd80-b1ad-11eb-8af7-840794ec27d3.png)

![image](https://user-images.githubusercontent.com/50071772/117630275-9c9e2300-b1ad-11eb-88b2-7f1aecd92984.png)

**Comment by eethan212** [comment]
我也有同样的问题 我的scrapy settings的内容是
![image](https://user-images.githubusercontent.com/50071772/117630350-b0e22000-b1ad-11eb-8d52-ab0c3188dfc8.png)
![image](https://user-images.githubusercontent.com/50071772/117630417-bf303c00-b1ad-11eb-878e-13f605755fd7.png)

**Comment by eethan212** [comment]
@ykiller2012  能帮我看一下问题吗

**Comment by ykiller2012** [comment]
> @ykiller2012 能帮我看一下问题吗
settings中不可使用变量，不可以有import
