### ISSUE TITLE
start task error: exec: "cmd": executable file not found in %PATH%

### ISSUE THREAD

**Issue by zxshiwo** [crawlab-team/crawlab#941]
之前可以运行爬虫,不知道为啥现在报错了,没有改动过什么东西

![image](https://user-images.githubusercontent.com/36983747/113403060-a6777e00-93d8-11eb-840b-ff92f8538e76.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
