### ISSUE TITLE
爬虫市场报错： tls: handshake failure

### ISSUE THREAD

**Issue by csethomas** [crawlab-team/crawlab#958]
**Bug 描述**
爬虫市场连接失败，报错: tls: handshake failure

**Comment by LZC6244** [comment]
> **Bug 描述**
> 爬虫市场连接失败，报错: tls: handshake failure

+1

**Comment by huangzhong0406** [comment]
> **Bug 描述**
> 爬虫市场连接失败，报错: tls: handshake failure

+1

**Comment by wahyd4** [comment]
The same issue still exists in the latest version as I writing this comment today.
