### ISSUE TITLE
同一个爬虫，爬取多次后只能看到最新的爬取日志，看不到历史日志

### ISSUE THREAD

**Issue by LZC6244** [crawlab-team/crawlab#966]
**Bug 描述**
同一个爬虫，爬取多次后只能看到最新的爬取日志，看不到历史日志
爬虫为 scrapy 爬虫，将其类型定义为【自定义爬虫】，通过入口文件启动
如：python run_spider.py spider_name 
PS：1. 已尝试将其定义为【scrapy爬虫】仍然看不到历史日志
        2. 使用入口文件运行爬虫时，入口文件定义使用了日志，也无法在 docker 中看到日志文件

**复现步骤**
该 Bug 复现步骤如下
1. 【爬虫】界面运行爬虫

**期望结果**
可以查看每次运行的日志

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
