### ISSUE TITLE
Github synchronising with multiple branches not working

### ISSUE THREAD

**Issue by MlataIbrahim** [crawlab-team/crawlab#968]
1 - I'm running two spiders each one with a different branch, actually crawlab is fetching only master branch and if trying to synchronize an other branch the Web UI shows that the branch is second one but when checking the code i recognise that is still using master in the background .

2 - when trying to use SSH key and Git SSH URL i'm getting this error 
![Screen Shot 2021-06-08 at 12 41 36](https://user-images.githubusercontent.com/17418470/121178883-eb93b280-c856-11eb-8d23-f170d57e5fd6.png)

**Comment by moritz-fenske** [comment]
I have the same error. Can someone help me?

**Comment by thouger** [comment]
same  problem
