### ISSUE TITLE
git log里点击checkout 不能回到那个版本

### ISSUE THREAD

**Issue by shilin414** [crawlab-team/crawlab#973]
**Bug 描述**
git部署了爬虫，在log里选择checkout到某个版本，但是没有效果

**复现步骤**
该 Bug 复现步骤如下
1. 部署爬虫
2. 该爬虫有多个版本
3. checkout任意一个版本，但是代码没有发生变化

**期望结果**
代码能回到那个版本

**备注**
不知道是不是我操作得不对

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
