### ISSUE TITLE
[BUG]添加一个定时任务自动刷新后会把其它爬虫的定时任务也显示出来

### ISSUE THREAD

**Issue by NewGreenHand** [crawlab-team/crawlab#974]
**Bug 描述**
添加一个定时任务自动刷新后会把其它爬虫的定时任务也显示出来. 刷新整个页面后重新进入到该爬出详情页面查看定时任务则正常

**复现步骤**
该 Bug 复现步骤如下
1. 点击左侧 爬虫 菜单  -> 点击一条爬虫查看详情 -> 切换到 定时任务 tab 添加定时任务
2.  点击添加, 填好必要数据后保存
3. 保存后会把其它爬虫的定时任务也显示出来

**期望结果**
应该是保存后请求的地址写错了。

**截屏**
![image](https://user-images.githubusercontent.com/24251207/124888590-d0a88f80-e008-11eb-8dbd-757be744948a.png)
![image](https://user-images.githubusercontent.com/24251207/124888676-e61db980-e008-11eb-9274-da8ee7b606ae.png)
![image](https://user-images.githubusercontent.com/24251207/124888766-fe8dd400-e008-11eb-8f48-dab7165c1516.png)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
