### ISSUE TITLE
部署完毕，登录时提示  您的网络异常，无法链接服务器

### ISSUE THREAD

**Issue by holding-on** [crawlab-team/crawlab#975]
![图片](https://user-images.githubusercontent.com/87268157/125196231-a74b6600-e28b-11eb-8b67-f1dcaaf1de2e.png)
![图片](https://user-images.githubusercontent.com/87268157/125196249-bdf1bd00-e28b-11eb-8bc5-8d9f776b4b74.png)

**Comment by mengguiyouziyi** [comment]
请问这个问题解决了么，我也是这个问题

**Comment by yuxinliu-alex** [comment]
mongodb的连接问题，如果是用docker，地址需要用docker的地址
