### ISSUE TITLE
v0.6.0上传文件夹时出现空白警告提示

### ISSUE THREAD

**Issue by mkdir700** [crawlab-team/crawlab#990]
**Bug 描述**
当文件夹中的文件较多时，上传整个文件夹，将会报空白的错误提示。

在这个页面，等待一段时间，再次刷新页面，文件则已成功上传。

**复现步骤**
该 Bug 复现步骤如下
1. 准备一个包含多个文件的文件夹
2. 创建爬虫，并上传文件夹

**期望结果**
1. 可以显示上传进度
2. 支持上传zip格式的压缩包

**截屏**

![314e1b84243b7788f3d4a0cc7f2177b](https://user-images.githubusercontent.com/56359329/128318625-0f417838-3f49-44ad-ac88-35922aedd343.png)

**Comment by tikazyq** [comment]
能看到后端的错误日志么？

**Comment by mkdir700** [comment]
> 能看到后端的错误日志么？

看了下请求日志，感觉和后端没有关系。应该是前端的问题。

我抓包看了，请求没有发出，就已经报错了。

**Comment by kuangcaibao** [comment]
![image](https://user-images.githubusercontent.com/4852014/130047728-f3f1924c-009a-4f53-8624-38dcf78aa042.png)
确实没看到后台上传请求，直接就报错了

**Comment by kuangcaibao** [comment]
表述有错误，文件夹方式上传没问题，zip包上传，会报楼主中的截图错误

**Comment by tikazyq** [comment]
可能是上传了个空文件夹导致的

**Comment by kuangcaibao** [comment]
上传文件夹没问题，是正常的。zip包上传不支持

**Comment by tikazyq** [comment]
最新0.6是不支持上传zip包的，可以直接上传文件夹

**Comment by tikazyq** [comment]
Duplicated in https://github.com/crawlab-team/crawlab/issues/1022
