### ISSUE TITLE
解决Crawlab无法获取安装Python依赖Bug

### ISSUE THREAD

**Issue by SimonChenX** [crawlab-team/crawlab#992]
Crawlab 0.5.1版本

问题描述
在节点详情->安装 安装依赖那里。点击搜索无返回结果

问题定位
跟踪源代码，在源代码 /services/system.go 此文件中 297行的 FetchPythonDepList 方法里

// 请求URL
res, err := req.Get(url)
输出res 显示清华站点识别到访问是移动设备，所以给了个警告页面，这就导致后面的 提取依赖名的动作无法正常执行

解决方法
方法1，避免将 Python依赖源 写死 参考 https://github.com/crawlab-team/crawlab/issues/895
方法2，增加一个请求头（推荐）
// 增加请求头
header := req.Header{
"Accept":     "*/*",
"User-Agent": "Mozilla/5.0",
}

// 请求URL
res, err := req.Get(url, header)
问题解决。

博客地址：https://blog.glemon.cn/post/%E8%A7%A3%E5%86%B3Crawlab%E6%97%A0%E6%B3%95%E8%8E%B7%E5%8F%96%E5%AE%89%E8%A3%85Python%E4%BE%9D%E8%B5%96Bug

**Comment by Q-Simon** [comment]
另一种解决依赖的方法

在Docker里给Crawlab安装Python依赖


https://blog.glemon.cn/post/%E5%9C%A8Docker%E9%87%8C%E7%BB%99Crawlab%E5%AE%89%E8%A3%85Python%E4%BE%9D%E8%B5%96

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
