### ISSUE TITLE
日志报错  页面错乱

### ISSUE THREAD

**Issue by ggandrr** [crawlab-team/crawlab#993]
![image](https://user-images.githubusercontent.com/48814372/128659305-68cbb9f5-9944-4e62-8a16-eeda20234351.png)

**Comment by tikazyq** [comment]
应该是css文件加载问题，或者其他什么问题，可以看看静态资源是否正常加载

**Comment by tikazyq** [comment]
应该是css文件加载问题，或者其他什么问题，可以看看静态资源是否正常加载

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
