### ISSUE TITLE
后台分页的部分数据跳动、过滤不起作用

### ISSUE THREAD

**Issue by 6wukong6** [crawlab-team/crawlab#998]
**Bug 描述**
当后台数据多时，基本有分页的部分都会出现数据跳动、过滤不起作用的现象发生

**复现步骤**
该 Bug 复现步骤如下
1. 新增一些爬虫，用项目区分开来，比如项目1,2,3,4，每个项目下面又有一些爬虫
2. 到有分页部分的功能查看，就会发现数据经常跳动，一会很多，一会很少，跳来跳去
3. 点击带有过滤部分的功能，会发现有时不起作用

**Comment by tikazyq** [comment]
哪个版本？

**Comment by 6wukong6** [comment]
@tikazyq docker最新得

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
