### ISSUE TITLE
任务日志超过24小时后就无法查看

### ISSUE THREAD

**Issue by shilin414** [crawlab-team/crawlab#999]
**Bug 描述**
任务日志一超过24小时就无法查看，如图
![image](https://user-images.githubusercontent.com/17375773/129650752-82b9a4f0-4df5-48a2-a40f-aea31ebd81d5.png)

**复现步骤**
该 Bug 复现步骤如下
1. docker-compose 使用文档里默认的的，并且把日志持久化的注释都取消掉，其他默认，我的docker-compose文件放在附件里，因为yml文件无法上传，后缀改为txt了
2. 这样起起来的crawlab，任务日志超过24小时就无法查看了
3. 前端页面-设置-日志，日志过期时间 是默认的不过期。

**期望结果**
希望日志过期时间能够生效，或者通过其他设置可以选择日志的过期时间

**截屏**
![image](https://user-images.githubusercontent.com/17375773/129650996-4635d747-c0b8-4a35-ad98-2e933d67c222.png)

[docker-compose.txt](https://github.com/crawlab-team/crawlab/files/6996497/docker-compose.txt)

**Comment by zkqiang** [comment]
先关闭了，如果 v0.6 仍有此问题可重新打开
